#region defines
DEFINE ATTACH_BEGIN        := BOUNDARY_DELIMITER
DEFINE ATTACH_CONTENTID          := 2
DEFINE ATTACH_CONTENTTYPE        := 5
DEFINE ATTACH_FILENAME           := 4
DEFINE ATTACH_FILESIZE           := 3
DEFINE ATTACH_FULLPATH           := 7
DEFINE ATTACH_SIZE               := 8
DEFINE ATTACH_STOREID            := 1
DEFINE ATTACH_TRANSFERENCODING   := 6
DEFINE ATTACHMENT_END            := BOUNDARY_DELIMITER + CRLF + CRLF + "." + CRLF
DEFINE BOUNDARY_DELIMITER        := "--"
DEFINE BOUNDARY_START            := CRLF + BOUNDARY_DELIMITER
DEFINE BOUNDARY_VO               := "===" + BOUNDARY_VO_ID + "==="
DEFINE BOUNDARY_VO_ID            := "Visual_Objects_BOUNDARY"
DEFINE CHARSET_ISO               := "iso-8859-"
DEFINE CHARSET_ISO1              := '"'+CHARSET_ISO + '1"'
DEFINE CHARSET_USASCII           := "us-ascii"
DEFINE CHARSET_UTF8              := "utf-8"
DEFINE CLOSING_CONNECTION        := 4
DEFINE CODING_7BIT               := "7bit"
DEFINE CODING_8BIT               := "8bit"
DEFINE CODING_BASE64             := "base64"
DEFINE CODING_QP                 := "quoted-printable"
DEFINE CODING_TYPE_7BIT          := 4
DEFINE CODING_TYPE_8BIT          := 5
DEFINE CODING_TYPE_BASE64        := 2
DEFINE CODING_TYPE_NONE          := 0
DEFINE CODING_TYPE_PRINTABLE     := 3
DEFINE CODING_TYPE_UNKNOWN       := 5
DEFINE CODING_TYPE_UUENCODE      := 1
DEFINE CODING_UUENCODE           := "uuencode"
DEFINE CONNECTED                 := 12
DEFINE CONNECTING                := 1
DEFINE CONTENT_APPLICATION       := "application/octet-stream"
DEFINE CONTENT_AUDIO             := "audio"
DEFINE CONTENT_DEFAULT           := "text/plain; charset=us-ascii"
DEFINE CONTENT_IMAGE             := "image"
DEFINE CONTENT_MESSAGE           := "message"
DEFINE CONTENT_MULTIPART         := "multipart"
DEFINE CONTENT_MULTIPART_ALTERNATE := CONTENT_MULTIPART + "/alternative"
DEFINE CONTENT_MULTIPART_MIXED   := CONTENT_MULTIPART + "/mixed"
DEFINE CONTENT_MULTIPART_RELATED := CONTENT_MULTIPART + "/related"
DEFINE CONTENT_MULTIPART_REPORT  := CONTENT_MULTIPART + "/report"
DEFINE CONTENT_TEXT              := "text"
DEFINE CONTENT_TEXT_HTML         := CONTENT_TEXT + "/html"
DEFINE CONTENT_TEXT_PLAIN        := CONTENT_TEXT+"/plain"
DEFINE CONTENT_VIDEO             := "video"
DEFINE DEFAULT_BOUNDARY          := CRLF + CRLF
DEFINE DEFAULT_STOPDATA          := CRLF + "." + CRLF
DEFINE EMAIL_FORMAT_MIME         := 2
DEFINE EMAIL_FORMAT_UUENCODE     := 1
DEFINE ERR_FILE_EXISTS           := INTERNET_ERROR_BASE  + 224
DEFINE ERR_LOGON_FAILED          := INTERNET_ERROR_BASE  + 223
DEFINE ERR_NEWSGROUP_MISSING     := INTERNET_ERROR_BASE  + 411
DEFINE ERR_NO_ARTICLE            := INTERNET_ERROR_BASE  + 430
DEFINE ERR_NO_ARTICLE_NUMBER     := INTERNET_ERROR_BASE  + 423
DEFINE ERR_NO_ARTICLE_SELECTED   := INTERNET_ERROR_BASE  + 420
DEFINE ERR_NO_NEWSGROUP          := INTERNET_ERROR_BASE  + 412
DEFINE ERR_UNKNOWN_CODE_TYPE     := INTERNET_ERROR_BASE  + 225
DEFINE ERR_WSA_WAIT_TIMEOUT      := 12258
DEFINE ESTABLISHING_SESSION      := 2
DEFINE IMAGE_BMP                 := "image/bmp"
DEFINE IMAGE_JPEG                := "image/jpeg"
DEFINE IMAGE_JPG                 := "image/jpg"
DEFINE IMAGE_TYPE                := "image"
DEFINE IPPORT_IMAP               := 143
DEFINE IPPORT_NNTP               := 119
DEFINE IPPORT_POP                := 110
DEFINE LOGGED_OFF                := 11
DEFINE LOGGED_ON                 := 10
DEFINE LOGGING_ON                := 6
DEFINE MAX_SOCKBUFF              := 2500
DEFINE MIME_MULTI_PART           := "This is a multi-part message in MIME format."
DEFINE MY_STOPDATA               := CRLF + ".." +CRLF
DEFINE RETREIVING_DATA           := 8
DEFINE SENDING_DATA              := 9
DEFINE SENDING_HEADER            := 3
DEFINE SENDING_REQUEST           := 7
DEFINE TAB                       := _CHR(9)
DEFINE TEMP_ATTACHMENT           := "attachment"
DEFINE TEMP_BCC                  := "Bcc:"
DEFINE TEMP_BOUNDARY             := "boundary="
DEFINE TEMP_BOUND                := TEMP_BOUNDARY + '"'
DEFINE TEMP_CC                   := "Cc:"
DEFINE TEMP_CHARSET              := "charset="
DEFINE TEMP_CONTENT              := "Content-Type:"
DEFINE TEMP_CONTENTDISPOSITION   := "Content-Disposition:"
DEFINE TEMP_CONTENTID            := "Content-Id:"
DEFINE TEMP_DATE                 := "Date:"
DEFINE TEMP_DECODE_BOUND         := CRLF+CRLF
DEFINE TEMP_DISPOSITIONNOTIFICATION := "Disposition-Notification-To:"
DEFINE TEMP_ENCODE               := "Content-Transfer-Encoding:"
DEFINE TEMP_FNAME                := "filename="
DEFINE TEMP_FOLLOWUP             := "Followup-To:"
DEFINE TEMP_FROM                 := "From:"
DEFINE TEMP_INLINE         		 := "inline"
DEFINE TEMP_MAILER               := "X-Mailer:"
DEFINE TEMP_MESSAGEID            := "Message-ID:"
DEFINE TEMP_MIMEVERSION          := "Mime-Version: 1.0"
DEFINE TEMP_MULIPARTINFO         := "This is a multi-part message in MIME format."
DEFINE TEMP_NAME                 := "name="
DEFINE TEMP_NEWSGROUPS           := "Newsgroups:"
DEFINE TEMP_ORGANIZATION         := "Organization:"
DEFINE TEMP_PATH                 := "Path:"
DEFINE TEMP_POSTED               := "Posted:"
DEFINE TEMP_PRIORITY             := "X-Priority:"
DEFINE TEMP_REFERENCES           := "References:"
DEFINE TEMP_REPLY                := "Reply-To:"
DEFINE TEMP_RETURN_RECEIPT       := "Return-Receipt-To:"
DEFINE TEMP_SENDER               := "Sender:"
DEFINE TEMP_STOP                 := '"'
DEFINE TEMP_SUBJECT              := "Subject:"
DEFINE TEMP_TO                   := "To:"
DEFINE UUE_END                   := CRLF + "end"
DEFINE UUE_START_EMAIL           := "begin 777 "
DEFINE UUE_START_NEWS            := "begin"
DEFINE UUE_STOP                  := _CHR(96) + CRLF
DEFINE WAITING_FOR_ACTION        := 5
#endregion
