FUNCTION SystemErrorString  (nErr AS DWORD, cDefaultMsg AS STRING)  AS STRING STRICT

    LOCAL cRet  AS STRING
    LOCAL pMsg  AS PSZ

    IF nErr > 0
        FormatMessage(_Or(FORMAT_MESSAGE_ALLOCATE_BUFFER, FORMAT_MESSAGE_FROM_SYSTEM), ;
                      NULL_PTR, nErr, 0, @pMsg, 0, NULL_PTR)
        cRet := Psz2String(pMsg)
        LocalFree(pMsg)
        IF SLen(cRet) = 0
            cRet := __CavoStr(nErr)
            IF SLen(cRet) = 0
                cRet := cDefaultMsg
            ENDIF
        ENDIF
    ELSE
        cRet := cDefaultMsg
    ENDIF

    RETURN cRet



#region defines
DEFINE WSA_WAIT_TIMEOUT      := STATUS_TIMEOUT


/*
#warning DEFINES also defined in WinAPI
DEFINE WSABASEERR            := 10000
//
// All Windows Sockets error constants are biased by WSABASEERR from
//
// Windows Sockets definitions of regular Microsoft C error constants
DEFINE WSAEACCES            := WSABASEERR+13
DEFINE WSAEADDRINUSE        := WSABASEERR+48
DEFINE WSAEADDRNOTAVAIL     := WSABASEERR+49
DEFINE WSAEAFNOSUPPORT      := WSABASEERR+47
DEFINE WSAEALREADY          := WSABASEERR+37
DEFINE WSAEBADF             := WSABASEERR+9
DEFINE WSAECONNABORTED      := WSABASEERR+53
DEFINE WSAECONNREFUSED      := WSABASEERR+61
DEFINE WSAECONNRESET        := WSABASEERR+54
DEFINE WSAEDESTADDRREQ      := WSABASEERR+39
DEFINE WSAEDISCON           := WSABASEERR+101
//  Extended Windows Sockets error constant definitions
DEFINE WSAEDQUOT            := WSABASEERR+69
DEFINE WSAEFAULT            := WSABASEERR+14
DEFINE WSAEHOSTDOWN         := WSABASEERR+64
DEFINE WSAEHOSTUNREACH      := WSABASEERR+65
DEFINE WSAEINPROGRESS       := WSABASEERR+36
DEFINE WSAEINTR             := WSABASEERR+4
DEFINE WSAEINVAL            := WSABASEERR+22
DEFINE WSAEISCONN           := WSABASEERR+56
DEFINE WSAELOOP             := WSABASEERR+62
DEFINE WSAEMFILE            := WSABASEERR+24
// Windows Sockets definitions of regular Berkeley error constants
DEFINE WSAEMSGSIZE          := WSABASEERR+40
DEFINE WSAENAMETOOLONG      := WSABASEERR+63
DEFINE WSAENETDOWN          := WSABASEERR+50
DEFINE WSAENETRESET         := WSABASEERR+52
DEFINE WSAENETUNREACH       := WSABASEERR+51
DEFINE WSAENOBUFS           := WSABASEERR+55
DEFINE WSAENOPROTOOPT       := WSABASEERR+42
DEFINE WSAENOTCONN          := WSABASEERR+57
DEFINE WSAENOTEMPTY         := WSABASEERR+66
DEFINE WSAENOTSOCK          := WSABASEERR+38
DEFINE WSAEOPNOTSUPP        := WSABASEERR+45
DEFINE WSAEPFNOSUPPORT      := WSABASEERR+46
DEFINE WSAEPROCLIM          := WSABASEERR+67
DEFINE WSAEPROTONOSUPPORT   := WSABASEERR+43
DEFINE WSAEPROTOTYPE        := WSABASEERR+41
DEFINE WSAEREMOTE           := WSABASEERR+71
DEFINE WSAESHUTDOWN         := WSABASEERR+58
DEFINE WSAESOCKTNOSUPPORT   := WSABASEERR+44
DEFINE WSAESTALE            := WSABASEERR+70
DEFINE WSAETIMEDOUT         := WSABASEERR+60
DEFINE WSAETOOMANYREFS      := WSABASEERR+59
DEFINE WSAEUSERS            := WSABASEERR+68
DEFINE WSAEWOULDBLOCK       := WSABASEERR+35
DEFINE WSAHOST_NOT_FOUND    := WSABASEERR+1001
DEFINE WSANO_ADDRESS        := WSANO_DATA
DEFINE WSANO_DATA           := WSABASEERR+1004
DEFINE WSANO_RECOVERY       := WSABASEERR+1003
DEFINE WSANOTINITIALISED    := WSABASEERR+93
   //  Error return codes from gethostbyname() and gethostbyaddr()
DEFINE WSASYSNOTREADY       := WSABASEERR+91
DEFINE WSATRY_AGAIN         := WSABASEERR+1002
DEFINE WSAVERNOTSUPPORTED   := WSABASEERR+92
*/
#endregion
