#region defines
DEFINE ccOptimistic			:= 1
DEFINE ccNone				:= 0
DEFINE ccStable				:= 2
DEFINE ccRepeatable		:= 3
DEFINE ccFile				:= 4
DEFINE ccUser				:= 1000
DEFINE DBC_INDEXNAME	:= 1
DEFINE DBC_INDEXPATH	:= 2
DEFINE DBC_ORDERS		:= 3
DEFINE DBC_TAGNAME		:= 1
DEFINE DBC_DUPLICATE		:= 2
DEFINE DBC_ASCENDING	:= 3
DEFINE DBC_KEYEXP		:= 4
DEFINE DBC_FOREXP		:= 5
DEFINE DBC_SYMBOL		:= 1
DEFINE DBC_NAME			:= 2
DEFINE DBC_FIELDSPEC		:= 3
DEFINE NOTIFYFIELDCHANGE :=  -1
DEFINE NOTIFYCLEARRELATION :=  25
DEFINE NOTIFYCLOSE :=  0
DEFINE NOTIFYCOMPLETION :=  1
DEFINE NOTIFYINTENTTOMOVE :=  2
DEFINE NOTIFYRECORDCHANGE :=  3
DEFINE NOTIFYGOBOTTOM :=  4
DEFINE NOTIFYGOTOP :=  5
DEFINE NOTIFYDELETE :=  6
DEFINE NOTIFYAPPEND :=  7
DEFINE NOTIFYFILECHANGE :=  10
DEFINE NOTIFYRELATIONCHANGE :=  20
DEFINE NOTIFYCONCURRENCYCONTROLMODE := 50
DEFINE TYPE_MULTIMEDIA := 42
// Ansgar 7/9/97 added Bitmap
DEFINE MAXFILENAME      := 260
DEFINE MAXEXTNAME       := 128
DEFINE MAXDIRNAME       := 256
DEFINE MAXDRIVENAME     := 128
#endregion
