// Usage.prg

USING System

FUNCTION Usage AS VOID
	Console.WriteLine("VFPXPorterCmd — VFP to X#/WinForms code generator")
	Console.WriteLine()
	Console.WriteLine("Usage:")
	Console.WriteLine("  VFPXPorterCmd -o:<output> [-f:<file> ...] [-p:<project>] [options]")
	Console.WriteLine()
	Console.WriteLine("Input:")
	Console.WriteLine("  -f:<path>             SCX (form) or VCX (class library) to convert.")
	Console.WriteLine("                        Can be repeated for multiple files.")
	Console.WriteLine("  -p:<path>             PJX (VFP project) to convert entirely")
	Console.WriteLine("                        (forms, libraries, menus, programs).")
	Console.WriteLine("  -o:<path>             Output folder. Created if it does not exist.")
	Console.WriteLine()
	Console.WriteLine("General options:")
	Console.WriteLine("  -b                    Backup source to XML before converting.")
	Console.WriteLine("  -l:<path>             Write log to file (in addition to console).")
	Console.WriteLine()
	Console.WriteLine("Conversion options:")
	Console.WriteLine("  -keepOriginal         Keep original VFP code as comments (default).")
	Console.WriteLine("  -noKeepOriginal       Do not keep original VFP code as comments.")
	Console.WriteLine("  -convertHandlers      Apply code converter to event handlers.")
	Console.WriteLine("  -convertUserDef       Apply code converter to user-defined methods.")
	Console.WriteLine("  -storeInFolders       Organize output into Forms/Libs/Menus/Code subfolders.")
	Console.WriteLine("  -outputType:<type>    WindowsExe (default) | ClassLibrary | Console.")
	Console.WriteLine("  -modifier:<mod>       Field access modifier: PUBLIC (default) | PROTECTED | PRIVATE.")
	Console.WriteLine()
	Console.WriteLine("Notes:")
	Console.WriteLine("  Paths may be absolute or relative to the current directory.")
	Console.WriteLine("  Wrap paths containing spaces in double quotes:")
	Console.WriteLine(e"    -f:\"C:\\My App\\myform.scx\"")
	Console.WriteLine()
	Console.WriteLine("Examples:")
	Console.WriteLine(e"  VFPXPorterCmd -f:\"C:\\MyApp\\myform.scx\" -o:\"C:\\Output\"")
	Console.WriteLine(e"  VFPXPorterCmd -p:\"C:\\MyApp\\myapp.pjx\" -o:\"C:\\Output\" -b -l:convert.log")
	Console.WriteLine(e"  VFPXPorterCmd -f:myform.scx -o:out -convertHandlers -storeInFolders")
	Console.WriteLine()
	Console.WriteLine("Exit codes:  0 = success,  1 = error")
	RETURN
