//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.24.0.1
//     Timestamp      : 28/12/2025 12:51:12
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE VFPXPorter
    PUBLIC PARTIAL CLASS ExportProjectWindow	;
		INHERIT System.Windows.Forms.Form
        PRIVATE components	:=	NULL AS System.ComponentModel.IContainer
        PRIVATE resultText AS System.Windows.Forms.TextBox
        PRIVATE exportButton AS System.Windows.Forms.Button
        PRIVATE label2 AS System.Windows.Forms.Label
        PRIVATE scxButton AS System.Windows.Forms.Button
        PRIVATE outputButton AS System.Windows.Forms.Button
        PRIVATE label3 AS System.Windows.Forms.Label
        PRIVATE analysisButton AS System.Windows.Forms.Button
        PUBLIC outputPathTextBox AS System.Windows.Forms.TextBox
        PRIVATE infoStrip AS System.Windows.Forms.StatusStrip
        PRIVATE infoStripLabel AS System.Windows.Forms.ToolStripStatusLabel
        PUBLIC pjxPathTextBox AS System.Windows.Forms.TextBox
        PRIVATE openButton AS System.Windows.Forms.Button
        PRIVATE backgroundExport AS System.ComponentModel.BackgroundWorker
        PRIVATE infoStripBar AS System.Windows.Forms.ToolStripProgressBar
        PRIVATE cancelBtn AS System.Windows.Forms.Button
        PRIVATE infoStripError AS System.Windows.Forms.ToolStripStatusLabel
        PRIVATE label1 AS System.Windows.Forms.Label
		PRIVATE LabelType AS System.Windows.Forms.Label
		PRIVATE TypeComboBox AS System.Windows.Forms.ComboBox
		PRIVATE AppendCheckBox AS System.Windows.Forms.CheckBox
		PRIVATE PlaceSolutionInSameDirectory AS System.Windows.Forms.CheckBox
		PRIVATE label4 AS System.Windows.Forms.Label
		PUBLIC SolutionName AS System.Windows.Forms.TextBox

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .AND. (components != NULL))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
            RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        																				PRIVATE METHOD InitializeComponent() AS VOID STRICT
			SELF:label1	:=	System.Windows.Forms.Label{}
			SELF:resultText	:=	System.Windows.Forms.TextBox{}
			SELF:exportButton	:=	System.Windows.Forms.Button{}
			SELF:label2	:=	System.Windows.Forms.Label{}
			SELF:pjxPathTextBox	:=	System.Windows.Forms.TextBox{}
			SELF:scxButton	:=	System.Windows.Forms.Button{}
			SELF:outputButton	:=	System.Windows.Forms.Button{}
			SELF:outputPathTextBox	:=	System.Windows.Forms.TextBox{}
			SELF:label3	:=	System.Windows.Forms.Label{}
			SELF:analysisButton	:=	System.Windows.Forms.Button{}
			SELF:infoStrip	:=	System.Windows.Forms.StatusStrip{}
			SELF:infoStripBar	:=	System.Windows.Forms.ToolStripProgressBar{}
			SELF:infoStripLabel	:=	System.Windows.Forms.ToolStripStatusLabel{}
			SELF:infoStripError	:=	System.Windows.Forms.ToolStripStatusLabel{}
			SELF:openButton	:=	System.Windows.Forms.Button{}
			SELF:backgroundExport	:=	System.ComponentModel.BackgroundWorker{}
			SELF:cancelBtn	:=	System.Windows.Forms.Button{}
			SELF:LabelType	:=	System.Windows.Forms.Label{}
			SELF:TypeComboBox	:=	System.Windows.Forms.ComboBox{}
			SELF:AppendCheckBox	:=	System.Windows.Forms.CheckBox{}
			SELF:PlaceSolutionInSameDirectory	:=	System.Windows.Forms.CheckBox{}
			SELF:SolutionName	:=	System.Windows.Forms.TextBox{}
			SELF:label4	:=	System.Windows.Forms.Label{}
			SELF:infoStrip:SuspendLayout()
			SELF:SuspendLayout()
			//	
			//	label1
			//	
			SELF:label1:AutoSize	:=	true
			SELF:label1:Location	:=	System.Drawing.Point{417, 10}
			SELF:label1:Margin	:=	System.Windows.Forms.Padding{2, 0, 2, 0}
			SELF:label1:Name	:=	"label1"
			SELF:label1:Size	:=	System.Drawing.Size{51, 13}
			SELF:label1:TabIndex	:=	0
			SELF:label1:Text	:=	"Analysis :"
			//	
			//	resultText
			//	
			SELF:resultText:Anchor	:=	((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 	;
						| System.Windows.Forms.AnchorStyles.Left) 	;
						| System.Windows.Forms.AnchorStyles.Right)))
			SELF:resultText:Location	:=	System.Drawing.Point{419, 27}
			SELF:resultText:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:resultText:Multiline	:=	true
			SELF:resultText:Name	:=	"resultText"
			SELF:resultText:ReadOnly	:=	true
			SELF:resultText:ScrollBars	:=	System.Windows.Forms.ScrollBars.Both
			SELF:resultText:Size	:=	System.Drawing.Size{266, 223}
			SELF:resultText:TabIndex	:=	1
			SELF:resultText:WordWrap	:=	false
			//	
			//	exportButton
			//	
			SELF:exportButton:Location	:=	System.Drawing.Point{169, 231}
			SELF:exportButton:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:exportButton:Name	:=	"exportButton"
			SELF:exportButton:Size	:=	System.Drawing.Size{56, 20}
			SELF:exportButton:TabIndex	:=	4
			SELF:exportButton:Text	:=	"Export"
			SELF:exportButton:UseVisualStyleBackColor	:=	true
			SELF:exportButton:Click	+=	System.EventHandler{ SELF, @exportButton_Click() }
			//	
			//	label2
			//	
			SELF:label2:AutoSize	:=	true
			SELF:label2:Location	:=	System.Drawing.Point{13, 53}
			SELF:label2:Margin	:=	System.Windows.Forms.Padding{2, 0, 2, 0}
			SELF:label2:Name	:=	"label2"
			SELF:label2:Size	:=	System.Drawing.Size{67, 13}
			SELF:label2:TabIndex	:=	3
			SELF:label2:Text	:=	"Input Project"
			//	
			//	pjxPathTextBox
			//	
			SELF:pjxPathTextBox:Location	:=	System.Drawing.Point{15, 70}
			SELF:pjxPathTextBox:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:pjxPathTextBox:Name	:=	"pjxPathTextBox"
			SELF:pjxPathTextBox:Size	:=	System.Drawing.Size{270, 20}
			SELF:pjxPathTextBox:TabIndex	:=	0
			//	
			//	scxButton
			//	
			SELF:scxButton:Location	:=	System.Drawing.Point{289, 70}
			SELF:scxButton:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:scxButton:Name	:=	"scxButton"
			SELF:scxButton:Size	:=	System.Drawing.Size{33, 19}
			SELF:scxButton:TabIndex	:=	1
			SELF:scxButton:Text	:=	"..."
			SELF:scxButton:UseVisualStyleBackColor	:=	true
			SELF:scxButton:Click	+=	System.EventHandler{ SELF, @scxButton_Click() }
			//	
			//	outputButton
			//	
			SELF:outputButton:Location	:=	System.Drawing.Point{289, 118}
			SELF:outputButton:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:outputButton:Name	:=	"outputButton"
			SELF:outputButton:Size	:=	System.Drawing.Size{33, 19}
			SELF:outputButton:TabIndex	:=	3
			SELF:outputButton:Text	:=	"..."
			SELF:outputButton:UseVisualStyleBackColor	:=	true
			SELF:outputButton:Click	+=	System.EventHandler{ SELF, @outputButton_Click() }
			//	
			//	outputPathTextBox
			//	
			SELF:outputPathTextBox:Location	:=	System.Drawing.Point{15, 118}
			SELF:outputPathTextBox:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:outputPathTextBox:Name	:=	"outputPathTextBox"
			SELF:outputPathTextBox:Size	:=	System.Drawing.Size{270, 20}
			SELF:outputPathTextBox:TabIndex	:=	2
			//	
			//	label3
			//	
			SELF:label3:AutoSize	:=	true
			SELF:label3:Location	:=	System.Drawing.Point{13, 101}
			SELF:label3:Margin	:=	System.Windows.Forms.Padding{2, 0, 2, 0}
			SELF:label3:Name	:=	"label3"
			SELF:label3:Size	:=	System.Drawing.Size{71, 13}
			SELF:label3:TabIndex	:=	6
			SELF:label3:Text	:=	"Output Folder"
			//	
			//	analysisButton
			//	
			SELF:analysisButton:Location	:=	System.Drawing.Point{359, 27}
			SELF:analysisButton:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:analysisButton:Name	:=	"analysisButton"
			SELF:analysisButton:Size	:=	System.Drawing.Size{56, 20}
			SELF:analysisButton:TabIndex	:=	5
			SELF:analysisButton:Text	:=	"Analyze"
			SELF:analysisButton:UseVisualStyleBackColor	:=	true
			SELF:analysisButton:Click	+=	System.EventHandler{ SELF, @analysisButton_Click() }
			//	
			//	infoStrip
			//	
			SELF:infoStrip:ImageScalingSize	:=	System.Drawing.Size{20, 20}
			SELF:infoStrip:Items:AddRange(<System.Windows.Forms.ToolStripItem>{ SELF:infoStripBar, SELF:infoStripLabel, SELF:infoStripError })
			SELF:infoStrip:Location	:=	System.Drawing.Point{0, 263}
			SELF:infoStrip:Name	:=	"infoStrip"
			SELF:infoStrip:Padding	:=	System.Windows.Forms.Padding{1, 0, 10, 0}
			SELF:infoStrip:Size	:=	System.Drawing.Size{695, 22}
			SELF:infoStrip:TabIndex	:=	10
			SELF:infoStrip:Text	:=	"statusStrip1"
			//	
			//	infoStripBar
			//	
			SELF:infoStripBar:Name	:=	"infoStripBar"
			SELF:infoStripBar:Size	:=	System.Drawing.Size{75, 16}
			//	
			//	infoStripLabel
			//	
			SELF:infoStripLabel:Name	:=	"infoStripLabel"
			SELF:infoStripLabel:Size	:=	System.Drawing.Size{0, 17}
			//	
			//	infoStripError
			//	
			SELF:infoStripError:ForeColor	:=	System.Drawing.Color.Red
			SELF:infoStripError:IsLink	:=	true
			SELF:infoStripError:Name	:=	"infoStripError"
			SELF:infoStripError:Size	:=	System.Drawing.Size{0, 17}
			//	
			//	openButton
			//	
			SELF:openButton:Location	:=	System.Drawing.Point{229, 230}
			SELF:openButton:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:openButton:Name	:=	"openButton"
			SELF:openButton:Size	:=	System.Drawing.Size{56, 20}
			SELF:openButton:TabIndex	:=	12
			SELF:openButton:Text	:=	"Open"
			SELF:openButton:UseVisualStyleBackColor	:=	true
			SELF:openButton:Click	+=	System.EventHandler{ SELF, @openButton_Click() }
			//	
			//	backgroundExport
			//	
			SELF:backgroundExport:WorkerReportsProgress	:=	true
			SELF:backgroundExport:WorkerSupportsCancellation	:=	true
			SELF:backgroundExport:DoWork	+=	System.ComponentModel.DoWorkEventHandler{ SELF, @backgroundExport_DoWork() }
			SELF:backgroundExport:ProgressChanged	+=	System.ComponentModel.ProgressChangedEventHandler{ SELF, @backgroundExport_ProgressChanged() }
			SELF:backgroundExport:RunWorkerCompleted	+=	System.ComponentModel.RunWorkerCompletedEventHandler{ SELF, @backgroundExport_RunWorkerCompleted() }
			//	
			//	cancelBtn
			//	
			SELF:cancelBtn:Location	:=	System.Drawing.Point{109, 231}
			SELF:cancelBtn:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:cancelBtn:Name	:=	"cancelBtn"
			SELF:cancelBtn:Size	:=	System.Drawing.Size{56, 20}
			SELF:cancelBtn:TabIndex	:=	13
			SELF:cancelBtn:Text	:=	"Cancel"
			SELF:cancelBtn:UseVisualStyleBackColor	:=	true
			SELF:cancelBtn:Visible	:=	false
			SELF:cancelBtn:Click	+=	System.EventHandler{ SELF, @cancelBtn_Click() }
			//	
			//	LabelType
			//	
			SELF:LabelType:AutoSize	:=	true
			SELF:LabelType:Location	:=	System.Drawing.Point{12, 10}
			SELF:LabelType:Margin	:=	System.Windows.Forms.Padding{2, 0, 2, 0}
			SELF:LabelType:Name	:=	"LabelType"
			SELF:LabelType:Size	:=	System.Drawing.Size{70, 13}
			SELF:LabelType:TabIndex	:=	14
			SELF:LabelType:Text	:=	"Project Type:"
			//	
			//	TypeComboBox
			//	
			SELF:TypeComboBox:DropDownStyle	:=	System.Windows.Forms.ComboBoxStyle.DropDownList
			SELF:TypeComboBox:FormattingEnabled	:=	true
			SELF:TypeComboBox:Items:AddRange(<System.Object>{ "Windows EXE", "Class Library (DLL)", "Console App" })
			SELF:TypeComboBox:Location	:=	System.Drawing.Point{14, 26}
			SELF:TypeComboBox:Name	:=	"TypeComboBox"
			SELF:TypeComboBox:Size	:=	System.Drawing.Size{123, 21}
			SELF:TypeComboBox:TabIndex	:=	15
			//	
			//	AppendCheckBox
			//	
			SELF:AppendCheckBox:AutoSize	:=	true
			SELF:AppendCheckBox:Location	:=	System.Drawing.Point{143, 28}
			SELF:AppendCheckBox:Name	:=	"AppendCheckBox"
			SELF:AppendCheckBox:Size	:=	System.Drawing.Size{179, 17}
			SELF:AppendCheckBox:TabIndex	:=	16
			SELF:AppendCheckBox:Text	:=	"Append to existing Solution (.sln)"
			SELF:AppendCheckBox:UseVisualStyleBackColor	:=	true
			//	
			//	PlaceSolutionInSameDirectory
			//	
			SELF:PlaceSolutionInSameDirectory:AutoSize	:=	true
			SELF:PlaceSolutionInSameDirectory:Location	:=	System.Drawing.Point{16, 198}
			SELF:PlaceSolutionInSameDirectory:Name	:=	"PlaceSolutionInSameDirectory"
			SELF:PlaceSolutionInSameDirectory:Size	:=	System.Drawing.Size{248, 17}
			SELF:PlaceSolutionInSameDirectory:TabIndex	:=	17
			SELF:PlaceSolutionInSameDirectory:Text	:=	"Place solution and project in the same directory"
			SELF:PlaceSolutionInSameDirectory:UseVisualStyleBackColor	:=	true
			//	
			//	SolutionName
			//	
			SELF:SolutionName:Location	:=	System.Drawing.Point{16, 169}
			SELF:SolutionName:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:SolutionName:Name	:=	"SolutionName"
			SELF:SolutionName:Size	:=	System.Drawing.Size{270, 20}
			SELF:SolutionName:TabIndex	:=	18
			//	
			//	label4
			//	
			SELF:label4:AutoSize	:=	true
			SELF:label4:Location	:=	System.Drawing.Point{14, 152}
			SELF:label4:Margin	:=	System.Windows.Forms.Padding{2, 0, 2, 0}
			SELF:label4:Name	:=	"label4"
			SELF:label4:Size	:=	System.Drawing.Size{76, 13}
			SELF:label4:TabIndex	:=	19
			SELF:label4:Text	:=	"Solution Name"
			//	
			//	ExportProjectWindow
			//	
			SELF:AutoScaleDimensions	:=	System.Drawing.SizeF{6, 13}
			SELF:AutoScaleMode	:=	System.Windows.Forms.AutoScaleMode.Font
			SELF:ClientSize	:=	System.Drawing.Size{695, 285}
			SELF:Controls:Add(SELF:SolutionName)
			SELF:Controls:Add(SELF:label4)
			SELF:Controls:Add(SELF:PlaceSolutionInSameDirectory)
			SELF:Controls:Add(SELF:AppendCheckBox)
			SELF:Controls:Add(SELF:TypeComboBox)
			SELF:Controls:Add(SELF:LabelType)
			SELF:Controls:Add(SELF:cancelBtn)
			SELF:Controls:Add(SELF:openButton)
			SELF:Controls:Add(SELF:infoStrip)
			SELF:Controls:Add(SELF:analysisButton)
			SELF:Controls:Add(SELF:outputButton)
			SELF:Controls:Add(SELF:outputPathTextBox)
			SELF:Controls:Add(SELF:label3)
			SELF:Controls:Add(SELF:scxButton)
			SELF:Controls:Add(SELF:pjxPathTextBox)
			SELF:Controls:Add(SELF:label2)
			SELF:Controls:Add(SELF:exportButton)
			SELF:Controls:Add(SELF:resultText)
			SELF:Controls:Add(SELF:label1)
			SELF:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:Name	:=	"ExportProjectWindow"
			SELF:Text	:=	"Export Project"
			SELF:infoStrip:ResumeLayout(false)
			SELF:infoStrip:PerformLayout()
			SELF:ResumeLayout(false)
			SELF:PerformLayout()
		END METHOD 

        #endregion

    END CLASS 
END NAMESPACE
