//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.16.0.6
//     Timestamp      : 11/06/2023 16:43:08
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE VFPXPorter
    PUBLIC PARTIAL CLASS SettingsDialog	;
		INHERIT System.Windows.Forms.Form
        PRIVATE outputButton AS System.Windows.Forms.Button
        PRIVATE outputPathTextBox AS System.Windows.Forms.TextBox
        PRIVATE label3 AS System.Windows.Forms.Label
        PRIVATE okButton AS System.Windows.Forms.Button
        PRIVATE cancelButton1 AS System.Windows.Forms.Button
        PRIVATE vfpButton AS System.Windows.Forms.Button
        PRIVATE vfpPathTextBox AS System.Windows.Forms.TextBox
        PRIVATE label1 AS System.Windows.Forms.Label
        PRIVATE checkLibraryAsSubFolder AS System.Windows.Forms.CheckBox
        PRIVATE checkIgnoreExportError AS System.Windows.Forms.CheckBox
        PRIVATE checkConvertHandlers AS System.Windows.Forms.CheckBox
        PRIVATE checkConvertUserDef AS System.Windows.Forms.CheckBox
        PRIVATE checkStoreInFolders AS System.Windows.Forms.CheckBox
        PRIVATE itemsButton AS System.Windows.Forms.Button
        PRIVATE columnHeader1 AS System.Windows.Forms.ColumnHeader
        PRIVATE columnHeader2 AS System.Windows.Forms.ColumnHeader
        PRIVATE listFolders AS System.Windows.Forms.ListView
        PRIVATE checkPrefix AS System.Windows.Forms.CheckBox
        PRIVATE checkEmptyFolder AS System.Windows.Forms.CheckBox
        PRIVATE checkKeepOriginal AS System.Windows.Forms.CheckBox
        PRIVATE tabSettingsCtrl AS System.Windows.Forms.TabControl
        PRIVATE tabFolders AS System.Windows.Forms.TabPage
        PRIVATE tabExport AS System.Windows.Forms.TabPage
        PRIVATE tabProject AS System.Windows.Forms.TabPage
        PRIVATE label2 AS System.Windows.Forms.Label
        PRIVATE comboModifiers AS System.Windows.Forms.ComboBox
        PRIVATE checkConvertThisObject AS System.Windows.Forms.CheckBox
        PRIVATE checkStatement AS System.Windows.Forms.CheckBox
        PRIVATE components	:=	NULL AS System.ComponentModel.IContainer
		PRIVATE checkSetEvent AS System.Windows.Forms.CheckBox
		PRIVATE checkPrefixEventInForm AS System.Windows.Forms.CheckBox
		PRIVATE checkStatementLast AS System.Windows.Forms.CheckBox
		PRIVATE editButton AS System.Windows.Forms.Button
		PRIVATE toolTipCtrl AS System.Windows.Forms.ToolTip
		PRIVATE checkKeepFoxProEventName AS System.Windows.Forms.CheckBox
		PRIVATE buttonReset AS System.Windows.Forms.Button
		PRIVATE buttonFolder AS System.Windows.Forms.Button
		PRIVATE label4 AS System.Windows.Forms.Label
		PRIVATE ressourcesButton AS System.Windows.Forms.Button
		PRIVATE ressourcesTextBox AS System.Windows.Forms.TextBox
		PRIVATE checkGenerateOnlyHandledEvent AS System.Windows.Forms.CheckBox
                                                                                                        
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .AND. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
            RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        PRIVATE METHOD InitializeComponent() AS VOID STRICT
			SELF:components	:=	System.ComponentModel.Container{}
			LOCAL groupBox1 AS System.Windows.Forms.GroupBox
			SELF:checkKeepFoxProEventName	:=	System.Windows.Forms.CheckBox{}
			SELF:editButton	:=	System.Windows.Forms.Button{}
			SELF:checkStatementLast	:=	System.Windows.Forms.CheckBox{}
			SELF:checkPrefixEventInForm	:=	System.Windows.Forms.CheckBox{}
			SELF:checkSetEvent	:=	System.Windows.Forms.CheckBox{}
			SELF:checkNameUDF	:=	System.Windows.Forms.CheckBox{}
			SELF:checkStatement	:=	System.Windows.Forms.CheckBox{}
			SELF:checkConvertHandlers	:=	System.Windows.Forms.CheckBox{}
			SELF:checkConvertThisObject	:=	System.Windows.Forms.CheckBox{}
			SELF:checkConvertUserDef	:=	System.Windows.Forms.CheckBox{}
			SELF:checkKeepOriginal	:=	System.Windows.Forms.CheckBox{}
			SELF:outputButton	:=	System.Windows.Forms.Button{}
			SELF:outputPathTextBox	:=	System.Windows.Forms.TextBox{}
			SELF:label3	:=	System.Windows.Forms.Label{}
			SELF:okButton	:=	System.Windows.Forms.Button{}
			SELF:cancelButton1	:=	System.Windows.Forms.Button{}
			SELF:vfpButton	:=	System.Windows.Forms.Button{}
			SELF:vfpPathTextBox	:=	System.Windows.Forms.TextBox{}
			SELF:label1	:=	System.Windows.Forms.Label{}
			SELF:checkLibraryAsSubFolder	:=	System.Windows.Forms.CheckBox{}
			SELF:checkIgnoreExportError	:=	System.Windows.Forms.CheckBox{}
			SELF:checkStoreInFolders	:=	System.Windows.Forms.CheckBox{}
			SELF:itemsButton	:=	System.Windows.Forms.Button{}
			SELF:listFolders	:=	System.Windows.Forms.ListView{}
			SELF:columnHeader1	:=	System.Windows.Forms.ColumnHeader{}
			SELF:columnHeader2	:=	System.Windows.Forms.ColumnHeader{}
			SELF:checkPrefix	:=	System.Windows.Forms.CheckBox{}
			SELF:checkEmptyFolder	:=	System.Windows.Forms.CheckBox{}
			SELF:tabSettingsCtrl	:=	System.Windows.Forms.TabControl{}
			SELF:tabFolders	:=	System.Windows.Forms.TabPage{}
			SELF:label4	:=	System.Windows.Forms.Label{}
			SELF:ressourcesTextBox	:=	System.Windows.Forms.TextBox{}
			SELF:ressourcesButton	:=	System.Windows.Forms.Button{}
			SELF:tabExport	:=	System.Windows.Forms.TabPage{}
			SELF:label2	:=	System.Windows.Forms.Label{}
			SELF:comboModifiers	:=	System.Windows.Forms.ComboBox{}
			SELF:tabProject	:=	System.Windows.Forms.TabPage{}
			SELF:toolTipCtrl	:=	System.Windows.Forms.ToolTip{SELF:components}
			SELF:buttonReset	:=	System.Windows.Forms.Button{}
			SELF:buttonFolder	:=	System.Windows.Forms.Button{}
			SELF:checkGenerateOnlyHandledEvent	:=	System.Windows.Forms.CheckBox{}
			groupBox1	:=	System.Windows.Forms.GroupBox{}
			groupBox1:SuspendLayout()
			SELF:tabSettingsCtrl:SuspendLayout()
			SELF:tabFolders:SuspendLayout()
			SELF:tabExport:SuspendLayout()
			SELF:tabProject:SuspendLayout()
			SELF:SuspendLayout()
			//	
			//	groupBox1
			//	
			groupBox1:Controls:Add(SELF:checkGenerateOnlyHandledEvent)
			groupBox1:Controls:Add(SELF:checkKeepFoxProEventName)
			groupBox1:Controls:Add(SELF:editButton)
			groupBox1:Controls:Add(SELF:checkStatementLast)
			groupBox1:Controls:Add(SELF:checkPrefixEventInForm)
			groupBox1:Controls:Add(SELF:checkSetEvent)
			groupBox1:Controls:Add(SELF:checkNameUDF)
			groupBox1:Controls:Add(SELF:checkStatement)
			groupBox1:Controls:Add(SELF:checkConvertHandlers)
			groupBox1:Controls:Add(SELF:checkConvertThisObject)
			groupBox1:Controls:Add(SELF:checkConvertUserDef)
			groupBox1:Controls:Add(SELF:checkKeepOriginal)
			groupBox1:Location	:=	System.Drawing.Point{15, 45}
			groupBox1:Name	:=	"groupBox1"
			groupBox1:Size	:=	System.Drawing.Size{491, 388}
			groupBox1:TabIndex	:=	27
			groupBox1:TabStop	:=	false
			groupBox1:Text	:=	"Code Conversion"
			//	
			//	checkKeepFoxProEventName
			//	
			SELF:checkKeepFoxProEventName:AutoSize	:=	true
			SELF:checkKeepFoxProEventName:Location	:=	System.Drawing.Point{6, 283}
			SELF:checkKeepFoxProEventName:Name	:=	"checkKeepFoxProEventName"
			SELF:checkKeepFoxProEventName:Size	:=	System.Drawing.Size{326, 20}
			SELF:checkKeepFoxProEventName:TabIndex	:=	33
			SELF:checkKeepFoxProEventName:Text	:=	"Keep Visual FoxPro Event name in EventHandlers"
			SELF:toolTipCtrl:SetToolTip(SELF:checkKeepFoxProEventName, "Use the VFP Event Name when generating the EventHandler")
			SELF:checkKeepFoxProEventName:UseVisualStyleBackColor	:=	true
			//	
			//	editButton
			//	
			SELF:editButton:Location	:=	System.Drawing.Point{374, 136}
			SELF:editButton:Margin	:=	System.Windows.Forms.Padding{4}
			SELF:editButton:Name	:=	"editButton"
			SELF:editButton:Size	:=	System.Drawing.Size{100, 28}
			SELF:editButton:TabIndex	:=	32
			SELF:editButton:Text	:=	"&Edit"
			SELF:toolTipCtrl:SetToolTip(SELF:editButton, "Edit the Statements file")
			SELF:editButton:UseVisualStyleBackColor	:=	true
			SELF:editButton:Click	+=	System.EventHandler{ SELF, @editButton_Click() }
			//	
			//	checkStatementLast
			//	
			SELF:checkStatementLast:AutoSize	:=	true
			SELF:checkStatementLast:Location	:=	System.Drawing.Point{37, 153}
			SELF:checkStatementLast:Name	:=	"checkStatementLast"
			SELF:checkStatementLast:Size	:=	System.Drawing.Size{206, 20}
			SELF:checkStatementLast:TabIndex	:=	31
			SELF:checkStatementLast:Text	:=	"Convert only if last item on line"
			SELF:checkStatementLast:UseVisualStyleBackColor	:=	true
			//	
			//	checkPrefixEventInForm
			//	
			SELF:checkPrefixEventInForm:AutoSize	:=	true
			SELF:checkPrefixEventInForm:Location	:=	System.Drawing.Point{6, 257}
			SELF:checkPrefixEventInForm:Name	:=	"checkPrefixEventInForm"
			SELF:checkPrefixEventInForm:Size	:=	System.Drawing.Size{258, 20}
			SELF:checkPrefixEventInForm:TabIndex	:=	30
			SELF:checkPrefixEventInForm:Text	:=	"Prefix Event methods with FORM name"
			SELF:toolTipCtrl:SetToolTip(SELF:checkPrefixEventInForm, "Add the name of the Form in front of Event methods")
			SELF:checkPrefixEventInForm:UseVisualStyleBackColor	:=	true
			//	
			//	checkSetEvent
			//	
			SELF:checkSetEvent:AutoSize	:=	true
			SELF:checkSetEvent:Location	:=	System.Drawing.Point{6, 231}
			SELF:checkSetEvent:Name	:=	"checkSetEvent"
			SELF:checkSetEvent:Size	:=	System.Drawing.Size{298, 20}
			SELF:checkSetEvent:TabIndex	:=	29
			SELF:checkSetEvent:Text	:=	e"Remove \"Set_\" prefix if present in EventRules"
			SELF:checkSetEvent:UseVisualStyleBackColor	:=	true
			//	
			//	checkNameUDF
			//	
			SELF:checkNameUDF:AutoSize	:=	true
			SELF:checkNameUDF:Location	:=	System.Drawing.Point{6, 205}
			SELF:checkNameUDF:Name	:=	"checkNameUDF"
			SELF:checkNameUDF:Size	:=	System.Drawing.Size{238, 20}
			SELF:checkNameUDF:TabIndex	:=	28
			SELF:checkNameUDF:Text	:=	"Fullname for User-defined Methods"
			SELF:checkNameUDF:UseVisualStyleBackColor	:=	true
			//	
			//	checkStatement
			//	
			SELF:checkStatement:AutoSize	:=	true
			SELF:checkStatement:Location	:=	System.Drawing.Point{6, 127}
			SELF:checkStatement:Name	:=	"checkStatement"
			SELF:checkStatement:Size	:=	System.Drawing.Size{334, 20}
			SELF:checkStatement:TabIndex	:=	27
			SELF:checkStatement:Text	:=	"Convert Statement to Call : Release => Release(), ..."
			SELF:checkStatement:UseVisualStyleBackColor	:=	true
			//	
			//	checkConvertHandlers
			//	
			SELF:checkConvertHandlers:AutoSize	:=	true
			SELF:checkConvertHandlers:Enabled	:=	false
			SELF:checkConvertHandlers:Location	:=	System.Drawing.Point{6, 22}
			SELF:checkConvertHandlers:Name	:=	"checkConvertHandlers"
			SELF:checkConvertHandlers:Size	:=	System.Drawing.Size{365, 20}
			SELF:checkConvertHandlers:TabIndex	:=	5
			SELF:checkConvertHandlers:Text	:=	"Convert THIS/THISFORM/THIS.Parent in EventHandlers"
			SELF:toolTipCtrl:SetToolTip(SELF:checkConvertHandlers, "Old Setting - Disabled")
			SELF:checkConvertHandlers:UseVisualStyleBackColor	:=	true
			SELF:checkConvertHandlers:CheckedChanged	+=	System.EventHandler{ SELF, @checkConvertHandlers_CheckedChanged() }
			//	
			//	checkConvertThisObject
			//	
			SELF:checkConvertThisObject:AutoSize	:=	true
			SELF:checkConvertThisObject:Location	:=	System.Drawing.Point{6, 100}
			SELF:checkConvertThisObject:Name	:=	"checkConvertThisObject"
			SELF:checkConvertThisObject:Size	:=	System.Drawing.Size{468, 20}
			SELF:checkConvertThisObject:TabIndex	:=	26
			SELF:checkConvertThisObject:Text	:=	"Convert VFP Elements to WinForms (This=>thisObject, Parent=>_Parent,...)"
			SELF:checkConvertThisObject:UseVisualStyleBackColor	:=	true
			SELF:checkConvertThisObject:CheckedChanged	+=	System.EventHandler{ SELF, @checkConvertThisObject_CheckedChanged() }
			//	
			//	checkConvertUserDef
			//	
			SELF:checkConvertUserDef:AutoSize	:=	true
			SELF:checkConvertUserDef:Enabled	:=	false
			SELF:checkConvertUserDef:Location	:=	System.Drawing.Point{6, 48}
			SELF:checkConvertUserDef:Name	:=	"checkConvertUserDef"
			SELF:checkConvertUserDef:Size	:=	System.Drawing.Size{392, 20}
			SELF:checkConvertUserDef:TabIndex	:=	6
			SELF:checkConvertUserDef:Text	:=	"Convert THIS/THISFORM/THIS.Parent in User-Defined Code"
			SELF:toolTipCtrl:SetToolTip(SELF:checkConvertUserDef, "Old Setting - Disabled")
			SELF:checkConvertUserDef:UseVisualStyleBackColor	:=	true
			SELF:checkConvertUserDef:CheckedChanged	+=	System.EventHandler{ SELF, @checkConvertUserDef_CheckedChanged() }
			//	
			//	checkKeepOriginal
			//	
			SELF:checkKeepOriginal:AutoSize	:=	true
			SELF:checkKeepOriginal:Location	:=	System.Drawing.Point{6, 179}
			SELF:checkKeepOriginal:Name	:=	"checkKeepOriginal"
			SELF:checkKeepOriginal:Size	:=	System.Drawing.Size{215, 20}
			SELF:checkKeepOriginal:TabIndex	:=	23
			SELF:checkKeepOriginal:Text	:=	"Keep original code in Comment"
			SELF:toolTipCtrl:SetToolTip(SELF:checkKeepOriginal, "Add a comment with original code before modified lines")
			SELF:checkKeepOriginal:UseVisualStyleBackColor	:=	true
			//	
			//	outputButton
			//	
			SELF:outputButton:Location	:=	System.Drawing.Point{348, 94}
			SELF:outputButton:Margin	:=	System.Windows.Forms.Padding{3, 2, 3, 2}
			SELF:outputButton:Name	:=	"outputButton"
			SELF:outputButton:Size	:=	System.Drawing.Size{44, 23}
			SELF:outputButton:TabIndex	:=	3
			SELF:outputButton:Text	:=	"..."
			SELF:outputButton:UseVisualStyleBackColor	:=	true
			SELF:outputButton:Click	+=	System.EventHandler{ SELF, @outputButton_Click() }
			//	
			//	outputPathTextBox
			//	
			SELF:outputPathTextBox:Location	:=	System.Drawing.Point{16, 94}
			SELF:outputPathTextBox:Margin	:=	System.Windows.Forms.Padding{3, 2, 3, 2}
			SELF:outputPathTextBox:Name	:=	"outputPathTextBox"
			SELF:outputPathTextBox:Size	:=	System.Drawing.Size{327, 22}
			SELF:outputPathTextBox:TabIndex	:=	2
			//	
			//	label3
			//	
			SELF:label3:AutoSize	:=	true
			SELF:label3:Location	:=	System.Drawing.Point{13, 73}
			SELF:label3:Name	:=	"label3"
			SELF:label3:Size	:=	System.Drawing.Size{132, 16}
			SELF:label3:TabIndex	:=	9
			SELF:label3:Text	:=	"Default Output Folder"
			//	
			//	okButton
			//	
			SELF:okButton:Location	:=	System.Drawing.Point{439, 523}
			SELF:okButton:Margin	:=	System.Windows.Forms.Padding{4}
			SELF:okButton:Name	:=	"okButton"
			SELF:okButton:Size	:=	System.Drawing.Size{100, 28}
			SELF:okButton:TabIndex	:=	8
			SELF:okButton:Text	:=	"&Ok"
			SELF:okButton:UseVisualStyleBackColor	:=	true
			SELF:okButton:Click	+=	System.EventHandler{ SELF, @okButton_Click() }
			//	
			//	cancelButton1
			//	
			SELF:cancelButton1:Location	:=	System.Drawing.Point{328, 523}
			SELF:cancelButton1:Margin	:=	System.Windows.Forms.Padding{4}
			SELF:cancelButton1:Name	:=	"cancelButton1"
			SELF:cancelButton1:Size	:=	System.Drawing.Size{100, 28}
			SELF:cancelButton1:TabIndex	:=	9
			SELF:cancelButton1:Text	:=	"Cancel"
			SELF:cancelButton1:UseVisualStyleBackColor	:=	true
			SELF:cancelButton1:Click	+=	System.EventHandler{ SELF, @cancelButton1_Click() }
			//	
			//	vfpButton
			//	
			SELF:vfpButton:Location	:=	System.Drawing.Point{349, 34}
			SELF:vfpButton:Margin	:=	System.Windows.Forms.Padding{3, 2, 3, 2}
			SELF:vfpButton:Name	:=	"vfpButton"
			SELF:vfpButton:Size	:=	System.Drawing.Size{44, 23}
			SELF:vfpButton:TabIndex	:=	1
			SELF:vfpButton:Text	:=	"..."
			SELF:vfpButton:UseVisualStyleBackColor	:=	true
			SELF:vfpButton:Click	+=	System.EventHandler{ SELF, @vfpButton_Click() }
			//	
			//	vfpPathTextBox
			//	
			SELF:vfpPathTextBox:Location	:=	System.Drawing.Point{17, 34}
			SELF:vfpPathTextBox:Margin	:=	System.Windows.Forms.Padding{3, 2, 3, 2}
			SELF:vfpPathTextBox:Name	:=	"vfpPathTextBox"
			SELF:vfpPathTextBox:Size	:=	System.Drawing.Size{327, 22}
			SELF:vfpPathTextBox:TabIndex	:=	0
			//	
			//	label1
			//	
			SELF:label1:AutoSize	:=	true
			SELF:label1:Location	:=	System.Drawing.Point{14, 13}
			SELF:label1:Name	:=	"label1"
			SELF:label1:Size	:=	System.Drawing.Size{155, 16}
			SELF:label1:TabIndex	:=	14
			SELF:label1:Text	:=	"Default VFP Items Folder"
			//	
			//	checkLibraryAsSubFolder
			//	
			SELF:checkLibraryAsSubFolder:AutoSize	:=	true
			SELF:checkLibraryAsSubFolder:CheckAlign	:=	System.Drawing.ContentAlignment.MiddleRight
			SELF:checkLibraryAsSubFolder:Location	:=	System.Drawing.Point{15, 69}
			SELF:checkLibraryAsSubFolder:Name	:=	"checkLibraryAsSubFolder"
			SELF:checkLibraryAsSubFolder:RightToLeft	:=	System.Windows.Forms.RightToLeft.Yes
			SELF:checkLibraryAsSubFolder:Size	:=	System.Drawing.Size{241, 20}
			SELF:checkLibraryAsSubFolder:TabIndex	:=	3
			SELF:checkLibraryAsSubFolder:Text	:=	"Each ClassLibrary is in a SubFolder"
			SELF:checkLibraryAsSubFolder:UseVisualStyleBackColor	:=	true
			//	
			//	checkIgnoreExportError
			//	
			SELF:checkIgnoreExportError:AutoSize	:=	true
			SELF:checkIgnoreExportError:CheckAlign	:=	System.Drawing.ContentAlignment.MiddleRight
			SELF:checkIgnoreExportError:Location	:=	System.Drawing.Point{15, 15}
			SELF:checkIgnoreExportError:Name	:=	"checkIgnoreExportError"
			SELF:checkIgnoreExportError:RightToLeft	:=	System.Windows.Forms.RightToLeft.Yes
			SELF:checkIgnoreExportError:Size	:=	System.Drawing.Size{146, 20}
			SELF:checkIgnoreExportError:TabIndex	:=	0
			SELF:checkIgnoreExportError:Text	:=	"Ignore export Errors"
			SELF:checkIgnoreExportError:UseVisualStyleBackColor	:=	true
			//	
			//	checkStoreInFolders
			//	
			SELF:checkStoreInFolders:AutoSize	:=	true
			SELF:checkStoreInFolders:CheckAlign	:=	System.Drawing.ContentAlignment.MiddleRight
			SELF:checkStoreInFolders:Location	:=	System.Drawing.Point{15, 42}
			SELF:checkStoreInFolders:Name	:=	"checkStoreInFolders"
			SELF:checkStoreInFolders:RightToLeft	:=	System.Windows.Forms.RightToLeft.Yes
			SELF:checkStoreInFolders:Size	:=	System.Drawing.Size{240, 20}
			SELF:checkStoreInFolders:TabIndex	:=	1
			SELF:checkStoreInFolders:Text	:=	"Store Items in Folders by Items type"
			SELF:checkStoreInFolders:UseVisualStyleBackColor	:=	true
			//	
			//	itemsButton
			//	
			SELF:itemsButton:Location	:=	System.Drawing.Point{346, 40}
			SELF:itemsButton:Margin	:=	System.Windows.Forms.Padding{3, 2, 3, 2}
			SELF:itemsButton:Name	:=	"itemsButton"
			SELF:itemsButton:Size	:=	System.Drawing.Size{44, 23}
			SELF:itemsButton:TabIndex	:=	2
			SELF:itemsButton:Text	:=	">>"
			SELF:itemsButton:UseVisualStyleBackColor	:=	true
			SELF:itemsButton:Click	+=	System.EventHandler{ SELF, @itemsButton_Click() }
			//	
			//	listFolders
			//	
			SELF:listFolders:Columns:AddRange(<System.Windows.Forms.ColumnHeader>{ SELF:columnHeader1, SELF:columnHeader2 })
			SELF:listFolders:FullRowSelect	:=	true
			SELF:listFolders:GridLines	:=	true
			SELF:listFolders:HeaderStyle	:=	System.Windows.Forms.ColumnHeaderStyle.Nonclickable
			SELF:listFolders:HideSelection	:=	false
			SELF:listFolders:LabelEdit	:=	true
			SELF:listFolders:Location	:=	System.Drawing.Point{285, 123}
			SELF:listFolders:Name	:=	"listFolders"
			SELF:listFolders:Size	:=	System.Drawing.Size{217, 179}
			SELF:listFolders:TabIndex	:=	22
			SELF:listFolders:UseCompatibleStateImageBehavior	:=	false
			SELF:listFolders:View	:=	System.Windows.Forms.View.Details
			SELF:listFolders:Visible	:=	false
			//	
			//	columnHeader1
			//	
			SELF:columnHeader1:Text	:=	"Folder Name"
			SELF:columnHeader1:Width	:=	83
			//	
			//	columnHeader2
			//	
			SELF:columnHeader2:Text	:=	"Item Type"
			SELF:columnHeader2:Width	:=	96
			//	
			//	checkPrefix
			//	
			SELF:checkPrefix:AutoSize	:=	true
			SELF:checkPrefix:CheckAlign	:=	System.Drawing.ContentAlignment.MiddleRight
			SELF:checkPrefix:Location	:=	System.Drawing.Point{15, 18}
			SELF:checkPrefix:Name	:=	"checkPrefix"
			SELF:checkPrefix:RightToLeft	:=	System.Windows.Forms.RightToLeft.Yes
			SELF:checkPrefix:Size	:=	System.Drawing.Size{322, 20}
			SELF:checkPrefix:TabIndex	:=	4
			SELF:checkPrefix:Text	:=	"Prefix Class filenames with the name of the Library"
			SELF:checkPrefix:UseVisualStyleBackColor	:=	true
			//	
			//	checkEmptyFolder
			//	
			SELF:checkEmptyFolder:AutoSize	:=	true
			SELF:checkEmptyFolder:CheckAlign	:=	System.Drawing.ContentAlignment.MiddleRight
			SELF:checkEmptyFolder:Location	:=	System.Drawing.Point{15, 96}
			SELF:checkEmptyFolder:Name	:=	"checkEmptyFolder"
			SELF:checkEmptyFolder:RightToLeft	:=	System.Windows.Forms.RightToLeft.Yes
			SELF:checkEmptyFolder:Size	:=	System.Drawing.Size{294, 20}
			SELF:checkEmptyFolder:TabIndex	:=	4
			SELF:checkEmptyFolder:Text	:=	"Empty the destination Folder (if already exist)"
			SELF:checkEmptyFolder:UseVisualStyleBackColor	:=	true
			//	
			//	tabSettingsCtrl
			//	
			SELF:tabSettingsCtrl:Controls:Add(SELF:tabFolders)
			SELF:tabSettingsCtrl:Controls:Add(SELF:tabExport)
			SELF:tabSettingsCtrl:Controls:Add(SELF:tabProject)
			SELF:tabSettingsCtrl:Location	:=	System.Drawing.Point{12, 12}
			SELF:tabSettingsCtrl:Name	:=	"tabSettingsCtrl"
			SELF:tabSettingsCtrl:SelectedIndex	:=	0
			SELF:tabSettingsCtrl:Size	:=	System.Drawing.Size{531, 504}
			SELF:tabSettingsCtrl:TabIndex	:=	24
			//	
			//	tabFolders
			//	
			SELF:tabFolders:Controls:Add(SELF:label4)
			SELF:tabFolders:Controls:Add(SELF:ressourcesTextBox)
			SELF:tabFolders:Controls:Add(SELF:ressourcesButton)
			SELF:tabFolders:Controls:Add(SELF:vfpPathTextBox)
			SELF:tabFolders:Controls:Add(SELF:label3)
			SELF:tabFolders:Controls:Add(SELF:outputPathTextBox)
			SELF:tabFolders:Controls:Add(SELF:outputButton)
			SELF:tabFolders:Controls:Add(SELF:label1)
			SELF:tabFolders:Controls:Add(SELF:vfpButton)
			SELF:tabFolders:Location	:=	System.Drawing.Point{4, 25}
			SELF:tabFolders:Name	:=	"tabFolders"
			SELF:tabFolders:Padding	:=	System.Windows.Forms.Padding{3}
			SELF:tabFolders:Size	:=	System.Drawing.Size{523, 475}
			SELF:tabFolders:TabIndex	:=	0
			SELF:tabFolders:Text	:=	"Folders"
			SELF:tabFolders:UseVisualStyleBackColor	:=	true
			//	
			//	label4
			//	
			SELF:label4:AutoSize	:=	true
			SELF:label4:Location	:=	System.Drawing.Point{13, 139}
			SELF:label4:Name	:=	"label4"
			SELF:label4:Size	:=	System.Drawing.Size{208, 16}
			SELF:label4:TabIndex	:=	17
			SELF:label4:Text	:=	"Default XPorter ressources Folder"
			//	
			//	ressourcesTextBox
			//	
			SELF:ressourcesTextBox:Location	:=	System.Drawing.Point{16, 160}
			SELF:ressourcesTextBox:Margin	:=	System.Windows.Forms.Padding{3, 2, 3, 2}
			SELF:ressourcesTextBox:Name	:=	"ressourcesTextBox"
			SELF:ressourcesTextBox:Size	:=	System.Drawing.Size{327, 22}
			SELF:ressourcesTextBox:TabIndex	:=	15
			//	
			//	ressourcesButton
			//	
			SELF:ressourcesButton:Location	:=	System.Drawing.Point{348, 160}
			SELF:ressourcesButton:Margin	:=	System.Windows.Forms.Padding{3, 2, 3, 2}
			SELF:ressourcesButton:Name	:=	"ressourcesButton"
			SELF:ressourcesButton:Size	:=	System.Drawing.Size{44, 23}
			SELF:ressourcesButton:TabIndex	:=	16
			SELF:ressourcesButton:Text	:=	"..."
			SELF:ressourcesButton:UseVisualStyleBackColor	:=	true
			SELF:ressourcesButton:Click	+=	System.EventHandler{ SELF, @ressourcesButton_Click() }
			//	
			//	tabExport
			//	
			SELF:tabExport:Controls:Add(groupBox1)
			SELF:tabExport:Controls:Add(SELF:label2)
			SELF:tabExport:Controls:Add(SELF:comboModifiers)
			SELF:tabExport:Controls:Add(SELF:checkPrefix)
			SELF:tabExport:Location	:=	System.Drawing.Point{4, 25}
			SELF:tabExport:Name	:=	"tabExport"
			SELF:tabExport:Padding	:=	System.Windows.Forms.Padding{3}
			SELF:tabExport:Size	:=	System.Drawing.Size{523, 475}
			SELF:tabExport:TabIndex	:=	1
			SELF:tabExport:Text	:=	"Export"
			SELF:tabExport:UseVisualStyleBackColor	:=	true
			//	
			//	label2
			//	
			SELF:label2:AutoSize	:=	true
			SELF:label2:Location	:=	System.Drawing.Point{18, 442}
			SELF:label2:Name	:=	"label2"
			SELF:label2:Size	:=	System.Drawing.Size{147, 16}
			SELF:label2:TabIndex	:=	25
			SELF:label2:Text	:=	"Default Fields modifiers"
			//	
			//	comboModifiers
			//	
			SELF:comboModifiers:DropDownStyle	:=	System.Windows.Forms.ComboBoxStyle.DropDownList
			SELF:comboModifiers:FormattingEnabled	:=	true
			SELF:comboModifiers:Items:AddRange(<System.Object>{ "PRIVATE", "PROTECTED", "INTERNAL", "PUBLIC" })
			SELF:comboModifiers:Location	:=	System.Drawing.Point{174, 439}
			SELF:comboModifiers:Name	:=	"comboModifiers"
			SELF:comboModifiers:Size	:=	System.Drawing.Size{121, 24}
			SELF:comboModifiers:TabIndex	:=	24
			//	
			//	tabProject
			//	
			SELF:tabProject:Controls:Add(SELF:checkEmptyFolder)
			SELF:tabProject:Controls:Add(SELF:listFolders)
			SELF:tabProject:Controls:Add(SELF:checkIgnoreExportError)
			SELF:tabProject:Controls:Add(SELF:itemsButton)
			SELF:tabProject:Controls:Add(SELF:checkLibraryAsSubFolder)
			SELF:tabProject:Controls:Add(SELF:checkStoreInFolders)
			SELF:tabProject:Location	:=	System.Drawing.Point{4, 25}
			SELF:tabProject:Name	:=	"tabProject"
			SELF:tabProject:Padding	:=	System.Windows.Forms.Padding{3}
			SELF:tabProject:Size	:=	System.Drawing.Size{523, 475}
			SELF:tabProject:TabIndex	:=	2
			SELF:tabProject:Text	:=	"Project"
			SELF:tabProject:UseVisualStyleBackColor	:=	true
			//	
			//	buttonReset
			//	
			SELF:buttonReset:Location	:=	System.Drawing.Point{13, 523}
			SELF:buttonReset:Margin	:=	System.Windows.Forms.Padding{4}
			SELF:buttonReset:Name	:=	"buttonReset"
			SELF:buttonReset:Size	:=	System.Drawing.Size{145, 28}
			SELF:buttonReset:TabIndex	:=	25
			SELF:buttonReset:Text	:=	"Reset Settings"
			SELF:buttonReset:UseVisualStyleBackColor	:=	true
			SELF:buttonReset:Click	+=	System.EventHandler{ SELF, @buttonReset_Click() }
			//	
			//	buttonFolder
			//	
			SELF:buttonFolder:Location	:=	System.Drawing.Point{166, 523}
			SELF:buttonFolder:Margin	:=	System.Windows.Forms.Padding{4}
			SELF:buttonFolder:Name	:=	"buttonFolder"
			SELF:buttonFolder:Size	:=	System.Drawing.Size{145, 28}
			SELF:buttonFolder:TabIndex	:=	26
			SELF:buttonFolder:Text	:=	"Open Settings Folder"
			SELF:buttonFolder:UseVisualStyleBackColor	:=	true
			SELF:buttonFolder:Click	+=	System.EventHandler{ SELF, @buttonFolder_Click() }
			//	
			//	checkGenerateOnlyHandledEvent
			//	
			SELF:checkGenerateOnlyHandledEvent:AutoSize	:=	true
			SELF:checkGenerateOnlyHandledEvent:Location	:=	System.Drawing.Point{6, 309}
			SELF:checkGenerateOnlyHandledEvent:Name	:=	"checkGenerateOnlyHandledEvent"
			SELF:checkGenerateOnlyHandledEvent:Size	:=	System.Drawing.Size{329, 20}
			SELF:checkGenerateOnlyHandledEvent:TabIndex	:=	34
			SELF:checkGenerateOnlyHandledEvent:Text	:=	"Generate only EventHandlers that have a definition"
			SELF:toolTipCtrl:SetToolTip(SELF:checkGenerateOnlyHandledEvent, "Only generate Handlers for Events that appears in EventRules.json")
			SELF:checkGenerateOnlyHandledEvent:UseVisualStyleBackColor	:=	true
			//	
			//	SettingsDialog
			//	
			SELF:AcceptButton	:=	SELF:okButton
			SELF:AutoScaleMode	:=	System.Windows.Forms.AutoScaleMode.None
			SELF:ClientSize	:=	System.Drawing.Size{549, 564}
			SELF:Controls:Add(SELF:buttonFolder)
			SELF:Controls:Add(SELF:buttonReset)
			SELF:Controls:Add(SELF:tabSettingsCtrl)
			SELF:Controls:Add(SELF:cancelButton1)
			SELF:Controls:Add(SELF:okButton)
			SELF:FormBorderStyle	:=	System.Windows.Forms.FormBorderStyle.FixedDialog
			SELF:Margin	:=	System.Windows.Forms.Padding{4}
			SELF:MaximizeBox	:=	false
			SELF:MinimizeBox	:=	false
			SELF:Name	:=	"SettingsDialog"
			SELF:StartPosition	:=	System.Windows.Forms.FormStartPosition.CenterParent
			SELF:Text	:=	"Exporter Settings"
			SELF:Load	+=	System.EventHandler{ SELF, @SettingsDialog_Load() }
			groupBox1:ResumeLayout(false)
			groupBox1:PerformLayout()
			SELF:tabSettingsCtrl:ResumeLayout(false)
			SELF:tabFolders:ResumeLayout(false)
			SELF:tabFolders:PerformLayout()
			SELF:tabExport:ResumeLayout(false)
			SELF:tabExport:PerformLayout()
			SELF:tabProject:ResumeLayout(false)
			SELF:tabProject:PerformLayout()
			SELF:ResumeLayout(false)
		END METHOD
        PRIVATE checkNameUDF AS System.Windows.Forms.CheckBox
                            
        #endregion
    
    END CLASS 
END NAMESPACE
