//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.16.0.0
//     Timestamp      : 09/05/2023 21:54:46
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE VFPXPorter

    PUBLIC PARTIAL CLASS WarningDialog

        /// <summary>
        /// Required designer variable.
        /// </summary>
        private components	:=	NULL AS System.ComponentModel.IContainer
		PRIVATE buttonAgreed AS System.Windows.Forms.Button
		PUBLIC checkDontShow AS System.Windows.Forms.CheckBox
		PRIVATE rtfWarning AS System.Windows.Forms.RichTextBox

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override method Dispose(disposing as logic) as void strict

            if (disposing .and. (components != null))
                components:Dispose()
            endif
            Super:Dispose(disposing)
			return
        end method
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private METHOD InitializeComponent() AS VOID STRICT
			SELF:buttonAgreed	:=	System.Windows.Forms.Button{}
			SELF:checkDontShow	:=	System.Windows.Forms.CheckBox{}
			SELF:rtfWarning	:=	System.Windows.Forms.RichTextBox{}
			SELF:SuspendLayout()
			//	
			//	buttonAgreed
			//	
			SELF:buttonAgreed:Enabled	:=	false
			SELF:buttonAgreed:Location	:=	System.Drawing.Point{734, 371}
			SELF:buttonAgreed:Name	:=	"buttonAgreed"
			SELF:buttonAgreed:Size	:=	System.Drawing.Size{95, 42}
			SELF:buttonAgreed:TabIndex	:=	0
			SELF:buttonAgreed:Text	:=	"Ok"
			SELF:buttonAgreed:UseVisualStyleBackColor	:=	true
			SELF:buttonAgreed:Click	+=	System.EventHandler{ SELF, @buttonAgreed_Click() }
			//	
			//	checkDontShow
			//	
			SELF:checkDontShow:AutoSize	:=	true
			SELF:checkDontShow:Enabled	:=	false
			SELF:checkDontShow:Location	:=	System.Drawing.Point{24, 383}
			SELF:checkDontShow:Name	:=	"checkDontShow"
			SELF:checkDontShow:Size	:=	System.Drawing.Size{228, 20}
			SELF:checkDontShow:TabIndex	:=	1
			SELF:checkDontShow:Text	:=	"Don't show this on the next Startup"
			SELF:checkDontShow:UseVisualStyleBackColor	:=	true
			//	
			//	rtfWarning
			//	
			SELF:rtfWarning:Location	:=	System.Drawing.Point{12, 12}
			SELF:rtfWarning:Name	:=	"rtfWarning"
			SELF:rtfWarning:ReadOnly	:=	true
			SELF:rtfWarning:Size	:=	System.Drawing.Size{817, 344}
			SELF:rtfWarning:TabIndex	:=	2
			SELF:rtfWarning:Text	:=	""
			SELF:rtfWarning:VScroll	+=	System.EventHandler{ SELF, @rtfWarning_VScroll() }
			//	
			//	WarningDialog
			//	
			SELF:AutoScaleDimensions	:=	System.Drawing.SizeF{8, 16}
			SELF:AutoScaleMode	:=	System.Windows.Forms.AutoScaleMode.Font
			SELF:ClientSize	:=	System.Drawing.Size{841, 458}
			SELF:ControlBox	:=	false
			SELF:Controls:Add(SELF:rtfWarning)
			SELF:Controls:Add(SELF:checkDontShow)
			SELF:Controls:Add(SELF:buttonAgreed)
			SELF:FormBorderStyle	:=	System.Windows.Forms.FormBorderStyle.FixedDialog
			SELF:MaximizeBox	:=	false
			SELF:MinimizeBox	:=	false
			SELF:Name	:=	"WarningDialog"
			SELF:StartPosition	:=	System.Windows.Forms.FormStartPosition.CenterScreen
			SELF:Text	:=	"Warning !!"
			SELF:TopMost	:=	true
			SELF:Load	+=	System.EventHandler{ SELF, @WarningDialog_Load() }
			SELF:ResumeLayout(false)
			SELF:PerformLayout()
		END METHOD
        #endregion
    END CLASS 
END NAMESPACE
