//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.6.0.0
//     Timestamp      : 03/02/2021 15:47:54
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE XSharp.Debugger

    PUBLIC PARTIAL CLASS VariablesWindow ;
        INHERIT System.Windows.Forms.Form
        PRIVATE setting AS System.Windows.Forms.ColumnHeader
        PRIVATE settingValue AS System.Windows.Forms.ColumnHeader
        PRIVATE btnClose AS System.Windows.Forms.Button
        PROTECTED variablesListView AS System.Windows.Forms.ListView
        PRIVATE components := NULL AS System.ComponentModel.IContainer

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        OVERRIDE PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .and. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
         RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        PRIVATE METHOD InitializeComponent() AS VOID STRICT
            SELF:variablesListView := System.Windows.Forms.ListView{}
            SELF:setting := System.Windows.Forms.ColumnHeader{}
            SELF:settingValue := System.Windows.Forms.ColumnHeader{}
            SELF:btnClose := System.Windows.Forms.Button{}
            SELF:SuspendLayout()
            // 
            // variablesListView
            // 
            SELF:variablesListView:AllowColumnReorder := true
            SELF:variablesListView:Anchor := ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)  ;
                        | System.Windows.Forms.AnchorStyles.Left)  ;
                        | System.Windows.Forms.AnchorStyles.Right)))
            SELF:variablesListView:Columns:AddRange(<System.Windows.Forms.ColumnHeader>{ SELF:setting, SELF:settingValue })
            SELF:variablesListView:GridLines := true
            SELF:variablesListView:HideSelection := false
            SELF:variablesListView:Location := System.Drawing.Point{0, 0}
            SELF:variablesListView:Name := "variablesListView"
            SELF:variablesListView:Size := System.Drawing.Size{466, 474}
            SELF:variablesListView:Sorting := System.Windows.Forms.SortOrder.@@Ascending
            SELF:variablesListView:TabIndex := 0
            SELF:variablesListView:UseCompatibleStateImageBehavior := false
            SELF:variablesListView:View := System.Windows.Forms.View.Details
            // 
            // setting
            // 
            SELF:setting:Text := "Name"
            // 
            // settingValue
            // 
            SELF:settingValue:Text := "Value"
            // 
            // btnClose
            // 
            SELF:btnClose:Anchor := ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)))
            SELF:btnClose:DialogResult := System.Windows.Forms.DialogResult.Cancel
            SELF:btnClose:Location := System.Drawing.Point{366, 484}
            SELF:btnClose:Name := "btnClose"
            SELF:btnClose:Size := System.Drawing.Size{100, 37}
            SELF:btnClose:TabIndex := 1
            SELF:btnClose:Text := "&Close"
            SELF:btnClose:UseVisualStyleBackColor := true
            SELF:btnClose:Click += System.EventHandler{ SELF, @btnClose_Click() }
            // 
            // VariablesWindow
            // 
            SELF:AcceptButton := SELF:btnClose
            SELF:AutoScaleDimensions := System.Drawing.SizeF{6, 13}
            SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            SELF:CancelButton := SELF:btnClose
            SELF:ClientSize := System.Drawing.Size{476, 531}
            SELF:ControlBox := false
            SELF:Controls:Add(SELF:btnClose)
            SELF:Controls:Add(SELF:variablesListView)
            SELF:Name := "VariablesWindow"
            SELF:ShowInTaskbar := false
            SELF:StartPosition := System.Windows.Forms.FormStartPosition.CenterScreen
            SELF:Text := "XSharp Runtime State - Variables"
            SELF:ResumeLayout(false)

        #endregion
    END CLASS 
END NAMESPACE
