VOSTRUCT _WINDVTARGETDEVICE	  // ALIGN 2	RvdH 070411 removed alignment
    MEMBER tdSize 				AS DWORD
    MEMBER tdDriverNameOffset AS WORD
    MEMBER tdDeviceNameOffset AS WORD
    MEMBER tdPortNameOffset 	AS WORD
    MEMBER tdExtDevmodeOffset AS WORD
    MEMBER DIM tdData[1] 		AS BYTE

VOSTRUCT _WINSTGMEDIUM	ALIGN 4
	MEMBER tymed				AS DWORD
	MEMBER u						IS _WINSTGMEDIUM_DATA
	MEMBER pUnkForRelease 	AS PTR
VOSTRUCT _WINFORMATETC	ALIGN 4
    MEMBER cfFormat  	AS WORD
    MEMBER ptd 			AS _WINDVTARGETDEVICE
    MEMBER dwAspect 	AS DWORD
    MEMBER lindex 		AS LONGINT
    MEMBER tymed 		AS DWORD

VOSTRUCT  _WINOLEUIINSERTOBJECT
	// These IN fields are standard across all OLEUI dialog functions.
	MEMBER cbStruct 		AS DWORD       // STRUCTURE Size
	MEMBER dwFlags  		AS DWORD       // IN-OUT:  Flags
	MEMBER hWndOwner 		AS PTR         // Owning window
	MEMBER lpszCaption 	AS PSZ    		// Dialog caption bar contents
	MEMBER lpfnHook    	AS PTR        // Hook callback: UINT (CALLBACK *LPFNOLEUIHOOK)(HWND, UINT, WPARAM, LPARAM);

	MEMBER lCustData   	AS LONGINT      	// Custom data to pass to hook
	MEMBER hInstance		AS PTR      	// Instance for customized template name
	MEMBER lpszTemplate 	AS PSZ		   // Customized template name
	MEMBER hResource	 	AS PTR        // Customized template handle

	// Specifics for OLEUIINSERTOBJECT.
	MEMBER clsid		IS _WINGUID    // OUT: Return space for class ID
	MEMBER lpszFile	AS PSZ       	// IN-OUT: Filename for inserts or links
	MEMBER cchFile	AS DWORD         	// IN: Size of lpszFile buffer: MAX_PATH
	MEMBER cClsidExclude	AS DWORD  	// IN: CLSIDs in lpClsidExclude
	MEMBER lpClsidExclude AS PTR 	   // IN: List of CLSIDs (array of _WINGUID) to exclude from listing.

	// Specific to create objects if flags say so
	MEMBER iid 		 	IS _WINGUID    // IN: Requested interface on creation.
	MEMBER oleRender 	AS DWORD       // IN: Rendering option
	MEMBER lpFormatEtc AS PTR    		// IN: Desired format
	MEMBER lpIOleClientSite AS PTR   // IN: Site to be use for the object.
	MEMBER lpIStorage	AS PTR     		// IN: Storage used for the object
	MEMBER ppvObj		AS PTR        	// OUT: Where the object is returned.
	MEMBER sc			AS LONGINT     	// OUT: Result of creation calls.
	MEMBER hMetaPict	AS PTR	      // OUT: metafile aspect (METAFILEPICT)

_DLL FUNCTION OleInitialize(pvReserved AS PTR) AS LONGINT PASCAL:OLE32.OleInitialize
_DLL FUNCTION OleUninitialize() AS VOID PASCAL:OLE32.OleUninitialize

_DLL FUNCTION DoDragDrop( oIDataObject AS PTR,;
	oIDropSource AS PTR,;
	dwOKEffect AS DWORD,;
	pdwEffect AS DWORD PTR;
	) AS LONGINT PASCAL:OLE32.DoDragDrop
_DLL FUNCTION RegisterDragDrop( hwnd AS PTR, oIDropTarget AS PTR) AS LONGINT PASCAL:OLE32.RegisterDragDrop
_DLL FUNCTION RevokeDragDrop(   hwnd AS PTR	) AS LONGINT PASCAL:OLE32.RevokeDragDrop
_DLL FUNCTION OleSave(oIPersistStorage AS PTR ,oIStorage AS PTR,lSameAsLoad AS LOGIC) AS LONGINT PASCAL:OLE32.OleSave
_DLL FUNCTION OleSetContainedObject(oIUnknown AS PTR,lContained AS LOGIC) AS LONGINT PASCAL:OLE32.OleSetContainedObject
_DLL FUNCTION OleDraw(oIUnknown AS PTR,dwAspect AS DWORD,hDC AS PTR,sBounds AS _WINRECT) AS LONGINT PASCAL:OLE32.OleDraw
_DLL FUNCTION StgCreateDocfile(pwcsName AS PTR,grfMode AS DWORD,reserved AS DWORD,pStorage AS OBJECT PTR) AS LONGINT PASCAL:OLE32.StgCreateDocfile
_DLL FUNCTION WriteClassStg(oIStorage AS PTR,sClsID AS _winGUID) AS LONGINT PASCAL:OLE32.WriteClassStg
_DLL FUNCTION OleRun(oIUnknown AS PTR) AS LONGINT PASCAL:OLE32.OleRun
_DLL FUNCTION CoGetMalloc(dwMemContext AS DWORD,ppMalloc AS PTR) AS LONGINT PASCAL:OLE32.CoGetMalloc
_DLL FUNCTION CoInitialize(ptrMemAlloc AS PTR) AS LONGINT PASCAL:OLE32.CoInitialize
_DLL FUNCTION CoTaskMemAlloc(nBytes AS DWORD) AS PTR PASCAL:OLE32.CoTaskMemAlloc
_DLL FUNCTION CoTaskMemFree(ptrMem AS PTR) AS VOID PASCAL:OLE32.CoTaskMemFree
_DLL FUNCTION CoUninitialize() AS VOID PASCAL:OLE32.CoUninitialize
_DLL FUNCTION WriteFmtUserTypeStg(pStg AS PTR,cf AS DWORD,lpszUserType AS PTR) AS LONGINT PASCAL:OLE32.WriteFmtUserTypeStg
_DLL FUNCTION CreateDataAdviseHolder(ppDAHolder AS OBJECT PTR) AS LONGINT PASCAL:OLE32.CreateDataAdviseHolder
_DLL FUNCTION CreateOleAdviseHolder(ppOAHolder AS PTR) AS LONGINT PASCAL:OLE32.CreateOleAdviseHolder
_DLL FUNCTION OleRegEnumVerbs(clsid AS _winGUID,ppenumOleVerb AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleRegEnumVerbs
_DLL FUNCTION OleRegGetMiscStatus(clsid AS _winGUID,dwAspect AS DWORD,pdwStatus AS DWORD PTR) AS LONGINT PASCAL:OLE32.OleRegGetMiscStatus
_DLL FUNCTION OleRegGetUserType(clsid AS _winGUID,dwFormOfType AS DWORD,pszUserType AS PTR) AS LONGINT PASCAL:OLE32.OleRegGetUserType
_DLL FUNCTION CreateDataCache(pUnkOuter AS PTR,rclsid AS _winGUID,riid AS _winGUID,ppvObj AS OBJECT PTR) AS LONGINT PASCAL:OLE32.CreateDataCache
_DLL FUNCTION CoLockObjectExternal(oIUnknown AS PTR,lLock AS LOGIC,lLastUnlockReleases AS LOGIC) AS LONGINT PASCAL:OLE32.CoLockObjectExternal
_DLL FUNCTION ReleaseStgMedium(sMedium AS _WINSTGMEDIUM) AS VOID PASCAL:OLE32.ReleaseStgMedium
_DLL FUNCTION GetRunningObjectTable(reserved AS DWORD,pprot AS PTR) AS LONGINT PASCAL:OLE32.GetRunningObjectTable
_DLL FUNCTION CreateILockBytesOnHGlobal(hGlobal AS PTR,lDeleteOnRelease AS LOGIC,pILockBytes AS OBJECT PTR) AS LONGINT PASCAL:OLE32.CreateILockBytesOnHGlobal
_DLL FUNCTION StgCreateDocfileOnILockBytes(oILockBytes AS OBJECT,grfMode AS DWORD,nReserved AS DWORD,pIStorage AS OBJECT PTR) AS LONGINT PASCAL:OLE32.StgCreateDocfileOnILockBytes
_DLL FUNCTION OleGetClipboard(pIDataObject AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleGetClipboard
_DLL FUNCTION OleCreateFromData(oISrcDataObj AS PTR,riid AS _winGUID,renderopt AS DWORD,pFormatEtc AS _WINFormatEtc,oIClientSite AS PTR,oIStg AS PTR,pIUnknown AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleCreateFromData
_DLL FUNCTION OleGetIconOfClass(rclsid AS _winGUID,lpszLabel AS PTR,lUseTypeAsLabel AS LOGIC) AS PTR PASCAL:OLE32.OleGetIconOfClass
_DLL FUNCTION OleUIAddVerbMenu(lpOleObj AS PTR,lpszShortType AS PTR,hMenu AS PTR,uPos AS DWORD,uIDVerbMin AS DWORD,uIDVerbMax AS DWORD,lAddConvert AS LOGIC,idConvert AS DWORD,lphMenu AS PTR PTR) AS LOGIC PASCAL:OLEDlg.OleUIAddVerbMenuA
_DLL FUNCTION OleGetIconOfFile(lpszPath AS PTR,fUseFileAsLabel AS LOGIC) AS PTR PASCAL:OLE32.OleGetIconOfFile
_DLL FUNCTION OleCreateFromFile(rclsid AS _winGUID,lpszFileName AS PTR,riid AS _winGUID,renderopt AS DWORD,pFormatEtc AS _WINFORMATETC,oClientSite AS PTR,oStg AS PTR,pObject AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleCreateFromFile
_DLL FUNCTION GetClassFile(szFileName AS PTR,pclsid AS _winGUID) AS LONGINT PASCAL:OLE32.GetClassFile
_DLL FUNCTION OleCreateLinkToFile(lpszFileName AS PTR,riid AS _winGUID,renderopt AS DWORD,pFormatEtc AS _WINFORMATETC,oClientSite AS PTR,oStg AS PTR,pObject AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleCreateLinkToFile
_DLL FUNCTION OleUIInsertObject(sOleUIInsertObject AS _WINOLEUIINSERTOBJECT) AS DWORD PASCAL:OLEDLG.OleUIInsertObjectA
_DLL FUNCTION CoCreateInstance(rclsid AS _winGUID, oUnkOuter AS PTR, dwClsContext AS DWORD, riid AS _winGUID, ppv AS OBJECT PTR) AS LONGINT PASCAL:OLE32.CoCreateInstance
_DLL FUNCTION CLSIDFromProgID(lpszProgID AS PTR,pclsid AS _winGUID) AS LONGINT PASCAL:OLE32.CLSIDFromProgID
_DLL FUNCTION CLSIDFromString(lpszProgID AS PTR,pclsid IS _WinGUID) AS LONGINT PASCAL:OLE32.CLSIDFromString
_DLL FUNCTION ProgIDFromCLSID(pclsid AS _winGUID, lplpszProgID AS PTR PTR) AS LONGINT PASCAL:OLE32.ProgIDFromCLSID
_DLL FUNCTION OleSetMenuDescriptor(holemenu AS PTR,hwndFrame AS PTR,hwndActiveObject AS PTR,oIFrame AS OBJECT,oActiveObj AS OBJECT) AS LONGINT PASCAL:OLE32.OleSetMenuDescriptor
_DLL FUNCTION CreateFileMoniker(pFile AS PTR,ppmk AS OBJECT PTR) AS LONGINT PASCAL:OLE32.CreateFileMoniker
_DLL FUNCTION BindMoniker(pmk AS OBJECT,grfOpt AS DWORD,riid AS _winGUID,ppvObj AS OBJECT PTR) AS LONGINT PASCAL:OLE32.BindMoniker
_DLL FUNCTION CoFreeUnusedLibraries() AS VOID PASCAL:OLE32.CoFreeUnusedLibraries
_DLL FUNCTION OleIsRunning(oIOleObject AS PTR) AS LOGIC PASCAL:OLE32.OleIsRunning
_DLL FUNCTION CreateBindCtx(reserved AS DWORD,poIBindCtx AS OBJECT PTR) AS LONGINT PASCAL:OLE32.CreateBindCtx
_DLL FUNCTION OleCreate(sCLSID AS _winGUID,sRIID AS _winGUID,nRenderOpt AS DWORD,sFormatEtc AS _WINFORMATETC,oIClientSite AS PTR,IStg AS PTR,pObject AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleCreate
_DLL FUNCTION OleCreateStaticFromData(oISrcDataObj AS PTR,riid AS _winGUID,renderopt AS DWORD,pFormatEtc AS _WINFormatEtc,oIClientSite AS PTR,oIStg AS PTR,pIUnknown AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleCreateFromData
_DLL FUNCTION OleLoad(oIStorage AS PTR,sRIID AS _winGUID,oIClientSite AS PTR,oIUnknown AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleLoad
_DLL FUNCTION StgOpenStorage(pName AS PTR,oIPriority AS PTR,nMode AS DWORD,pExclude AS PTR,nReserved AS DWORD,poIStorage AS OBJECT PTR) AS LONGINT PASCAL:OLE32.StgOpenStorage
_DLL FUNCTION StringFromGUID2(sGUID AS _winGUID,pBuffer AS PTR,nBufferSize AS LONGINT) AS LONGINT PASCAL:OLE32.StringFromGUID2
_DLL FUNCTION OleCreateLinkFromData(oISrcDataObj AS PTR,riid AS _winGUID,renderopt AS DWORD,pFormatEtc AS _WINFormatEtc,oIClientSite AS PTR,oIStg AS PTR,pIUnknown AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleCreateLinkFromData
_DLL FUNCTION OleCreateLink(oIMoniker AS PTR,riid AS _winGUID,renderopt AS DWORD,pFormatEtc AS _WINFormatEtc,oIClientSite AS PTR,oIStg AS PTR,pIUnknown AS OBJECT PTR) AS LONGINT PASCAL:OLE32.OleCreateLink
_DLL FUNCTION CreateItemMoniker(pDelim AS PTR,pItem AS PTR,ppmk AS OBJECT PTR) AS LONGINT PASCAL:OLE32.CreateItemMoniker
_DLL FUNCTION OleFlushClipboard() AS LONGINT PASCAL:OLE32.OleFlushClipboard
_DLL FUNCTION OleIsCurrentClipboard(oIDataObject AS PTR) AS LONGINT PASCAL:OLE32.OleIsCurrentClipboard
_DLL FUNCTION OleSetClipboard(oIDataObject AS PTR) AS LONGINT PASCAL:OLE32.OleSetClipboard
_DLL FUNCTION CreateStreamOnHGlobal(hGlobal AS PTR, fDeleteOnRelease AS LOGIC, ppstm REF PTR) AS LONGINT PASCAL:OLE32.CreateStreamOnHGlobal

//Defines
UNION _WINSTGMEDIUM_DATA
	MEMBER hBitMap			AS PTR
	MEMBER hMetaFilePict	AS PTR
	MEMBER hEnhMetaFile 	AS PTR
	MEMBER hGlobal			AS PTR
	MEMBER lpszFileName	AS PSZ
	MEMBER pStm				AS PTR
	MEMBER pStg				AS PTR



#region defines
DEFINE TYMED_HGLOBAL                :=1
DEFINE TYMED_FILE                       :=2
DEFINE TYMED_ISTREAM                  :=4
DEFINE TYMED_ISTORAGE                 :=8
DEFINE TYMED_GDI                        :=16
DEFINE TYMED_MFPICT                     :=32
DEFINE TYMED_ENHMF                      :=64
DEFINE TYMED_NULL                       :=0
DEFINE DATADIR_GET                  :=1
DEFINE DATADIR_SET                  :=2
DEFINE DROPEFFECT_NONE              :=0
DEFINE DROPEFFECT_COPY              :=1
DEFINE DROPEFFECT_MOVE              :=2
DEFINE DROPEFFECT_LINK                :=4
DEFINE DROPEFFECT_SCROLL              :=0x80000000
DEFINE OLEMISC_RECOMPOSEONRESIZE        :=0x1
DEFINE OLEMISC_ONLYICONIC             :=0x2
DEFINE OLEMISC_INSERTNOTREPLACE         :=0x4
DEFINE OLEMISC_STATIC               :=0x8
DEFINE OLEMISC_CANTLINKINSIDE           :=0x10
DEFINE OLEMISC_CANLINKBYOLE1            :=0x20
DEFINE OLEMISC_ISLINKOBJECT           :=0x40
DEFINE OLEMISC_INSIDEOUT              :=0x80
DEFINE OLEMISC_ACTIVATEWHENVISIBLE        :=0x100
DEFINE OLEMISC_RENDERINGISDEVICEINDEPENDENT :=0x200
DEFINE OLEMISC_INVISIBLEATRUNTIME         :=0x400
DEFINE OLEMISC_ALWAYSRUN              :=0x800
DEFINE OLEMISC_ACTSLIKEBUTTON         :=0x1000
DEFINE OLEMISC_ACTSLIKELABEL            :=0x2000
DEFINE OLEMISC_NOUIACTIVATE           :=0x4000
DEFINE OLEMISC_ALIGNABLE              :=0x8000
DEFINE OLEMISC_SIMPLEFRAME            :=0x10000
DEFINE OLEMISC_SETCLIENTSITEFIRST         :=0x20000
DEFINE OLEMISC_IMEMODE              :=0x40000
DEFINE OLEMISC_IGNOREACTIVATEWHENVISIBLE    :=0x80000
DEFINE OLEMISC_WANTSTOMENUMERGE       :=0x100000
DEFINE OLEMISC_SUPPORTSMULTILEVELUNDO     :=0x200000
DEFINE OLEGETMONIKER_ONLYIFTHERE        :=1
DEFINE OLEGETMONIKER_FORCEASSIGN        :=2
DEFINE OLEGETMONIKER_UNASSIGN             :=3
DEFINE OLEGETMONIKER_TEMPFORUSER        :=4
DEFINE OLEWHICHMK_CONTAINER             :=1
DEFINE OLEWHICHMK_OBJREL                :=2
DEFINE OLEWHICHMK_OBJFULL               :=3
DEFINE PSSTATE_UNINIT               :=1
DEFINE PSSTATE_SCRIBBLE             :=2
DEFINE PSSTATE_HANDSOFF               :=3
DEFINE STREAM_SEEK_SET              :=0
DEFINE STREAM_SEEK_CUR              :=1
DEFINE STREAM_SEEK_END              :=2
DEFINE PSSTATE_ZOMBIE                 :=4
DEFINE OLERENDER_NONE                 :=0
DEFINE OLERENDER_DRAW                 :=1
DEFINE OLERENDER_FORMAT               :=2
DEFINE OLERENDER_ASIS                 :=3
DEFINE ADVF_NODATA                        :=1
DEFINE ADVF_PRIMEFIRST                :=2
DEFINE ADVF_ONLYONCE                        :=4
DEFINE ADVF_DATAONSTOP              :=64
DEFINE ADVFCACHE_NOHANDLER            :=8
DEFINE ADVFCACHE_FORCEBUILTIN           :=16
DEFINE ADVFCACHE_ONSAVE             :=32
DEFINE CLSCTX_REMOTE_SERVER           :=16
DEFINE CLSCTX_SERVER                :=CLSCTX_INPROC_SERVER+CLSCTX_LOCAL_SERVER
DEFINE CLSCTX_ALL                 :=CLSCTX_INPROC_HANDLER+CLSCTX_INPROC_SERVER+CLSCTX_LOCAL_SERVER
DEFINE HIMETRIC_PER_INCH              :=2540
DEFINE CFSTR_EMBEDSOURCE            :="Embed Source"
DEFINE CFSTR_EMBEDDEDOBJECT           :="Embedded Object"
DEFINE CFSTR_LINKSOURCE             :="Link Source"
DEFINE CFSTR_CUSTOMLINKSOURCE         :="Custom Link Source"
DEFINE CFSTR_OBJECTDESCRIPTOR           :="Object Descriptor"
DEFINE CFSTR_LINKSRCDESCRIPTOR          :="Link Source Descriptor"
DEFINE OLEUPDATE_ALWAYS                 :=1
DEFINE OLEUPDATE_ONCALL                 :=3
DEFINE OLELINKBIND_EVENIFCLASSDIFF        :=1
DEFINE TKIND_ENUM                 :=0
DEFINE TKIND_RECORD               :=TKIND_ENUM + 1
DEFINE TKIND_MODULE               :=TKIND_RECORD + 1
DEFINE TKIND_INTERFACE                :=TKIND_MODULE + 1
DEFINE TKIND_DISPATCH               :=TKIND_INTERFACE + 1
DEFINE TKIND_COCLASS                :=TKIND_DISPATCH + 1
DEFINE TKIND_ALIAS                  :=TKIND_COCLASS + 1
DEFINE TKIND_UNION                  :=TKIND_ALIAS + 1
DEFINE TKIND_MAX                  :=TKIND_UNION + 1
DEFINE DVASPECT_OPAQUE                    :=16
DEFINE DVASPECT_TRANSPARENT             :=32
DEFINE DVASPECTINFOFLAG_CANOPTIMIZE       :=1
DEFINE INVOKE_FUNC                  :=DISPATCH_METHOD
DEFINE MEMBERID_NIL                 :=DISPID_UNKNOWN
DEFINE CC_FASTCALL                  :=0
DEFINE CC_CDECL                   :=1
DEFINE CC_MSCPASCAL               :=CC_CDECL + 1
DEFINE CC_PASCAL                  :=CC_MSCPASCAL
DEFINE CC_MACPASCAL               :=CC_PASCAL + 1
DEFINE CC_STDCALL                 :=CC_MACPASCAL + 1
DEFINE CC_FPFASTCALL                :=CC_STDCALL + 1
DEFINE CC_SYSCALL                 :=CC_FPFASTCALL + 1
DEFINE CC_MPWCDECL                :=CC_SYSCALL + 1
DEFINE CC_MPWPASCAL               :=CC_MPWCDECL + 1
DEFINE CC_MAX                   :=CC_MPWPASCAL + 1
DEFINE FUNC_VIRTUAL               :=0
DEFINE FUNC_PUREVIRTUAL             :=FUNC_VIRTUAL + 1
DEFINE FUNC_NONVIRTUAL              :=FUNC_PUREVIRTUAL + 1
DEFINE FUNC_STATIC                  :=FUNC_NONVIRTUAL + 1
DEFINE FUNC_DISPATCH                :=FUNC_STATIC + 1
DEFINE IMPLTYPEFLAG_FDEFAULT              :=0x1
DEFINE IMPLTYPEFLAG_FSOURCE                 :=0x2
DEFINE IMPLTYPEFLAG_FRESTRICTED           :=0x4
DEFINE IMPLTYPEFLAG_FDEFAULTVTABLE        :=0x800
DEFINE VAR_PERINSTANCE              :=0
DEFINE VAR_STATIC                 :=VAR_PERINSTANCE+1
DEFINE VAR_CONST                  :=VAR_STATIC+1
DEFINE VAR_DISPATCH               :=VAR_CONST+1
DEFINE OLEIVERB_PROPERTIES            :=-7
DEFINE STGM_DIRECT                        :=0x00000000
DEFINE STGM_TRANSACTED                    :=0x00010000
DEFINE STGM_SIMPLE                          :=0x08000000
DEFINE STGM_READ                            :=0x00000000
DEFINE STGM_WRITE                           :=0x00000001
DEFINE STGM_READWRITE                       :=0x00000002
DEFINE STGM_SHARE_DENY_NONE             :=0x00000040
DEFINE STGM_SHARE_DENY_READ             :=0x00000030
DEFINE STGM_SHARE_DENY_WRITE            :=0x00000020
DEFINE STGM_SHARE_EXCLUSIVE             :=0x00000010
DEFINE STGM_PRIORITY                        :=0x00040000
DEFINE STGM_DELETEONRELEASE           :=0x04000000
DEFINE STGM_NOSCRATCH                     :=0x00100000
DEFINE STGM_CREATE                          :=0x00001000
DEFINE STGM_CONVERT                         :=0x00020000
DEFINE STGM_FAILIFTHERE                     :=0x00000000
DEFINE STGM_NOSNAPSHOT                    :=0x00200000
DEFINE ASYNC_MODE_COMPATIBILITY           :=0x00000001
DEFINE ASYNC_MODE_DEFAULT                   :=0x00000000
DEFINE STGTY_REPEAT                           :=0x00000100
DEFINE STG_TOEND                                :=0xFFFFFFFF
DEFINE STG_LAYOUT_SEQUENTIAL            :=0x00000000
DEFINE STG_LAYOUT_INTERLEAVED           :=0x00000001
DEFINE STGFMT_STORAGE                     :=0
DEFINE STGFMT_NATIVE                        :=1
DEFINE STGFMT_FILE                          :=3
DEFINE STGFMT_ANY                           :=4
DEFINE STGFMT_DOCFILE                       :=5
DEFINE MKSYS_NONE                 :=0
DEFINE MKSYS_GENERICCOMPOSITE         :=1
DEFINE MKSYS_FILEMONIKER              :=2
DEFINE MKSYS_ANTIMONIKER              :=3
DEFINE MKSYS_ITEMMONIKER              :=4
DEFINE MKSYS_POINTERMONIKER           :=5
DEFINE MKSYS_CLASSMONIKER           :=7
DEFINE OLECLOSE_NOSAVE                    :=1
DEFINE OLECLOSE_PROMPTSAVE              :=2
DEFINE OLECLOSE_SAVEIFDIRTY           :=0
DEFINE OLEIVERB_DISCARDUNDOSTATE        :=-6
DEFINE OLEIVERB_HIDE                          :=-3
DEFINE OLEIVERB_INPLACEACTIVATE           :=-5
DEFINE OLEIVERB_OPEN                          :=-2
DEFINE OLEIVERB_PRIMARY                     :=0
DEFINE OLEIVERB_SHOW                          :=-1
DEFINE OLEIVERB_UIACTIVATE                  :=-4
DEFINE USERCLASSTYPE_APPNAME              :=3
DEFINE USERCLASSTYPE_FULL                   :=1
DEFINE USERCLASSTYPE_SHORT              :=2
DEFINE CONNECT_E_FIRST              :=0x80040200	//RvdH 070116 Added 0x prefix
DEFINE CONNECT_E_ADVISELIMIT              :=CONNECT_E_FIRST+1
DEFINE CONNECT_E_CANNOTCONNECT        :=CONNECT_E_FIRST+2
DEFINE CONNECT_E_NOCONNECTION         :=CONNECT_E_FIRST+0
DEFINE CONNECT_E_OVERRIDDEN             :=CONNECT_E_FIRST+3
DEFINE STGTY_STORAGE                    :=1
DEFINE STGTY_STREAM                     :=2
DEFINE STGTY_LOCKBYTES                  :=3
DEFINE STGTY_PROPERTY                   :=4
//OLE UI Defines
DEFINE OLEUI_FALSE                              :=0
DEFINE OLEUI_SUCCESS                            :=1
DEFINE OLEUI_OK                                 :=1
DEFINE OLEUI_CANCEL                            :=2
DEFINE OLEUI_ERR_STANDARDMIN   			:=100
DEFINE OLEUI_ERR_OLEMEMALLOC   			:=100
DEFINE OLEUI_ERR_STRUCTURENULL      :=101
DEFINE OLEUI_ERR_STRUCTUREINVALID		:=102
DEFINE OLEUI_ERR_CBSTRUCTINCORRECT		:=103
DEFINE OLEUI_ERR_HWNDOWNERINVALID		:=104
DEFINE OLEUI_ERR_LPSZCAPTIONINVALID		:=105
DEFINE OLEUI_ERR_LPFNHOOKINVALID			:=106
DEFINE OLEUI_ERR_HINSTANCEINVALID			:=107
DEFINE OLEUI_ERR_LPSZTEMPLATEINVALID		:=108
DEFINE OLEUI_ERR_HRESOURCEINVALID		:=109
DEFINE OLEUI_ERR_FINDTEMPLATEFAILURE  :=110
DEFINE OLEUI_ERR_LOADTEMPLATEFAILURE	:=111
DEFINE OLEUI_ERR_DIALOGFAILURE			:=112
DEFINE OLEUI_ERR_LOCALMEMALLOC			:=113
DEFINE OLEUI_ERR_GLOBALMEMALLOC			:=114
DEFINE OLEUI_ERR_LOADSTRING				:=115
DEFINE OLEUI_ERR_STANDARDMAX      :=116
DEFINE IOF_SHOWHELP						:=0x00000001L
DEFINE IOF_SELECTCREATENEW				:=0x00000002L
DEFINE IOF_SELECTCREATEFROMFILE			:=0x00000004L
DEFINE IOF_CHECKLINK						:=0x00000008L
DEFINE IOF_CHECKDISPLAYASICON				:=0x00000010L
DEFINE IOF_CREATENEWOBJECT				:=0x00000020L
DEFINE IOF_CREATEFILEOBJECT				:=0x00000040L
DEFINE IOF_CREATELINKOBJECT				:=0x00000080L
DEFINE IOF_DISABLELINK						:=0x00000100L
DEFINE IOF_VERIFYSERVERSEXIST				:=0x00000200L
DEFINE IOF_DISABLEDISPLAYASICON			:=0x00000400L
DEFINE IOF_HIDECHANGEICON					:=0x00000800L
DEFINE IOF_SHOWINSERTCONTROL			:=0x00001000L
DEFINE IOF_SELECTCREATECONTROL			:=0x00002000L
DEFINE OLEUI_IOERR_LPSZFILEINVALID			:=(OLEUI_ERR_STANDARDMAX+0)
DEFINE OLEUI_IOERR_LPSZLABELINVALID		:=(OLEUI_ERR_STANDARDMAX+1)
DEFINE OLEUI_IOERR_HICONINVALID			:=(OLEUI_ERR_STANDARDMAX+2)
DEFINE OLEUI_IOERR_LPFORMATETCINVALID	:=(OLEUI_ERR_STANDARDMAX+3)
DEFINE OLEUI_IOERR_PPVOBJINVALID			:=(OLEUI_ERR_STANDARDMAX+4)
DEFINE OLEUI_IOERR_LPIOLECLIENTSITEINVALID:=(OLEUI_ERR_STANDARDMAX+5)
DEFINE OLEUI_IOERR_LPISTORAGEINVALID		:=(OLEUI_ERR_STANDARDMAX+6)
DEFINE OLEUI_IOERR_SCODEHASERROR		:=(OLEUI_ERR_STANDARDMAX+7)
DEFINE OLEUI_IOERR_LPCLSIDEXCLUDEINVALID	:=(OLEUI_ERR_STANDARDMAX+8)
DEFINE OLEUI_IOERR_CCHFILEINVALID			:=(OLEUI_ERR_STANDARDMAX+9)
#endregion
