VOSTRUCT _WINOPENFILENAME ALIGN 1
	MEMBER  lStructSize AS DWORD
	MEMBER  hwndOwner AS PTR
	MEMBER  hInstance AS PTR
	MEMBER  lpstrFilter AS PSZ
	MEMBER  lpstrCustomFilter AS PSZ
	MEMBER  nMaxCustFilter AS DWORD
	MEMBER  nFilterIndex AS DWORD
	MEMBER  lpstrFile AS PSZ
	MEMBER  nMaxFile AS DWORD
	MEMBER  lpstrFileTitle AS PSZ
	MEMBER  nMaxFileTitle AS DWORD
	MEMBER  lpstrInitialDir AS PSZ
	MEMBER  lpstrTitle AS PSZ
	MEMBER  Flags AS DWORD
	MEMBER  nFileOffset AS WORD
	MEMBER  nFileExtension AS WORD
	MEMBER  lpstrDefExt AS PSZ
	MEMBER  lCustData AS LONGINT
	MEMBER  lpfnHook AS PTR
	MEMBER  lpTemplateName AS PSZ
	MEMBER  pvReserved AS PTR
	MEMBER  dwReserved AS PTR
	MEMBER  FlagsEx AS DWORD

VOSTRUCT _winOFNOTIFY ALIGN 1
	MEMBER  hdr IS _winNMHDR
	MEMBER  lpOFN AS _winOPENFILENAME
	MEMBER  pszFile AS PSZ


VOSTRUCT _winCHOOSECOLOR ALIGN 1
	MEMBER  lStructSize AS DWORD
	MEMBER  hwndOwner AS PTR
	MEMBER  hInstance AS PTR
	MEMBER  rgbResult AS DWORD
	MEMBER  lpCustColors AS PTR
	MEMBER  Flags AS DWORD
	MEMBER  lCustData AS LONGINT
	MEMBER  lpfnHook AS PTR
	MEMBER  lpTemplateName AS PSZ


VOSTRUCT _winFINDREPLACE  ALIGN 1
	MEMBER  lStructSize AS DWORD
	MEMBER  hwndOwner AS PTR
	MEMBER  hInstance AS PTR

	MEMBER  Flags AS DWORD
	MEMBER  lpstrFindWhat AS PSZ
	MEMBER  lpstrReplaceWith AS PSZ
	MEMBER  wFindWhatLen AS WORD
	MEMBER  wReplaceWithLen AS WORD
	MEMBER  lCustData AS LONGINT
	MEMBER  lpfnHook AS PTR
	MEMBER  lpTemplateName AS PSZ


VOSTRUCT _winCHOOSEFONT 	 ALIGN 1
	MEMBER  lStructSize 	AS DWORD
	MEMBER  hwndOwner AS PTR
	MEMBER  hDC AS PTR
	MEMBER  lpLogFont  AS _winLOGFONT
	MEMBER  iPointSize AS INT
	MEMBER  Flags AS DWORD
	MEMBER  rgbColors AS DWORD
	MEMBER  lCustData AS LONGINT
	MEMBER  lpfnHook AS PTR
	MEMBER  lpTemplateName AS PSZ
	MEMBER  hInstance AS PTR

	MEMBER  lpszStyle AS PSZ

	MEMBER  nFontType AS WORD


	MEMBER  ___MISSING_ALIGNMENT__ AS WORD
	MEMBER  nSizeMin AS INT
	MEMBER  nSizeMax AS INT







VOSTRUCT _WINPRINTDLG  ALIGN 1
	MEMBER  lStructSize AS DWORD
	MEMBER  hwndOwner AS PTR
	MEMBER  hDevMode AS PTR
	MEMBER  hDevNames AS PTR
	MEMBER  hDC AS PTR
	MEMBER  Flags AS DWORD
	MEMBER  nFromPage AS WORD
	MEMBER  nToPage AS WORD
	MEMBER  nMinPage AS WORD
	MEMBER  nMaxPage AS WORD
	MEMBER  nCopies AS WORD
	MEMBER  hInstance AS PTR
	MEMBER  lCustData AS LONGINT
	MEMBER  lpfnPrintHook AS PTR
	MEMBER  lpfnSetupHook AS PTR
	MEMBER  lpPrintTemplateName AS PSZ
	MEMBER  lpSetupTemplateName AS PSZ
	MEMBER  hPrintTemplate AS PTR
	MEMBER  hSetupTemplate AS PTR  

VOSTRUCT _winDEVNAMES  ALIGN 1
	MEMBER  wDriverOffset AS WORD
	MEMBER  wDeviceOffset AS WORD
	MEMBER  wOutputOffset AS WORD
	MEMBER  wDefault AS WORD


VOSTRUCT _winPAGESETUPDLG ALIGN 1
	MEMBER lStructSize AS DWORD
	MEMBER hwndOwner AS PTR
	MEMBER hDevMode AS PTR
	MEMBER hDevNames AS PTR
	MEMBER Flags AS DWORD
	MEMBER ptPaperSize IS _winPOINT
	MEMBER rtMinMargin IS _winRECT
	MEMBER rtMargin IS _winRECT
	MEMBER hInstance AS PTR
	MEMBER lCustData AS LONGINT
	MEMBER lpfnPageSetupHook AS PTR
	MEMBER lpfnPagePaintHook AS PTR
	MEMBER lpPageSetupTemplateName AS PSZ
	MEMBER hPageSetupTemplate AS PTR



_DLL FUNC GetOpenFileName(lpofn AS _winOPENFILENAME) AS LOGIC PASCAL:comdlg32.GetOpenFileNameA



_DLL FUNC GetSaveFileName(lpofn AS _winOPENFILENAME) AS LOGIC PASCAL:COMDLG32.GetSaveFileNameA



_DLL FUNC GetFileTitle(lpszFile AS PSZ, lpszTitle AS PSZ, cbBuf AS DWORD) AS SHORT PASCAL:COMDLG32.GetFileTitleA


FUNCTION CommDlg_OpenSave_GetSpec(_hdlg AS PTR, _psz AS LONGINT, _cbmax AS DWORD) AS DWORD STRICT
	RETURN DWORD(_CAST,SendMessage(_hdlg, CDM_GETSPEC, _cbmax, _psz))



// lParam = pointer to text buffer that gets filled in
// wParam = max number of characters of the text buffer (including NULL)
// return = < 0 if error; number of characters needed (including NULL)
FUNCTION CommDlg_OpenSave_GetFilePath(_hdlg AS PTR, _psz AS LONGINT, _cbmax AS DWORD) AS DWORD STRICT
	RETURN DWORD(_CAST,SendMessage(_hdlg, CDM_GETFILEPATH, _cbmax, _psz))



// lParam = pointer to text buffer that gets filled in
// wParam = max number of characters of the text buffer (including NULL)
// return = < 0 if error; number of characters needed (including NULL)
FUNCTION CommDlg_OpenSave_GetFolderPath(_hdlg AS PTR , _psz AS LONGINT, _cbmax AS DWORD) AS DWORD STRICT
	RETURN DWORD(_CAST,SendMessage(_hdlg, CDM_GETFOLDERPATH, _cbmax, _psz))


// lParam = pointer to ITEMIDLIST buffer that gets filled in
// wParam = size of the ITEMIDLIST buffer
// return = < 0 if error; length of buffer needed
FUNCTION CommDlg_OpenSave_GetFolderIDList(_hdlg AS PTR, _pidl AS LONGINT, _cbmax AS DWORD) AS DWORD STRICT
	RETURN  DWORD(_CAST,SendMessage(_hdlg, CDM_GETFOLDERIDLIST, _cbmax, _pidl))



FUNCTION CommDlg_OpenSave_SetControlText(_hdlg AS PTR, _id AS DWORD, _text AS LONGINT) AS VOID STRICT
	SendMessage(_hdlg, CDM_SETCONTROLTEXT, _id, _text)
   RETURN


FUNCTION CommDlg_OpenSave_HideControl(_hdlg AS PTR, _id AS DWORD) AS VOID STRICT
	SendMessage   (_hdlg, CDM_HIDECONTROL, _id, 0)
   RETURN


FUNCTION CommDlg_OpenSave_SetDefExt(_hdlg AS PTR, _pszext AS LONGINT) AS VOID STRICT
	SendMessage(_hdlg, CDM_SETDEFEXT, 0, _pszext)
   RETURN


_DLL FUNC ChooseColor( lpcc AS _winCHOOSECOLOR) AS LOGIC PASCAL:COMDLG32.ChooseColorA


_DLL FUNC FindText( lpfr AS _winFINDREPLACE) AS PTR PASCAL:COMDLG32.FindTextA



_DLL FUNC ReplaceText(lpfr AS _winFINDREPLACE) AS PTR PASCAL:COMDLG32.ReplaceTextA



_DLL FUNC ChooseFont(lpcf AS _winCHOOSEFONT) AS LOGIC PASCAL:COMDLG32.ChooseFontA


_DLL FUNC PrintDlg(lppd AS _WINPRINTDLG) AS LOGIC PASCAL:COMDLG32.PrintDlgA



_DLL FUNC CommDlgExtendedError() AS DWORD PASCAL:COMDLG32.CommDlgExtendedError


_DLL FUNC PageSetupDlg( lppd AS _winPAGESETUPDLG) AS LOGIC PASCAL:COMDLG32.PageSetupDlgA



#region defines
DEFINE OPENFILENAME_SIZE_VERSION_400 := 76
DEFINE OFN_READONLY                 := 0x00000001
DEFINE OFN_OVERWRITEPROMPT          := 0x00000002
DEFINE OFN_HIDEREADONLY             := 0x00000004
DEFINE OFN_NOCHANGEDIR              := 0x00000008
DEFINE OFN_SHOWHELP                 := 0x00000010
DEFINE OFN_ENABLEHOOK               := 0x00000020
DEFINE OFN_ENABLETEMPLATE           := 0x00000040
DEFINE OFN_ENABLETEMPLATEHANDLE     := 0x00000080
DEFINE OFN_NOVALIDATE               := 0x00000100
DEFINE OFN_ALLOWMULTISELECT         := 0x00000200
DEFINE OFN_EXTENSIONDIFFERENT       := 0x00000400
DEFINE OFN_PATHMUSTEXIST            := 0x00000800
DEFINE OFN_FILEMUSTEXIST            := 0x00001000
DEFINE OFN_CREATEPROMPT             := 0x00002000
DEFINE OFN_SHAREAWARE               := 0x00004000
DEFINE OFN_NOREADONLYRETURN         := 0x00008000
DEFINE OFN_NOTESTFILECREATE         := 0x00010000
DEFINE OFN_NONETWORKBUTTON          := 0x00020000
DEFINE OFN_NOLONGNAMES              := 0x00040000
DEFINE OFN_EXPLORER                 := 0x00080000
DEFINE OFN_NODEREFERENCELINKS       := 0x00100000
DEFINE OFN_LONGNAMES                := 0x00200000
DEFINE OFN_ENABLEINCLUDENOTIFY      := 0x00400000     // send include message to callback
DEFINE OFN_ENABLESIZING 				:= 0x00800000
DEFINE OFN_DONTADDTORECENT          := 0x02000000
DEFINE OFN_FORCESHOWHIDDEN          := 0x10000000    // Show All files including System and hidden files
DEFINE OFN_SHAREFALLTHROUGH     := 2
DEFINE OFN_SHARENOWARN          := 1
DEFINE OFN_SHAREWARN            := 0
DEFINE OFN_EX_NOPLACESBAR := 0x00000001
DEFINE CDN_INITDONE            := (CDN_FIRST - 0x0000)
DEFINE CDN_SELCHANGE           := (CDN_FIRST - 0x0001)
DEFINE CDN_FOLDERCHANGE        := (CDN_FIRST - 0x0002)
DEFINE CDN_SHAREVIOLATION      := (CDN_FIRST - 0x0003)
DEFINE CDN_HELP                := (CDN_FIRST - 0x0004)
DEFINE CDN_FILEOK              := (CDN_FIRST - 0x0005)
DEFINE CDN_TYPECHANGE          := (CDN_FIRST - 0x0006)
DEFINE CDN_INCLUDEITEM         := (CDN_FIRST - 0x0007)
DEFINE CDM_FIRST       := WM_USER +100
DEFINE CDM_LAST        := WM_USER +200
// Messages to query information from the Open or Save dialogs
// lParam = pointer to text buffer that gets filled in
// wParam = max number of characters of the text buffer (including NULL)
// return = < 0 if error; number of characters needed (including NULL)
DEFINE CDM_GETSPEC             := (CDM_FIRST + 0x0000)
DEFINE CDM_GETFILEPATH         := (CDM_FIRST + 0x0001)
DEFINE CDM_GETFOLDERPATH       := (CDM_FIRST + 0x0002)
DEFINE CDM_GETFOLDERIDLIST     := (CDM_FIRST + 0x0003)
DEFINE CDM_SETCONTROLTEXT      := (CDM_FIRST + 0x0004)
DEFINE CDM_HIDECONTROL         := (CDM_FIRST + 0x0005)
DEFINE CDM_SETDEFEXT           := (CDM_FIRST + 0x0006)
DEFINE CC_RGBINIT               := 0x00000001
DEFINE CC_FULLOPEN              := 0x00000002
DEFINE CC_PREVENTFULLOPEN       := 0x00000004
DEFINE CC_SHOWHELP              := 0x00000008
DEFINE CC_ENABLEHOOK            := 0x00000010
DEFINE CC_ENABLETEMPLATE        := 0x00000020
DEFINE CC_ENABLETEMPLATEHANDLE  := 0x00000040
DEFINE CC_SOLIDCOLOR            := 0x00000080
DEFINE CC_ANYCOLOR              := 0x00000100
DEFINE FR_DOWN                         := 0x00000001
DEFINE FR_WHOLEWORD                    := 0x00000002
DEFINE FR_MATCHCASE                    := 0x00000004
DEFINE FR_FINDNEXT                     := 0x00000008
DEFINE FR_REPLACE                      := 0x00000010
DEFINE FR_REPLACEALL                   := 0x00000020
DEFINE FR_DIALOGTERM                   := 0x00000040
DEFINE FR_SHOWHELP                     := 0x00000080
DEFINE FR_ENABLEHOOK                   := 0x00000100
DEFINE FR_ENABLETEMPLATE               := 0x00000200
DEFINE FR_NOUPDOWN                     := 0x00000400
DEFINE FR_NOMATCHCASE                  := 0x00000800
DEFINE FR_NOWHOLEWORD                  := 0x00001000
DEFINE FR_ENABLETEMPLATEHANDLE         := 0x00002000
DEFINE FR_HIDEUPDOWN                   := 0x00004000
DEFINE FR_HIDEMATCHCASE                := 0x00008000
DEFINE FR_HIDEWHOLEWORD                := 0x00010000
DEFINE FR_RAW                          := 0x00020000
DEFINE FR_MATCHDIAC                    := 0x20000000
DEFINE FR_MATCHKASHIDA                 := 0x40000000
DEFINE FR_MATCHALEFHAMZA               := 0x80000000
DEFINE CF_SCREENFONTS             := 0x00000001
DEFINE CF_PRINTERFONTS            := 0x00000002
DEFINE CF_BOTH                    := 0x00000003
DEFINE CF_SHOWHELP                := 0x00000004L
DEFINE CF_ENABLEHOOK              := 0x00000008L
DEFINE CF_ENABLETEMPLATE          := 0x00000010L
DEFINE CF_ENABLETEMPLATEHANDLE    := 0x00000020L
DEFINE CF_INITTOLOGFONTSTRUCT     := 0x00000040L
DEFINE CF_USESTYLE                := 0x00000080L
DEFINE CF_EFFECTS                 := 0x00000100L
DEFINE CF_APPLY                   := 0x00000200L
DEFINE CF_ANSIONLY                := 0x00000400L
DEFINE CF_SCRIPTSONLY             := CF_ANSIONLY
DEFINE CF_NOVECTORFONTS           := 0x00000800L
DEFINE CF_NOOEMFONTS              := CF_NOVECTORFONTS
DEFINE CF_NOSIMULATIONS           := 0x00001000L
DEFINE CF_LIMITSIZE               := 0x00002000L
DEFINE CF_FIXEDPITCHONLY          := 0x00004000L
DEFINE CF_WYSIWYG                 := 0x00008000L
DEFINE CF_FORCEFONTEXIST          := 0x00010000L
DEFINE CF_SCALABLEONLY            := 0x00020000L
DEFINE CF_TTONLY                  := 0x00040000L
DEFINE CF_NOFACESEL               := 0x00080000L
DEFINE CF_NOSTYLESEL              := 0x00100000L
DEFINE CF_NOSIZESEL               := 0x00200000L
DEFINE CF_SELECTSCRIPT           :=  0x00400000L
DEFINE CF_NOSCRIPTSEL            :=  0x00800000L
DEFINE CF_NOVERTFONTS            :=  0x01000000L
// these are extra nFontType bits that are added to what is returned to the
// EnumFonts callback routine
DEFINE SIMULATED_FONTTYPE    := 0x8000
DEFINE PRINTER_FONTTYPE      := 0x4000
DEFINE SCREEN_FONTTYPE       := 0x2000
DEFINE BOLD_FONTTYPE         := 0x0100
DEFINE ITALIC_FONTTYPE       := 0x0200
DEFINE REGULAR_FONTTYPE      := 0x0400
DEFINE PS_OPENTYPE_FONTTYPE  := 0x10000
DEFINE TT_OPENTYPE_FONTTYPE  := 0x20000
DEFINE TYPE1_FONTTYPE        := 0x40000
DEFINE WM_CHOOSEFONT_GETLOGFONT      := (WM_USER + 1)
DEFINE WM_CHOOSEFONT_SETLOGFONT      := (WM_USER + 101)
DEFINE WM_CHOOSEFONT_SETFLAGS        := (WM_USER + 102)
// strings used to obtain unique window message for communication
// between dialog and caller
DEFINE LBSELCHSTRING := "commdlg_LBSelChangedNotify"
DEFINE SHAREVISTRING  := "commdlg_ShareViolation"
DEFINE FILEOKSTRING   := "commdlg_FileNameOK"
DEFINE COLOROKSTRING  := "commdlg_ColorOK"
DEFINE SETRGBSTRING   := "commdlg_SetRGBColor"
DEFINE HELPMSGSTRING  := "commdlg_help"
DEFINE FINDMSGSTRING  := "commdlg_FindReplace"
// HIWORD values for lParam of commdlg_LBSelChangeNotify message
DEFINE CD_LBSELNOITEMS := -1
DEFINE CD_LBSELCHANGE  :=  0
DEFINE CD_LBSELSUB     :=  1
DEFINE CD_LBSELADD     :=  2
DEFINE PD_ALLPAGES                  := 0x00000000
DEFINE PD_SELECTION                 := 0x00000001
DEFINE PD_PAGENUMS                  := 0x00000002
DEFINE PD_NOSELECTION               := 0x00000004
DEFINE PD_NOPAGENUMS                := 0x00000008
DEFINE PD_COLLATE                   := 0x00000010
DEFINE PD_PRINTTOFILE               := 0x00000020
DEFINE PD_PRINTSETUP                := 0x00000040
DEFINE PD_NOWARNING                 := 0x00000080
DEFINE PD_RETURNDC                  := 0x00000100
DEFINE PD_RETURNIC                  := 0x00000200
DEFINE PD_RETURNDEFAULT             := 0x00000400
DEFINE PD_SHOWHELP                  := 0x00000800
DEFINE PD_ENABLEPRINTHOOK           := 0x00001000
DEFINE PD_ENABLESETUPHOOK           := 0x00002000
DEFINE PD_ENABLEPRINTTEMPLATE       := 0x00004000
DEFINE PD_ENABLESETUPTEMPLATE       := 0x00008000
DEFINE PD_ENABLEPRINTTEMPLATEHANDLE := 0x00010000
DEFINE PD_ENABLESETUPTEMPLATEHANDLE := 0x00020000
DEFINE PD_USEDEVMODECOPIES          := 0x00040000
DEFINE PD_USEDEVMODECOPIESANDCOLLATE := 0x00040000
DEFINE PD_DISABLEPRINTTOFILE        := 0x00080000
DEFINE PD_HIDEPRINTTOFILE           := 0x00100000
DEFINE PD_NONETWORKBUTTON           := 0x00200000
DEFINE PD_CURRENTPAGE                 := 0x00400000
DEFINE PD_NOCURRENTPAGE               := 0x00800000
DEFINE PD_EXCLUSIONFLAGS              := 0x01000000
DEFINE PD_USELARGETEMPLATE            := 0x10000000
DEFINE PD_EXCL_COPIESANDCOLLATE       := (DM_COPIES | DM_COLLATE)
DEFINE DN_DEFAULTPRN      := 0x0001
DEFINE WM_PSD_PAGESETUPDLG     := (WM_USER  )
DEFINE WM_PSD_FULLPAGERECT     := (WM_USER+1)
DEFINE WM_PSD_MINMARGINRECT    := (WM_USER+2)
DEFINE WM_PSD_MARGINRECT       := (WM_USER+3)
DEFINE WM_PSD_GREEKTEXTRECT    := (WM_USER+4)
DEFINE WM_PSD_ENVSTAMPRECT     := (WM_USER+5)
DEFINE WM_PSD_YAFULLPAGERECT   := (WM_USER+6)
DEFINE PSD_DEFAULTMINMARGINS             := 0x00000000
DEFINE PSD_INWININIINTLMEASURE           := 0x00000000
DEFINE PSD_MINMARGINS                    := 0x00000001
DEFINE PSD_MARGINS                       := 0x00000002
DEFINE PSD_INTHOUSANDTHSOFINCHES         := 0x00000004
DEFINE PSD_INHUNDREDTHSOFMILLIMETERS     := 0x00000008
DEFINE PSD_DISABLEMARGINS                := 0x00000010
DEFINE PSD_DISABLEPRINTER                := 0x00000020
DEFINE PSD_NOWARNING                     := 0x00000080
DEFINE PSD_DISABLEORIENTATION            := 0x00000100
DEFINE PSD_RETURNDEFAULT                 := 0x00000400
DEFINE PSD_DISABLEPAPER                  := 0x00000200
DEFINE PSD_SHOWHELP                      := 0x00000800
DEFINE PSD_ENABLEPAGESETUPHOOK           := 0x00002000
DEFINE PSD_ENABLEPAGESETUPTEMPLATE       := 0x00008000
DEFINE PSD_ENABLEPAGESETUPTEMPLATEHANDLE := 0x00020000
DEFINE PSD_ENABLEPAGEPAINTHOOK           := 0x00040000
DEFINE PSD_DISABLEPAGEPAINTING           := 0x00080000
DEFINE PSD_NONETWORKBUTTON               := 0x00200000 // must be same as PD_*
#endregion
