VOSTRUCT _winNCB
	MEMBER  ncb_command AS BYTE
	MEMBER  ncb_retcode  AS BYTE
	MEMBER  ncb_lsn AS BYTE
	MEMBER ncb_num AS BYTE
	MEMBER  ncb_buffer AS PTR
	MEMBER  ncb_length AS WORD
	MEMBER  DIM ncb_callname[NCBNAMSZ] AS BYTE
	MEMBER  DIM ncb_name[NCBNAMSZ] AS BYTE
	MEMBER  ncb_rto AS BYTE
	MEMBER  ncb_sto AS BYTE
	MEMBER  ncb_postproc AS PTR
	MEMBER  ncb_lana_num AS BYTE
	MEMBER  ncb_cmd_cplt AS BYTE
	MEMBER  DIM ncb_reserve[10] AS BYTE
	MEMBER  ncb_event AS PTR







VOSTRUCT _winADAPTER_STATUS
	MEMBER DIM  adapter_address[6] AS BYTE
	MEMBER  rev_major AS BYTE
	MEMBER  reserved0 AS BYTE
	MEMBER  adapter_type AS BYTE
	MEMBER  rev_minor AS BYTE
	MEMBER  duration AS WORD
	MEMBER  frmr_recv AS WORD
	MEMBER  frmr_xmit AS WORD

	MEMBER  iframe_recv_err AS WORD

	MEMBER  xmit_aborts AS WORD
	MEMBER  xmit_success AS DWORD
	MEMBER  recv_success AS DWORD

	MEMBER  iframe_xmit_err AS WORD

	MEMBER  recv_buff_unavail AS WORD
	MEMBER  t1_timeouts AS WORD
	MEMBER  ti_timeouts AS WORD
	MEMBER  reserved1 AS DWORD
	MEMBER  free_ncbs AS WORD
	MEMBER  max_cfg_ncbs AS WORD
	MEMBER  max_ncbs AS WORD
	MEMBER  xmit_buf_unavail AS WORD
	MEMBER  max_dgram_size AS WORD
	MEMBER  pending_sess AS WORD
	MEMBER  max_cfg_sess AS WORD
	MEMBER  max_sess AS WORD
	MEMBER  max_sess_pkt_size AS WORD
	MEMBER  name_count AS WORD


VOSTRUCT _winNAME_BUFFER
	MEMBER DIM  name[NCBNAMSZ] AS BYTE
	MEMBER  name_num AS BYTE
	MEMBER  name_flags AS BYTE


VOSTRUCT _winSESSION_HEADER
	MEMBER  sess_name AS BYTE
	MEMBER  num_sess AS BYTE
	MEMBER  rcv_dg_outstanding AS BYTE
	MEMBER  rcv_any_outstanding AS BYTE


VOSTRUCT _winSESSION_BUFFER
	MEMBER  lsn AS BYTE
	MEMBER  state AS BYTE
	MEMBER  DIM local_name[NCBNAMSZ] AS BYTE
	MEMBER  DIM remote_name[NCBNAMSZ] AS BYTE
	MEMBER  rcvs_outstanding AS BYTE
	MEMBER  sends_outstanding AS BYTE


VOSTRUCT _winLANA_ENUM
	MEMBER  length AS BYTE
	MEMBER DIM  lana[MAX_LANA+1] AS BYTE



VOSTRUCT _winFIND_NAME_HEADER
	MEMBER  node_count AS WORD
	MEMBER  reserved AS BYTE
	MEMBER  unique_group AS BYTE

VOSTRUCT _winFIND_NAME_BUFFER
	MEMBER  length AS BYTE
	MEMBER  access_control AS BYTE
	MEMBER  frame_control AS BYTE
	MEMBER  DIM destination_addr[6] AS BYTE
	MEMBER  DIM source_addr[6] AS BYTE
	MEMBER  DIM routing_info[18] AS BYTE



VOSTRUCT _winACTION_HEADER
	MEMBER  transport_id AS DWORD
	MEMBER  action_code AS WORD
	MEMBER  reserved AS WORD


_DLL FUNC Netbios(pncb AS  _winNCB) AS BYTE PASCAL:NETAPI32.Netbios



#region defines
DEFINE NCBNAMSZ        := 16
DEFINE MAX_LANA        := 254
DEFINE NAME_FLAGS_MASK := 0x87
DEFINE GROUP_NAME      := 0x80
DEFINE UNIQUE_NAME     := 0x00
DEFINE REGISTERING     := 0x00
DEFINE REGISTERED      := 0x04
DEFINE DEREGISTERED    := 0x05
DEFINE DUPLICATE       := 0x06
DEFINE DUPLICATE_DEREG := 0x07
DEFINE LISTEN_OUTSTANDING      := 0x01
DEFINE CALL_PENDING            := 0x02
DEFINE SESSION_ESTABLISHED     := 0x03
DEFINE HANGUP_PENDING          := 0x04
DEFINE HANGUP_COMPLETE         := 0x05
DEFINE SESSION_ABORTED         := 0x06
DEFINE ALL_TRANSPORTS  := "M\0\0\0"
DEFINE MS_NBF          := "MNBF"
DEFINE NCBCALL         := 0x10
DEFINE NCBLISTEN       := 0x11
DEFINE NCBHANGUP       := 0x12
DEFINE NCBSEND         := 0x14
DEFINE NCBRECV         := 0x15
DEFINE NCBRECVANY      := 0x16
DEFINE NCBCHAINSEND    := 0x17
DEFINE NCBDGSEND       := 0x20
DEFINE NCBDGRECV       := 0x21
DEFINE NCBDGSENDBC     := 0x22
DEFINE NCBDGRECVBC     := 0x23
DEFINE NCBADDNAME      := 0x30
DEFINE NCBDELNAME      := 0x31
DEFINE NCBRESET        := 0x32
DEFINE NCBASTAT        := 0x33
DEFINE NCBSSTAT        := 0x34
DEFINE NCBCANCEL       := 0x35
DEFINE NCBADDGRNAME    := 0x36
DEFINE NCBENUM         := 0x37
DEFINE NCBUNLINK       := 0x70
DEFINE NCBSENDNA       := 0x71
DEFINE NCBCHAINSENDNA  := 0x72
DEFINE NCBLANSTALERT   := 0x73
DEFINE NCBACTION       := 0x77
DEFINE NCBFINDNAME     := 0x78
DEFINE NCBTRACE        := 0x79
DEFINE ASYNCH          := 0x80
DEFINE NRC_GOODRET     := 0x00
DEFINE NRC_BUFLEN      := 0x01
DEFINE NRC_ILLCMD      := 0x03
DEFINE NRC_CMDTMO      := 0x05
DEFINE NRC_INCOMP      := 0x06
DEFINE NRC_BADDR       := 0x07
DEFINE NRC_SNUMOUT     := 0x08
DEFINE NRC_NORES       := 0x09
DEFINE NRC_SCLOSED     := 0x0a
DEFINE NRC_CMDCAN      := 0x0b
DEFINE NRC_DUPNAME     := 0x0d
DEFINE NRC_NAMTFUL     := 0x0e
DEFINE NRC_ACTSES      := 0x0f
DEFINE NRC_LOCTFUL     := 0x11
DEFINE NRC_REMTFUL     := 0x12
DEFINE NRC_ILLNN       := 0x13
DEFINE NRC_NOCALL      := 0x14
DEFINE NRC_NOWILD      := 0x15
DEFINE NRC_INUSE       := 0x16
DEFINE NRC_NAMERR      := 0x17
DEFINE NRC_SABORT      := 0x18
DEFINE NRC_NAMCONF     := 0x19
DEFINE NRC_IFBUSY      := 0x21
DEFINE NRC_TOOMANY     := 0x22
DEFINE NRC_BRIDGE      := 0x23
DEFINE NRC_CANOCCR     := 0x24
DEFINE NRC_CANCEL      := 0x26
DEFINE NRC_DUPENV      := 0x30
DEFINE NRC_ENVNOTDEF   := 0x34
DEFINE NRC_OSRESNOTAV  := 0x35
DEFINE NRC_MAXAPPS     := 0x36
DEFINE NRC_NOSAPS      := 0x37
DEFINE NRC_NORESOURCES := 0x38
DEFINE NRC_INVADDRESS  := 0x39
DEFINE NRC_INVDDID     := 0x3B
DEFINE NRC_LOCKFAIL    := 0x3C
DEFINE NRC_OPENERR     := 0x3f
DEFINE NRC_SYSTEM      := 0x40
DEFINE NRC_PENDING     := 0xff
#endregion
