VOSTRUCT _winLAYERPLANEDESCRIPTOR
	MEMBER nSize AS WORD
	MEMBER nVersion AS WORD
	MEMBER dwFlags AS DWORD
	MEMBER iPixelType AS BYTE
	MEMBER cColorBits AS BYTE
	MEMBER cRedBits AS BYTE
	MEMBER cRedShift AS BYTE
	MEMBER cGreenBits AS BYTE
	MEMBER cGreenShift AS BYTE
	MEMBER cBlueBits AS BYTE
	MEMBER cBlueShift AS BYTE
	MEMBER cAlphaBits AS BYTE
	MEMBER cAlphaShift AS BYTE
	MEMBER cAccumBits AS BYTE
	MEMBER cAccumRedBits AS BYTE
	MEMBER cAccumGreenBits AS BYTE
	MEMBER cAccumBlueBits AS BYTE
	MEMBER cAccumAlphaBits AS BYTE
	MEMBER cDepthBits AS BYTE
	MEMBER cStencilBits AS BYTE
	MEMBER cAuxBuffers AS BYTE
	MEMBER iLayerPlane AS BYTE
	MEMBER bReserved AS BYTE
	MEMBER crTransparent AS DWORD

_DLL FUNC wglCopyContext(hglrcSrc AS PTR, hglrcDst AS PTR, mask AS DWORD);
	AS LOGIC PASCAL:OpenGL32.wglCopyContext

_DLL FUNC wglCreateContext(hDC AS PTR) AS PTR PASCAL:OpenGL32.wglCreateContext

_DLL FUNC wglCreateLayerContext(hDC AS PTR, iLayerPlane AS INT);
	AS PTR PASCAL:OpenGL32.wglCreateLayerContext

_DLL FUNC wglDeleteContext(hglrc AS PTR) AS LOGIC PASCAL:OpenGL32.wglDeleteContext

_DLL FUNC wglDescribeLayerPlane(hDC AS PTR, iPixelFormat AS INT, iLayerPlane AS INT,;
	nBytes AS DWORD, plpd AS _winLAYERPLANEDESCRIPTOR) AS LOGIC PASCAL:OpenGL32.wglDescribeLayerPlane

_DLL FUNC wglGetCurrentContext() AS PTR PASCAL:OpenGL32.wglGetCurrentContext

_DLL FUNC wglGetCurrentDC() AS PTR PASCAL:OpenGL32.wglGetCurrentDC

_DLL FUNC wglGetLayerPaletteEntries(hDC AS PTR, iLayerPlane AS INT, iStart AS INT,;
	cEntries AS INT, pcr AS DWORD PTR) AS INT PASCAL:OpenGL32.wglGetLayerPaletteEntries

_DLL FUNC wglGetProcAddress(lpszProc AS PSZ) AS PTR PASCAL:OpenGL32.wglGetProcAddress

_DLL FUNC wglMakeCurrent(hdc AS PTR, hglrc AS PTR) AS LOGIC PASCAL:OpenGL32.wglMakeCurrent

_DLL FUNC wglRealizeLayerPalette(hDC AS PTR, iLayerPlane AS INT, bRealize AS LOGIC);
	AS LOGIC PASCAL:OpenGL32.wglRealizeLayerPalette

_DLL FUNC wglSetLayerPaletteEntries(hDC AS PTR, iLayerPlane AS INT, iStart AS INT,;
	cEntries AS INT, pcr AS DWORD PTR) AS INT PASCAL:OpenGL32.wglSetLayerPaletteEntries

_DLL FUNC wglShareLists(hglrc1 AS PTR, hglrc2 AS PTR) AS LOGIC PASCAL:OpenGL32.wglShareLists

_DLL FUNC wglSwapLayerBuffers(hDC AS PTR, fuPlanes AS DWORD) AS LOGIC PASCAL:OpenGL32.wglSwapLayerBuffers

_DLL FUNC wglUseFontBitmaps(hdc AS PTR, first AS DWORD, Count AS DWORD,;
	listBase AS DWORD) AS LOGIC PASCAL:OpenGL32.wglUseFontBitmapsA

_DLL FUNC wglUseFontOutlines(bhdc AS PTR,  first AS DWORD, Count AS DWORD,;
	listBase AS DWORD,	deviation AS REAL4,;
	extrusion AS REAL4,    format AS INT,;
	lpgmf AS _winGLYPHMETRICSFLOAT);
	AS LOGIC PASCAL:OpenGL32.wglUseFontOutlinesA



#region defines
DEFINE LPD_DOUBLEBUFFER        := 0x00000001
DEFINE LPD_STEREO              := 0x00000002
DEFINE LPD_SUPPORT_GDI         := 0x00000010
DEFINE LPD_SUPPORT_OPENGL      := 0x00000020
DEFINE LPD_SHARE_DEPTH         := 0x00000040
DEFINE LPD_SHARE_STENCIL       := 0x00000080
DEFINE LPD_SHARE_ACCUM         := 0x00000100
DEFINE LPD_SWAP_EXCHANGE       := 0x00000200
DEFINE LPD_SWAP_COPY           := 0x00000400
DEFINE LPD_TRANSPARENT         := 0x00001000
DEFINE LPD_TYPE_RGBA        := 0
DEFINE LPD_TYPE_COLORINDEX  := 1
/* wglSwapLayerBuffers flags */
DEFINE WGL_SWAP_MAIN_PLANE     := 0x00000001
DEFINE WGL_SWAP_OVERLAY1       := 0x00000002
DEFINE WGL_SWAP_OVERLAY2       := 0x00000004
DEFINE WGL_SWAP_OVERLAY3       := 0x00000008
DEFINE WGL_SWAP_OVERLAY4       := 0x00000010
DEFINE WGL_SWAP_OVERLAY5       := 0x00000020
DEFINE WGL_SWAP_OVERLAY6       := 0x00000040
DEFINE WGL_SWAP_OVERLAY7       := 0x00000080
DEFINE WGL_SWAP_OVERLAY8       := 0x00000100
DEFINE WGL_SWAP_OVERLAY9       := 0x00000200
DEFINE WGL_SWAP_OVERLAY10      := 0x00000400
DEFINE WGL_SWAP_OVERLAY11      := 0x00000800
DEFINE WGL_SWAP_OVERLAY12      := 0x00001000
DEFINE WGL_SWAP_OVERLAY13      := 0x00002000
DEFINE WGL_SWAP_OVERLAY14      := 0x00004000
DEFINE WGL_SWAP_OVERLAY15      := 0x00008000
DEFINE WGL_SWAP_UNDERLAY1      := 0x00010000
DEFINE WGL_SWAP_UNDERLAY2      := 0x00020000
DEFINE WGL_SWAP_UNDERLAY3      := 0x00040000
DEFINE WGL_SWAP_UNDERLAY4      := 0x00080000
DEFINE WGL_SWAP_UNDERLAY5      := 0x00100000
DEFINE WGL_SWAP_UNDERLAY6      := 0x00200000
DEFINE WGL_SWAP_UNDERLAY7      := 0x00400000
DEFINE WGL_SWAP_UNDERLAY8      := 0x00800000
DEFINE WGL_SWAP_UNDERLAY9      := 0x01000000
DEFINE WGL_SWAP_UNDERLAY10     := 0x02000000
DEFINE WGL_SWAP_UNDERLAY11     := 0x04000000
DEFINE WGL_SWAP_UNDERLAY12     := 0x08000000
DEFINE WGL_SWAP_UNDERLAY13     := 0x10000000
DEFINE WGL_SWAP_UNDERLAY14     := 0x20000000
DEFINE WGL_SWAP_UNDERLAY15     := 0x40000000
#endregion
