VOSTRUCT _winRECT
	MEMBER left AS LONGINT
	MEMBER top AS LONGINT
	MEMBER right AS LONGINT
	MEMBER bottom AS LONGINT


VOSTRUCT _WINRECTL
	MEMBER left AS LONGINT
	MEMBER top AS LONGINT
	MEMBER right AS LONGINT
	MEMBER  bottom AS LONGINT



VOSTRUCT _winPOINT
	MEMBER x AS LONGINT
	MEMBER y AS LONGINT

VOSTRUCT _winPOINTL
	MEMBER x AS LONGINT
	MEMBER y AS LONGINT

VOSTRUCT _winSIZE
	MEMBER cx AS LONGINT
	MEMBER cy AS LONGINT

VOSTRUCT _winPOINTS
	MEMBER x AS SHORTINT
	MEMBER y AS SHORTINT
FUNCTION Get_Device_lParam(lParam AS DWORD) AS WORD
	RETURN  _and(HiWord(lParam),FAPPCOMMAND_MASK)

FUNCTION Get_MouseOrKey_lParam(lParam AS DWORD) AS WORD
	RETURN Get_Device_lParam(lParam)

FUNCTION Get_Flags_lParam(lParam AS DWORD) AS WORD
	RETURN LoWord(lParam)

FUNCTION Get_KeyState_lParam(lParam AS DWORD) AS WORD
	RETURN Get_Flags_lParam(lParam)

FUNCTION Get_AppCommand_lParam(lParam AS DWORD) AS DWORD
	RETURN _and(HiWord(lParam),_not(FAPPCOMMAND_MASK))



#region defines
#ifndef __XRUNTIME__
DEFINE MAX_PATH          := 260
#endif
DEFINE HFILE_ERROR := -1
#endregion
