VOSTRUCT  _winNETRESOURCE
	MEMBER  dwScope AS DWORD
	MEMBER  dwType AS DWORD
	MEMBER  dwDisplayType AS DWORD
	MEMBER  dwUsage AS DWORD
	MEMBER  lpLocalName AS PSZ
	MEMBER  lpRemoteName AS PSZ
	MEMBER  lpComment  AS PSZ
	MEMBER  lpProvider AS PSZ

VOSTRUCT  _NETRESOURCEW
	MEMBER  dwScope AS DWORD
	MEMBER  dwType AS DWORD
	MEMBER  dwDisplayType AS DWORD
	MEMBER  dwUsage AS DWORD
	MEMBER  lpLocalName AS PSZ
	MEMBER  lpRemoteName AS PSZ
	MEMBER  lpComment AS PSZ
	MEMBER  lpProvider AS PSZ





VOSTRUCT _winCONNECTDLGSTRUCT
	MEMBER cbStructure AS DWORD
	MEMBER hwndOwner AS PTR
	MEMBER lpConnRes AS _winNETRESOURCE
	MEMBER dwFlags AS DWORD
	MEMBER dwDevNum AS DWORD



VOSTRUCT _winDISCDLGSTRUCT
	MEMBER cbStructure AS DWORD
	MEMBER hwndOwner AS PTR
	MEMBER lpLocalName AS PSZ
	MEMBER lpRemoteName AS PSZ
	MEMBER dwFlags AS DWORD



VOSTRUCT  _winUNIVERSAL_NAME_INFO
	MEMBER    lpUniversalName AS PSZ


VOSTRUCT  _winREMOTE_NAME_INFO
	MEMBER    lpUniversalName AS PSZ
	MEMBER   lpConnectionName AS PSZ
	MEMBER  lpRemainingPath AS PSZ



VOSTRUCT _winNETINFOSTRUCT
	MEMBER  cbStructure AS DWORD
	MEMBER  dwProviderVersion AS DWORD
	MEMBER  dwStatus AS DWORD
	MEMBER  dwCharacteristics AS DWORD
	MEMBER  dwHandle AS DWORD
	MEMBER  wNetType AS DWORD
	MEMBER  dwPrinters AS DWORD
	MEMBER  dwDrives AS DWORD

VOSTRUCT _winNETCONNECTINFOSTRUCT
	MEMBER  cbStructure AS DWORD
	MEMBER  dwFlags AS DWORD
	MEMBER  dwSpeed AS DWORD
	MEMBER  dwDelay AS DWORD
	MEMBER  dwOptDataSize AS DWORD

_DLL FUNC WNetAddConnection(lpRemoteName AS PSZ, lpPassword AS PSZ, lpLocalName AS PSZ);
	AS DWORD PASCAL:MPR.WNetAddConnectionA




_DLL FUNC WNetAddConnection2(lpNerResource AS _winNETRESOURCE, lpPassword AS PSZ,;
	lpUserName AS PSZ, dwFlags AS DWORD);
	AS DWORD PASCAL:MPR.WNetAddConnection2A




_DLL FUNC WNetAddConnection3( hwndOwner AS PTR, lpNetResource AS _winNETRESOURCE,;
	lpPassword AS PSZ, lpUserName AS PSZ, dwFlags AS DWORD);
	AS DWORD PASCAL:MPR.WNetAddConnection3A




_DLL FUNC WNetCancelConnection( lpName AS PSZ, fForce AS LOGIC);
	AS DWORD PASCAL:MPR.WNetCancelConnectionA




_DLL FUNC WNetCancelConnection2( lpName AS PSZ, dwFlags AS DWORD, fForce AS LOGIC);
	AS DWORD PASCAL:MPR.WNetCancelConnection2A




_DLL FUNC WNetGetConnection( lpLocalName AS PSZ, lpRemoteName AS PSZ,;
	lpnLenght AS DWORD PTR) AS DWORD PASCAL:MPR.WNetGetConnectionA





_DLL FUNC WNetUseConnection(hwndOwner AS PTR, lpNetResource AS _winNETRESOURCE,;
	lpUserId AS PSZ, lpPassword AS PSZ, dwFlags AS DWORD,;
	lpAccessName AS PSZ, lpBufferSize AS DWORD PTR,;
	lpResult AS DWORD PTR);
	AS DWORD PASCAL:MPR.WNetUseConnectionA



_DLL FUNC WNetSetConnection( lpName AS PSZ, dwProperties AS DWORD, pvValues AS PTR);
	AS DWORD PASCAL:MPR.WNetSetConnectionA






_DLL FUNC WNetConnectionDialog(hWnd AS PTR, dwType AS DWORD)   AS DWORD PASCAL:MPR.WNetConnectionDialog


_DLL FUNC WNetConnectionDialog1( lpCounnDlgStruct AS _winCONNECTDLGSTRUCT);
	AS DWORD PASCAL:MPR.WNetConnectionDialog1A


_DLL FUNC WNetDisconnectDialog1( lpConnDlgStruct AS _winDISCDLGSTRUCT);
	AS DWORD PASCAL:MPR.WNetDisconnectDialog1A






_DLL FUNC WNetOpenEnum( dwScope AS DWORD, dwType AS DWORD, dwUsage AS DWORD,;
	lpNetResource AS _winNETRESOURCE, lphEnum AS PTR);
	AS DWORD PASCAL:MPR.WNetOpenEnumA



_DLL FUNC WNetEnumResource(hEnum AS PTR, lpCount AS DWORD PTR, lpBuffer AS PTR,;
	lpBufferSize AS DWORD PTR) AS DWORD PASCAL:MPR.WNetEnumResourceA


_DLL FUNC WNetCloseEnum( hEnum AS PTR) AS DWORD PASCAL:MPR.WNetCloseEnum



_DLL FUNC WNetGetUniversalName(lpLocalPath AS PSZ, dwInfoLevel AS DWORD,;
	lpBuffer AS PTR, lpBufferSize AS DWORD PTR);
	AS DWORD PASCAL:MPR.WNetGetUniversalNameA




_DLL FUNC WNetGetUser( lpName AS PSZ, lpUserName AS PSZ, lpnLength AS DWORD PTR);
	AS DWORD PASCAL:MPR.WNetGetUserA





_DLL FUNC WNetGetProviderName(dwNetType AS DWORD, lpProviderName AS PSZ,;
	lpBufferSize AS DWORD PTR) AS DWORD PASCAL:MPR.WNetGetProviderNameA


_DLL FUNC WNetGetNetworkInformation( lpProvider AS PSZ, lpNetInfoStruct AS _winNETINFOSTRUCT);
	AS DWORD PASCAL:MPR.WNetGetNetworkInformationA




_DLL FUNC WNetGetLastError( lpError AS DWORD PTR, lpErrorBuf AS PSZ, nErrorBufSize AS DWORD,;
	lpNameBuf AS PSZ, nNameBufSize AS DWORD);
	AS DWORD PASCAL:MPR.WNetGetLastErrorA




_DLL FUNC MultinetGetConnectionPerformance( lpNetResource AS _winNETRESOURCE,;
	lpNetConnectInfoStruct AS _winNETCONNECTINFOSTRUCT);
	AS DWORD PASCAL:MPR.MultinetGetConnectionPerformanceA



#region defines
DEFINE     WNNC_NET_MSNET      := 0x00010000
DEFINE     WNNC_NET_LANMAN     := 0x00020000
DEFINE     WNNC_NET_NETWARE    := 0x00030000
DEFINE     WNNC_NET_VINES      := 0x00040000
DEFINE     WNNC_NET_10NET      := 0x00050000
DEFINE     WNNC_NET_LOCUS      := 0x00060000
DEFINE     WNNC_NET_SUN_PC_NFS := 0x00070000
DEFINE     WNNC_NET_LANSTEP    := 0x00080000
DEFINE     WNNC_NET_9TILES     := 0x00090000
DEFINE     WNNC_NET_LANTASTIC  := 0x000A0000
DEFINE     WNNC_NET_AS400      := 0x000B0000
DEFINE     WNNC_NET_FTP_NFS    := 0x000C0000
DEFINE     WNNC_NET_PATHWORKS  := 0x000D0000
DEFINE     WNNC_NET_LIFENET    := 0x000E0000
DEFINE     WNNC_NET_POWERLAN   := 0x000F0000
DEFINE     WNNC_NET_BWNFS      := 0x00100000
DEFINE     WNNC_NET_COGENT     := 0x00110000
DEFINE     WNNC_NET_FARALLON   := 0x00120000
DEFINE     WNNC_NET_APPLETALK  := 0x00130000
DEFINE RESOURCE_CONNECTED      := 0x00000001
DEFINE RESOURCE_GLOBALNET      := 0x00000002
DEFINE RESOURCE_REMEMBERED     := 0x00000003
DEFINE RESOURCE_RECENT         := 0x00000004
DEFINE RESOURCE_CONTEXT        := 0x00000005
DEFINE RESOURCETYPE_ANY        := 0x00000000
DEFINE RESOURCETYPE_DISK       := 0x00000001
DEFINE RESOURCETYPE_PRINT      := 0x00000002
DEFINE RESOURCETYPE_RESERVED   := 0x00000008
DEFINE RESOURCETYPE_UNKNOWN    := 0xFFFFFFFF
DEFINE RESOURCEUSAGE_CONNECTABLE   := 0x00000001
DEFINE RESOURCEUSAGE_CONTAINER     := 0x00000002
DEFINE RESOURCEUSAGE_NOLOCALDEVICE := 0x00000004
DEFINE RESOURCEUSAGE_SIBLING       := 0x00000008
DEFINE RESOURCEUSAGE_ALL           := 0x00000003
DEFINE RESOURCEUSAGE_RESERVED      := 0x80000000
DEFINE RESOURCEDISPLAYTYPE_GENERIC        := 0x00000000
DEFINE RESOURCEDISPLAYTYPE_DOMAIN         := 0x00000001
DEFINE RESOURCEDISPLAYTYPE_SERVER         := 0x00000002
DEFINE RESOURCEDISPLAYTYPE_SHARE          := 0x00000003
DEFINE RESOURCEDISPLAYTYPE_FILE           := 0x00000004
DEFINE RESOURCEDISPLAYTYPE_GROUP          := 0x00000005
DEFINE RESOURCEDISPLAYTYPE_NETWORK        := 0x00000006
DEFINE RESOURCEDISPLAYTYPE_ROOT           := 0x00000007
DEFINE RESOURCEDISPLAYTYPE_SHAREADMIN     := 0x00000008
DEFINE RESOURCEDISPLAYTYPE_DIRECTORY      := 0x00000009
DEFINE RESOURCEDISPLAYTYPE_TREE           := 0x0000000A
DEFINE NETPROPERTY_PERSISTENT       := 1
DEFINE CONNECT_UPDATE_PROFILE      := 0x00000001
DEFINE CONNECT_UPDATE_RECENT       := 0x00000002
DEFINE CONNECT_TEMPORARY           := 0x00000004
DEFINE CONNECT_INTERACTIVE         := 0x00000008
DEFINE CONNECT_PROMPT              := 0x00000010
DEFINE CONNECT_NEED_DRIVE          := 0x00000020
DEFINE CONNECT_REFCOUNT            := 0x00000040
DEFINE CONNECT_REDIRECT            := 0x00000080
DEFINE CONNECT_LOCALDRIVE          := 0x00000100
DEFINE CONNECT_CURRENT_MEDIA       := 0x00000200
DEFINE CONNDLG_RO_PATH     := 0x00000001
DEFINE CONNDLG_CONN_POINT  := 0x00000002
DEFINE CONNDLG_USE_MRU     := 0x00000004
DEFINE CONNDLG_HIDE_BOX    := 0x00000008
DEFINE CONNDLG_PERSIST     := 0x00000010
DEFINE CONNDLG_NOT_PERSIST := 0x00000020
DEFINE DISC_UPDATE_PROFILE         := 0x00000001
DEFINE DISC_NO_FORCE               := 0x00000040
DEFINE UNIVERSAL_NAME_INFO_LEVEL   := 0x00000001
DEFINE REMOTE_NAME_INFO_LEVEL      := 0x00000002
DEFINE WNFMT_MULTILINE         := 0x01
DEFINE WNFMT_ABBREVIATED       := 0x02
DEFINE WNFMT_INENUM            := 0x10
DEFINE WNFMT_CONNECTION        := 0x20
DEFINE NETINFO_DLL16       := 0x00000001
DEFINE NETINFO_DISKRED     := 0x00000004
DEFINE NETINFO_PRINTERRED  := 0x00000008
DEFINE RP_LOGON    := 0x01
DEFINE RP_INIFILE  := 0x02
DEFINE PP_DISPLAYERRORS    := 0x01
DEFINE WN_SUCCESS                      := NO_ERROR
DEFINE WN_NO_ERROR                     := NO_ERROR
DEFINE WN_NOT_SUPPORTED                := ERROR_NOT_SUPPORTED
DEFINE WN_CANCEL                       := ERROR_CANCELLED
DEFINE WN_RETRY                        := ERROR_RETRY
DEFINE WN_NET_ERROR                    := ERROR_UNEXP_NET_ERR
DEFINE WN_MORE_DATA                    := ERROR_MORE_DATA
DEFINE WN_BAD_POINTER                  := ERROR_INVALID_ADDRESS
DEFINE WN_BAD_VALUE                    := ERROR_INVALID_PARAMETER
DEFINE WN_BAD_USER                     := ERROR_BAD_USERNAME
DEFINE WN_BAD_PASSWORD                 := ERROR_INVALID_PASSWORD
DEFINE WN_ACCESS_DENIED                := ERROR_ACCESS_DENIED
DEFINE WN_FUNCTION_BUSY                := ERROR_BUSY
DEFINE WN_WINDOWS_ERROR                := ERROR_UNEXP_NET_ERR
DEFINE WN_OUT_OF_MEMORY                := ERROR_NOT_ENOUGH_MEMORY
DEFINE WN_NO_NETWORK                   := ERROR_NO_NETWORK
DEFINE WN_EXTENDED_ERROR               := ERROR_EXTENDED_ERROR
DEFINE WN_BAD_LEVEL                    := ERROR_INVALID_LEVEL
DEFINE WN_BAD_HANDLE                   := ERROR_INVALID_HANDLE
DEFINE WN_NOT_INITIALIZING             := ERROR_ALREADY_INITIALIZED
DEFINE WN_NO_MORE_DEVICES              := ERROR_NO_MORE_DEVICES
DEFINE WN_NOT_CONNECTED                := ERROR_NOT_CONNECTED
DEFINE WN_OPEN_FILES                   := ERROR_OPEN_FILES
DEFINE WN_DEVICE_IN_USE                := ERROR_DEVICE_IN_USE
DEFINE WN_BAD_NETNAME                  := ERROR_BAD_NET_NAME
DEFINE WN_BAD_LOCALNAME                := ERROR_BAD_DEVICE
DEFINE WN_ALREADY_CONNECTED            := ERROR_ALREADY_ASSIGNED
DEFINE WN_DEVICE_ERROR                 := ERROR_GEN_FAILURE
DEFINE WN_CONNECTION_CLOSED            := ERROR_CONNECTION_UNAVAIL
DEFINE WN_NO_NET_OR_BAD_PATH           := ERROR_NO_NET_OR_BAD_PATH
DEFINE WN_BAD_PROVIDER                 := ERROR_BAD_PROVIDER
DEFINE WN_CANNOT_OPEN_PROFILE          := ERROR_CANNOT_OPEN_PROFILE
DEFINE WN_BAD_PROFILE                  := ERROR_BAD_PROFILE
DEFINE WN_BAD_DEV_TYPE                 := ERROR_BAD_DEV_TYPE
DEFINE WN_DEVICE_ALREADY_REMEMBERED    := ERROR_DEVICE_ALREADY_REMEMBERED
DEFINE WN_NO_MORE_ENTRIES              := ERROR_NO_MORE_ITEMS
DEFINE WN_NOT_CONTAINER                := ERROR_NOT_CONTAINER
DEFINE WN_NOT_AUTHENTICATED            := ERROR_NOT_AUTHENTICATED
DEFINE WN_NOT_LOGGED_ON                := ERROR_NOT_LOGGED_ON
DEFINE WN_NOT_VALIDATED                := ERROR_NO_LOGON_SERVERS
DEFINE WNCON_FORNETCARD        := 0x00000001
DEFINE WNCON_NOTROUTED         := 0x00000002
DEFINE WNCON_SLOWLINK          := 0x00000004
DEFINE WNCON_DYNAMIC           := 0x00000008
#endregion
