VOSTRUCT  _winRemHGLOBAL
	MEMBER fNullHGlobal AS LONGINT
	MEMBER  cbData AS DWORD
	MEMBER DIM data[ 1 ] AS BYTE


VOSTRUCT  _winRemHMETAFILEPICT
	MEMBER  mm AS LONGINT
	MEMBER  xExt AS LONGINT
	MEMBER  yExt AS LONGINT
	MEMBER  cbData AS DWORD
	MEMBER  DIM data[ 1 ] AS BYTE




VOSTRUCT  _winRemHENHMETAFILE
	MEMBER cbData AS DWORD
	MEMBER DIM data[ 1 ] AS BYTE


VOSTRUCT  _winRemHBITMAP
	MEMBER cbData AS DWORD
	MEMBER DIM data[ 1 ] AS BYTE


VOSTRUCT  _winRemHPALETTE
	MEMBER cbData AS DWORD
	MEMBER DIM data[ 1 ] AS BYTE


VOSTRUCT  _winRemBRUSH
	MEMBER cbData AS DWORD
	MEMBER DIM data[ 1 ] AS BYTE




#region defines
DEFINE  MEMCTX_TASK  := 1
DEFINE  MEMCTX_SHARED  := 2
DEFINE  MEMCTX_MACSYSTEM := 3
DEFINE  MEMCTX_UNKNOWN   := -1
DEFINE  MEMCTX_SAME  := -2
DEFINE  CLSCTX_INPROC_SERVER  := 1
DEFINE  CLSCTX_INPROC_HANDLER := 2
DEFINE  CLSCTX_LOCAL_SERVER := 4
DEFINE  CLSCTX_INPROC_SERVER16  := 8
DEFINE  MSHLFLAGS_NORMAL  := 0
DEFINE  MSHLFLAGS_TABLESTRONG := 1
DEFINE  MSHLFLAGS_TABLEWEAK := 2
DEFINE  MSHCTX_LOCAL          := 0
DEFINE  MSHCTX_NOSHAREDMEM  := 1
DEFINE  MSHCTX_DIFFERENTMACHINE := 2
DEFINE  MSHCTX_INPROC         := 3
DEFINE  DVASPECT_CONTENT  := 1
DEFINE  DVASPECT_THUMBNAIL  := 2
DEFINE  DVASPECT_ICON         := 4
DEFINE  DVASPECT_DOCPRINT := 8
DEFINE  STGC_DEFAULT          := 0
DEFINE  STGC_OVERWRITE          := 1
DEFINE  STGC_ONLYIFCURRENT  := 2
DEFINE  STGC_DANGEROUSLYCOMMITMERELYTODISKCACHE := 4
DEFINE  STGMOVE_MOVE  := 0
DEFINE  STGMOVE_COPY  := 1
DEFINE  STATFLAG_DEFAULT  := 0
DEFINE  STATFLAG_NONAME         := 1
#endregion
