//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.12.2.0
//     Timestamp      : 20-7-2022 10:28:36
//
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE XSharpModel.Formatting
   USING System
   /// <summary>
   ///   A strongly-typed resource class, for looking up localized strings, etc.
   /// </summary>
   // This class was auto-generated by the StronglyTypedResourceBuilder
   // class via a tool like ResGen or Visual Studio.
   // To add or remove a member, edit your .ResX file then rerun ResGen
   // with the /str option, or rebuild your VS project.
   [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")] ;
   [global::System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
   [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
   PUBLIC CLASS XFormattingRules
      [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
      INTERNAL CONSTRUCTOR() STRICT
      PRIVATE STATIC resourceMan AS global::System.Resources.ResourceManager
      PRIVATE STATIC resourceCulture AS global::System.Globalization.CultureInfo
      /// <summary>
      ///   Returns the cached ResourceManager instance used by this class.
      /// </summary>
      [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] ;
      INTERNAL STATIC PROPERTY ResourceManager AS global::System.Resources.ResourceManager

         GET
            IF System.Object.ReferenceEquals(resourceMan, NULL)
               LOCAL temp := global::System.Resources.ResourceManager{"XSharpModel.Formatting.XFormattingRules", typeof(XFormattingRules):Assembly} AS global::System.Resources.ResourceManager
               resourceMan := temp
            ENDIF
            RETURN resourceMan
         END GET
      END PROPERTY
      /// <summary>
      ///   Overrides the current thread's CurrentUICulture property for all
      ///   resource lookups using this strongly typed resource class.
      /// </summary>
      [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] ;
      INTERNAL STATIC PROPERTY Culture AS global::System.Globalization.CultureInfo

         GET
            RETURN resourceCulture
         END GET

         SET
            resourceCulture := value
         END SET
      END PROPERTY
      /// <summary>
      ///   Looks up a localized string similar to /*
      ///Formattingrules.txt
      ///Each line consists of one or more begin token(s) followed by a comma and the matching end token(s)
      ///Tokens that are followed by a question mark are optional
      ///After the end token there may be another comma and a list of &quot;options&quot;
      ///These options can be:
      ///- OPTIONAL (end token is optional)
      ///- MIDDLE   (block with a middle token, such as DO CASE)
      ///- CASE     (for special indenting rules for CASE blocks)
      ///- SINGLE (for rules that may be single line such as property)
      ///Section delimiters i [rest of string was truncated]&quot;;.
      /// </summary>
      INTERNAL STATIC PROPERTY Rules AS STRING

         GET
            RETURN ResourceManager:GetString("Rules", resourceCulture)
         END GET
      END PROPERTY

   END CLASS
END NAMESPACE
