// R795 Structure sizes not correctly aligned.
// https://github.com/X-Sharp/XSharpPublic/issues/734
// Note that the reference sizes are taken from VO 2.8 Sp3 and VO 2.8 Sp4

FUNCTION Start() AS VOID STRICT

    
	? "unaligned"
	Expected("EXCHG_PROTOCOL_HEAD:", _sizeof(EXCHG_PROTOCOL_HEAD), 28)
	Expected("EXCHG_PROTOCOL_DPT:", _sizeof(EXCHG_PROTOCOL_DPT), 16)
	Expected("EXCHG_PROTOCOL_RECORD:" , _sizeof(EXCHG_PROTOCOL_RECORD), 28)
	? "align 1"
	Expected("EXCHG_PROTOCOL_HEAD1:" , _sizeof(EXCHG_PROTOCOL_HEAD1),27)
	Expected("EXCHG_PROTOCOL_DPT1:" , _sizeof(EXCHG_PROTOCOL_DPT1),14)
	Expected("EXCHG_PROTOCOL_RECORD1:" , _sizeof(EXCHG_PROTOCOL_RECORD1),23)
	? "align 2"
	Expected("EXCHG_PROTOCOL_HEAD2:" , _sizeof(EXCHG_PROTOCOL_HEAD2),28)
	Expected("EXCHG_PROTOCOL_DPT2:" , _sizeof(EXCHG_PROTOCOL_DPT2),14)
	Expected("EXCHG_PROTOCOL_RECORD2:" , _sizeof(EXCHG_PROTOCOL_RECORD2),24)
	? "align 4"
	Expected("EXCHG_PROTOCOL_HEAD4:" , _sizeof(EXCHG_PROTOCOL_HEAD4),28)
	Expected("EXCHG_PROTOCOL_DPT4:" , _sizeof(EXCHG_PROTOCOL_DPT4),16)
	Expected("EXCHG_PROTOCOL_RECORD4:" , _sizeof(EXCHG_PROTOCOL_RECORD4),28)
	? "align 8"
	Expected("EXCHG_PROTOCOL_HEAD8:" , _sizeof(EXCHG_PROTOCOL_HEAD8),32)
	Expected("EXCHG_PROTOCOL_DPT8:" , _sizeof(EXCHG_PROTOCOL_DPT8),24)
	Expected("EXCHG_PROTOCOL_RECORD8:" , _sizeof(EXCHG_PROTOCOL_RECORD8),48)

	RETURN
FUNCTION Expected (cDesc AS STRING, nSize1 AS DWORD, nSize2 AS DWORD) 
	IF nSize1 == nSize2
		? cDesc, "Ok"
	ELSE
		? cDesc, "Fail, Expected", nSize2, "actual", nSize1
		THROW Exception{}
	ENDIF
RETURN NIL	

VOSTRUCT EXCHG_PROTOCOL_HEAD
	MEMBER DIM cPrefix[15] AS BYTE
	MEMBER nVersion AS DWORD
	MEMBER Creation IS _WINFILETIME

VOSTRUCT EXCHG_PROTOCOL_DPT
	MEMBER nCode1 AS INT
	MEMBER nCode2 AS INT
	MEMBER DIM cDptID[6] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_RECORD
	MEMBER nType AS DWORD
	MEMBER Dpt IS EXCHG_PROTOCOL_DPT
	MEMBER cbSize AS DWORD
	MEMBER DIM bData[1] AS BYTE



VOSTRUCT EXCHG_PROTOCOL_HEAD1 ALIGN 1
	MEMBER DIM cPrefix[15] AS BYTE
	MEMBER nVersion AS DWORD
	MEMBER Creation IS _WINFILETIME

VOSTRUCT EXCHG_PROTOCOL_DPT1 ALIGN 1
	MEMBER nCode1 AS INT
	MEMBER nCode2 AS INT
	MEMBER DIM cDptID[6] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_RECORD1 ALIGN 1
	MEMBER nType AS DWORD
	MEMBER Dpt IS EXCHG_PROTOCOL_DPT1
	MEMBER cbSize AS DWORD
	MEMBER DIM bData[1] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_HEAD2 ALIGN 2
	MEMBER DIM cPrefix[15] AS BYTE
	MEMBER nVersion AS DWORD
	MEMBER Creation IS _WINFILETIME

VOSTRUCT EXCHG_PROTOCOL_DPT2 ALIGN 2
	MEMBER nCode1 AS INT
	MEMBER nCode2 AS INT
	MEMBER DIM cDptID[6] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_RECORD2 ALIGN 2
	MEMBER nType AS DWORD
	MEMBER Dpt IS EXCHG_PROTOCOL_DPT2
	MEMBER cbSize AS DWORD
	MEMBER DIM bData[1] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_HEAD4 ALIGN 4
	MEMBER DIM cPrefix[15] AS BYTE
	MEMBER nVersion AS DWORD
	MEMBER Creation IS _WINFILETIME

VOSTRUCT EXCHG_PROTOCOL_DPT4 ALIGN 4
	MEMBER nCode1 AS INT
	MEMBER nCode2 AS INT
	MEMBER DIM cDptID[6] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_RECORD4 ALIGN 4
	MEMBER nType AS DWORD
	MEMBER Dpt IS EXCHG_PROTOCOL_DPT4
	MEMBER cbSize AS DWORD
	MEMBER DIM bData[1] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_HEAD8 ALIGN 8
	MEMBER DIM cPrefix[15] AS BYTE
	MEMBER nVersion AS DWORD
	MEMBER Creation IS _WINFILETIME

VOSTRUCT EXCHG_PROTOCOL_DPT8 ALIGN 8
	MEMBER nCode1 AS INT
	MEMBER nCode2 AS INT
	MEMBER DIM cDptID[6] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_RECORD8 ALIGN 8
	MEMBER nType AS DWORD
	MEMBER Dpt IS EXCHG_PROTOCOL_DPT8
	MEMBER cbSize AS DWORD
	MEMBER DIM bData[1] AS BYTE


