//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 1.0.0.0
//     Timestamp      : 21-6-2017 15:24:21
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE Email
    PUBLIC PARTIAL CLASS webBrowserHost ;
        INHERIT System.Windows.Forms.Form
        
        PUBLIC axWebBrowser1 AS AxSHDocVw.AxWebBrowser
        PRIVATE components := NULL AS System.ComponentModel.IContainer
        PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID
            if (disposing .AND. (components != null))
                components:Dispose()
            endif
            Super:Dispose(disposing)
            return
        PRIVATE METHOD InitializeComponent() AS VOID
            LOCAL resources := System.ComponentModel.ComponentResourceManager{typeof(webBrowserHost)} AS System.ComponentModel.ComponentResourceManager
            SELF:axWebBrowser1 := AxSHDocVw.AxWebBrowser{}
            ((System.ComponentModel.ISupportInitialize)(SELF:axWebBrowser1)):BeginInit()
            SELF:SuspendLayout()
            // 
            // axWebBrowser1
            // 
            SELF:axWebBrowser1:Enabled := true
            SELF:axWebBrowser1:Location := System.Drawing.Point{27, 56}
            SELF:axWebBrowser1:OcxState := ((System.Windows.Forms.AxHost.State)(resources:GetObject("axWebBrowser1.OcxState")))
            SELF:axWebBrowser1:Size := System.Drawing.Size{222, 171}
            SELF:axWebBrowser1:TabIndex := 0
            // 
            // webBrowserHost
            // 
            SELF:AutoScaleDimensions := System.Drawing.SizeF{6, 13}
            SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            SELF:ClientSize := System.Drawing.Size{284, 261}
            SELF:Controls:Add(SELF:axWebBrowser1)
            SELF:Name := "webBrowserHost"
            SELF:Text := "webBrowserHost"
            ((System.ComponentModel.ISupportInitialize)(SELF:axWebBrowser1)):EndInit()
            SELF:ResumeLayout(false)
    
    END CLASS
END NAMESPACE
