<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Runtime.Sdk.Props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>XSharp.MacroCompiler</RootNamespace>
    <AssemblyName>XSharp.MacroCompiler</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>Preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Common\Constants.cs">
      <Link>Properties\Constants.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\XSharp.Core\XSharp.Core.Next.xsproj">
      <Name>XSharp.Core</Name>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
    </ProjectReference>
    <ProjectReference Include="..\XSharp.RT\XSharp.RT.Next.xsproj">
      <Name>XSharp.RT</Name>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\Common\StandardHeaders.resx">
      <Link>Preprocessor\StandardHeaders.resx</Link>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <Import Project="..\XmlDoc.Props" />
</Project>
