//
// Copyright (c) XSharp B.V.  All Rights Reserved.  
// Licensed under the Apache License, Version 2.0.  
// See License.txt in the project root for license information.
//

BEGIN NAMESPACE XSharp.ADS
ENUM AceError AS WORD
	MEMBER SUCCESS := ACE.AE_SUCCESS
	MEMBER ALLOCATION_FAILED := ACE.AE_ALLOCATION_FAILED
	MEMBER COMM_MISMATCH := ACE.AE_COMM_MISMATCH
	MEMBER DATA_TOO_LONG := ACE.AE_DATA_TOO_LONG
	MEMBER FILE_NOT_FOUND := ACE.AE_FILE_NOT_FOUND
	MEMBER INSUFFICIENT_BUFFER := ACE.AE_INSUFFICIENT_BUFFER
	MEMBER INVALID_BOOKMARK := ACE.AE_INVALID_BOOKMARK
	MEMBER INVALID_CALLBACK := ACE.AE_INVALID_CALLBACK
	MEMBER INVALID_CENTURY := ACE.AE_INVALID_CENTURY
	MEMBER INVALID_DATEFORMAT := ACE.AE_INVALID_DATEFORMAT
	MEMBER INVALID_DECIMALS := ACE.AE_INVALID_DECIMALS
	MEMBER INVALID_EXPRESSION := ACE.AE_INVALID_EXPRESSION
	MEMBER INVALID_FIELDDEF := ACE.AE_INVALID_FIELDDEF
	MEMBER INVALID_FILTER_OPTION := ACE.AE_INVALID_FILTER_OPTION
	MEMBER INVALID_INDEX_HANDLE := ACE.AE_INVALID_INDEX_HANDLE
	MEMBER INVALID_INDEX_NAME := ACE.AE_INVALID_INDEX_NAME
	MEMBER INVALID_INDEX_ORDER_NAME := ACE.AE_INVALID_INDEX_ORDER_NAME
	MEMBER INVALID_INDEX_TYPE := ACE.AE_INVALID_INDEX_TYPE
	MEMBER INVALID_HANDLE := ACE.AE_INVALID_HANDLE
	MEMBER INVALID_OPTION := ACE.AE_INVALID_OPTION
	MEMBER INVALID_PATH := ACE.AE_INVALID_PATH
	MEMBER INVALID_POINTER := ACE.AE_INVALID_POINTER
	MEMBER INVALID_RECORD_NUMBER := ACE.AE_INVALID_RECORD_NUMBER
	MEMBER INVALID_TABLE_HANDLE := ACE.AE_INVALID_TABLE_HANDLE
	MEMBER INVALID_CONNECTION_HANDLE := ACE.AE_INVALID_CONNECTION_HANDLE
	MEMBER INVALID_TABLETYPE := ACE.AE_INVALID_TABLETYPE
	MEMBER INVALID_WORKAREA := ACE.AE_INVALID_WORKAREA
	MEMBER INVALID_CHARSETTYPE := ACE.AE_INVALID_CHARSETTYPE
	MEMBER INVALID_LOCKTYPE := ACE.AE_INVALID_LOCKTYPE
	MEMBER INVALID_RIGHTSOPTION := ACE.AE_INVALID_RIGHTSOPTION
	MEMBER INVALID_FIELDNUMBER := ACE.AE_INVALID_FIELDNUMBER
	MEMBER INVALID_KEY_LENGTH := ACE.AE_INVALID_KEY_LENGTH
	MEMBER INVALID_FIELDNAME := ACE.AE_INVALID_FIELDNAME
	MEMBER NO_DRIVE_CONNECTION := ACE.AE_NO_DRIVE_CONNECTION
	MEMBER FILE_NOT_ON_SERVER := ACE.AE_FILE_NOT_ON_SERVER
	MEMBER LOCK_FAILED := ACE.AE_LOCK_FAILED
	MEMBER NO_CONNECTION := ACE.AE_NO_CONNECTION
	MEMBER NO_FILTER := ACE.AE_NO_FILTER
	MEMBER NO_SCOPE := ACE.AE_NO_SCOPE
	MEMBER NO_TABLE := ACE.AE_NO_TABLE
	MEMBER NO_WORKAREA := ACE.AE_NO_WORKAREA
	MEMBER NOT_FOUND := ACE.AE_NOT_FOUND
	MEMBER NOT_IMPLEMENTED := ACE.AE_NOT_IMPLEMENTED
	MEMBER MAX_THREADS_EXCEEDED := ACE.AE_MAX_THREADS_EXCEEDED
	MEMBER START_THREAD_FAIL := ACE.AE_START_THREAD_FAIL
	MEMBER TOO_MANY_INDEXES := ACE.AE_TOO_MANY_INDEXES
	MEMBER TOO_MANY_TAGS := ACE.AE_TOO_MANY_TAGS
	MEMBER TRANS_OUT_OF_SEQUENCE := ACE.AE_TRANS_OUT_OF_SEQUENCE
	MEMBER UNKNOWN_ERRCODE := ACE.AE_UNKNOWN_ERRCODE
	MEMBER UNSUPPORTED_LANGUAGE := ACE.AE_UNSUPPORTED_LANGUAGE
	MEMBER NAME_TOO_LONG := ACE.AE_NAME_TOO_LONG
	MEMBER DUPLICATE_ALIAS := ACE.AE_DUPLICATE_ALIAS
	MEMBER TABLE_CLOSED_IN_TRANSACTION := ACE.AE_TABLE_CLOSED_IN_TRANSACTION
	MEMBER PERMISSION_DENIED := ACE.AE_PERMISSION_DENIED
	MEMBER STRING_NOT_FOUND := ACE.AE_STRING_NOT_FOUND
	MEMBER UNKNOWN_CHAR_SET := ACE.AE_UNKNOWN_CHAR_SET
	MEMBER INVALID_OEM_CHAR_FILE := ACE.AE_INVALID_OEM_CHAR_FILE
	MEMBER INVALID_MEMO_BLOCK_SIZE := ACE.AE_INVALID_MEMO_BLOCK_SIZE
	MEMBER NO_FILE_FOUND := ACE.AE_NO_FILE_FOUND
	MEMBER NO_INF_LOCK := ACE.AE_NO_INF_LOCK
	MEMBER INF_FILE_ERROR := ACE.AE_INF_FILE_ERROR
	MEMBER RECORD_NOT_LOCKED := ACE.AE_RECORD_NOT_LOCKED
	MEMBER ILLEGAL_COMMAND_DURING_TRANS := ACE.AE_ILLEGAL_COMMAND_DURING_TRANS
	MEMBER TABLE_NOT_SHARED := ACE.AE_TABLE_NOT_SHARED
	MEMBER INDEX_ALREADY_OPEN := ACE.AE_INDEX_ALREADY_OPEN
	MEMBER INVALID_FIELD_TYPE := ACE.AE_INVALID_FIELD_TYPE
	MEMBER TABLE_NOT_EXCLUSIVE := ACE.AE_TABLE_NOT_EXCLUSIVE
	MEMBER NO_CURRENT_RECORD := ACE.AE_NO_CURRENT_RECORD
	MEMBER PRECISION_LOST := ACE.AE_PRECISION_LOST
	MEMBER INVALID_DATA_TYPE := ACE.AE_INVALID_DATA_TYPE
	MEMBER DATA_TRUNCATED := ACE.AE_DATA_TRUNCATED
	MEMBER TABLE_READONLY := ACE.AE_TABLE_READONLY
	MEMBER INVALID_RECORD_LENGTH := ACE.AE_INVALID_RECORD_LENGTH
	MEMBER NO_ERROR_MESSAGE := ACE.AE_NO_ERROR_MESSAGE
	MEMBER INDEX_SHARED := ACE.AE_INDEX_SHARED
	MEMBER INDEX_EXISTS := ACE.AE_INDEX_EXISTS
	MEMBER CYCLIC_RELATION := ACE.AE_CYCLIC_RELATION
	MEMBER INVALID_RELATION := ACE.AE_INVALID_RELATION
	MEMBER INVALID_DAY := ACE.AE_INVALID_DAY
	MEMBER INVALID_MONTH := ACE.AE_INVALID_MONTH
	MEMBER CORRUPT_TABLE := ACE.AE_CORRUPT_TABLE
	MEMBER INVALID_BINARY_OFFSET := ACE.AE_INVALID_BINARY_OFFSET
	MEMBER BINARY_FILE_ERROR := ACE.AE_BINARY_FILE_ERROR
	MEMBER INVALID_DELETED_BYTE_VALUE := ACE.AE_INVALID_DELETED_BYTE_VALUE
	MEMBER NO_PENDING_UPDATE := ACE.AE_NO_PENDING_UPDATE
	MEMBER PENDING_UPDATE := ACE.AE_PENDING_UPDATE
	MEMBER TABLE_NOT_LOCKED := ACE.AE_TABLE_NOT_LOCKED
	MEMBER CORRUPT_INDEX := ACE.AE_CORRUPT_INDEX
	MEMBER AUTOOPEN_INDEX := ACE.AE_AUTOOPEN_INDEX
	MEMBER SAME_TABLE := ACE.AE_SAME_TABLE
	MEMBER INVALID_IMAGE := ACE.AE_INVALID_IMAGE
	MEMBER COLLATION_SEQUENCE_MISMATCH := ACE.AE_COLLATION_SEQUENCE_MISMATCH
	MEMBER INVALID_INDEX_ORDER := ACE.AE_INVALID_INDEX_ORDER
	MEMBER TABLE_CACHED := ACE.AE_TABLE_CACHED
	MEMBER INVALID_DATE := ACE.AE_INVALID_DATE
	MEMBER ENCRYPTION_NOT_ENABLED := ACE.AE_ENCRYPTION_NOT_ENABLED
	MEMBER INVALID_PASSWORD := ACE.AE_INVALID_PASSWORD
	MEMBER TABLE_ENCRYPTED := ACE.AE_TABLE_ENCRYPTED
	MEMBER SERVER_MISMATCH := ACE.AE_SERVER_MISMATCH
	MEMBER INVALID_USERNAME := ACE.AE_INVALID_USERNAME
	MEMBER INVALID_VALUE := ACE.AE_INVALID_VALUE
	MEMBER INVALID_CONTINUE := ACE.AE_INVALID_CONTINUE
	MEMBER UNRECOGNIZED_VERSION := ACE.AE_UNRECOGNIZED_VERSION
	MEMBER RECORD_ENCRYPTED := ACE.AE_RECORD_ENCRYPTED
	MEMBER UNRECOGNIZED_ENCRYPTION := ACE.AE_UNRECOGNIZED_ENCRYPTION
	MEMBER INVALID_SQLSTATEMENT_HANDLE := ACE.AE_INVALID_SQLSTATEMENT_HANDLE
	MEMBER INVALID_SQLCURSOR_HANDLE := ACE.AE_INVALID_SQLCURSOR_HANDLE
	MEMBER NOT_PREPARED := ACE.AE_NOT_PREPARED
	MEMBER CURSOR_NOT_CLOSED := ACE.AE_CURSOR_NOT_CLOSED
	MEMBER INVALID_SQL_PARAM_NUMBER := ACE.AE_INVALID_SQL_PARAM_NUMBER
	MEMBER INVALID_SQL_PARAM_NAME := ACE.AE_INVALID_SQL_PARAM_NAME
	MEMBER INVALID_COLUMN_NUMBER := ACE.AE_INVALID_COLUMN_NUMBER
	MEMBER INVALID_COLUMN_NAME := ACE.AE_INVALID_COLUMN_NAME
	MEMBER INVALID_READONLY_OPTION := ACE.AE_INVALID_READONLY_OPTION
	MEMBER IS_CURSOR_HANDLE := ACE.AE_IS_CURSOR_HANDLE
	MEMBER INDEX_EXPR_NOT_FOUND := ACE.AE_INDEX_EXPR_NOT_FOUND
	MEMBER NOT_DML := ACE.AE_NOT_DML
	MEMBER INVALID_CONSTRAIN_TYPE := ACE.AE_INVALID_CONSTRAIN_TYPE
	MEMBER INVALID_CURSORHANDLE := ACE.AE_INVALID_CURSORHANDLE
	MEMBER OBSOLETE_FUNCTION := ACE.AE_OBSOLETE_FUNCTION
	MEMBER TADSDATASET_GENERAL := ACE.AE_TADSDATASET_GENERAL
	MEMBER UDF_OVERWROTE_BUFFER := ACE.AE_UDF_OVERWROTE_BUFFER
	MEMBER INDEX_UDF_NOT_SET := ACE.AE_INDEX_UDF_NOT_SET
	MEMBER CONCURRENT_PROBLEM := ACE.AE_CONCURRENT_PROBLEM
	MEMBER INVALID_DICTIONARY_HANDLE := ACE.AE_INVALID_DICTIONARY_HANDLE
	MEMBER INVALID_PROPERTY_ID := ACE.AE_INVALID_PROPERTY_ID
	MEMBER INVALID_PROPERTY := ACE.AE_INVALID_PROPERTY
	MEMBER DICTIONARY_ALREADY_EXISTS := ACE.AE_DICTIONARY_ALREADY_EXISTS
	MEMBER INVALID_FIND_HANDLE := ACE.AE_INVALID_FIND_HANDLE
	MEMBER DD_REQUEST_NOT_COMPLETED := ACE.AE_DD_REQUEST_NOT_COMPLETED
	MEMBER INVALID_OBJECT_ID := ACE.AE_INVALID_OBJECT_ID
	MEMBER INVALID_OBJECT_NAME := ACE.AE_INVALID_OBJECT_NAME
	MEMBER INVALID_PROPERTY_LENGTH := ACE.AE_INVALID_PROPERTY_LENGTH
	MEMBER INVALID_KEY_OPTIONS := ACE.AE_INVALID_KEY_OPTIONS
	MEMBER CONSTRAINT_VALIDATION_ERROR := ACE.AE_CONSTRAINT_VALIDATION_ERROR
	MEMBER INVALID_OBJECT_TYPE := ACE.AE_INVALID_OBJECT_TYPE
	MEMBER NO_OBJECT_FOUND := ACE.AE_NO_OBJECT_FOUND
	MEMBER PROPERTY_NOT_SET := ACE.AE_PROPERTY_NOT_SET
	MEMBER NO_PRIMARY_KEY_EXISTS := ACE.AE_NO_PRIMARY_KEY_EXISTS
	MEMBER LOCAL_CONN_DISABLED := ACE.AE_LOCAL_CONN_DISABLED
	MEMBER RI_RESTRICT := ACE.AE_RI_RESTRICT
	MEMBER RI_CASCADE := ACE.AE_RI_CASCADE
	MEMBER RI_FAILED := ACE.AE_RI_FAILED
	MEMBER RI_CORRUPTED := ACE.AE_RI_CORRUPTED
	MEMBER RI_UNDO_FAILED := ACE.AE_RI_UNDO_FAILED
	MEMBER RI_RULE_EXISTS := ACE.AE_RI_RULE_EXISTS
	MEMBER COLUMN_CANNOT_BE_NULL := ACE.AE_COLUMN_CANNOT_BE_NULL
	MEMBER MIN_CONSTRAINT_VIOLATION := ACE.AE_MIN_CONSTRAINT_VIOLATION
	MEMBER MAX_CONSTRAINT_VIOLATION := ACE.AE_MAX_CONSTRAINT_VIOLATION
	MEMBER RECORD_CONSTRAINT_VIOLATION := ACE.AE_RECORD_CONSTRAINT_VIOLATION
	MEMBER CANNOT_DELETE_TEMP_INDEX := ACE.AE_CANNOT_DELETE_TEMP_INDEX
	MEMBER RESTRUCTURE_FAILED := ACE.AE_RESTRUCTURE_FAILED
	MEMBER INVALID_STATEMENT := ACE.AE_INVALID_STATEMENT
	MEMBER STORED_PROCEDURE_FAILED := ACE.AE_STORED_PROCEDURE_FAILED
	MEMBER INVALID_DICTIONARY_FILE := ACE.AE_INVALID_DICTIONARY_FILE
	MEMBER NOT_MEMBER_OF_GROUP := ACE.AE_NOT_MEMBER_OF_GROUP
	MEMBER ALREADY_MEMBER_OF_GROUP := ACE.AE_ALREADY_MEMBER_OF_GROUP
	MEMBER INVALID_OBJECT_RIGHT := ACE.AE_INVALID_OBJECT_RIGHT
	MEMBER INVALID_OBJECT_PERMISSION := ACE.AE_INVALID_OBJECT_PERMISSION
	MEMBER CANNOT_OPEN_DATABASE_TABLE := ACE.AE_CANNOT_OPEN_DATABASE_TABLE
	MEMBER INVALID_CONSTRAINT := ACE.AE_INVALID_CONSTRAINT
	MEMBER NOT_ADMINISTRATOR := ACE.AE_NOT_ADMINISTRATOR
	MEMBER NO_TABLE_ENCRYPTION_PASSWORD := ACE.AE_NO_TABLE_ENCRYPTION_PASSWORD
	MEMBER TABLE_NOT_ENCRYPTED := ACE.AE_TABLE_NOT_ENCRYPTED
	MEMBER INVALID_ENCRYPTION_VERSION := ACE.AE_INVALID_ENCRYPTION_VERSION
	MEMBER NO_STORED_PROC_EXEC_RIGHTS := ACE.AE_NO_STORED_PROC_EXEC_RIGHTS
	MEMBER DD_UNSUPPORTED_DEPLOYMENT := ACE.AE_DD_UNSUPPORTED_DEPLOYMENT
	MEMBER INFO_AUTO_CREATION_OCCURRED := ACE.AE_INFO_AUTO_CREATION_OCCURRED
	MEMBER INFO_COPY_MADE_BY_CLIENT := ACE.AE_INFO_COPY_MADE_BY_CLIENT
	MEMBER DATABASE_REQUIRES_NEW_SERVER := ACE.AE_DATABASE_REQUIRES_NEW_SERVER
	MEMBER COLUMN_PERMISSION_DENIED := ACE.AE_COLUMN_PERMISSION_DENIED
	MEMBER DATABASE_REQUIRES_NEW_CLIENT := ACE.AE_DATABASE_REQUIRES_NEW_CLIENT
	MEMBER INVALID_LINK_NUMBER := ACE.AE_INVALID_LINK_NUMBER
	MEMBER LINK_ACTIVATION_FAILED := ACE.AE_LINK_ACTIVATION_FAILED
	MEMBER INDEX_COLLATION_MISMATCH := ACE.AE_INDEX_COLLATION_MISMATCH
	MEMBER ILLEGAL_USER_OPERATION := ACE.AE_ILLEGAL_USER_OPERATION
	MEMBER TRIGGER_FAILED := ACE.AE_TRIGGER_FAILED
	MEMBER NO_ASA_FUNCTION_FOUND := ACE.AE_NO_ASA_FUNCTION_FOUND
	MEMBER VALUE_OVERFLOW := ACE.AE_VALUE_OVERFLOW
	MEMBER UNRECOGNIZED_FTS_VERSION := ACE.AE_UNRECOGNIZED_FTS_VERSION
	MEMBER TRIG_CREATION_FAILED := ACE.AE_TRIG_CREATION_FAILED
	MEMBER MEMTABLE_SIZE_EXCEEDED := ACE.AE_MEMTABLE_SIZE_EXCEEDED
	MEMBER OUTDATED_CLIENT_VERSION := ACE.AE_OUTDATED_CLIENT_VERSION
	MEMBER FREE_TABLE := ACE.AE_FREE_TABLE
	MEMBER LOCAL_CONN_RESTRICTED := ACE.AE_LOCAL_CONN_RESTRICTED
	MEMBER OLD_RECORD := ACE.AE_OLD_RECORD
	MEMBER QUERY_NOT_ACTIVE := ACE.AE_QUERY_NOT_ACTIVE
	MEMBER KEY_EXCEEDS_PAGE_SIZE := ACE.AE_KEY_EXCEEDS_PAGE_SIZE
	MEMBER TABLE_FOUND := ACE.AE_TABLE_FOUND
	MEMBER TABLE_NOT_FOUND := ACE.AE_TABLE_NOT_FOUND
	MEMBER LOCK_OBJECT := ACE.AE_LOCK_OBJECT
	MEMBER INVALID_REPLICATION_IDENT := ACE.AE_INVALID_REPLICATION_IDENT
	MEMBER ILLEGAL_COMMAND_DURING_BACKUP := ACE.AE_ILLEGAL_COMMAND_DURING_BACKUP
	MEMBER NO_MEMO_FILE := ACE.AE_NO_MEMO_FILE
	MEMBER SUBSCRIPTION_QUEUE_NOT_EMPTY := ACE.AE_SUBSCRIPTION_QUEUE_NOT_EMPTY
	MEMBER UNABLE_TO_DISABLE_TRIGGERS := ACE.AE_UNABLE_TO_DISABLE_TRIGGERS
	MEMBER UNABLE_TO_ENABLE_TRIGGERS := ACE.AE_UNABLE_TO_ENABLE_TRIGGERS
	MEMBER BACKUP := ACE.AE_BACKUP
	MEMBER FREETABLEFAILED := ACE.AE_FREETABLEFAILED
	MEMBER BLURRY_SNAPSHOT := ACE.AE_BLURRY_SNAPSHOT
	MEMBER INVALID_VERTICAL_FILTER := ACE.AE_INVALID_VERTICAL_FILTER
	MEMBER INVALID_USE_OF_HANDLE_IN_AEP := ACE.AE_INVALID_USE_OF_HANDLE_IN_AEP
	MEMBER COLLATION_NOT_RECOGNIZED := ACE.AE_COLLATION_NOT_RECOGNIZED
	MEMBER INVALID_COLLATION := ACE.AE_INVALID_COLLATION
	MEMBER NOT_VFP_NULLABLE_FIELD := ACE.AE_NOT_VFP_NULLABLE_FIELD
	MEMBER NOT_VFP_VARIABLE_FIELD := ACE.AE_NOT_VFP_VARIABLE_FIELD
	MEMBER ILLEGAL_EVENT_COMMAND := ACE.AE_ILLEGAL_EVENT_COMMAND
	MEMBER KEY_CANNOT_BE_NULL := ACE.AE_KEY_CANNOT_BE_NULL
END ENUM

ENUM AceTrigEvent AS DWORD
    MEMBER INSERT := ACE.ADS_TRIGEVENT_INSERT 
    MEMBER UPDATE := ACE.ADS_TRIGEVENT_UPDATE
    MEMBER DELETE := ACE.ADS_TRIGEVENT_DELETE
END ENUM

ENUM AceTrigType  AS DWORD
    MEMBER BEFORE       := ACE.ADS_TRIGTYPE_BEFORE 
    MEMBER INSTEADOF    := ACE.ADS_TRIGTYPE_INSTEADOF 
    MEMBER AFTER        := ACE.ADS_TRIGTYPE_AFTER 
    MEMBER CONFLICTON   := ACE.ADS_TRIGTYPE_CONFLICTON 
END ENUM


ENUM AceTrigOptions AS DWORD
    MEMBER NO_VALUES            := ACE.ADS_TRIGOPTIONS_NO_VALUES 
    MEMBER WANT_VALUES          := ACE.ADS_TRIGOPTIONS_WANT_VALUES 
    MEMBER WANT_MEMOS_AND_BLOBS := ACE.ADS_TRIGOPTIONS_WANT_MEMOS_AND_BLOBS 
    MEMBER DEFAULT              := ACE.ADS_TRIGOPTIONS_DEFAULT 
    MEMBER NO_TRANSACTION       := ACE.ADS_TRIGOPTIONS_NO_TRANSACTION 
END ENUM


ENUM AceValidate AS WORD
	MEMBER NO           := ACE.ADS_NO_VALIDATE 
	MEMBER NO_SAVE      := ACE.ADS_VALIDATE_NO_SAVE 
	MEMBER WRITE_FAIL   := ACE.ADS_VALIDATE_WRITE_FAIL 
	MEMBER APPEND_FAIL  := ACE.ADS_VALIDATE_APPEND_FAIL 
	MEMBER RETURN_ERROR := ACE.ADS_VALIDATE_RETURN_ERROR 
END ENUM

PUBLIC ENUM AdsCharTypes AS WORD
	MEMBER ADS_ANSI := 1
	MEMBER ADS_OEM
	MEMBER CZECH_VFP_CI_AS_1250
	MEMBER GENERAL_VFP_CI_AS_1250
	MEMBER HUNGARY_VFP_CI_AS_1250
	MEMBER MACHINE_VFP_BIN_1250
	MEMBER POLISH_VFP_CI_AS_1250
	MEMBER SLOVAK_VFP_CI_AS_1250
	MEMBER MACHINE_VFP_BIN_1251
	MEMBER RUSSIAN_VFP_CI_AS_1251
	MEMBER DUTCH_VFP_CI_AS_1252
	MEMBER GENERAL_VFP_CI_AS_1252
	MEMBER GERMAN_VFP_CI_AS_1252
	MEMBER ICELAND_VFP_CI_AS_1252
	MEMBER MACHINE_VFP_BIN_1252
	MEMBER NORDAN_VFP_CI_AS_1252
	MEMBER SPANISH_VFP_CI_AS_1252
	MEMBER SWEFIN_VFP_CI_AS_1252
	MEMBER UNIQWT_VFP_CS_AS_1252
	MEMBER GREEK_VFP_CI_AS_1253
	MEMBER MACHINE_VFP_BIN_1253
	MEMBER GENERAL_VFP_CI_AS_1254
	MEMBER MACHINE_VFP_BIN_1254
	MEMBER TURKISH_VFP_CI_AS_1254
	MEMBER DUTCH_VFP_CI_AS_437
	MEMBER GENERAL_VFP_CI_AS_437
	MEMBER GERMAN_VFP_CI_AS_437
	MEMBER ICELAND_VFP_CI_AS_437
	MEMBER MACHINE_VFP_BIN_437
	MEMBER NORDAN_VFP_CI_AS_437
	MEMBER SPANISH_VFP_CI_AS_437
	MEMBER SWEFIN_VFP_CI_AS_437
	MEMBER UNIQWT_VFP_CS_AS_437
	MEMBER GENERAL_VFP_CI_AS_620
	MEMBER MACHINE_VFP_BIN_620
	MEMBER POLISH_VFP_CI_AS_620
	MEMBER GREEK_VFP_CI_AS_737
	MEMBER MACHINE_VFP_BIN_737
	MEMBER DUTCH_VFP_CI_AS_850
	MEMBER GENERAL_VFP_CI_AS_850
	MEMBER ICELAND_VFP_CI_AS_850
	MEMBER MACHINE_VFP_BIN_850
	MEMBER NORDAN_VFP_CI_AS_850
	MEMBER SPANISH_VFP_CI_AS_850
	MEMBER SWEFIN_VFP_CI_AS_850
	MEMBER UNIQWT_VFP_CS_AS_850
	MEMBER CZECH_VFP_CI_AS_852
	MEMBER GENERAL_VFP_CI_AS_852
	MEMBER HUNGARY_VFP_CI_AS_852
	MEMBER MACHINE_VFP_BIN_852
	MEMBER POLISH_VFP_CI_AS_852
	MEMBER SLOVAK_VFP_CI_AS_852
	MEMBER GENERAL_VFP_CI_AS_857
	MEMBER MACHINE_VFP_BIN_857
	MEMBER TURKISH_VFP_CI_AS_857
	MEMBER GENERAL_VFP_CI_AS_861
	MEMBER ICELAND_VFP_CI_AS_861
	MEMBER MACHINE_VFP_BIN_861
	MEMBER GENERAL_VFP_CI_AS_865
	MEMBER MACHINE_VFP_BIN_865
	MEMBER NORDAN_VFP_CI_AS_865
	MEMBER SWEFIN_VFP_CI_AS_865
	MEMBER MACHINE_VFP_BIN_866
	MEMBER RUSSIAN_VFP_CI_AS_866
	MEMBER CZECH_VFP_CI_AS_895
	MEMBER GENERAL_VFP_CI_AS_895
	MEMBER MACHINE_VFP_BIN_895
	MEMBER SLOVAK_VFP_CI_AS_895
END ENUM

PUBLIC ENUM AdsFieldType
    MEMBER LOGICAL              := ACE.ADS_LOGICAL 
    MEMBER NUMERIC              := ACE.ADS_NUMERIC 
    MEMBER DATE                 := ACE.ADS_DATE 
    MEMBER STRING               := ACE.ADS_STRING 
    MEMBER MEMO                 := ACE.ADS_MEMO 
    MEMBER BINARY               := ACE.ADS_BINARY 
    MEMBER IMAGE                := ACE.ADS_IMAGE 
    MEMBER VARCHAR              := ACE.ADS_VARCHAR 
    MEMBER COMPACTDATE          := ACE.ADS_COMPACTDATE 
    MEMBER DOUBLE               := ACE.ADS_DOUBLE 
    MEMBER INTEGER              := ACE.ADS_INTEGER 
    MEMBER SHORTINT             := ACE.ADS_SHORTINT 
    MEMBER TIME                 := ACE.ADS_TIME 
    MEMBER TIMESTAMP            := ACE.ADS_TIMESTAMP 
    MEMBER AUTOINC              := ACE.ADS_AUTOINC 
    MEMBER RAW                  := ACE.ADS_RAW 
    MEMBER CURDOUBLE            := ACE.ADS_CURDOUBLE 
    MEMBER MONEY                := ACE.ADS_MONEY 
    MEMBER INT64                := ACE.ADS_INT64
    MEMBER CISTRING             := ACE.ADS_CISTRING 
    MEMBER ROWVERSION           := ACE.ADS_ROWVERSION 
    MEMBER MODTIME              := ACE.ADS_MODTIME 
    MEMBER VARCHAR_FOX          := ACE.ADS_VARCHAR_FOX 
    MEMBER VARBINARY_FOX        := ACE.ADS_VARBINARY_FOX 
    MEMBER SYSTEM_FIELD         := ACE.ADS_SYSTEM_FIELD 
    MEMBER NCHAR                := ACE.ADS_NCHAR 
    MEMBER NVARCHAR             := ACE.ADS_NVARCHAR  
    MEMBER NMEMO                := ACE.ADS_NMEMO  
END ENUM

END NAMESPACE


STATIC CLASS AdsEnumExtensions
    STATIC METHOD IsMemo(SELF type AS AdsFieldType ) AS LOGIC
        SWITCH type
        CASE AdsFieldType.MEMO
        CASE AdsFieldType.NMEMO
            RETURN TRUE
        END SWITCH
        RETURN FALSE

    STATIC METHOD IsUnicode(SELF type AS AdsFieldType ) AS LOGIC
        SWITCH type
        CASE AdsFieldType.NCHAR
        CASE AdsFieldType.NVARCHAR
        CASE AdsFieldType.NMEMO
            RETURN TRUE
        END SWITCH
        RETURN FALSE

    STATIC METHOD IsBinary(SELF type AS AdsFieldType ) AS LOGIC
        SWITCH type
        CASE AdsFieldType.IMAGE
        CASE AdsFieldType.BINARY
        CASE AdsFieldType.RAW
        CASE AdsFieldType.VARBINARY_FOX
            RETURN TRUE
        END SWITCH
        RETURN FALSE

    STATIC METHOD IsDouble(SELF type AS AdsFieldType ) AS LOGIC
        SWITCH type
        CASE AdsFieldType.DOUBLE
        CASE AdsFieldType.CURDOUBLE
            RETURN TRUE
        END SWITCH
        RETURN FALSE


END CLASS
