//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.20.0.3
//     Timestamp      : 05/07/2024 13:12:43
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE XSharp.VOEditors.Dialogs

    PUBLIC PARTIAL CLASS WindowCloneSelectDlg

        /// <summary>
        /// Required designer variable.
        /// </summary>
        PRIVATE components := NULL AS System.ComponentModel.IContainer
        PRIVATE oCancelButton AS System.Windows.Forms.Button
        PRIVATE oOKButton AS System.Windows.Forms.Button
        PRIVATE oFilesList AS System.Windows.Forms.ListBox

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED OVERRIDE METHOD Dispose(disposing AS LOGIC) AS VOID STRICT

            IF (disposing .and. (components != null))
                components:Dispose()
            ENDIF
            SUPER:Dispose(disposing)
			RETURN
        END METHOD
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
                                        PRIVATE METHOD InitializeComponent() AS VOID STRICT
            SELF:oCancelButton := System.Windows.Forms.Button{}
            SELF:oOKButton := System.Windows.Forms.Button{}
            SELF:oFilesList := System.Windows.Forms.ListBox{}
            SELF:SuspendLayout()
            // 
            // oCancelButton
            // 
            SELF:oCancelButton:Anchor := System.Windows.Forms.AnchorStyles.Right
            SELF:oCancelButton:DialogResult := System.Windows.Forms.DialogResult.Cancel
            SELF:oCancelButton:Location := System.Drawing.Point{346, 353}
            SELF:oCancelButton:Name := "oCancelButton"
            SELF:oCancelButton:Size := System.Drawing.Size{115, 23}
            SELF:oCancelButton:TabIndex := 2
            SELF:oCancelButton:Text := "&Cancel"
            // 
            // oOKButton
            // 
            SELF:oOKButton:Anchor := System.Windows.Forms.AnchorStyles.Left
            SELF:oOKButton:Location := System.Drawing.Point{12, 353}
            SELF:oOKButton:Name := "oOKButton"
            SELF:oOKButton:Size := System.Drawing.Size{115, 23}
            SELF:oOKButton:TabIndex := 1
            SELF:oOKButton:Text := "&OK"
            SELF:oOKButton:Click += System.EventHandler{ SELF, @oOKButton_Click() }
            // 
            // oFilesList
            // 
            SELF:oFilesList:Anchor := System.Windows.Forms.AnchorStyles.Top
            SELF:oFilesList:Location := System.Drawing.Point{12, 10}
            SELF:oFilesList:Name := "oFilesList"
            SELF:oFilesList:Size := System.Drawing.Size{449, 329}
            SELF:oFilesList:TabIndex := 0
            SELF:oFilesList:DoubleClick += System.EventHandler{ SELF, @oOKButton_Click() }
            // 
            // WindowCloneSelectDlg
            // 
            SELF:AcceptButton := SELF:oOKButton
            SELF:CancelButton := SELF:oCancelButton
            SELF:ClientSize := System.Drawing.Size{473, 385}
            SELF:Controls:Add(SELF:oCancelButton)
            SELF:Controls:Add(SELF:oOKButton)
            SELF:Controls:Add(SELF:oFilesList)
            SELF:Location := System.Drawing.Point{100, 100}
            SELF:MaximizeBox := false
            SELF:MinimizeBox := false
            SELF:Name := "WindowCloneSelectDlg"
            SELF:StartPosition := System.Windows.Forms.FormStartPosition.Manual
            SELF:Text := "Choose source window to duplicate:"
            SELF:ResumeLayout(false)
        END METHOD
        #endregion
    END CLASS 
END NAMESPACE
