//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.9.0.0
//     Timestamp      : 29/09/2021 16:32:43
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE UDCTesterApp

    EXPORT PARTIAL CLASS UDCTester
    
        HIDDEN label1 AS System.Windows.Forms.Label
        HIDDEN label2 AS System.Windows.Forms.Label
        HIDDEN label3 AS System.Windows.Forms.Label
        HIDDEN panel1 AS System.Windows.Forms.Panel
        HIDDEN TestButton AS System.Windows.Forms.Button
        HIDDEN OkButton AS System.Windows.Forms.Button
        HIDDEN tbUDC AS System.Windows.Forms.TextBox
        HIDDEN tbSource AS System.Windows.Forms.TextBox
        HIDDEN tbResult AS System.Windows.Forms.TextBox
        HIDDEN chkStandardDefs AS System.Windows.Forms.CheckBox
        HIDDEN lblDialect AS System.Windows.Forms.Label
        HIDDEN comboDialect AS System.Windows.Forms.ComboBox
        HIDDEN btnSettings AS System.Windows.Forms.Button
        HIDDEN tableLayoutPanel1 AS System.Windows.Forms.TableLayoutPanel

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        PROTECTED METHOD Dispose(disposing AS LOGIC) AS VOID  STRICT

            SUPER:Dispose(disposing)
    RETURN

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        HIDDEN METHOD InitializeComponent() AS VOID STRICT
			LOCAL resources	:=	System.ComponentModel.ComponentResourceManager{TYPEOF(UDCTester)} AS System.ComponentModel.ComponentResourceManager
			SELF:tableLayoutPanel1	:=	System.Windows.Forms.TableLayoutPanel{}
			SELF:tbResult	:=	System.Windows.Forms.TextBox{}
			SELF:tbSource	:=	System.Windows.Forms.TextBox{}
			SELF:label1	:=	System.Windows.Forms.Label{}
			SELF:label2	:=	System.Windows.Forms.Label{}
			SELF:label3	:=	System.Windows.Forms.Label{}
			SELF:panel1	:=	System.Windows.Forms.Panel{}
			SELF:btnSettings	:=	System.Windows.Forms.Button{}
			SELF:lblDialect	:=	System.Windows.Forms.Label{}
			SELF:comboDialect	:=	System.Windows.Forms.ComboBox{}
			SELF:chkStandardDefs	:=	System.Windows.Forms.CheckBox{}
			SELF:OkButton	:=	System.Windows.Forms.Button{}
			SELF:TestButton	:=	System.Windows.Forms.Button{}
			SELF:tbUDC	:=	System.Windows.Forms.TextBox{}
			SELF:tableLayoutPanel1:SuspendLayout()
			SELF:panel1:SuspendLayout()
			SELF:SuspendLayout()
			//	
			//	tableLayoutPanel1
			//	
			SELF:tableLayoutPanel1:AutoSizeMode	:=	System.Windows.Forms.AutoSizeMode.GrowAndShrink
			SELF:tableLayoutPanel1:ColumnCount	:=	2
			SELF:tableLayoutPanel1:ColumnStyles:Add(System.Windows.Forms.ColumnStyle{System.Windows.Forms.SizeType.Absolute, 75})
			SELF:tableLayoutPanel1:ColumnStyles:Add(System.Windows.Forms.ColumnStyle{})
			SELF:tableLayoutPanel1:Controls:Add(SELF:tbResult, 1, 2)
			SELF:tableLayoutPanel1:Controls:Add(SELF:tbSource, 1, 1)
			SELF:tableLayoutPanel1:Controls:Add(SELF:label1, 0, 0)
			SELF:tableLayoutPanel1:Controls:Add(SELF:label2, 0, 1)
			SELF:tableLayoutPanel1:Controls:Add(SELF:label3, 0, 2)
			SELF:tableLayoutPanel1:Controls:Add(SELF:panel1, 1, 3)
			SELF:tableLayoutPanel1:Controls:Add(SELF:tbUDC, 1, 0)
			SELF:tableLayoutPanel1:Dock	:=	System.Windows.Forms.DockStyle.Fill
			SELF:tableLayoutPanel1:Location	:=	System.Drawing.Point{0, 0}
			SELF:tableLayoutPanel1:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:tableLayoutPanel1:Name	:=	"tableLayoutPanel1"
			SELF:tableLayoutPanel1:RowCount	:=	4
			SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 33.3333321})
			SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 33.3333359})
			SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 33.3333359})
			SELF:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Absolute, 50})
			SELF:tableLayoutPanel1:Size	:=	System.Drawing.Size{1018, 597}
			SELF:tableLayoutPanel1:TabIndex	:=	0
			//	
			//	tbResult
			//	
			SELF:tbResult:Dock	:=	System.Windows.Forms.DockStyle.Fill
			SELF:tbResult:Font	:=	System.Drawing.Font{"Courier New", 12, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:tbResult:Location	:=	System.Drawing.Point{78, 367}
			SELF:tbResult:Multiline	:=	true
			SELF:tbResult:Name	:=	"tbResult"
			SELF:tbResult:ReadOnly	:=	true
			SELF:tbResult:ScrollBars	:=	System.Windows.Forms.ScrollBars.Vertical
			SELF:tbResult:Size	:=	System.Drawing.Size{940, 176}
			SELF:tbResult:TabIndex	:=	7
			//	
			//	tbSource
			//	
			SELF:tbSource:AcceptsReturn	:=	true
			SELF:tbSource:Dock	:=	System.Windows.Forms.DockStyle.Fill
			SELF:tbSource:Font	:=	System.Drawing.Font{"Courier New", 12, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:tbSource:Location	:=	System.Drawing.Point{78, 185}
			SELF:tbSource:Multiline	:=	true
			SELF:tbSource:Name	:=	"tbSource"
			SELF:tbSource:ScrollBars	:=	System.Windows.Forms.ScrollBars.Vertical
			SELF:tbSource:Size	:=	System.Drawing.Size{940, 176}
			SELF:tbSource:TabIndex	:=	6
			SELF:tbSource:WordWrap	:=	false
			//	
			//	label1
			//	
			SELF:label1:AutoSize	:=	true
			SELF:label1:Font	:=	System.Drawing.Font{"Microsoft Sans Serif", 12, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:label1:Location	:=	System.Drawing.Point{3, 0}
			SELF:label1:Name	:=	"label1"
			SELF:label1:Size	:=	System.Drawing.Size{44, 20}
			SELF:label1:TabIndex	:=	2
			SELF:label1:Text	:=	"UDC"
			//	
			//	label2
			//	
			SELF:label2:AutoSize	:=	true
			SELF:label2:Font	:=	System.Drawing.Font{"Microsoft Sans Serif", 12, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:label2:Location	:=	System.Drawing.Point{3, 182}
			SELF:label2:Name	:=	"label2"
			SELF:label2:Size	:=	System.Drawing.Size{64, 20}
			SELF:label2:TabIndex	:=	3
			SELF:label2:Text	:=	"Source:"
			//	
			//	label3
			//	
			SELF:label3:AutoSize	:=	true
			SELF:label3:Font	:=	System.Drawing.Font{"Microsoft Sans Serif", 12, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:label3:Location	:=	System.Drawing.Point{3, 364}
			SELF:label3:Name	:=	"label3"
			SELF:label3:Size	:=	System.Drawing.Size{55, 20}
			SELF:label3:TabIndex	:=	4
			SELF:label3:Text	:=	"Result"
			//	
			//	panel1
			//	
			SELF:panel1:Controls:Add(SELF:btnSettings)
			SELF:panel1:Controls:Add(SELF:lblDialect)
			SELF:panel1:Controls:Add(SELF:comboDialect)
			SELF:panel1:Controls:Add(SELF:chkStandardDefs)
			SELF:panel1:Controls:Add(SELF:OkButton)
			SELF:panel1:Controls:Add(SELF:TestButton)
			SELF:panel1:Dock	:=	System.Windows.Forms.DockStyle.Fill
			SELF:panel1:Location	:=	System.Drawing.Point{78, 549}
			SELF:panel1:Name	:=	"panel1"
			SELF:panel1:Size	:=	System.Drawing.Size{940, 45}
			SELF:panel1:TabIndex	:=	8
			//	
			//	btnSettings
			//	
			SELF:btnSettings:Font	:=	System.Drawing.Font{"Microsoft Sans Serif", 9.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:btnSettings:Location	:=	System.Drawing.Point{10, 7}
			SELF:btnSettings:Name	:=	"btnSettings"
			SELF:btnSettings:Size	:=	System.Drawing.Size{75, 31}
			SELF:btnSettings:TabIndex	:=	5
			SELF:btnSettings:Text	:=	"&Settings"
			SELF:btnSettings:UseVisualStyleBackColor	:=	true
			SELF:btnSettings:Click	+=	System.EventHandler{ SELF, @btnSettings_Click() }
			//	
			//	lblDialect
			//	
			SELF:lblDialect:AutoSize	:=	true
			SELF:lblDialect:Location	:=	System.Drawing.Point{177, 16}
			SELF:lblDialect:Name	:=	"lblDialect"
			SELF:lblDialect:Size	:=	System.Drawing.Size{43, 13}
			SELF:lblDialect:TabIndex	:=	4
			SELF:lblDialect:Text	:=	"Dialect:"
			//	
			//	comboDialect
			//	
			SELF:comboDialect:DropDownStyle	:=	System.Windows.Forms.ComboBoxStyle.DropDownList
			SELF:comboDialect:FormattingEnabled	:=	true
			SELF:comboDialect:Items:AddRange(<System.Object>{ "Core", "Vulcan", "VO", "FoxPro", "XPP", "Harbour" })
			SELF:comboDialect:Location	:=	System.Drawing.Point{226, 13}
			SELF:comboDialect:Name	:=	"comboDialect"
			SELF:comboDialect:Size	:=	System.Drawing.Size{222, 21}
			SELF:comboDialect:TabIndex	:=	3
			//	
			//	chkStandardDefs
			//	
			SELF:chkStandardDefs:AutoSize	:=	true
			SELF:chkStandardDefs:Location	:=	System.Drawing.Point{96, 15}
			SELF:chkStandardDefs:Name	:=	"chkStandardDefs"
			SELF:chkStandardDefs:Size	:=	System.Drawing.Size{77, 17}
			SELF:chkStandardDefs:TabIndex	:=	2
			SELF:chkStandardDefs:Text	:=	"/nostddefs"
			SELF:chkStandardDefs:UseVisualStyleBackColor	:=	true
			//	
			//	OkButton
			//	
			SELF:OkButton:Anchor	:=	((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)))
			SELF:OkButton:Font	:=	System.Drawing.Font{"Microsoft Sans Serif", 9.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:OkButton:Location	:=	System.Drawing.Point{853, 7}
			SELF:OkButton:Name	:=	"OkButton"
			SELF:OkButton:Size	:=	System.Drawing.Size{75, 31}
			SELF:OkButton:TabIndex	:=	1
			SELF:OkButton:Text	:=	"&Close"
			SELF:OkButton:UseVisualStyleBackColor	:=	true
			SELF:OkButton:Click	+=	System.EventHandler{ SELF, @OkButton_Click() }
			//	
			//	TestButton
			//	
			SELF:TestButton:Anchor	:=	((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)))
			SELF:TestButton:Font	:=	System.Drawing.Font{"Microsoft Sans Serif", 9.75, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:TestButton:Location	:=	System.Drawing.Point{742, 7}
			SELF:TestButton:Name	:=	"TestButton"
			SELF:TestButton:Size	:=	System.Drawing.Size{75, 31}
			SELF:TestButton:TabIndex	:=	0
			SELF:TestButton:Text	:=	"&Test"
			SELF:TestButton:UseVisualStyleBackColor	:=	true
			SELF:TestButton:Click	+=	System.EventHandler{ SELF, @TestButton_Click() }
			//	
			//	tbUDC
			//	
			SELF:tbUDC:AcceptsReturn	:=	true
			SELF:tbUDC:Dock	:=	System.Windows.Forms.DockStyle.Fill
			SELF:tbUDC:Font	:=	System.Drawing.Font{"Courier New", 12, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
			SELF:tbUDC:Location	:=	System.Drawing.Point{78, 3}
			SELF:tbUDC:Multiline	:=	true
			SELF:tbUDC:Name	:=	"tbUDC"
			SELF:tbUDC:ScrollBars	:=	System.Windows.Forms.ScrollBars.Vertical
			SELF:tbUDC:Size	:=	System.Drawing.Size{940, 176}
			SELF:tbUDC:TabIndex	:=	5
			SELF:tbUDC:WordWrap	:=	false
			//	
			//	UDCTester
			//	
			SELF:AutoScaleDimensions	:=	System.Drawing.SizeF{6, 13}
			SELF:AutoScaleMode	:=	System.Windows.Forms.AutoScaleMode.Font
			SELF:ClientSize	:=	System.Drawing.Size{1018, 597}
			SELF:Controls:Add(SELF:tableLayoutPanel1)
			SELF:Icon	:=	((System.Drawing.Icon)(resources:GetObject("$this.Icon")))
			SELF:Margin	:=	System.Windows.Forms.Padding{2}
			SELF:Name	:=	"UDCTester"
			SELF:StartPosition	:=	System.Windows.Forms.FormStartPosition.CenterScreen
			SELF:Text	:=	"UDCTester"
			SELF:tableLayoutPanel1:ResumeLayout(false)
			SELF:tableLayoutPanel1:PerformLayout()
			SELF:panel1:ResumeLayout(false)
			SELF:panel1:PerformLayout()
			SELF:ResumeLayout(false)

        #endregion
    END CLASS 
END NAMESPACE
