
USING System
USING System.Collections.Generic
USING System.Text
USING System.Xml.Serialization

CLASS FRXItem
	
	// PLATFORM,C,8,0
	PROPERTY PLATFORM AS STRING AUTO
	// UNIQUEID,C,10,0
	PROPERTY UNIQUEID AS STRING AUTO
	// TIMESTAMP,N,10,0
	PROPERTY TIMESTAMP AS INT AUTO
	// OBJTYPE,N,2,0
	PROPERTY OBJTYPE AS INT AUTO
	// OBJCODE,N,3,0
	PROPERTY OBJCODE AS INT AUTO
	// NAME,M,4,0
	PROPERTY NAME AS STRING AUTO
	// EXPR,M,4,0
	PROPERTY EXPR AS STRING AUTO
	// VPOS,N,9,3
	PROPERTY VPOS AS Double AUTO
	// HPOS,N,9,3
	PROPERTY HPOS AS Double AUTO
	// HEIGHT,N,9,3
	PROPERTY HEIGHT AS Double AUTO
	// WIDTH,N,9,3
	PROPERTY WIDTH AS Double AUTO
	// STYLE,M,4,0
	PROPERTY STYLE AS STRING AUTO
	// PICTURE,M,4,0
	PROPERTY PICTURE AS STRING AUTO
	// ORDER,M,4,0
	[XmlIgnore];
	PROPERTY ORDER AS OBJECT AUTO
	// UNIQUE,L,1,0
	PROPERTY UNIQUE AS LOGIC AUTO
	// COMMENT,M,4,0
	PROPERTY COMMENT AS STRING AUTO
	// ENVIRON,L,1,0
	PROPERTY ENVIRON AS LOGIC AUTO
	// BOXCHAR,C,1,0
	PROPERTY BOXCHAR AS STRING AUTO
	// FILLCHAR,C,1,0
	PROPERTY FILLCHAR AS STRING AUTO
	// TAG,M,4,0
	PROPERTY TAG AS STRING AUTO
	// TAG2,M,4,0
	[XmlIgnore];
	PROPERTY TAG2 AS OBJECT AUTO
	// PENRED,N,5,0
	PROPERTY PENRED AS INT AUTO
	// PENGREEN,N,5,0
	PROPERTY PENGREEN AS INT AUTO
	// PENBLUE,N,5,0
	PROPERTY PENBLUE AS INT AUTO
	// FILLRED,N,5,0
	PROPERTY FILLRED AS INT AUTO
	// FILLGREEN,N,5,0
	PROPERTY FILLGREEN AS INT AUTO
	// FILLBLUE,N,5,0
	PROPERTY FILLBLUE AS INT AUTO
	// PENSIZE,N,5,0
	PROPERTY PENSIZE AS INT AUTO
	// PENPAT,N,5,0
	PROPERTY PENPAT AS INT AUTO
	// FILLPAT,N,5,0
	PROPERTY FILLPAT AS INT AUTO
	// FONTFACE,M,4,0
	PROPERTY FONTFACE AS STRING AUTO
	// FONTSTYLE,N,3,0
	PROPERTY FONTSTYLE AS INT AUTO
	// FONTSIZE,N,3,0
	PROPERTY FONTSIZE AS INT AUTO
	// MODE,N,3,0
	PROPERTY MODE AS INT AUTO
	// RULER,N,1,0
	PROPERTY RULER AS INT AUTO
	// RULERLINES,N,1,0
	PROPERTY RULERLINES AS INT AUTO
	// GRID,L,1,0
	PROPERTY GRID AS LOGIC AUTO
	// GRIDV,N,2,0
	PROPERTY GRIDV AS INT AUTO
	// GRIDH,N,2,0
	PROPERTY GRIDH AS INT AUTO
	// FLOAT,L,1,0
	PROPERTY FLOAT AS LOGIC AUTO
	// STRETCH,L,1,0
	PROPERTY STRETCH AS LOGIC AUTO
	// STRETCHTOP,L,1,0
	PROPERTY STRETCHTOP AS LOGIC AUTO
	// TOP,L,1,0
	PROPERTY TOP AS LOGIC AUTO
	// BOTTOM,L,1,0
	PROPERTY BOTTOM AS LOGIC AUTO
	// SUPTYPE,N,1,0
	PROPERTY SUPTYPE AS INT AUTO
	// SUPREST,N,1,0
	PROPERTY SUPREST AS INT AUTO
	// NOREPEAT,L,1,0
	PROPERTY NOREPEAT AS LOGIC AUTO
	// RESETRPT,N,2,0
	PROPERTY RESETRPT AS INT AUTO
	// PAGEBREAK,L,1,0
	PROPERTY PAGEBREAK AS LOGIC AUTO
	// COLBREAK,L,1,0
	PROPERTY COLBREAK AS LOGIC AUTO
	// RESETPAGE,L,1,0
	PROPERTY RESETPAGE AS LOGIC AUTO
	// GENERAL,N,3,0
	PROPERTY GENERAL AS INT AUTO
	// SPACING,N,3,0
	PROPERTY SPACING AS INT AUTO
	// DOUBLE,L,1,0
	PROPERTY DOUBLE AS LOGIC AUTO
	// SWAPHEADER,L,1,0
	PROPERTY SWAPHEADER AS LOGIC AUTO
	// SWAPFOOTER,L,1,0
	PROPERTY SWAPFOOTER AS LOGIC AUTO
	// EJECTBEFOR,L,1,0
	PROPERTY EJECTBEFOR AS LOGIC AUTO
	// EJECTAFTER,L,1,0
	PROPERTY EJECTAFTER AS LOGIC AUTO
	// PLAIN,L,1,0
	PROPERTY PLAIN AS LOGIC AUTO
	// SUMMARY,L,1,0
	PROPERTY SUMMARY AS LOGIC AUTO
	// ADDALIAS,L,1,0
	PROPERTY ADDALIAS AS LOGIC AUTO
	// OFFSET,N,3,0
	PROPERTY OFFSET AS INT AUTO
	// TOPMARGIN,N,3,0
	PROPERTY TOPMARGIN AS INT AUTO
	// BOTMARGIN,N,3,0
	PROPERTY BOTMARGIN AS INT AUTO
	// TOTALTYPE,N,2,0
	PROPERTY TOTALTYPE AS INT AUTO
	// RESETTOTAL,N,2,0
	PROPERTY RESETTOTAL AS INT AUTO
	// RESOID,N,3,0
	PROPERTY RESOID AS INT AUTO
	// CURPOS,L,1,0
	PROPERTY CURPOS AS LOGIC AUTO
	// SUPALWAYS,L,1,0
	PROPERTY SUPALWAYS AS LOGIC AUTO
	// SUPOVFLOW,L,1,0
	PROPERTY SUPOVFLOW AS LOGIC AUTO
	// SUPRPCOL,N,1,0
	PROPERTY SUPRPCOL AS INT AUTO
	// SUPGROUP,N,2,0
	PROPERTY SUPGROUP AS INT AUTO
	// SUPVALCHNG,L,1,0
	PROPERTY SUPVALCHNG AS LOGIC AUTO
	// SUPEXPR,M,4,0
	PROPERTY SUPEXPR AS STRING AUTO
	// USER,M,4,0
	PROPERTY USER AS STRING AUTO
	
	
	CONSTRUCTOR()
		SELF:PLATFORM := FieldGet(FieldPos("PLATFORM"))
		SELF:UNIQUEID := FieldGet(FieldPos("UNIQUEID"))
		SELF:TIMESTAMP := FieldGet(FieldPos("TIMESTAMP"))
		SELF:OBJTYPE := FieldGet(FieldPos("OBJTYPE"))
		SELF:OBJCODE := FieldGet(FieldPos("OBJCODE"))
		SELF:NAME := FieldGet(FieldPos("NAME"))
		SELF:EXPR := FieldGet(FieldPos("EXPR"))
		SELF:VPOS := FieldGet(FieldPos("VPOS"))
		SELF:HPOS := FieldGet(FieldPos("HPOS"))
		SELF:HEIGHT := FieldGet(FieldPos("HEIGHT"))
		SELF:WIDTH := FieldGet(FieldPos("WIDTH"))
		SELF:STYLE := FieldGet(FieldPos("STYLE"))
		SELF:PICTURE := FieldGet(FieldPos("PICTURE"))
		SELF:ORDER := FieldGet(FieldPos("ORDER"))
		SELF:UNIQUE := FieldGet(FieldPos("UNIQUE"))
		SELF:COMMENT := FieldGet(FieldPos("COMMENT"))
		SELF:ENVIRON := FieldGet(FieldPos("ENVIRON"))
		SELF:BOXCHAR := FieldGet(FieldPos("BOXCHAR"))
		SELF:FILLCHAR := FieldGet(FieldPos("FILLCHAR"))
		SELF:TAG := FieldGet(FieldPos("TAG"))
		SELF:TAG2 := FieldGet(FieldPos("TAG2"))
		SELF:PENRED := FieldGet(FieldPos("PENRED"))
		SELF:PENGREEN := FieldGet(FieldPos("PENGREEN"))
		SELF:PENBLUE := FieldGet(FieldPos("PENBLUE"))
		SELF:FILLRED := FieldGet(FieldPos("FILLRED"))
		SELF:FILLGREEN := FieldGet(FieldPos("FILLGREEN"))
		SELF:FILLBLUE := FieldGet(FieldPos("FILLBLUE"))
		SELF:PENSIZE := FieldGet(FieldPos("PENSIZE"))
		SELF:PENPAT := FieldGet(FieldPos("PENPAT"))
		SELF:FILLPAT := FieldGet(FieldPos("FILLPAT"))
		SELF:FONTFACE := FieldGet(FieldPos("FONTFACE"))
		SELF:FONTSTYLE := FieldGet(FieldPos("FONTSTYLE"))
		SELF:FONTSIZE := FieldGet(FieldPos("FONTSIZE"))
		SELF:MODE := FieldGet(FieldPos("MODE"))
		SELF:RULER := FieldGet(FieldPos("RULER"))
		SELF:RULERLINES := FieldGet(FieldPos("RULERLINES"))
		SELF:GRID := FieldGet(FieldPos("GRID"))
		SELF:GRIDV := FieldGet(FieldPos("GRIDV"))
		SELF:GRIDH := FieldGet(FieldPos("GRIDH"))
		SELF:FLOAT := FieldGet(FieldPos("FLOAT"))
		SELF:STRETCH := FieldGet(FieldPos("STRETCH"))
		SELF:STRETCHTOP := FieldGet(FieldPos("STRETCHTOP"))
		SELF:TOP := FieldGet(FieldPos("TOP"))
		SELF:BOTTOM := FieldGet(FieldPos("BOTTOM"))
		SELF:SUPTYPE := FieldGet(FieldPos("SUPTYPE"))
		SELF:SUPREST := FieldGet(FieldPos("SUPREST"))
		SELF:NOREPEAT := FieldGet(FieldPos("NOREPEAT"))
		SELF:RESETRPT := FieldGet(FieldPos("RESETRPT"))
		SELF:PAGEBREAK := FieldGet(FieldPos("PAGEBREAK"))
		SELF:COLBREAK := FieldGet(FieldPos("COLBREAK"))
		SELF:RESETPAGE := FieldGet(FieldPos("RESETPAGE"))
		SELF:GENERAL := FieldGet(FieldPos("GENERAL"))
		SELF:SPACING := FieldGet(FieldPos("SPACING"))
		SELF:DOUBLE := FieldGet(FieldPos("DOUBLE"))
		SELF:SWAPHEADER := FieldGet(FieldPos("SWAPHEADER"))
		SELF:SWAPFOOTER := FieldGet(FieldPos("SWAPFOOTER"))
		SELF:EJECTBEFOR := FieldGet(FieldPos("EJECTBEFOR"))
		SELF:EJECTAFTER := FieldGet(FieldPos("EJECTAFTER"))
		SELF:PLAIN := FieldGet(FieldPos("PLAIN"))
		SELF:SUMMARY := FieldGet(FieldPos("SUMMARY"))
		SELF:ADDALIAS := FieldGet(FieldPos("ADDALIAS"))
		SELF:OFFSET := FieldGet(FieldPos("OFFSET"))
		SELF:TOPMARGIN := FieldGet(FieldPos("TOPMARGIN"))
		SELF:BOTMARGIN := FieldGet(FieldPos("BOTMARGIN"))
		SELF:TOTALTYPE := FieldGet(FieldPos("TOTALTYPE"))
		SELF:RESETTOTAL := FieldGet(FieldPos("RESETTOTAL"))
		SELF:RESOID := FieldGet(FieldPos("RESOID"))
		SELF:CURPOS := FieldGet(FieldPos("CURPOS"))
		SELF:SUPALWAYS := FieldGet(FieldPos("SUPALWAYS"))
		SELF:SUPOVFLOW := FieldGet(FieldPos("SUPOVFLOW"))
		SELF:SUPRPCOL := FieldGet(FieldPos("SUPRPCOL"))
		SELF:SUPGROUP := FieldGet(FieldPos("SUPGROUP"))
		SELF:SUPVALCHNG := FieldGet(FieldPos("SUPVALCHNG"))
		SELF:SUPEXPR := FieldGet(FieldPos("SUPEXPR"))
		SELF:USER := FieldGet(FieldPos("USER"))
		
		RETURN
	
	CONSTRUCTOR( itemToCopy AS FRXItem)
		SELF:PLATFORM := itemToCopy:PLATFORM
		SELF:UNIQUEID := itemToCopy:UNIQUEID
		SELF:TIMESTAMP := itemToCopy:TIMESTAMP
		SELF:OBJTYPE := itemToCopy:OBJTYPE
		SELF:OBJCODE := itemToCopy:OBJCODE
		SELF:NAME := itemToCopy:NAME
		SELF:EXPR := itemToCopy:EXPR
		SELF:VPOS := itemToCopy:VPOS
		SELF:HPOS := itemToCopy:HPOS
		SELF:HEIGHT := itemToCopy:HEIGHT
		SELF:WIDTH := itemToCopy:WIDTH
		SELF:STYLE := itemToCopy:STYLE
		SELF:PICTURE := itemToCopy:PICTURE
		SELF:ORDER := itemToCopy:ORDER
		SELF:UNIQUE := itemToCopy:UNIQUE
		SELF:COMMENT := itemToCopy:COMMENT
		SELF:ENVIRON := itemToCopy:ENVIRON
		SELF:BOXCHAR := itemToCopy:BOXCHAR
		SELF:FILLCHAR := itemToCopy:FILLCHAR
		SELF:TAG := itemToCopy:TAG
		SELF:TAG2 := itemToCopy:TAG2
		SELF:PENRED := itemToCopy:PENRED
		SELF:PENGREEN := itemToCopy:PENGREEN
		SELF:PENBLUE := itemToCopy:PENBLUE
		SELF:FILLRED := itemToCopy:FILLRED
		SELF:FILLGREEN := itemToCopy:FILLGREEN
		SELF:FILLBLUE := itemToCopy:FILLBLUE
		SELF:PENSIZE := itemToCopy:PENSIZE
		SELF:PENPAT := itemToCopy:PENPAT
		SELF:FILLPAT := itemToCopy:FILLPAT
		SELF:FONTFACE := itemToCopy:FONTFACE
		SELF:FONTSTYLE := itemToCopy:FONTSTYLE
		SELF:FONTSIZE := itemToCopy:FONTSIZE
		SELF:MODE := itemToCopy:MODE
		SELF:RULER := itemToCopy:RULER
		SELF:RULERLINES := itemToCopy:RULERLINES
		SELF:GRID := itemToCopy:GRID
		SELF:GRIDV := itemToCopy:GRIDV
		SELF:GRIDH := itemToCopy:GRIDH
		SELF:FLOAT := itemToCopy:FLOAT
		SELF:STRETCH := itemToCopy:STRETCH
		SELF:STRETCHTOP := itemToCopy:STRETCHTOP
		SELF:TOP := itemToCopy:TOP
		SELF:BOTTOM := itemToCopy:BOTTOM
		SELF:SUPTYPE := itemToCopy:SUPTYPE
		SELF:SUPREST := itemToCopy:SUPREST
		SELF:NOREPEAT := itemToCopy:NOREPEAT
		SELF:RESETRPT := itemToCopy:RESETRPT
		SELF:PAGEBREAK := itemToCopy:PAGEBREAK
		SELF:COLBREAK := itemToCopy:COLBREAK
		SELF:RESETPAGE := itemToCopy:RESETPAGE
		SELF:GENERAL := itemToCopy:GENERAL
		SELF:SPACING := itemToCopy:SPACING
		SELF:DOUBLE := itemToCopy:DOUBLE
		SELF:SWAPHEADER := itemToCopy:SWAPHEADER
		SELF:SWAPFOOTER := itemToCopy:SWAPFOOTER
		SELF:EJECTBEFOR := itemToCopy:EJECTBEFOR
		SELF:EJECTAFTER := itemToCopy:EJECTAFTER
		SELF:PLAIN := itemToCopy:PLAIN
		SELF:SUMMARY := itemToCopy:SUMMARY
		SELF:ADDALIAS := itemToCopy:ADDALIAS
		SELF:OFFSET := itemToCopy:OFFSET
		SELF:TOPMARGIN := itemToCopy:TOPMARGIN
		SELF:BOTMARGIN := itemToCopy:BOTMARGIN
		SELF:TOTALTYPE := itemToCopy:TOTALTYPE
		SELF:RESETTOTAL := itemToCopy:RESETTOTAL
		SELF:RESOID := itemToCopy:RESOID
		SELF:CURPOS := itemToCopy:CURPOS
		SELF:SUPALWAYS := itemToCopy:SUPALWAYS
		SELF:SUPOVFLOW := itemToCopy:SUPOVFLOW
		SELF:SUPRPCOL := itemToCopy:SUPRPCOL
		SELF:SUPGROUP := itemToCopy:SUPGROUP
		SELF:SUPVALCHNG := itemToCopy:SUPVALCHNG
		SELF:SUPEXPR := itemToCopy:SUPEXPR
		SELF:USER := itemToCopy:USER
		
		RETURN	
		
	END CLASS