// PJXItem.prg
// Created by    : fabri
// Creation Date : 11/9/2019 2:01:49 PM
// Created for   : 
// WorkStation   : FABPORTABLE


USING System
USING System.Collections.Generic
USING System.Text

BEGIN NAMESPACE VFPXPorterLib

	/// <summary>
	/// The PJXItem class : 
	/// </summary>
	CLASS PJXItem
		// NAME,M,4,0
		PROPERTY NAME AS STRING AUTO
		// TYPE,C,1,0
		PROPERTY TYPE AS STRING AUTO
		// ID,N,10,0
		PROPERTY ID AS INT AUTO
		// TIMESTAMP,N,10,0
		PROPERTY TIMESTAMP AS INT AUTO
		// OUTFILE,M,4,0
		PROPERTY OUTFILE AS STRING AUTO
		// HOMEDIR,M,4,0
		PROPERTY HOMEDIR AS STRING AUTO
		// EXCLUDE,L,1,0
		PROPERTY EXCLUDE AS LOGIC AUTO
		// MAINPROG,L,1,0
		PROPERTY MAINPROG AS LOGIC AUTO
		// SAVECODE,L,1,0
		PROPERTY SAVECODE AS LOGIC AUTO
		// DEBUG,L,1,0
		PROPERTY isDEBUG AS LOGIC AUTO
		// ENCRYPT,L,1,0
		PROPERTY ENCRYPT AS LOGIC AUTO
		// NOLOGO,L,1,0
		PROPERTY NOLOGO AS LOGIC AUTO
		// CMNTSTYLE,N,1,0
		PROPERTY CMNTSTYLE AS INT AUTO
		// OBJREV,N,5,0
		PROPERTY OBJREV AS INT AUTO
		// DEVINFO,M,4,0
		PROPERTY DEVINFO AS STRING AUTO
		// SYMBOLS,M,4,0
		//PROPERTY SYMBOLS AS STRING AUTO
		// OBJECT,M,4,0
		//PROPERTY OBJECT AS STRING AUTO
		// CKVAL,N,6,0
		PROPERTY CKVAL AS INT AUTO
		// CPID,N,5,0
		PROPERTY CPID AS INT AUTO
		// OSTYPE,C,4,0
		PROPERTY OSTYPE AS STRING AUTO
		// OSCREATOR,C,4,0
		PROPERTY OSCREATOR AS STRING AUTO
		// COMMENTS,M,4,0
		PROPERTY COMMENTS AS STRING AUTO
		// RESERVED1,M,4,0
		PROPERTY RESERVED1 AS STRING AUTO
		// RESERVED2,M,4,0
		PROPERTY RESERVED2 AS STRING AUTO
		// SCCDATA,M,4,0
		PROPERTY SCCDATA AS STRING AUTO
		// LOCAL,L,1,0
		PROPERTY LOCAL AS LOGIC AUTO
		// KEY,C,32,0
		PROPERTY KEY AS STRING AUTO
		// USER,M,4,0
		PROPERTY USER AS STRING AUTO
		
		CONSTRUCTOR()
			SELF:NAME := FieldGet(FieldPos("NAME"))
			SELF:TYPE := FieldGet(FieldPos("TYPE"))
			SELF:ID := FieldGet(FieldPos("ID"))
			SELF:TIMESTAMP := FieldGet(FieldPos("TIMESTAMP"))
			SELF:OUTFILE := FieldGet(FieldPos("OUTFILE"))
			SELF:HOMEDIR := FieldGet(FieldPos("HOMEDIR"))
			SELF:EXCLUDE := FieldGet(FieldPos("EXCLUDE"))
			SELF:MAINPROG := FieldGet(FieldPos("MAINPROG"))
			SELF:SAVECODE := FieldGet(FieldPos("SAVECODE"))
			SELF:isDEBUG := FieldGet(FieldPos("DEBUG"))
			SELF:ENCRYPT := FieldGet(FieldPos("ENCRYPT"))
			SELF:NOLOGO := FieldGet(FieldPos("NOLOGO"))
			SELF:CMNTSTYLE := FieldGet(FieldPos("CMNTSTYLE"))
			SELF:OBJREV := FieldGet(FieldPos("OBJREV"))
			SELF:DEVINFO := FieldGet(FieldPos("DEVINFO"))
			//SELF:SYMBOLS := FieldGet(FieldPos("SYMBOLS"))
			//SELF:OBJECT := FieldGet(FieldPos("OBJECT"))
			SELF:CKVAL := FieldGet(FieldPos("CKVAL"))
			SELF:CPID := FieldGet(FieldPos("CPID"))
			SELF:OSTYPE := FieldGet(FieldPos("OSTYPE"))
			SELF:OSCREATOR := FieldGet(FieldPos("OSCREATOR"))
			SELF:COMMENTS := FieldGet(FieldPos("COMMENTS"))
			SELF:RESERVED1 := FieldGet(FieldPos("RESERVED1"))
			SELF:RESERVED2 := FieldGet(FieldPos("RESERVED2"))
			SELF:SCCDATA := FieldGet(FieldPos("SCCDATA"))
			SELF:LOCAL := FieldGet(FieldPos("LOCAL"))
			SELF:KEY := FieldGet(FieldPos("KEY"))
			SELF:USER := FieldGet(FieldPos("USER"))
			RETURN
			
		CONSTRUCTOR( itemToCopy AS PJXItem )
			SELF:NAME := itemToCopy:NAME
			SELF:TYPE := itemToCopy:TYPE
			SELF:ID := itemToCopy:ID
			SELF:TIMESTAMP := itemToCopy:TIMESTAMP
			SELF:OUTFILE := itemToCopy:OUTFILE
			SELF:HOMEDIR := itemToCopy:HOMEDIR
			SELF:EXCLUDE := itemToCopy:EXCLUDE
			SELF:MAINPROG := itemToCopy:MAINPROG
			SELF:SAVECODE := itemToCopy:SAVECODE
			SELF:isDEBUG := itemToCopy:isDEBUG
			SELF:ENCRYPT := itemToCopy:ENCRYPT
			SELF:NOLOGO := itemToCopy:NOLOGO
			SELF:CMNTSTYLE := itemToCopy:CMNTSTYLE
			SELF:OBJREV := itemToCopy:OBJREV
			SELF:DEVINFO := itemToCopy:DEVINFO
			//SELF:SYMBOLS := itemToCopy:SYMBOLS
			//SELF:OBJECT := itemToCopy:OBJECT
			SELF:CKVAL := itemToCopy:CKVAL
			SELF:CPID := itemToCopy:CPID
			SELF:OSTYPE := itemToCopy:OSTYPE
			SELF:OSCREATOR := itemToCopy:OSCREATOR
			SELF:COMMENTS := itemToCopy:COMMENTS
			SELF:RESERVED1 := itemToCopy:RESERVED1
			SELF:RESERVED2 := itemToCopy:RESERVED2
			SELF:SCCDATA := itemToCopy:SCCDATA
			SELF:LOCAL := itemToCopy:LOCAL
			SELF:KEY := itemToCopy:KEY
			SELF:USER := itemToCopy:USER
			RETURN
			
			END CLASS
			
END NAMESPACE // FabVFPXPorter