// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharp.LanguageService.LanguageService
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidLanguage_Service_2015PkgString = "e9b6ee0f-9bfa-4cff-a60b-51a08bbc5050";
        public static Guid guidLanguage_Service_2015Pkg = new Guid(guidLanguage_Service_2015PkgString);

        public const string guidLanguage_Service_2015CmdSetString = "6511ea00-4558-4ae7-84ee-0e2aebd40d88";
        public static Guid guidLanguage_Service_2015CmdSet = new Guid(guidLanguage_Service_2015CmdSetString);

        public const string guidImagesString = "8a6dba2e-d52a-437e-bcd6-a1fb9d7c9268";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int cmdidInsertSnippet = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}