//
// Copyright (c) XSharp B.V.  All Rights Reserved.  
// Licensed under the Apache License, Version 2.0.  
// See License.txt in the project root for license information.
//
using System
using System.Runtime.InteropServices
using System.Runtime.CompilerServices

begin namespace XSharp
	// use explicit layout so we can compact the size into 12 bytes
	// Type is Immutable, so no settable properties
	/// <summary>Internal type that implements the VO Compatible FLOAT type.
	/// This type has many operators and implicit converters that normally are never directly called from user code.
	/// </summary>
	/// <seealso cref="T:XSharp.IFloat"/>
	/// <seealso cref="T:XSharp.RDD.DbFloat"/>
	[StructLayout(LayoutKind.Explicit, Pack := 4)];
	public structure __VOFloat implements IFLoat, ;
		IConvertible,; 
		IFormattable, ;
		IComparable<__VoFloat>, ;
		IEquatable<__VoFloat>, ;
		IComparable
	
		[FieldOffset(0)]  private initonly _value as real8
		[FieldOffset(8)]  private initonly _length as shortint
		[FieldOffset(10)] private initonly _decimals as shortint
		
		#region constructors
			/// <summary>This constructor is used in code generated by the compiler when needed.</summary>
			/// <param name="r8">Real8 value to convert to a FLOAT</param>
            [MethodImpl(MethodImplOptions.AggressiveInlining)];        
			constructor (r8 as real8)
				self:_value    := r8
				self:_length   := 0
				self:_decimals := 0
			
			/// <summary>This constructor is used in code generated by the compiler when needed.</summary>
            [MethodImpl(MethodImplOptions.AggressiveInlining)];        
			constructor (r8 as real8, decimals as int)
				self:_value    := r8
				self:_length   := 0
				self:_decimals := (shortint) decimals 
			
			/// <summary>This constructor is used in code generated by the compiler when needed.</summary>
            [MethodImpl(MethodImplOptions.AggressiveInlining)];        
			constructor (r8 as real8, decimals as dword)
				self:_value    := r8
				self:_length   := 0
				self:_decimals := (shortint) decimals 
			
			/// <summary>This constructor is used in code generated by the compiler when needed.</summary>
            [MethodImpl(MethodImplOptions.AggressiveInlining)];        
			constructor (r8 as real8, length as dword, decimals as dword)
				self:_value    := r8
				self:_length   := (shortint) length
				self:_decimals := (shortint) decimals 
			
			/// <summary>This constructor is used in code generated by the compiler when needed.</summary>
            [MethodImpl(MethodImplOptions.AggressiveInlining)];        
			constructor (r8 as real8, length as int, decimals as int )
				self:_value    := r8
				self:_length   := (shortint) length
				self:_decimals := (shortint) decimals
			
			/// <summary>This constructor is used in code generated by the compiler when needed.</summary>
            [MethodImpl(MethodImplOptions.AggressiveInlining)];        
			constructor (value as IFloat)
				self:_value		:= value:value
				self:_length	:= (short) value:Digits
				self:_decimals	:= (short) value:Decimals
		#endregion
		#region Properties
			/// <summary>REAL8 (System.Double) value</summary>
			PROPERTY @@Value    AS REAL8	GET _value			
			/// <summary>Width </summary>
			PROPERTY Digits   AS INT	GET _length		
			/// <summary>Number of decimals</summary>
			property Decimals as int	get _decimals	
		#endregion
		
		#region Equality Operators
			/// <summary>This method is used in code generated by the compiler when needed.</summary>
			override method Equals(rhs as object  ) as logic
				local result as logic
				if rhs != null .and. rhs is Float
					result := self:Equals( (Float) rhs)
				else
					result := false
				endif
				return result

			/// <summary>This method is used in code generated by the compiler when needed.</summary>
			method Equals(rhs as float ) as logic
				local delta as real8
				local diff  as real8
				local equal as logic
				delta := RuntimeState.FloatDelta
				diff := _value - rhs:_value
				if delta == 0.0
					equal :=  diff == 0.0
				elseif diff < 0.0
					equal :=  Math.Abs(diff) < delta
				else
					equal := diff < delta
				endif
				return equal

			/// <inheritdoc />
			virtual method GetHashCode() as int
				return self:_value:GetHashCode()
			
			/// <exclude />	
			method GetTypeCode() as TypeCode
				return TypeCode.Double
			
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator ==(lhs as Float, rhs as Float) as logic
				return lhs:Equals(rhs)
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator !=(lhs as Float, rhs as Float) as logic
				return ! lhs:Equals(rhs)
		#endregion
		
		#region Comparison Operators
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator >(lhs as Float, rhs as Float) as logic
				local delta as real8
				local diff  as real8
				delta := RuntimeState.FloatDelta
				diff := lhs:_value - rhs:_value
				if (delta == 0.0)
					return diff > 0.0
				endif
				return diff > delta
				
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator <(lhs as Float, rhs as Float) as logic
				local delta as real8
				local diff  as real8
				delta := RuntimeState.FloatDelta
				diff := lhs:_value - rhs:_value
				if (delta == 0.0)
					return diff < 0.0
				endif
				return diff < delta
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator >=(lhs as float, rhs as float) as logic
				// call other operator methods for simplicity
				// we may want to optimize this later
				return lhs > rhs .or. lhs == rhs

			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator <=(lhs as Float, rhs as Float) as logic
				// call other operator methods for simplicity
				// we may want to optimize this later
				return lhs < rhs .or. lhs == rhs

		#endregion
		
		#region Implicit Converters
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(b as byte) as Float
				return Float{b, 0}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(sb as SByte) as Float
				return Float{sb, 0}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(si as short) as Float
				return Float{si, 0}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(w as word) as Float
				return Float{w, 0}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(i as int) as Float
				return Float{i, 0}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(dw as dword) as Float
				return Float{dw, 0}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(i64 as int64) as Float
				return Float{i64, 0}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(ui64 as uint64) as Float
				return Float{ui64, 0}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(r4 as real4) as Float
				return Float{r4, RuntimeState.Decimals}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(r8 as real8) as Float
				return Float{r8, RuntimeState.Decimals}
			
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(value as System.Decimal) as Float
				return Float{ (real8) value, RuntimeState.Decimals}
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(fl  as Float) as real8
				return fl:_value
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(fl  as Float) as real4
				return (real4) fl:_value
			
			/// <summary>This implicit converter is used in code generated by the compiler when needed.</summary>
			static operator implicit(fl  as Float) as System.Decimal
				return (System.Decimal) fl:_value			
		#endregion
		#region Explicit Converters
			/// <summary>This explicit converter is used in code generated by the compiler when you use a cast in your code.</summary>
			static operator explicit(fl  as Float) as byte
				if RuntimeState.CompilerOptionVO11
					return Convert.ToByte(fl:_value)
				endif
				return (byte) fl:_value
			/// <summary>This explicit converter is used in code generated by the compiler when you use a cast in your code.</summary>
			static operator explicit(fl as Float) as SByte
				return (SByte) fl:_value
			/// <summary>This explicit converter is used in code generated by the compiler when you use a cast in your code.</summary>
			static operator explicit(fl  as Float) as short
				if RuntimeState.CompilerOptionVO11
					return Convert.ToInt16(fl:_value)
				endif
				return (short) fl:_value
			/// <summary>This explicit converter is used in code generated by the compiler when you use a cast in your code.</summary>
			static operator explicit(fl  as Float) as word
				return (word) fl:_value
			/// <summary>This explicit converter is used in code generated by the compiler when you use a cast in your code.</summary>
			static operator explicit(fl  as Float) as long
				if RuntimeState.CompilerOptionVO11
					return Convert.ToInt32(fl:_value)
				endif
				return (long) fl:_value
			/// <summary>This explicit converter is used in code generated by the compiler when you use a cast in your code.</summary>
			static operator explicit(fl  as Float) as dword
				return (dword) fl:_value
			/// <summary>This explicit converter is used in code generated by the compiler when you use a cast in your code.</summary>
			static operator explicit(fl  as Float) as int64
				if RuntimeState.CompilerOptionVO11
					return Convert.ToInt64(fl:_value)
				endif
				return (int64) fl:_value
			/// <summary>This explicit converter is used in code generated by the compiler when you use a cast in your code.</summary>
			static operator explicit(fl  as Float) as uint64
				return (uint64) fl:_value
			
		#endregion
		
		#region Numeric Operators
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator +(fl  as Float) as Float
				return fl
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator -(fl  as Float) as Float
				return Float{- fl:_value, fl:Digits, fl:Decimals}
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator+(lhs as Float, rhs as Float) as Float
				return lhs:Add(rhs)
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator+(lhs as Float, rhs as usual) as Float
				return lhs:Add(rhs)
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator+(lhs as usual, rhs as Float) as Float
				return rhs:Add(lhs)
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator-(lhs as Float, rhs as Float) as Float
				return lhs:Subtract(rhs)
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator-(lhs as Float, rhs as usual) as Float
				return lhs:Subtract(rhs)
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator-(lhs as usual, rhs as Float) as Float
				// set decimals for LHS to 0, so max decmals is decimals right
				return Float{lhs, 0}:Subtract(rhs)		
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator*(lhs as Float, rhs as Float) as Float
				return Float{ lhs:_value * rhs:_value, lhs:Decimals + rhs:Decimals}
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator/(lhs as Float, rhs as Float) as Float
				return Float{ lhs:_value / rhs:_value, RuntimeState.Decimals}
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator%(lhs as Float, rhs as Float) as Float
				return Float{ lhs:_value % rhs:_value, RuntimeState.Decimals}
			
		#endregion
		#region Unary Operators
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator ++ (fl  as Float) as Float
				return Float{fl:_value+1, fl:Digits, fl:Decimals}
			
			/// <summary>This operator is used in code generated by the compiler when needed.</summary>
			operator -- (fl  as Float) as Float
				return Float{fl:_value-1, fl:Digits, fl:Decimals}
		#endregion
		
		#region Explicit casts. Used inside Transform
    	/// <exclude />	
	   METHOD CastToInt() AS INT
		  RETURN (INT)(SELF:_value)

		/// <exclude />	
	   METHOD CastToInt64() AS INT64
		  RETURN (INT64)(SELF:_value)

		#endregion
		#region Add and Subtract
			/// <exclude />	
			method Add(rhs as Float) as Float
				return Float{ self:_value + rhs:_value, math.Max(self:_decimals, rhs:_decimals)}
			
			/// <exclude />	
			method Add(rhs as usual) as Float
				local result as Float
				if rhs:IsFloat
					result := self:Add ( (Float) rhs)
				elseif rhs:IsDecimal
					result := self:Add ( (System.Decimal) rhs)
				elseif  rhs:IsLong
					result := Float{ self:_value + (long) rhs, self:Digits, self:Decimals}
				else
					throw Error.ArgumentError(__ENTITY__,nameof(rhs), "Argument is not numeric")
				endif
				return result
			
			
			/// <exclude />	
			method Subtract(rhs as Float) as Float
				return Float{ self:_value - rhs:_value, math.Max(self:_decimals, rhs:_decimals)}
			
			/// <exclude />	
			method Subtract(rhs as usual) as Float
				local result as Float
				if rhs:IsFloat
					result := self:Subtract( (Float) rhs)
				elseif rhs:IsDecimal
					result := self:Subtract( (System.Decimal) rhs)
				elseif  rhs:IsLong
					result := Float{ self:_value - (long) rhs, self:Digits, self:Decimals}			
				else
					throw Error.ArgumentError(__ENTITY__,nameof(rhs), "Argument is not numeric")
				endif
				return result
			
			
		#endregion
		
		#region IConvertable
			/// <inheritdoc />
			public method IConvertible.ToBoolean(provider as System.IFormatProvider) as logic
				throw NotImplementedException{}
			
			/// <inheritdoc />
			public method IConvertible.ToByte(provider as System.IFormatProvider) as byte
				return ((IConvertible) _value):ToByte(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToChar(provider as System.IFormatProvider) as char
				return ((IConvertible) _value):ToChar(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToDateTime(provider as System.IFormatProvider) as System.DateTime
				return ((IConvertible) _value):ToDateTime(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToDecimal(provider as System.IFormatProvider) as Decimal
				return ((IConvertible) _value):ToDecimal(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToDouble(provider as System.IFormatProvider) as real8
				return ((IConvertible) _value):ToDouble(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToInt16(provider as System.IFormatProvider) as short
				return ((IConvertible) _value):ToInt16(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToInt32(provider as System.IFormatProvider) as long
				return ((IConvertible) _value):ToInt32(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToInt64(provider as System.IFormatProvider) as int64
				return ((IConvertible) _value):ToInt64(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToSByte(provider as System.IFormatProvider) as SByte
				return ((IConvertible) _value):ToSByte(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToSingle(provider as System.IFormatProvider) as real4
				return ((IConvertible) _value):ToSingle(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToType(conversionType as System.Type, provider as System.IFormatProvider) as object
				return ((IConvertible) _value):ToType(conversionType, provider)
			
			/// <inheritdoc />
			public method IConvertible.ToUInt16(provider as System.IFormatProvider) as word
				return ((IConvertible) _value):ToUInt16(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToUInt32(provider as System.IFormatProvider) as dword
				return ((IConvertible) _value):ToUInt32(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToUInt64(provider as System.IFormatProvider) as uint64
				return ((IConvertible) _value):ToUInt64(provider)
			
			/// <inheritdoc />
			public method IConvertible.ToString(provider as System.IFormatProvider) as string
				return ((IConvertible) _value):ToString(provider)
		#endregion
		#region IFormattable
			/// <inheritdoc />
			public method ToString() as string
				return Str1(self)
			
			/// <inheritdoc />
			public method ToString(sFormat as STRING) as string
				return _value:ToString(sFormat)

			/// <inheritdoc />
			public method ToString(format as string, provider as System.IFormatProvider) as string
				return ((IFormattable) _value):ToString(format, provider)
		#endregion
		#region IComparable
			/// <inheritdoc />
			public method CompareTo(rhs as Float) as int
				return _Value:CompareTo( rhs:_Value)
			
			/// <inheritdoc />
			public method CompareTo(rhs as object) as int
				return self:CompareTo( (Float) rhs)
		#endregion

	end structure
	
end namespace