BEGIN NAMESPACE XSharp.VOEditors
    #using System
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")] ;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    INTERNAL CLASS Resources
        
        STATIC PRIVATE resourceMan AS global::System.Resources.ResourceManager
        STATIC PRIVATE resourceCulture AS global::System.Globalization.CultureInfo
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
        INTERNAL CONSTRUCTOR()
            RETURN
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        INTERNAL STATIC ACCESS ResourceManager() AS global::System.Resources.ResourceManager
            IF System.Object.ReferenceEquals(resourceMan, NULL)
                LOCAL temp := global::System.Resources.ResourceManager{"XSharp.VOEditors.Resources", typeof(Resources):Assembly} AS global::System.Resources.ResourceManager
                resourceMan := temp
            ENDIF
            RETURN resourceMan
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        INTERNAL STATIC ACCESS Culture() AS global::System.Globalization.CultureInfo
            RETURN resourceCulture
        INTERNAL STATIC ASSIGN Culture( value AS global::System.Globalization.CultureInfo )
            resourceCulture := value
        
        /// <summary>
        ///   Looks up a localized string similar to VO Windows Editor.
        /// </summary>
        INTERNAL STATIC ACCESS EditorName() AS System.String
            RETURN ResourceManager:GetString("EditorName", resourceCulture)
        
        /// <summary>
        ///   Looks up a localized string similar to Window Editor Properties.
        /// </summary>
        INTERNAL STATIC ACCESS PropertiesCaption() AS System.String
            RETURN ResourceManager:GetString("PropertiesCaption", resourceCulture)
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Editor Toolbox.
        /// </summary>
        INTERNAL STATIC ACCESS ToolboxCaption() AS System.String
            RETURN ResourceManager:GetString("ToolboxCaption", resourceCulture)
    
    END CLASS
END NAMESPACE
