// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharp.Project
{
    internal sealed partial class Vsix
    {
        public const string Id = "XSharp.ProjectSystem";
        public const string Name = "XSharp Visual Studio Integration";
        public const string Description = @"X# Visual Studio Integration.
Includes a Project System, Language Service , Debugger Support, Custom Editors etc.";
        public const string Language = "en-US";
        public const string Version = "2.15.0.0";
        public const string Author = "XSharp BV";
        public const string Tags = "XSharp, XBase, FoxPro, Visual Objects, XBase++";
    }
}
