// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharp.Project
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidProjectPackageString = "e299fb7b-d273-4678-9acf-b37b4af04a12";
        public static Guid guidProjectPackage = new Guid(guidProjectPackageString);

        public const string guidImagesString = "9f1c712d-4803-4aff-9153-28b74c34e1bf";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidWinformsMenuGroupString = "74d21312-2aee-11d1-8bfb-00a0c90f26f7";
        public static Guid guidWinformsMenuGroup = new Guid(guidWinformsMenuGroupString);

        public const string guidVOFormEditorCmdSetString = "b9ce6f12-e66c-4e77-9be6-0491dfcdc2d3";
        public static Guid guidVOFormEditorCmdSet = new Guid(guidVOFormEditorCmdSetString);

        public const string guidVOFormEditorFactoryString = "fc9f8e69-f338-4fa6-aca3-aa41e445849a";
        public static Guid guidVOFormEditorFactory = new Guid(guidVOFormEditorFactoryString);

        public const string guidVOMenuEditorCmdSetString = "33ac76f1-2719-4565-94c8-7c6542b34a3e";
        public static Guid guidVOMenuEditorCmdSet = new Guid(guidVOMenuEditorCmdSetString);

        public const string guidVOMenuEditorFactoryString = "e4ae4582-98ae-40c8-9e48-6f3be61ebf79";
        public static Guid guidVOMenuEditorFactory = new Guid(guidVOMenuEditorFactoryString);

        public const string guidVOFieldSpecEditorCmdSetString = "6b22eb29-d289-455b-94cd-9b2d6fe02103";
        public static Guid guidVOFieldSpecEditorCmdSet = new Guid(guidVOFieldSpecEditorCmdSetString);

        public const string guidVOFieldSpecEditorFactoryString = "8c5d0bae-7a69-437b-ad0e-1e1b89721ebd";
        public static Guid guidVOFieldSpecEditorFactory = new Guid(guidVOFieldSpecEditorFactoryString);

        public const string guidVODbServerEditorCmdSetString = "d816dec6-0971-4576-844f-234501b8f52d";
        public static Guid guidVODbServerEditorCmdSet = new Guid(guidVODbServerEditorCmdSetString);

        public const string guidVODbServerEditorFactoryString = "c7e4c5f6-98b8-4826-9000-6b9b94dc2d97";
        public static Guid guidVODbServerEditorFactory = new Guid(guidVODbServerEditorFactoryString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int idXporter = 0x0100;
        public const int idWebsite = 0x0101;
        public const int idHelpOffLine = 0x0102;
        public const int idVOXporter = 0x0103;
        public const int idFoxXporter = 0x0104;
        public const int idDbgGlobalsWindow = 0x0105;
        public const int idDbgMemvarsWindow = 0x0106;
        public const int idDbgWorkareaWindow = 0x0107;
        public const int idDbgSettingsWindow = 0x0108;
        public const int idConvertXSharpRuntime = 0x0109;
        public const int idAddDesignerFile = 0x010A;
        public const int ExporterMenu = 0x1030;
        public const int ExporterGroup = 0x1040;
        public const int DebuggerMenu = 0x1050;
        public const int DebuggerGroup = 0x1060;
        public const int idToolsMenuGroup = 0x1020;
        public const int idHelpMenuGroup = 0x1021;
        public const int idViewMenuGroup = 0x1022;
        public const int idViewBarGroup = 0x1023;
        public const int idProjectContextMenuGroup = 0x1024;
        public const int idFileContextMenuGroup = 0x1025;
        public const int bmpProject = 0x0001;
        public const int bmpXSharp = 0x0002;
        public const int bmpForm = 0x0003;
        public const int bmpServer = 0x0004;
        public const int bmpFieldSpec = 0x0005;
        public const int bmpMenu = 0x0006;
        public const int bmpVO = 0x0007;
        public const int bmpGrid = 0x0008;
        public const int bmpTest = 0x0009;
        public const int bmpProperties = 0x000A;
        public const int bmpReference = 0x000B;
        public const int bmpDanglingReference = 0x000C;
        public const int bmpTabOrder = 0x000D;
        public const int bmpFoxPro = 0x000E;
        public const int IDM_IF_TOOLBAR_FORMAT = 0x0601;
        public const int IDG_IF_KEYBOARD = 0x0320;
        public const int cmdidShowGrid = 0x6001;
        public const int cmdidTestDialog = 0x6002;
        public const int VOFormEditorToolbar = 0x6003;
        public const int VOFormEditorToolbarGroup = 0x6004;
        public const int cmdIdXsTabOrder = 0x6005;
    }
}