//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.1.0.0
//     Timestamp      : 13-11-2019 14:54:36
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE XSharp.XPP
    USING System
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")] ;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    PUBLIC CLASS Collations
        PRIVATE static resourceMan AS global::System.Resources.ResourceManager
        PRIVATE static resourceCulture AS global::System.Globalization.CultureInfo
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
        CONSTRUCTOR()  STRICT
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY ResourceManager AS global::System.Resources.ResourceManager
        
            GET
                if (OBJECT.ReferenceEquals(resourceMan, NULL))
                    LOCAL temp := global::System.Resources.ResourceManager{"XSharp.XPP.Collations", typeof(Collations):@@Assembly} AS global::System.Resources.ResourceManager
                    resourceMan := temp
                endif
                RETURN resourceMan
            END GET
        END PROPERTY
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY Culture AS global::System.Globalization.CultureInfo
        
            GET
                RETURN resourceCulture
            END GET
        
            SET
                resourceCulture := value
            END SET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ASCII AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ASCII", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY BRITISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("BRITISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY DANISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("DANISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY DUTCH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("DUTCH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY FINISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("FINISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY FRENCH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("FRENCH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GERMAN AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GERMAN", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GREEK437 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GREEK437", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GREEK851 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GREEK851", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ICELANDIC850 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ICELANDIC850", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ICELANDIC861 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ICELANDIC861", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ITALIAN AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ITALIAN", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORWEGIAN AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORWEGIAN", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY PORTUGUESE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("PORTUGUESE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SPANISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SPANISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SWEDISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SWEDISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY USER AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("USER", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
    
    END CLASS
END NAMESPACE
