

//  DELDBE.CH


DEFINE  DELDBE_MODE             := DBE_USER+1
DEFINE  DELDBE_RECORD_TOKEN     := DBE_USER+2
DEFINE  DELDBE_FIELD_TOKEN      := DBE_USER+3
DEFINE  DELDBE_DECIMAL_TOKEN    := DBE_USER+4
DEFINE  DELDBE_DELIMITER_TOKEN  := DBE_USER+5
DEFINE  DELDBE_LOGICAL_TOKEN    := DBE_USER+6
DEFINE  DELDBE_MAX_BUFFERSIZE   := DBE_USER+7
DEFINE  DELDBE_FIELD_TYPES      := DBE_USER+8
DEFINE  DELDBE_IGNORE_CTRL_CHAR := DBE_USER+9
DEFINE  DELDBE_SHARED_SUPPORT   := DBE_USER+10
                                 
DEFINE  DELDBO_MODE             := DBE_USER+1

DEFINE  DELDBE_SINGLEFIELD      := 1
DEFINE  DELDBE_MULTIFIELD       := 2
DEFINE  DELDBE_AUTOFIELD        := 3

//  DBFDBE.CH
DEFINE  DBFDBE_MEMOFILE_EXT    := DBE_USER+1
DEFINE  DBFDBE_MEMOBLOCKSIZE   := DBE_USER+2
DEFINE  DBFDBE_LOCKMODE        := DBE_USER+3
DEFINE  DBFDBE_LOCKOFFSET      := DBE_USER+4
DEFINE  DBFDBE_LOCKDELAY       := DBE_USER+5
DEFINE  DBFDBE_LOCKRETRY       := DBE_USER+6
DEFINE  DBFDBE_CACHESIZE       := DBE_USER+7
DEFINE  DBFDBE_LIFETIME        := DBE_USER+8
DEFINE  DBFDBE_LOCKDELAY_MIN   := DBE_USER+9
DEFINE  DBFDBE_LOCKRETRY_MIN   := DBE_USER+10
DEFINE  DBFDBE_ANSI            := DBE_USER+11

// DBO instances of DBFDBE can use:
//
DEFINE  DBFDBO_LOCKMODE        := DBE_USER+1
DEFINE  DBFDBO_LOCKOFFSET      := DBE_USER+2
DEFINE  DBFDBO_LOCKDELAY       := DBE_USER+3
DEFINE  DBFDBO_LOCKRETRY       := DBE_USER+4
DEFINE  DBFDBO_DBFHANDLE       := DBE_USER+5
DEFINE  DBFDBO_DBTHANDLE       := DBE_USER+6
DEFINE  DBFDBO_ANSI            := DBE_USER+7


DEFINE DBF_NOLOCK             := 1      

// enhanced OS/2 mode performs autolocking for
// append, read/write, delete, recall
DEFINE DBF_AUTOLOCK           := 2      



//  DBTYPES.CH
DEFINE XPP_BLOB           := 16384   

