//
// Copyright (c) XSharp B.V.  All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// See License.txt in the project root for license information.
//
ENUM XSharp.FoxCollations
 //MEMBER ARABIC
 MEMBER CZECH
 MEMBER DUTCH
 MEMBER GENERAL
 MEMBER GERMAN
 MEMBER GREEK
 //MEMBER HEBREW
 MEMBER HUNGARY
 MEMBER ICELAND
 //MEMBER JAPANESE
 //MEMBER KOREAN
 MEMBER MACHINE
 MEMBER NORDAN
 //MEMBER PINYIN
 MEMBER POLISH
 MEMBER RUSSIAN
 MEMBER SLOVAK
 MEMBER SPANISH
 //MEMBER STROKE
 MEMBER SWEFIN
 //MEMBER THAI
 MEMBER TURKISH
 MEMBER UNIQWT
END ENUM

ENUM PropertyVisibilty
   MEMBER Public    := 1
   MEMBER Protected := 2
   MEMBER Hidden    := 3
END ENUM
