// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharp.Project
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidProjectPackageString = "e299fb7b-d273-4678-9acf-b37b4af04a12";
        public static Guid guidProjectPackage = new Guid(guidProjectPackageString);

        public const string guidImagesString = "9f1c712d-4803-4aff-9153-28b74c34e1bf";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidWinformsMenuGroupString = "74d21312-2aee-11d1-8bfb-00a0c90f26f7";
        public static Guid guidWinformsMenuGroup = new Guid(guidWinformsMenuGroupString);

        public const string guidVOFormEditorCmdSetString = "b9ce6f12-e66c-4e77-9be6-0491dfcdc2d3";
        public static Guid guidVOFormEditorCmdSet = new Guid(guidVOFormEditorCmdSetString);

        public const string guidVOFormEditorFactoryString = "fc9f8e69-f338-4fa6-aca3-aa41e445849a";
        public static Guid guidVOFormEditorFactory = new Guid(guidVOFormEditorFactoryString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int idXporter = 0x0100;
        public const int idWebsite = 0x0101;
        public const int idHelpOffLine = 0x0102;
        public const int idVOXporter = 0x0103;
        public const int idFoxXporter = 0x0104;
        public const int idDbgGlobalsWindow = 0x0105;
        public const int idDbgMemvarsWindow = 0x0106;
        public const int idDbgWorkareaWindow = 0x0107;
        public const int idDbgSettingsWindow = 0x0108;
        public const int idConvertXSharpRuntime = 0x0109;
        public const int idAddDesignerFile = 0x010A;
        public const int idViewRepo = 0x010B;
        public const int idUDCTester = 0x010C;
        public const int idRebuildIntellisense = 0x010D;
        public const int idViewInDisassembler = 0x010E;
        public const int idEditProjectFile = 0x010F;
        public const int idGenerateWinForm = 0x0120;
        public const int idExporterSubMenu = 0x1030;
        public const int idExporterGroup = 0x1040;
        public const int idDebuggerSubMenu = 0x1050;
        public const int idDebuggerMenuGroup = 0x1060;
        public const int idHelpMenuGroup = 0x1021;
        public const int idViewMenuGroup = 0x1022;
        public const int idViewBarGroup = 0x1023;
        public const int idProjectContextMenuGroup = 0x1024;
        public const int idFileContextMenuGroup = 0x1025;
        public const int idDebuggerToolbar = 0x2000;
        public const int idDebuggerToolbarGroup = 0x2001;
        public const int bmpProject = 0x0001;
        public const int bmpXSharp = 0x0002;
        public const int bmpVO = 0x0007;
        public const int bmpTabOrder = 0x000D;
        public const int bmpFoxPro = 0x000E;
        public const int IDM_IF_TOOLBAR_FORMAT = 0x0601;
        public const int IDG_IF_KEYBOARD = 0x0320;
        public const int cmdidShowGrid = 0x6001;
        public const int cmdidTestDialog = 0x6002;
        public const int VOFormEditorToolbar = 0x6003;
        public const int VOFormEditorToolbarGroup = 0x6004;
        public const int cmdIdXsTabOrder = 0x6005;
    }
}