// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XSharp.Project
{
    internal sealed partial class Vsix
    {
        public const string Id = "XSharp.ProjectSystem.2022";
        public const string Name = "XSharp VS Integration for 2022 and later";
        public const string Description = @"X# Visual Studio Integration.
Includes a Project System, Language Service , Debugger Support, Custom Editors etc.";
        public const string Language = "en-US";
        public const string Version = "3.0.1.0";
        public const string Author = "XSharp BV";
        public const string Tags = "XSharp, XBase, FoxPro, Visual Objects, Xbase++, Harbour";
        public const bool IsPreview = false;
    }
}
