//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 1.1.1.0
//     Timestamp      : 5-2-2018 13:38:25
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE _
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")] ;
    [System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    INTERNAL CLASS Designer
        
        PRIVATE static resourceMan AS System.Resources.ResourceManager
        PRIVATE static resourceCulture AS System.Globalization.CultureInfo
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
        CONSTRUCTOR()
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY ResourceManager AS System.Resources.ResourceManager
        
            GET
                if (OBJECT.ReferenceEquals(resourceMan, NULL))
                    LOCAL temp := System.Resources.ResourceManager{"_.Designer", typeof(Designer):@@Assembly} AS System.Resources.ResourceManager
                    resourceMan := temp
                endif
                RETURN resourceMan
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY Culture AS System.Globalization.CultureInfo
        
            GET
                RETURN resourceCulture
            END GET
        
            SET
                resourceCulture := value
            END SET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        INTERNAL STATIC PROPERTY XSharp AS System.Drawing.Icon
        
            GET
                LOCAL obj := ResourceManager:GetObject("XSharp", resourceCulture) AS OBJECT
                RETURN ((System.Drawing.Icon)(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        INTERNAL STATIC PROPERTY XSharpSm AS System.Drawing.Icon
        
            GET
                LOCAL obj := ResourceManager:GetObject("XSharpSm", resourceCulture) AS OBJECT
                RETURN ((System.Drawing.Icon)(obj))
            END GET
        END PROPERTY
    
    END CLASS
END NAMESPACE
