//
// Copyright (c) XSharp B.V.  All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// See License.txt in the project root for license information.
//

define  __WCSLIBRARYNAME 		 := VOErrors.__WCSLIBRARYNAME
define  __WCSINTERFACEERROR 	 := VOErrors.__WCSINTERFACEERROR
define  __WCSTYPEERROR 			 := VOErrors.__WCSTYPEERROR
define  __WCSLOADLIBRARYERROR 	 := VOErrors.__WCSLOADLIBRARYERROR
define  __WCSERROR 				 := VOErrors.__WCSERROR
define  __WCSAREAINDEX 			 := VOErrors.__WCSAREAINDEX
define  __WCSAREAINDEXLAST 		 := VOErrors.__WCSAREAINDEXLAST
define  __WCSUNKNOWN 			 := VOErrors.__WCSUNKNOWN
define  __WCSWARNING 			 := VOErrors.__WCSWARNING
define  __WCSCHGDISCARD 		 := VOErrors.__WCSCHGDISCARD
define  __WCSDATAWINDOW 		 := VOErrors.__WCSDATAWINDOW
define  __WCSDWUNTITLED 		 := VOErrors.__WCSDWUNTITLED
define  __WCSUNKNOWNSTATUS 		 := VOErrors.__WCSUNKNOWNSTATUS
define  __WCSUNKNOWNSTATUSMSG 	 := VOErrors.__WCSUNKNOWNSTATUSMSG
define  __WCSERROR2 			 := VOErrors.__WCSERROR2
define  __WCSDSNOTOPEN 			 := VOErrors.__WCSDSNOTOPEN
define  __WCSCHANGINGVIEW 		 := VOErrors.__WCSCHANGINGVIEW
define  __WCSDELETEDRECORD 		 := VOErrors.__WCSDELETEDRECORD
define  __WCSIPCSERVERNOTFOUND 	 := VOErrors.__WCSIPCSERVERNOTFOUND
define  __WCSIPCTOPICNOTFOUND 	 := VOErrors.__WCSIPCTOPICNOTFOUND
define  __WCSIPCITEMNOTFOUND 	 := VOErrors.__WCSIPCITEMNOTFOUND
define  __WCSIPCOUTOFMEMORY 	 := VOErrors.__WCSIPCOUTOFMEMORY
define  __WCSDELETEFAILED 		 := VOErrors.__WCSDELETEFAILED
define  __WCSDELETEFAILEDMSG 	 := VOErrors.__WCSDELETEFAILEDMSG
define  __WCSALLFILES 			 := VOErrors.__WCSALLFILES
define  __WCSPRINTERNODISKSPACE  := VOErrors.__WCSPRINTERNODISKSPACE
define  __WCSDATADIALOG 		 := VOErrors.__WCSDATADIALOG
define  __WCSDBROWSEROBJECT 	 := VOErrors.__WCSDBROWSEROBJECT
define  __WCSCREATECTLFAILED 	 := VOErrors.__WCSCREATECTLFAILED
define  __WCSCREATEDLGFAILED 	 := VOErrors.__WCSCREATEDLGFAILED
define  __WCSHOSTVOAPP 			 := VOErrors.__WCSHOSTVOAPP
define  __WCSHOSTDATABROWSER 	 := VOErrors.__WCSHOSTDATABROWSER
define  __WCSHOSTDATAWINDOW 	 := VOErrors.__WCSHOSTDATAWINDOW
define  __WCSPICTUREYN 			 := VOErrors.__WCSPICTUREYN
define  __WCSPICTURETFYN 		 := VOErrors.__WCSPICTURETFYN
define  __WCSNOOLESUPPORT 		 := VOErrors.__WCSNOOLESUPPORT
define  __WCSTEXTBOX 			 := VOErrors.__WCSTEXTBOX
define  __WCSINFOBOX 			 := VOErrors.__WCSINFOBOX
define  __WCSCAPAINTLOADFAILED 	 := VOErrors.__WCSCAPAINTLOADFAILED
define  __WCSCNOAUTOMATION 		 := VOErrors.__WCSCNOAUTOMATION


DEFINE  __WCToolTipOffset    := VoErrors.__WCTOOLBAROFFSET
define  __WCTOOLBAROFFSET    := VoErrors.__WCToolTipOffset

