// 949. ICE when calling method with default value in VO library from Core app
// https://github.com/X-Sharp/XSharpPublic/issues/1779

FUNCTION Start() AS VOID
LOCAL o := TestDefault{} AS TestDefault
o:TestDef()

/*
error XS9999: An internal compiler error has occurred: 'Index was outside the bounds of the array.',    at LanguageService.CodeAnalysis.XSharp.Symbols.ParameterSymbolExtensions.GetVODefaultParameter(ParameterSymbol param, SyntaxNode syntax, XSharpCompilation compilation, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Compiler\src\Compiler\XSharpCodeAnalysis\Symbols\ParameterSymbolExtensions.cs:line 67
   at LanguageService.CodeAnalysis.XSharp.Binder.XsDefaultValue(ParameterSymbol parameter, SyntaxNode syntax, XSharpCompilation compilation, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Compiler\src\Compiler\XSharpCodeAnalysis\Binder\Binder_Invocation.cs:line 70
   at LanguageService.CodeAnalysis.XSharp.Binder.<BindDefaultArguments>g__bindDefaultArgument|701_1(SyntaxNode syntax, ParameterSymbol parameter, Symbol containingMember, Boolean enableCallerInfo, BindingDiagnosticBag diagnostics, ArrayBuilder`1 argumentsBuilder, Int32 argumentsCount, ImmutableArray`1 argsToParamsOpt) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 1678
   at LanguageService.CodeAnalysis.XSharp.Binder.BindDefaultArguments(SyntaxNode node, ImmutableArray`1 parameters, ArrayBuilder`1 argumentsBuilder, ArrayBuilder`1 argumentRefKindsBuilder, ArrayBuilder`1 namesBuilder, ImmutableArray`1& argsToParamsOpt, BitVector& defaultArguments, Boolean expanded, Boolean enableCallerInfo, BindingDiagnosticBag diagnostics, Symbol attributedMember) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 1593
   at LanguageService.CodeAnalysis.XSharp.Binder.BindInvocationExpressionContinued(SyntaxNode node, SyntaxNode expression, String methodName, OverloadResolutionResult`1 result, AnalyzedArguments analyzedArguments, MethodGroup methodGroup, NamedTypeSymbol delegateTypeOpt, BindingDiagnosticBag diagnostics, XSharpSyntaxNode queryClause) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 1237
   at LanguageService.CodeAnalysis.XSharp.Binder.BindMethodGroupInvocation(SyntaxNode syntax, SyntaxNode expression, String methodName, BoundMethodGroup methodGroup, AnalyzedArguments analyzedArguments, BindingDiagnosticBag diagnostics, XSharpSyntaxNode queryClause, Boolean ignoreNormalFormIfHasValidParamsParameter, Boolean& anyApplicableCandidates, Boolean disallowExpandedNonArrayParams) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 867
   at LanguageService.CodeAnalysis.XSharp.Binder.BindInvocationExpression(SyntaxNode node, SyntaxNode expression, String methodName, BoundExpression boundExpression, AnalyzedArguments analyzedArguments, BindingDiagnosticBag diagnostics, XSharpSyntaxNode queryClause, Boolean ignoreNormalFormIfHasValidParamsParameter, Boolean disallowExpandedNonArrayParams) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 346
   at LanguageService.CodeAnalysis.XSharp.Binder.BindXsInvocationExpression(InvocationExpressionSyntax node, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Compiler\src\Compiler\XSharpCodeAnalysis\Binder\Binder_Invocation.cs:line 181
   at LanguageService.CodeAnalysis.XSharp.Binder.<BindExpressionInternal>g__bindExpressionInternal|419_0(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 616
   at LanguageService.CodeAnalysis.XSharp.Binder.BindExpressionInternal(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 590
   at LanguageService.CodeAnalysis.XSharp.Binder.BindExpression(ExpressionSyntax node, BindingDiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 540
   at LanguageService.CodeAnalysis.XSharp.Binder.BindExpressionStatement(XSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 651
   at LanguageService.CodeAnalysis.XSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 644
   at LanguageService.CodeAnalysis.XSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 73
   at LanguageService.CodeAnalysis.XSharp.Binder.BindBlockParts(BlockSyntax node, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1960
   at LanguageService.CodeAnalysis.XSharp.Binder.BindBlock(BlockSyntax node, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1947
   at LanguageService.CodeAnalysis.XSharp.Binder.BindStatement(StatementSyntax node, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 64
   at LanguageService.CodeAnalysis.XSharp.Binder.BindMethodBody(XSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 4131
   at LanguageService.CodeAnalysis.XSharp.Binder.BindMethodBody(XSharpSyntaxNode syntax, BindingDiagnosticBag diagnostics) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 3732
   at LanguageService.CodeAnalysis.XSharp.Binder.BindWithLambdaBindingCountDiagnostics[TSyntax,TArg,TResult](TSyntax syntax, TArg arg, BindingDiagnosticBag diagnostics, Func`5 bind) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Binder\Binder_Lambda.cs:line 444
   at LanguageService.CodeAnalysis.XSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1811
   at LanguageService.CodeAnalysis.XSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in D:\a\XSharpPublic\XSharpPublic\src\Roslyn\Src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1018
*/

