DEFINE __CAVOSTR_SYSLIB_FIRST_STRING:=	5000
DEFINE __CAVOSTR_SYSLIB_LAST_STRING :=	5099
DEFINE __CAVOSTR_SYSLIB_ARG:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 2)
DEFINE __CAVOSTR_SYSLIB_ARG_ERROR:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 3)
DEFINE __CAVOSTR_SYSLIB_ARGNUM:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 4)
DEFINE __CAVOSTR_SYSLIB_ARGS:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 5)
DEFINE __CAVOSTR_SYSLIB_ARGTYPE:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 6)
DEFINE __CAVOSTR_SYSLIB_ARGTYPE_REQ:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 7)
DEFINE __CAVOSTR_SYSLIB_BADTRANSLATIONARRAY:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 1)
DEFINE __CAVOSTR_SYSLIB_CALLED_FROM:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 8)
DEFINE __CAVOSTR_SYSLIB_CHOICE:= (__CAVOSTR_SYSLIB_FIRST_STRING+ 9)
DEFINE __CAVOSTR_SYSLIB_CMD_LINE:= (__CAVOSTR_SYSLIB_FIRST_STRING+10)
DEFINE __CAVOSTR_SYSLIB_CONVERSION:= (__CAVOSTR_SYSLIB_FIRST_STRING+11)
DEFINE __CAVOSTR_SYSLIB_CURDIR:= (__CAVOSTR_SYSLIB_FIRST_STRING+12)
DEFINE __CAVOSTR_SYSLIB_DANGER:= (__CAVOSTR_SYSLIB_FIRST_STRING+13)
DEFINE __CAVOSTR_SYSLIB_DISK:= (__CAVOSTR_SYSLIB_FIRST_STRING+14)
DEFINE __CAVOSTR_SYSLIB_DISK_FREE:= (__CAVOSTR_SYSLIB_FIRST_STRING+15)
DEFINE __CAVOSTR_SYSLIB_DOS_ERROR:= (__CAVOSTR_SYSLIB_FIRST_STRING+16)
DEFINE __CAVOSTR_SYSLIB_ENTITY:= (__CAVOSTR_SYSLIB_FIRST_STRING+17)
DEFINE __CAVOSTR_SYSLIB_ERR_IN_ERR:= (__CAVOSTR_SYSLIB_FIRST_STRING+18)
DEFINE __CAVOSTR_SYSLIB_ERROR:= (__CAVOSTR_SYSLIB_FIRST_STRING+19)
DEFINE __CAVOSTR_SYSLIB_FILE:= (__CAVOSTR_SYSLIB_FIRST_STRING+20)
DEFINE __CAVOSTR_SYSLIB_FILE_HANDLE:= (__CAVOSTR_SYSLIB_FIRST_STRING+21)
DEFINE __CAVOSTR_SYSLIB_FUNCPTR:= (__CAVOSTR_SYSLIB_FIRST_STRING+22)
DEFINE __CAVOSTR_SYSLIB_FUNCTION:= (__CAVOSTR_SYSLIB_FIRST_STRING+23)
DEFINE __CAVOSTR_SYSLIB_HANDLE:= (__CAVOSTR_SYSLIB_FIRST_STRING+24)
DEFINE __CAVOSTR_SYSLIB_HANDLE_CUR:= (__CAVOSTR_SYSLIB_FIRST_STRING+25)
DEFINE __CAVOSTR_SYSLIB_HANDLE_END:= (__CAVOSTR_SYSLIB_FIRST_STRING+26)
DEFINE __CAVOSTR_SYSLIB_IVARS:= (__CAVOSTR_SYSLIB_FIRST_STRING+27)
DEFINE __CAVOSTR_SYSLIB_LINE:= (__CAVOSTR_SYSLIB_FIRST_STRING+28)
DEFINE __CAVOSTR_SYSLIB_MAX:= (__CAVOSTR_SYSLIB_FIRST_STRING+29)
DEFINE __CAVOSTR_SYSLIB_MODULE:= (__CAVOSTR_SYSLIB_FIRST_STRING+30)
DEFINE __CAVOSTR_SYSLIB_OBJECT:= (__CAVOSTR_SYSLIB_FIRST_STRING+31)
DEFINE __CAVOSTR_SYSLIB_OPERATION:= (__CAVOSTR_SYSLIB_FIRST_STRING+32)
DEFINE __CAVOSTR_SYSLIB_SUBCODE:= (__CAVOSTR_SYSLIB_FIRST_STRING+33)
DEFINE __CAVOSTR_SYSLIB_SUBST_TYPE:= (__CAVOSTR_SYSLIB_FIRST_STRING+34)
DEFINE __CAVOSTR_SYSLIB_SUBSYSTEM:= (__CAVOSTR_SYSLIB_FIRST_STRING+35)
DEFINE __CAVOSTR_SYSLIB_TO:= (__CAVOSTR_SYSLIB_FIRST_STRING+36)
DEFINE __CAVOSTR_SYSLIB_TRIES:= (__CAVOSTR_SYSLIB_FIRST_STRING+37)
DEFINE __CAVOSTR_SYSLIB_WARNING:= (__CAVOSTR_SYSLIB_FIRST_STRING+38)
DEFINE __CAVOSTR_SYSLIB_OLEBASE := (__CAVOSTR_SYSLIB_FIRST_STRING+39)
DEFINE __CAVOSTR_SYSLIB_CONVERSION_CALLED_FROM:=(__CAVOSTR_SYSLIB_FIRST_STRING+40)	 //419@0001 MS 11/30/94
DEFINE __CAVOSTR_SYSLIB_CONVERSION_TO:=(__CAVOSTR_SYSLIB_FIRST_STRING+41)
DEFINE __CAVOSTR_SYSLIB_CONVERSION_TO_CALLED_FROM:=(__CAVOSTR_SYSLIB_FIRST_STRING+42)  //419@0001 MS 11/30/94
DEFINE __CAVOSTR_SYSLIB_FUNCTION_CALLED_FROM:=(__CAVOSTR_SYSLIB_FIRST_STRING+43)   //419@0001 MS 11/30/94
DEFINE __CAVOSTR_SYSLIB_NOMEM := (__CAVOSTR_SYSLIB_FIRST_STRING+44)
DEFINE __CAVOSTR_SYSLIB_INCTYPES := (__CAVOSTR_SYSLIB_FIRST_STRING+45)
//  System classes:
// 			from 	__CAVOSTR_SYSCLASS_FIRST_STRING 	5100
// 			to 	__CAVOSTR_SYSCLASS_LAST_STRING  	5199
DEFINE __CAVOSTR_SYSCLASS_FIRST_STRING 	:= 5100
DEFINE __CAVOSTR_SYSCLASS_LAST_STRING	:= 5199
DEFINE __CAVOSTR_SYSCLASS_BADDESCRIPTION 	:= (__CAVOSTR_SYSCLASS_FIRST_STRING+3)
DEFINE __CAVOSTR_SYSCLASS_BADCAPTION 		:= (__CAVOSTR_SYSCLASS_FIRST_STRING+2)
DEFINE __CAVOSTR_SYSCLASS_BADERROROBJECT 	:= (__CAVOSTR_SYSCLASS_FIRST_STRING+1)
DEFINE __CAVOSTR_SYSCLASS_BADHELPCONTEXT 	:= (__CAVOSTR_SYSCLASS_FIRST_STRING+4)
DEFINE __CAVOSTR_SYSCLASS_BADNAME 			:= (__CAVOSTR_SYSCLASS_FIRST_STRING+5)
//
//  DBF Classes :
// 			from 	__CAVOSTR_DBFCLASS_FIRST_STRING 	5200
// 			to 	__CAVOSTR_DBFCLASS_LAST_STRING	5299
//
DEFINE __CAVOSTR_DBFCLASS_FIRST_STRING  :=5200
DEFINE __CAVOSTR_DBFCLASS_LAST_STRING   :=5299
DEFINE __CAVOSTR_DBFCLASS_SELECTIVEVALUE:= (__CAVOSTR_DBFCLASS_FIRST_STRING+32)
DEFINE __CAVOSTR_DBFCLASS_ALIAS                 := (__CAVOSTR_DBFCLASS_FIRST_STRING+1)
DEFINE __CAVOSTR_DBFCLASS_BADCB                 := (__CAVOSTR_DBFCLASS_FIRST_STRING+38)
DEFINE __CAVOSTR_DBFCLASS_BADCHILD          := (__CAVOSTR_DBFCLASS_FIRST_STRING+2)
DEFINE __CAVOSTR_DBFCLASS_BADCONCURRENCYASSIGN:= (__CAVOSTR_DBFCLASS_FIRST_STRING+35)
DEFINE __CAVOSTR_DBFCLASS_BADDECIMALS   := (__CAVOSTR_DBFCLASS_FIRST_STRING+39)
DEFINE __CAVOSTR_DBFCLASS_BADDRIVE          := (__CAVOSTR_DBFCLASS_FIRST_STRING+40)
DEFINE __CAVOSTR_DBFCLASS_BADEXPRESSION := (__CAVOSTR_DBFCLASS_FIRST_STRING+3)
DEFINE __CAVOSTR_DBFCLASS_BADEXTENSION  := (__CAVOSTR_DBFCLASS_FIRST_STRING+41)
DEFINE __CAVOSTR_DBFCLASS_BADFIELDMATCH := (__CAVOSTR_DBFCLASS_FIRST_STRING+4)
DEFINE __CAVOSTR_DBFCLASS_BADFIELDPOSITION:= (__CAVOSTR_DBFCLASS_FIRST_STRING+36)
DEFINE __CAVOSTR_DBFCLASS_BADFILENAME   := (__CAVOSTR_DBFCLASS_FIRST_STRING+5)
DEFINE __CAVOSTR_DBFCLASS_BADFILTERBLOCK:= (__CAVOSTR_DBFCLASS_FIRST_STRING+6)
DEFINE __CAVOSTR_DBFCLASS_BADFS                 := (__CAVOSTR_DBFCLASS_FIRST_STRING+33)
DEFINE __CAVOSTR_DBFCLASS_BADHL                 := (__CAVOSTR_DBFCLASS_FIRST_STRING+42)
DEFINE __CAVOSTR_DBFCLASS_BADHLNAME         := (__CAVOSTR_DBFCLASS_FIRST_STRING+34)
DEFINE __CAVOSTR_DBFCLASS_BADLENGTH         := (__CAVOSTR_DBFCLASS_FIRST_STRING+43)
DEFINE __CAVOSTR_DBFCLASS_BADLREQ           := (__CAVOSTR_DBFCLASS_FIRST_STRING+44)
DEFINE __CAVOSTR_DBFCLASS_BADNAME           := (__CAVOSTR_DBFCLASS_FIRST_STRING+45)
DEFINE __CAVOSTR_DBFCLASS_BADNEXT   := (__CAVOSTR_DBFCLASS_FIRST_STRING+7)
DEFINE __CAVOSTR_DBFCLASS_BADNEXT_CAPTION:= (__CAVOSTR_DBFCLASS_FIRST_STRING+8)
DEFINE __CAVOSTR_DBFCLASS_BADPATH           := (__CAVOSTR_DBFCLASS_FIRST_STRING+46)
DEFINE __CAVOSTR_DBFCLASS_BADREADONLYMODE:= (__CAVOSTR_DBFCLASS_FIRST_STRING+9)
DEFINE __CAVOSTR_DBFCLASS_BADSHAREMODE  := (__CAVOSTR_DBFCLASS_FIRST_STRING+10)
DEFINE __CAVOSTR_DBFCLASS_BADSI                 := (__CAVOSTR_DBFCLASS_FIRST_STRING+47)
DEFINE __CAVOSTR_DBFCLASS_BADSTRING         := (__CAVOSTR_DBFCLASS_FIRST_STRING+48)
DEFINE __CAVOSTR_DBFCLASS_BADTRANSLATIONARRAY:= (__CAVOSTR_DBFCLASS_FIRST_STRING+37)
DEFINE __CAVOSTR_DBFCLASS_BADTYPE           := (__CAVOSTR_DBFCLASS_FIRST_STRING+49)
DEFINE __CAVOSTR_DBFCLASS_BADTYPE2          := (__CAVOSTR_DBFCLASS_FIRST_STRING+50)
DEFINE __CAVOSTR_DBFCLASS_FIELDSPEC         := (__CAVOSTR_DBFCLASS_FIRST_STRING+11)
DEFINE __CAVOSTR_DBFCLASS_INVALIDLENGTH := (__CAVOSTR_DBFCLASS_FIRST_STRING+51)
DEFINE __CAVOSTR_DBFCLASS_INVALIDMAX        := (__CAVOSTR_DBFCLASS_FIRST_STRING+52)
DEFINE __CAVOSTR_DBFCLASS_INVALIDMIN        := (__CAVOSTR_DBFCLASS_FIRST_STRING+53)
DEFINE __CAVOSTR_DBFCLASS_INVALIDMINLENGTH:= (__CAVOSTR_DBFCLASS_FIRST_STRING+54)
DEFINE __CAVOSTR_DBFCLASS_INVALIDRANGE  := (__CAVOSTR_DBFCLASS_FIRST_STRING+55)
//DEFINE __CAVOSTR_DBFCLASS_INVALIDRANGE2:= (__CAVOSTR_DBFCLASS_FIRST_STRING+56) //not used
DEFINE __CAVOSTR_DBFCLASS_INVALIDTYPE   := (__CAVOSTR_DBFCLASS_FIRST_STRING+57)
DEFINE __CAVOSTR_DBFCLASS_INVALIDVALUE  := (__CAVOSTR_DBFCLASS_FIRST_STRING+58)
DEFINE __CAVOSTR_DBFCLASS_LOCKFAILED        := (__CAVOSTR_DBFCLASS_FIRST_STRING+12)
DEFINE __CAVOSTR_DBFCLASS_LOCKFAILED_CAPTION:= (__CAVOSTR_DBFCLASS_FIRST_STRING+13)
DEFINE __CAVOSTR_DBFCLASS_MISMATCH          := (__CAVOSTR_DBFCLASS_FIRST_STRING+14)
DEFINE __CAVOSTR_DBFCLASS_NODATAFIELDSEXIST:= (__CAVOSTR_DBFCLASS_FIRST_STRING+15)
DEFINE __CAVOSTR_DBFCLASS_NOFIELDS          := (__CAVOSTR_DBFCLASS_FIRST_STRING+16)
DEFINE __CAVOSTR_DBFCLASS_NOFILENAME        := (__CAVOSTR_DBFCLASS_FIRST_STRING+17)
DEFINE __CAVOSTR_DBFCLASS_NOGOTOP           := (__CAVOSTR_DBFCLASS_FIRST_STRING+18)
DEFINE __CAVOSTR_DBFCLASS_NOGOTOP_CAPTION:= (__CAVOSTR_DBFCLASS_FIRST_STRING+19)
DEFINE __CAVOSTR_DBFCLASS_NOSEEK                := (__CAVOSTR_DBFCLASS_FIRST_STRING+20)
DEFINE __CAVOSTR_DBFCLASS_NOSELECTIONACTIVE:= (__CAVOSTR_DBFCLASS_FIRST_STRING+21)
DEFINE __CAVOSTR_DBFCLASS_NOTABLE           := (__CAVOSTR_DBFCLASS_FIRST_STRING+22)
DEFINE __CAVOSTR_DBFCLASS_NOTABLE_CAPTION:= (__CAVOSTR_DBFCLASS_FIRST_STRING+23)
DEFINE __CAVOSTR_DBFCLASS_NOTABLE2          := (__CAVOSTR_DBFCLASS_FIRST_STRING+24)
DEFINE __CAVOSTR_DBFCLASS_RECORDCHANGED := (__CAVOSTR_DBFCLASS_FIRST_STRING+25)
DEFINE __CAVOSTR_DBFCLASS_RECORDCHANGED_CAPTION:= (__CAVOSTR_DBFCLASS_FIRST_STRING+26)
DEFINE __CAVOSTR_DBFCLASS_REQUIRED          := (__CAVOSTR_DBFCLASS_FIRST_STRING+59)
//DEFINE __CAVOSTR_DBFCLASS_SELECTIVEBOF:= (__CAVOSTR_DBFCLASS_FIRST_STRING+27) //not used
//DEFINE __CAVOSTR_DBFCLASS_SELECTIVEEMPTY:= (__CAVOSTR_DBFCLASS_FIRST_STRING+28) //not used
//DEFINE __CAVOSTR_DBFCLASS_SELECTIVEEOF:= (__CAVOSTR_DBFCLASS_FIRST_STRING+29) //not used
DEFINE __CAVOSTR_DBFCLASS_SELECTIVENOTFOUND:= (__CAVOSTR_DBFCLASS_FIRST_STRING+30)
DEFINE __CAVOSTR_DBFCLASS_SELECTIVESEEK := (__CAVOSTR_DBFCLASS_FIRST_STRING+31)
DEFINE __CAVOSTR_DBFCLASS_INTENTTOMOVE  := (__CAVOSTR_DBFCLASS_FIRST_STRING+60)
DEFINE __CAVOSTR_DBFCLASS_INTENTTOMOVE_CAPTION:= (__CAVOSTR_DBFCLASS_FIRST_STRING+61)
DEFINE __CAVOSTR_DBFCLASS_BADPARENT         := (__CAVOSTR_DBFCLASS_FIRST_STRING+62)
DEFINE __CAVOSTR_DBFCLASS_INVALIDINDEX  := (__CAVOSTR_DBFCLASS_FIRST_STRING+63)
DEFINE __CAVOSTR_DBFCLASS_KEYVALUE          := (__CAVOSTR_DBFCLASS_FIRST_STRING+64)
DEFINE __CAVOSTR_DBFCLASS_INVALIDORDER  := (__CAVOSTR_DBFCLASS_FIRST_STRING+65)
DEFINE __CAVOSTR_DBFCLASS_NOFIELDMATCH  := (__CAVOSTR_DBFCLASS_FIRST_STRING+66)
DEFINE __CAVOSTR_DBFCLASS_BADALIAS  := (__CAVOSTR_DBFCLASS_FIRST_STRING+67)
DEFINE __CAVOSTR_DBFCLASS_BADERROROBJECT := (__CAVOSTR_DBFCLASS_FIRST_STRING+68)
//
//  OLE
//	from 	OLEAUTO_ERROR_FIRST					5300
// 	from 	OLEAUTO_ERROR_LAST					5400
//
DEFINE OLEAUTO_ERROR_FIRST			:= 5300
DEFINE OLEAUTO_ERROR_LAST			:= OLEAUTO_ERROR_FIRST	+ 100
DEFINE OLEAUTO_ERROR_SUBSYSTEM 			:= OLEAUTO_ERROR_FIRST + 0
DEFINE OLEAUTO_ERROR_MSG_NO_GET_PROPERTY 		:= OLEAUTO_ERROR_FIRST + 1
DEFINE OLEAUTO_ERROR_MSG_NO_SET_PROPERTY 		:= OLEAUTO_ERROR_FIRST + 2
//3
DEFINE OLEAUTO_ERROR_MSG_UNKNOWN_ERROR 		:= OLEAUTO_ERROR_FIRST + 3
DEFINE OLEAUTO_ERROR_MSG_NO_MEMORY				:= OLEAUTO_ERROR_FIRST + 4
DEFINE OLEAUTO_ERROR_MSG_CONVERTERR				:= OLEAUTO_ERROR_FIRST + 5
DEFINE OLEAUTO_ERROR_EXP_NO_DESC					:= OLEAUTO_ERROR_FIRST + 6
DEFINE OLEAUTO_ERROR_MSG_GET_PROPERTY_FAILED	:= OLEAUTO_ERROR_FIRST + 7
DEFINE OLEAUTO_ERROR_MSG_SET_PROPERTY_FAILED	:= OLEAUTO_ERROR_FIRST + 8
DEFINE OLEAUTO_ERROR_MSG_NO_METHOD				:= OLEAUTO_ERROR_FIRST + 9
DEFINE OLEAUTO_ERROR_MSG_METHOD_FAILED			:= OLEAUTO_ERROR_FIRST + 10
DEFINE OLEAUTO_ERROR_MSG_PARAM_MISSING 		:= OLEAUTO_ERROR_FIRST + 11
DEFINE OLEAUTO_ERROR_MSG_NAMED_ARG				:= OLEAUTO_ERROR_FIRST + 12
DEFINE OLEAUTO_ERROR_MSG_INIT_FAILED			:= OLEAUTO_ERROR_FIRST + 13
DEFINE OLEAUTO_ERROR_MSG_NAMED_ARG_LAST		:= OLEAUTO_ERROR_FIRST + 14
DEFINE OLEAUTO_ERROR_MSG_NAMED_ARG_NOTSUPP 	:= OLEAUTO_ERROR_FIRST + 15
DEFINE OLEAUTO_ERROR_MSG_VARIANT_ARGS			:= OLEAUTO_ERROR_FIRST + 16
DEFINE OLEAUTO_ERROR_NO_IDISPATCH_INTERFACE 	:= OLEAUTO_ERROR_FIRST + 17
DEFINE OLEAUTO_ERROR_NO_ITYPELIB_INTERFACE 	:= OLEAUTO_ERROR_FIRST + 18
DEFINE IDS_OLERUNTIME  				:= OLEAUTO_ERROR_FIRST + 50
DEFINE IDS_NOAPPDOCFILE 			:= OLEAUTO_ERROR_FIRST + 51
DEFINE IDS_NOINSERT    				:= OLEAUTO_ERROR_FIRST + 52
DEFINE IDS_CREATEFAILED 			:= OLEAUTO_ERROR_FIRST + 53
//
//
//  GUI Classes :
//        from 	_wcsFirst			4000
//	  to	__WCSLast 			4999
//	 and
// 			from 	__CAVOSTR_GUICLASS_FIRST_STRING 	5400
// 			to 	__CAVOSTR_GUICLASS_LAST_STRING	5499
//
DEFINE __CAVOSTR_GUICLASS_FIRST_STRING 		:= 5400
DEFINE __CAVOSTR_GUICLASS_LAST_STRING 		:= 5499
DEFINE __CAVOSTR_GUICLASS_ASSERTFAILED 		:= __CAVOSTR_GUICLASS_FIRST_STRING+ 1
DEFINE __CAVOSTR_GUICLASS_ASSERTIONFAILED 	:= __CAVOSTR_GUICLASS_FIRST_STRING+ 2
DEFINE __CAVOSTR_GUICLASS_ATTEMPTREPORTS 		:= __CAVOSTR_GUICLASS_FIRST_STRING+ 3
// 4
// 5
// 6
DEFINE __CAVOSTR_GUICLASS_CAPTIONINVALID 		:= __CAVOSTR_GUICLASS_FIRST_STRING+ 7
DEFINE __CAVOSTR_GUICLASS_CHANGINGVIEW 		:= __CAVOSTR_GUICLASS_FIRST_STRING+ 8
DEFINE __CAVOSTR_GUICLASS_CHGDISCARD 			:= __CAVOSTR_GUICLASS_FIRST_STRING+ 9
DEFINE __CAVOSTR_GUICLASS_CLOSINGCHANGES 		:= __CAVOSTR_GUICLASS_FIRST_STRING+10
DEFINE __CAVOSTR_GUICLASS_CLOSINGINVCHANGES 	:= __CAVOSTR_GUICLASS_FIRST_STRING+11
// 12
DEFINE __CAVOSTR_GUICLASS_CVIDINVALID 			:= __CAVOSTR_GUICLASS_FIRST_STRING+13
DEFINE __CAVOSTR_GUICLASS_DATAWINDOW 			:= __CAVOSTR_GUICLASS_FIRST_STRING+14
DEFINE __CAVOSTR_GUICLASS_DBROWSEROBJEDT 		:= __CAVOSTR_GUICLASS_FIRST_STRING+15
DEFINE __CAVOSTR_GUICLASS_DELETEDRECORD 		:= __CAVOSTR_GUICLASS_FIRST_STRING+16
DEFINE __CAVOSTR_GUICLASS_DELETEFAILED 		:= __CAVOSTR_GUICLASS_FIRST_STRING+17
DEFINE __CAVOSTR_GUICLASS_DELETEFAILEDMSG 	:= __CAVOSTR_GUICLASS_FIRST_STRING+18
DEFINE __CAVOSTR_GUICLASS_DWUNTITLED 			:= __CAVOSTR_GUICLASS_FIRST_STRING+19
DEFINE __CAVOSTR_GUICLASS_ERROR 					:= __CAVOSTR_GUICLASS_FIRST_STRING+20
// 21
DEFINE __CAVOSTR_GUICLASS_INTERFACEERROR 		:= __CAVOSTR_GUICLASS_FIRST_STRING+22
DEFINE __CAVOSTR_GUICLASS_INVALIDARG 			:= __CAVOSTR_GUICLASS_FIRST_STRING+23
DEFINE __CAVOSTR_GUICLASS_INVALIDCAT 			:= __CAVOSTR_GUICLASS_FIRST_STRING+24
DEFINE __CAVOSTR_GUICLASS_INVALIDRPC 			:= __CAVOSTR_GUICLASS_FIRST_STRING+25
DEFINE __CAVOSTR_GUICLASS_INVALIDVIEW 			:= __CAVOSTR_GUICLASS_FIRST_STRING+26
DEFINE __CAVOSTR_GUICLASS_INVARGUMENT 			:= __CAVOSTR_GUICLASS_FIRST_STRING+27
DEFINE __CAVOSTR_GUICLASS_INVMETHODARG 		:= __CAVOSTR_GUICLASS_FIRST_STRING+28
DEFINE __CAVOSTR_GUICLASS_NOPROMPT 				:= __CAVOSTR_GUICLASS_FIRST_STRING+29
DEFINE __CAVOSTR_GUICLASS_NOTFOUND 				:= __CAVOSTR_GUICLASS_FIRST_STRING+30
DEFINE __CAVOSTR_GUICLASS_OWNERINVALID 		:= __CAVOSTR_GUICLASS_FIRST_STRING+31
DEFINE __CAVOSTR_GUICLASS_PARMINVALID 			:= __CAVOSTR_GUICLASS_FIRST_STRING+32
DEFINE __CAVOSTR_GUICLASS_SHOULDAPP 			:= __CAVOSTR_GUICLASS_FIRST_STRING+33
DEFINE __CAVOSTR_GUICLASS_TYPEERROR 			:= __CAVOSTR_GUICLASS_FIRST_STRING+34
// 35
DEFINE __CAVOSTR_GUICLASS_UNKNOWN 				:= __CAVOSTR_GUICLASS_FIRST_STRING+36
DEFINE __CAVOSTR_GUICLASS_UNKNOWNPARM 			:= __CAVOSTR_GUICLASS_FIRST_STRING+37
DEFINE __CAVOSTR_GUICLASS_UNKNOWNSTATUS 		:= __CAVOSTR_GUICLASS_FIRST_STRING+38
DEFINE __CAVOSTR_GUICLASS_UNKNOWNSTATUSMSG 	:= __CAVOSTR_GUICLASS_FIRST_STRING+39
DEFINE __CAVOSTR_GUICLASS_WARNING 				:= __CAVOSTR_GUICLASS_FIRST_STRING+40
DEFINE __CAVOSTR_GUICLASS_WARNING2 				:= __CAVOSTR_GUICLASS_FIRST_STRING+41
DEFINE __CAVOSTR_GUICLASS_WARNING3 				:= __CAVOSTR_GUICLASS_FIRST_STRING+42
DEFINE __CAVOSTR_GUICLASS_YOUHAVECLOSED		:= __CAVOSTR_GUICLASS_FIRST_STRING+43
DEFINE __CAVOSTR_GUICLASS_ERROR2 				:= __CAVOSTR_GUICLASS_FIRST_STRING+44
DEFINE __CAVOSTR_GUICLASS_INFO 					:= __CAVOSTR_GUICLASS_FIRST_STRING+45
DEFINE __CAVOSTR_GUICLASS_DSNOTOPEN 			:= __CAVOSTR_GUICLASS_FIRST_STRING+46
DEFINE __WCSFirst 					:= 4000
DEFINE __WCSLibraryName 			:= (__WCSFirst + 1)
DEFINE __WCSInterfaceError 		:= (__WCSFirst + 2)
DEFINE __WCSTypeError 				:= (__WCSFirst + 3)
DEFINE __WCSLoadLibraryError 		:= (__WCSFirst + 4)
DEFINE __WCSError 					:= (__WCSFirst + 5)
DEFINE __WCSAreaIndex 				:= (__WCSFirst + 6)
//6-30 reserved for AreaIndex table
DEFINE __WCSAreaIndexLast 			:= (__WCSFirst + 30)
DEFINE __WCSUnknown 					:= (__WCSFirst + 31)
DEFINE __WCSWarning 					:= (__WCSFirst + 32)
DEFINE __WCSChgDiscard 				:= (__WCSFirst + 33)
DEFINE __WCSDataWindow 				:= (__WCSFirst + 34)
DEFINE __WCSDWUntitled 				:= (__WCSFirst + 35)
DEFINE __WCSUnknownStatus 			:= (__WCSFirst + 36)
DEFINE __WCSUnknownStatusMSG 		:= (__WCSFirst + 37)
DEFINE __WCSError2 					:= (__WCSFirst + 38)
DEFINE __WCSDSNotOpen 				:= (__WCSFirst + 39)
//40
DEFINE __WCSChangingView 			:= (__WCSFirst + 41)
DEFINE __WCSDeletedRecord 			:= (__WCSFirst + 43)
DEFINE __WCSIpcServerNotFound 	:= (__WCSFirst + 44)
DEFINE __WCSIpcTopicNotFound 		:= (__WCSFirst + 45)
DEFINE __WCSIpcItemNotFound 		:= (__WCSFirst + 46)
DEFINE __WCSIpcOutOfMemory 		:= (__WCSFirst + 47)
DEFINE __WCSDeleteFailed 			:= (__WCSFirst + 40)
DEFINE __WCSDeleteFailedMSG 		:= (__WCSFirst + 42)
DEFINE __WCSAllFiles 				:= (__WCSFirst + 48)
DEFINE __WCSPrinterNoDiskSpace 	:= (__WCSFirst + 49)
DEFINE __WCSDataDialog 				:= (__WCSFirst + 50)
DEFINE __WCSDBrowserObject 		:= (__WCSFirst + 51)
DEFINE __WCSCreateCtlFailed 		:= (__WCSFirst + 52)
DEFINE __WCSCreateDlgFailed 		:= (__WCSFirst + 53)
DEFINE __WCSHostVOApp 				:= (__WCSFirst + 54)
DEFINE __WCSHostDataBrowser 		:= (__WCSFirst + 55)
DEFINE __WCSHostDataWindow 		:= (__WCSFirst + 56)
DEFINE __WCSPictureYN 				:= (__WCSFirst + 57)
DEFINE __WCSPictureTFYN 			:= (__WCSFirst + 58)
DEFINE __WCSNoOLESupport 			:= (__WCSFirst + 59)
DEFINE __WCSTextBox 					:= (__WCSFirst + 60)
DEFINE __WCSInfoBox 					:= (__WCSFirst + 61)
DEFINE __WCSCAPaintLoadFailed 	:= (__WCSFirst + 62)
DEFINE __WCSCNoAutomation 			:= (__WCSFirst + 63)
DEFINE __WCToolBarOffset 			:= (__WCSFirst + 64)
DEFINE __WCSLast 						:= 4999
DEFINE __WCToolTipOffset := __WCToolBarOffset + 134
//
//  Report Classes :
// 			from 	__CAVOSTR_REPORTCLASS_FIRST_STRING 	5500
// 			to 	__CAVOSTR_REPORTCLASS_LAST_STRING 	5599
//
DEFINE __CAVOSTR_REPORTCLASS_FIRST_STRING:=  5500
DEFINE __CAVOSTR_REPORTCLASS_LAST_STRING:=  5599
DEFINE __CAVOSTR_REPORTCLASS_CLOSEDREPORT:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+ 2)
DEFINE __CAVOSTR_REPORTCLASS_COMMANDERROR1:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+ 3)
DEFINE __CAVOSTR_REPORTCLASS_COMMANDERROR2:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+ 4)
DEFINE __CAVOSTR_REPORTCLASS_COMPLETEDREPORT:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+ 5)
DEFINE __CAVOSTR_REPORTCLASS_DETECTEDERRORS:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+ 6)
DEFINE __CAVOSTR_REPORTCLASS_OPENEDREPORT:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+ 7)
DEFINE __CAVOSTR_REPORTCLASS_SAVEDREPORT:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+ 8)
DEFINE __CAVOSTR_REPORTCLASS_SAVETOFILEINFO1:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+ 9)
DEFINE __CAVOSTR_REPORTCLASS_SAVETOFILEINFO2:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+10)
DEFINE __CAVOSTR_REPORTCLASS_THEREPORT:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+11)
DEFINE __CAVOSTR_REPORTCLASS_TOCLOSEFILE:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+12)
DEFINE __CAVOSTR_REPORTCLASS_SYNCHRONOUS:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+13)
DEFINE __CAVOSTR_REPORTCLASS_ASYNCHRONOUS:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+14)
DEFINE __CAVOSTR_REPORTCLASS_DDE_PENDING:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+15)
DEFINE __CAVOSTR_REPORTCLASS_REPORTS_OPEN:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+16)
DEFINE __CAVOSTR_REPORTCLASS_REPORT:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+17)
DEFINE __CAVOSTR_REPORTCLASS_ISCLOSED:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+18)
DEFINE __CAVOSTR_REPORTCLASS_ABOUTTITLE:=(__CAVOSTR_REPORTCLASS_FIRST_STRING+19)
DEFINE __CAVOSTR_REPORTCLASS_ABOUTBODY:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+20)
DEFINE __CAVOSTR_REPORTCLASS_PARAMERROR:= (__CAVOSTR_REPORTCLASS_FIRST_STRING+21)
//
//  SQL Classes :
// 			from 	__CAVOSTR_SQLCLASS_FIRST_STRING 	5600
// 			to 	__CAVOSTR_SQLCLASS_LAST_STRING	5699
//
DEFINE __CAVOSTR_SQLCLASS_FIRST_STRING := 5600
DEFINE __CAVOSTR_SQLCLASS_LAST_STRING  := 5699
DEFINE __CAVOSTR_SQLCLASS_SUBSYS    := (__CAVOSTR_SQLCLASS_FIRST_STRING+ 1)
DEFINE __CAVOSTR_SQLCLASS__ENV_ALLOC:= (__CAVOSTR_SQLCLASS_FIRST_STRING+ 2)
DEFINE __CAVOSTR_SQLCLASS__ENV_FREE := (__CAVOSTR_SQLCLASS_FIRST_STRING+ 3)
DEFINE __CAVOSTR_SQLCLASS__CON_ALLOC:= (__CAVOSTR_SQLCLASS_FIRST_STRING+ 4)
DEFINE __CAVOSTR_SQLCLASS__CON_FREE := (__CAVOSTR_SQLCLASS_FIRST_STRING+ 5)
DEFINE __CAVOSTR_SQLCLASS__CONNECTED:= (__CAVOSTR_SQLCLASS_FIRST_STRING+ 6)
DEFINE __CAVOSTR_SQLCLASS__NOT_CONN := (__CAVOSTR_SQLCLASS_FIRST_STRING+ 7)
DEFINE __CAVOSTR_SQLCLASS__CANCELLED:= (__CAVOSTR_SQLCLASS_FIRST_STRING+ 9)
DEFINE __CAVOSTR_SQLCLASS__ODBC_VO      := (__CAVOSTR_SQLCLASS_FIRST_STRING+10)
DEFINE __CAVOSTR_SQLCLASS__GENERAL_ERR  := (__CAVOSTR_SQLCLASS_FIRST_STRING+11)
DEFINE __CAVOSTR_SQLCLASS__STMT_NOT_ALLOC:= (__CAVOSTR_SQLCLASS_FIRST_STRING+12)
DEFINE __CAVOSTR_SQLCLASS__STMT_PREP    := (__CAVOSTR_SQLCLASS_FIRST_STRING+13)
DEFINE __CAVOSTR_SQLCLASS__NO_STMT      := (__CAVOSTR_SQLCLASS_FIRST_STRING+14)
DEFINE __CAVOSTR_SQLCLASS__STMT_ALLOC   := (__CAVOSTR_SQLCLASS_FIRST_STRING+15)
DEFINE __CAVOSTR_SQLCLASS__FUNCSEQ_ERR  := (__CAVOSTR_SQLCLASS_FIRST_STRING+16)
DEFINE __CAVOSTR_SQLCLASS__PARM_TYPE    := (__CAVOSTR_SQLCLASS_FIRST_STRING+17)
DEFINE __CAVOSTR_SQLCLASS__MEM_ALLOC    := (__CAVOSTR_SQLCLASS_FIRST_STRING+18)
DEFINE __CAVOSTR_SQLCLASS__BADCOL       := (__CAVOSTR_SQLCLASS_FIRST_STRING+19)
DEFINE __CAVOSTR_SQLCLASS__BADFLD       := (__CAVOSTR_SQLCLASS_FIRST_STRING+20)
DEFINE __CAVOSTR_SQLCLASS__BADPAR       := (__CAVOSTR_SQLCLASS_FIRST_STRING+21)
DEFINE __CAVOSTR_SQLCLASS__BADRECNO     := (__CAVOSTR_SQLCLASS_FIRST_STRING+22)
DEFINE __CAVOSTR_SQLCLASS__BACKWARDS    := (__CAVOSTR_SQLCLASS_FIRST_STRING+23)
DEFINE __CAVOSTR_SQLCLASS__BOF          := (__CAVOSTR_SQLCLASS_FIRST_STRING+24)
DEFINE __CAVOSTR_SQLCLASS__EOF          := (__CAVOSTR_SQLCLASS_FIRST_STRING+25)
DEFINE __CAVOSTR_SQLCLASS__NOFLDS       := (__CAVOSTR_SQLCLASS_FIRST_STRING+26)
DEFINE __CAVOSTR_SQLCLASS__NO_KEY       := (__CAVOSTR_SQLCLASS_FIRST_STRING+27)
DEFINE __CAVOSTR_SQLCLASS__NO_ROW       := (__CAVOSTR_SQLCLASS_FIRST_STRING+28)
DEFINE __CAVOSTR_SQLCLASS__NO_INS       := (__CAVOSTR_SQLCLASS_FIRST_STRING+29)
DEFINE __CAVOSTR_SQLCLASS__INV_OP       := (__CAVOSTR_SQLCLASS_FIRST_STRING+30)
DEFINE __CAVOSTR_SQLCLASS__NO_CSR       := (__CAVOSTR_SQLCLASS_FIRST_STRING+31)
DEFINE __CAVOSTR_SQLCLASS__BADVALID     := (__CAVOSTR_SQLCLASS_FIRST_STRING+32)
DEFINE __CAVOSTR_SQLCLASS__EMPTY        := (__CAVOSTR_SQLCLASS_FIRST_STRING+33)
DEFINE __CAVOSTR_SQLCLASS__UPDATE_COL   := (__CAVOSTR_SQLCLASS_FIRST_STRING+34)
DEFINE __CAVOSTR_SQLCLASS__NODATAFIELDSEXIST := (__CAVOSTR_SQLCLASS_FIRST_STRING+35)
DEFINE __CAVOSTR_SQLCLASS__BADFIELDPOSITION := (__CAVOSTR_SQLCLASS_FIRST_STRING+36)
DEFINE __CAVOSTR_SQLCLASS__INVALIDCOLATT := (__CAVOSTR_SQLCLASS_FIRST_STRING+37)
// Terminal Lite
//				from	TERMINAL_FIRST	5700
//				to		TERMINAL_LAST	5799
DEFINE TERMINAL_FIRST		:= 5700
DEFINE TERMINAL_LAST			:= 5799
DEFINE TMSG_YN 				:= TERMINAL_FIRST + 1
DEFINE TMSG_ALERTDEFAULT 	:= TERMINAL_FIRST + 2
DEFINE TMSG_NOTERMWIN 		:= TERMINAL_FIRST + 3
DEFINE TMSG_FNTCHNG 			:= TERMINAL_FIRST + 4
DEFINE TMSG_SHADE 			:= TERMINAL_FIRST + 5
DEFINE TMSG_MARK 				:= TERMINAL_FIRST + 6
DEFINE TMSG_SCREEN2FILE 	:= TERMINAL_FIRST + 7
DEFINE TMSG_MEMRECOUR 		:= TERMINAL_FIRST + 8
DEFINE TMSG_DYNCHECKERR 	:= TERMINAL_FIRST + 9
DEFINE TMSG_HNDLINE 			:= TERMINAL_FIRST + 10
DEFINE TMSG_HNDENTITY 		:= TERMINAL_FIRST + 11
DEFINE TMSG_HNDCONTENTS 	:= TERMINAL_FIRST + 12
DEFINE TMSG_HNDVAR 			:= TERMINAL_FIRST + 13
DEFINE TMSG_NOCHANGE 		:= TERMINAL_FIRST + 14
DEFINE TMSG_FONTCHGERR 		:= TERMINAL_FIRST + 15
DEFINE TMSG_MUSTSELECT 		:= TERMINAL_FIRST + 16
DEFINE TMSG_NODEVSEL 		:= TERMINAL_FIRST + 17
DEFINE TMSG_NOLINK 			:= TERMINAL_FIRST + 18
DEFINE TMSG_PRNSETUP 		:= TERMINAL_FIRST + 19
DEFINE TMSG_PAGENO 			:= TERMINAL_FIRST + 20
DEFINE TMSG_PRESSANYKEY 	:= TERMINAL_FIRST + 21
DEFINE TMSG_APPENDSCREEN 	:= TERMINAL_FIRST + 22
DEFINE TMSG_APPENDALL 		:= TERMINAL_FIRST + 23
DEFINE TMSG_LOCKEDFONT 		:= TERMINAL_FIRST + 24
DEFINE TMSG_NOACCELERATORS := TERMINAL_FIRST + 25
DEFINE TMSG_ONTOP				:= TERMINAL_FIRST + 26

//RvdH 040322 Added version defines
DEFINE VOVER_BUILDNUMBER      := __VERSION__
DEFINE VOVER_COMPANY          := '"Computer Associates International, Inc."'
DEFINE VOVER_WEBSITE          := '"http://www.cavo.com" '
DEFINE VOVER_DEVWEBSITE       := '"http://www.grafxsoft.com"'
DEFINE VOVER_DEVELOPMENT      := '"GrafX Software Development Tools, Inc."'
DEFINE VOVER_PROD_NAME        := '"Visual Objects"'
DEFINE VOVER_FILE_VERSION_TXT := '"2.8.1.'+VOVER_BUILDNUMBER+'"'
DEFINE VOVER_PROD_VERSION_TXT := '"2.8 SP1 (build '+VOVER_BUILDNUMBER+')"'
DEFINE VOVER_COPYRIGHT        := '"Copyright \251 Computer Associates International 1992-2007"'
DEFINE VOVER_FILE_VERSION     := "2,8,1," + __version__
DEFINE VOVER_PROD_VERSION     := "2,8,1," + __version__
