//
// Copyright (c) XSharp B.V.  All Rights Reserved.  
// Licensed under the Apache License, Version 2.0.  
// See License.txt in the project root for license information.
//

BEGIN NAMESPACE XSharp.RDD
ENUM ERDD
	MEMBER MIN                  := 1100
	MEMBER OPEN_FILE			
	MEMBER OPEN_MEMO			
	MEMBER OPEN_ORDER 			
	MEMBER CREATE_FILE			
	MEMBER CREATE_MEMO			
	MEMBER CREATE_ORDER			:= 1106
	MEMBER READ					:= 1110
	MEMBER WRITE				
	MEMBER CORRUPT				
	MEMBER CORRUPT_HEADER 		

	MEMBER RDDVERSION 			:= 1115

	MEMBER DATATYPE				:= 1120
	MEMBER DATAWIDTH			
	MEMBER UNLOCKED				
	MEMBER SHARED 				
	MEMBER APPENDLOCK 			
	MEMBER READONLY				
	MEMBER NULLKEY				
	MEMBER NTXLIMIT				
	MEMBER TAGLIMIT				

	MEMBER INIT_LOCK		    := 1130
	MEMBER READ_LOCK			
	MEMBER WRITE_LOCK 			
	MEMBER READ_UNLOCK			
	MEMBER WRITE_UNLOCK			
	MEMBER READ_LOCK_TIMEOUT	
	MEMBER WRITE_LOCK_TIMEOUT 	
	MEMBER READ_UNLOCK_TIMEOUT	
	MEMBER WRITE_UNLOCK_TIMEOUT	

	MEMBER CLOSE_FILE 			:= 1140
	MEMBER CLOSE_MEMO 			
	MEMBER CLOSE_ORDER			

	MEMBER INVALID_ORDER		:= 1150
	MEMBER RECNO_MISSING		
	MEMBER NOORDER				
	MEMBER UNSUPPORTED			



	//
	//	Following errors are known as Clipper's internal errors
	//

	MEMBER WRITE_NTX				:= 1200
	MEMBER KEY_NOT_FOUND			
	MEMBER KEY_EVAL				
	MEMBER VAR_TYPE				

	MEMBER READ_BUFFER			    := 1206
	MEMBER SORT_INIT				
	MEMBER SORT_ADVANCE			    
	MEMBER SORT_SORT				
	MEMBER SORT_COMPLETE			
	MEMBER SORT_END				
	MEMBER READ_TEMPFILE			
	MEMBER STREAM_NUM 			    
	MEMBER CREATE_TEMPFILE		    

	MEMBER DISKIO_WRITE				:= 1216
	MEMBER WRONG_DRIVERTYPE		
	MEMBER OUTOFMEMORY			
	MEMBER INVALIDARG 			
	MEMBER USER                     := 2000
  
END ENUM


END NAMESPACE

#region Defines
DEFINE ERDD_OPEN_FILE		    := ERDD.OPEN_FILE		    
DEFINE ERDD_OPEN_MEMO		    := ERDD.OPEN_MEMO		    
DEFINE ERDD_OPEN_ORDER 		    := ERDD.OPEN_ORDER 		    
DEFINE ERDD_CREATE_FILE		    := ERDD.CREATE_FILE		    
DEFINE ERDD_CREATE_MEMO		    := ERDD.CREATE_MEMO		    
DEFINE ERDD_CREATE_ORDER	    := ERDD.CREATE_ORDER	    
DEFINE ERDD_READ			    := ERDD.READ			    
DEFINE ERDD_WRITE			    := ERDD.WRITE			    
DEFINE ERDD_CORRUPT			    := ERDD.CORRUPT			    
DEFINE ERDD_CORRUPT_HEADER 	    := ERDD.CORRUPT_HEADER 	    
DEFINE ERDD_RDDVERSION 		    := ERDD.RDDVERSION 		    
DEFINE ERDD_DATATYPE		    := ERDD.DATATYPE		    
DEFINE ERDD_DATAWIDTH		    := ERDD.DATAWIDTH		    
DEFINE ERDD_UNLOCKED		    := ERDD.UNLOCKED		    
DEFINE ERDD_SHARED 			    := ERDD.SHARED 			    
DEFINE ERDD_APPENDLOCK 		    := ERDD.APPENDLOCK 		    
DEFINE ERDD_READONLY		    := ERDD.READONLY		    
DEFINE ERDD_NULLKEY			    := ERDD.NULLKEY			    
DEFINE ERDD_NTXLIMIT		    := ERDD.NTXLIMIT		    
DEFINE ERDD_TAGLIMIT		    := ERDD.TAGLIMIT		    
DEFINE ERDD_INIT_LOCK		    := ERDD.INIT_LOCK		    
DEFINE ERDD_READ_LOCK		    := ERDD.READ_LOCK		    
DEFINE ERDD_WRITE_LOCK 		    := ERDD.WRITE_LOCK 		    
DEFINE ERDD_READ_UNLOCK		    := ERDD.READ_UNLOCK		    
DEFINE ERDD_WRITE_UNLOCK	    := ERDD.WRITE_UNLOCK	    
DEFINE ERDD_READ_LOCK_TIMEOUT   := ERDD.READ_LOCK_TIMEOUT    
DEFINE ERDD_WRITE_LOCK_TIMEOUT  := ERDD.WRITE_LOCK_TIMEOUT    
DEFINE ERDD_READ_UNLOCK_TIMEOUT := ERDD.READ_UNLOCK_TIMEOUT    
DEFINE ERDD_WRITE_UNLOCK_TIMEOUT:= ERDD.WRITE_UNLOCK_TIMEOUT    
DEFINE ERDD_CLOSE_FILE 		    := ERDD.CLOSE_FILE 		    
DEFINE ERDD_CLOSE_MEMO 		    := ERDD.CLOSE_MEMO 		    
DEFINE ERDD_CLOSE_ORDER		    := ERDD.CLOSE_ORDER		    
DEFINE ERDD_INVALID_ORDER	    := ERDD.INVALID_ORDER	    
DEFINE ERDD_RECNO_MISSING	    := ERDD.RECNO_MISSING	    
DEFINE ERDD_NOORDER			    := ERDD.NOORDER			    
DEFINE ERDD_UNSUPPORTED		    := ERDD.UNSUPPORTED		    
DEFINE ERDD_WRITE_NTX		    := ERDD.WRITE_NTX		    
DEFINE ERDD_KEY_NOT_FOUND	    := ERDD.KEY_NOT_FOUND	    
DEFINE ERDD_KEY_EVAL		    := ERDD.KEY_EVAL		    
DEFINE ERDD_VAR_TYPE		    := ERDD.VAR_TYPE		    
DEFINE ERDD_READ_BUFFER		    := ERDD.READ_BUFFER		    
DEFINE ERDD_SORT_INIT		    := ERDD.SORT_INIT		    
DEFINE ERDD_SORT_ADVANCE	    := ERDD.SORT_ADVANCE	    
DEFINE ERDD_SORT_SORT		    := ERDD.SORT_SORT		    
DEFINE ERDD_SORT_COMPLETE	    := ERDD.SORT_COMPLETE	    
DEFINE ERDD_SORT_END		    := ERDD.SORT_END		    
DEFINE ERDD_READ_TEMPFILE	    := ERDD.READ_TEMPFILE	    
DEFINE ERDD_STREAM_NUM 		    := ERDD.STREAM_NUM 		    
DEFINE ERDD_CREATE_TEMPFILE	    := ERDD.CREATE_TEMPFILE	    
DEFINE DISKIO_WRITE			    := ERDD.DISKIO_WRITE			    
DEFINE ERDD_WRONG_DRIVERTYPE    := ERDD.WRONG_DRIVERTYPE    
DEFINE ERDD_OUTOFMEMORY		    := ERDD.OUTOFMEMORY		    
DEFINE ERDD_INVALIDARG 		    := ERDD.INVALIDARG 		    
DEFINE ERDD_USER				:= ERDD.USER					
#endregion
