//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.0.2.0
//     Timestamp      : 26-6-2019 09:18:14
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE XSharp.RDD
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")] ;
    [System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    INTERNAL CLASS VfpCollations
        
        PRIVATE STATIC resourceMan AS System.Resources.ResourceManager
        PRIVATE STATIC resourceCulture AS System.Globalization.CultureInfo
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
        CONSTRUCTOR()  STRICT
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY ResourceManager AS System.Resources.ResourceManager
        
            GET
                IF (OBJECT.ReferenceEquals(resourceMan, NULL))
                    LOCAL temp := System.Resources.ResourceManager{"XSharp.RDD.VfpCollations", typeof(VfpCollations):Assembly} AS System.Resources.ResourceManager
                    resourceMan := temp
                ENDIF
                RETURN resourceMan
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY Culture AS System.Globalization.CultureInfo
        
            GET
                RETURN resourceCulture
            END GET
        
            SET
                resourceCulture := VALUE
            END SET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CZECH_1250_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CZECH_1250_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CZECH_1250_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CZECH_1250_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CZECH_852_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CZECH_852_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CZECH_852_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CZECH_852_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CZECH_895_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CZECH_895_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CZECH_895_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CZECH_895_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY DUTCH_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("DUTCH_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY DUTCH_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("DUTCH_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY DUTCH_850_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("DUTCH_850_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_1250_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_1250_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_1254_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_1254_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_620_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_620_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_850_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_850_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_852_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_852_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_857_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_857_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_861_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_861_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_865_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_865_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERAL_895_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERAL_895_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GERMAN_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GERMAN_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GERMAN_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GERMAN_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GREEK_1253_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GREEK_1253_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GREEK_737_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GREEK_737_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY HUNGARY_1250_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("HUNGARY_1250_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY HUNGARY_1250_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("HUNGARY_1250_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY HUNGARY_852_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("HUNGARY_852_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY HUNGARY_852_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("HUNGARY_852_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ICELAND_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ICELAND_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ICELAND_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ICELAND_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ICELAND_850_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ICELAND_850_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ICELAND_861_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ICELAND_861_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_1250_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_1250_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_1251_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_1251_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_1253_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_1253_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_1254_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_1254_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_620_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_620_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_737_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_737_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_850_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_850_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_852_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_852_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_857_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_857_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_861_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_861_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_865_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_865_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_866_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_866_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY MACHINE_895_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("MACHINE_895_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORDAN_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORDAN_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORDAN_1252_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORDAN_1252_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORDAN_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORDAN_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORDAN_437_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORDAN_437_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORDAN_850_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORDAN_850_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORDAN_850_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORDAN_850_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORDAN_865_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORDAN_865_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORDAN_865_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORDAN_865_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY POLISH_1250_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("POLISH_1250_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY POLISH_620_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("POLISH_620_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY POLISH_852_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("POLISH_852_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY RUSSIAN_1251_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("RUSSIAN_1251_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY RUSSIAN_866_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("RUSSIAN_866_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SLOVAK_1250_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SLOVAK_1250_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SLOVAK_1250_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SLOVAK_1250_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SLOVAK_852_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SLOVAK_852_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SLOVAK_852_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SLOVAK_852_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SLOVAK_895_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SLOVAK_895_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SLOVAK_895_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SLOVAK_895_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SPANISH_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SPANISH_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SPANISH_1252_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SPANISH_1252_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SPANISH_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SPANISH_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SPANISH_437_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SPANISH_437_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SPANISH_850_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SPANISH_850_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SPANISH_850_COMBI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SPANISH_850_COMBI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SWEFIN_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SWEFIN_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SWEFIN_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SWEFIN_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SWEFIN_850_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SWEFIN_850_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SWEFIN_865_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SWEFIN_865_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY TURKISH_1254_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("TURKISH_1254_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY TURKISH_857_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("TURKISH_857_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY UNIQWT_1252_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("UNIQWT_1252_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY UNIQWT_437_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("UNIQWT_437_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY UNIQWT_850_COLLATE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("UNIQWT_850_COLLATE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
    
    END CLASS
END NAMESPACE
