//
// Copyright (c) XSharp B.V.  All Rights Reserved.
// Licensed under the Apache License, Version 2.0.
// See License.txt in the project root for license information.
//

USING System
USING System.Collections.Generic
USING System.Text

DEFINE DBI_CONNECTIONSTRING			:= DBI_USER + 1
DEFINE DBI_CONNECTIONOBJECT 		:= DBI_USER + 2
DEFINE DBI_CLEARRECORDSET 			:= DBI_USER + 3
DEFINE DBI_RECORDSET      			:= DBI_USER + 4
DEFINE DBI_SQLSTRING 				:= DBI_USER + 5
DEFINE DBI_SAVECONNECTION			:= DBI_USER + 6
DEFINE DBI_SAVETABLEDEF				:= DBI_USER + 7
DEFINE DBI_SERVERFILTER				:= DBI_USER + 8
DEFINE DBI_BEGINTRANS      			:= DBI_USER + 9
DEFINE DBI_ROLLBACKTRANS       		:= DBI_USER + 10
DEFINE DBI_COMMITTRANS       		:= DBI_USER + 11
DEFINE DBI_HASTRANS      			:= DBI_USER + 12
DEFINE DBI_SAVEPROVIDER				:= DBI_USER + 13
DEFINE DBI_DROPTABLE				:= DBI_USER + 14
DEFINE DBI_LONGFIELDNAMES			:= DBI_USER + 15
DEFINE DBI_TABLELIST				:= DBI_USER + 16

DEFINE DBS_ADONET_Name			:= DBS_USER+1
DEFINE DBS_ADONET_Type			:= DBS_USER+2
DEFINE DBS_ADONET_Size 			:= DBS_USER+3
DEFINE DBS_ADONET_Precision 	:= DBS_USER+4
DEFINE DBS_ADONET_Scale			:= DBS_USER+5
DEFINE DBS_ADONET_Field			:= DBS_USER+6


