VOSTRUCT _WINWIN32_FIND_DATA
	MEMBER dwFileAttributes AS DWORD
	MEMBER ftCreationTime IS _WINFILETIME
	MEMBER ftLastAccessTime IS _WINFILETIME
	MEMBER ftLastWriteTime IS _WINFILETIME
	MEMBER nFileSizeHigh AS DWORD
	MEMBER nFileSizeLow AS DWORD
	MEMBER dwReserved0 AS DWORD
	MEMBER dwReserved1 AS DWORD
	MEMBER DIM cFileName[ 255 ] AS BYTE
	MEMBER DIM cAlternateFileName[ 14 ] AS BYTE

VOSTRUCT _WINFILETIME
	MEMBER dwLowDateTime AS  DWORD
	MEMBER dwHighDateTime AS DWORD

