/*
   Copyright 2016-2017 XSharp B.V.

Licensed under the X# compiler source code License, Version 1.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.xsharp.info/licenses

Unless required by applicable law or agreed to in writing, software
Distributed under the License is distributed on an "as is" basis,
without warranties or conditions of any kind, either express or implied.
See the License for the specific language governing permissions and   
limitations under the License.
*/
using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Roslyn.Utilities;
using Microsoft.Win32;
using System.Runtime.InteropServices;
using System.Diagnostics;
using Microsoft.CodeAnalysis.CommandLine;

namespace Microsoft.CodeAnalysis.CSharp.CommandLine
{
    internal sealed class Xsc : CSharpCompiler
    {
        internal Xsc(string responseFile, BuildPaths buildPaths, string[] args, IAnalyzerAssemblyLoader analyzerLoader)
            : base(CSharpCommandLineParser.Default, responseFile, args, buildPaths, Environment.GetEnvironmentVariable("LIB"), analyzerLoader)
        {
        }

        // Original csc Run() function
        /*
        internal static int Run(string[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
        {
            FatalError.Handler = FailFast.OnFatalException;

            var responseFile = Path.Combine(buildPaths.ClientDirectory, CSharpCompiler.ResponseFileName);
            var compiler = new Xsc(responseFile, buildPaths, args, analyzerLoader);
            return ConsoleUtil.RunWithUtf8Output(compiler.Arguments.Utf8Output, textWriter, tw => compiler.Run(tw));
        }
        */


        internal static int Run(string[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
        {
            FatalError.Handler = FailFast.OnFatalException;

            var includeDir = Environment.GetEnvironmentVariable("INCLUDE");
            string XSharpIncludeDir = String.Empty;
            string VulcanIncludeDir = string.Empty;
            try {
                string key;
                if (Environment.Is64BitProcess)
                    key = @"HKEY_LOCAL_MACHINE\" + global::XSharp.Constants.RegistryKey64;
                else
                    key = @"HKEY_LOCAL_MACHINE\" + global::XSharp.Constants.RegistryKey;
                XSharpIncludeDir = (string)Registry.GetValue(key, global::XSharp.Constants.RegistryValue, "");
            }
            catch (Exception) { }
            try {
                string key;
                if (Environment.Is64BitProcess)
                    key = @"HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Grafx\Vulcan.NET";
                else
                    key = @"HKEY_LOCAL_MACHINE\SOFTWARE\Grafx\Vulcan.NET";
                VulcanIncludeDir = (string)Registry.GetValue(key, "InstallPath", "");
            } catch (Exception) { }
            if (!String.IsNullOrEmpty(XSharpIncludeDir))
            {
                if (!XSharpIncludeDir.EndsWith("\\"))
                    XSharpIncludeDir += @"\";
                XSharpIncludeDir += @"Include\";
            }

            if (!String.IsNullOrEmpty(VulcanIncludeDir)) {
                if (!VulcanIncludeDir.EndsWith("\\"))
                    VulcanIncludeDir += @"\";
                VulcanIncludeDir += @"Include\";
            }
            includeDir = includeDir ?? "" + XSharpIncludeDir;
            if (!string.IsNullOrEmpty(VulcanIncludeDir))
                includeDir += ";" + VulcanIncludeDir;
            XSharpSpecificCompilationOptions.SetDefaultIncludeDir(includeDir);
            XSharpSpecificCompilationOptions.SetWinDir(Environment.GetFolderPath(Environment.SpecialFolder.Windows));
            XSharpSpecificCompilationOptions.SetSysDir(Environment.GetFolderPath(Environment.SpecialFolder.System));

            var responseFile = Path.Combine(buildPaths.ClientDirectory, CSharpCompiler.ResponseFileName);
            var compiler = new Xsc(responseFile, buildPaths, args, analyzerLoader);
            var result = ConsoleUtil.RunWithUtf8Output(compiler.Arguments.Utf8Output, textWriter, tw => compiler.Run(tw));

            if (result == 0 && !String.IsNullOrEmpty(compiler.Arguments.Win32ResourceFile))
            {
                // Added an extra step to fix the resources generated by Roslyn
                var file = ((CSharpCompiler)compiler).Arguments.OutputFileName;
                var dir = ((CSharpCompiler)compiler).Arguments.OutputDirectory;
                FixResources(dir + "\\" + file);
            }
            return result;
        }

        internal static void FixResources(string fileName)
        {
            var hRes = BeginUpdateResource(fileName, false);
            if (hRes != IntPtr.Zero)
            {
                var res = EndUpdateResource(hRes, false);
            }

        }

        [DllImport("kernel32.dll", SetLastError = true)]
        static extern IntPtr BeginUpdateResource(string pFileName, [MarshalAs(UnmanagedType.Bool)]bool bDeleteExistingResources);
        [DllImport("kernel32.dll", SetLastError = true)]
        static extern bool EndUpdateResource(IntPtr hUpdate, bool fDiscard);

    }
}
