#region defines
DEFINE DBCCON               := TRUE
DEFINE DBCCOFF              := FALSE
DEFINE DBCCREADONLY         := FALSE
DEFINE DBCCUPDATE           := TRUE
DEFINE DBEXCLUSIVE          := FALSE
DEFINE DBREADONLY           := TRUE
DEFINE DBREADWRITE          := FALSE
DEFINE DBSCOPEALL           := FALSE
DEFINE DBSCOPEREST          := TRUE
DEFINE DBSELECTIONEMPTY     := -2
DEFINE DBSELECTIONBOF       := -1
DEFINE DBSELECTIONEOF       := 1
DEFINE DBSELECTIONFOUND     := 2
DEFINE DBSELECTIONNULL      := 0
DEFINE DBSHARED             := TRUE
DEFINE ORD_KEYCOUNT         := 2
DEFINE ORD_KEYDEC           := 4
DEFINE ORD_KEYEXPR          := 3
DEFINE ORD_KEYINFO          := 8
DEFINE ORD_KEYSIZE          := 3
DEFINE ORD_KEYTYPE          := 1
DEFINE BUFFER_VALUE         := 1
DEFINE BUFFER_BLOB_VALUE    := 2
DEFINE BUFFER_IS_CHANGED    := 2
DEFINE BUFFER_IS_BLOB       := 2
#endregion
