VOSTRUCT _winDATE_STRUCT
	MEMBER year AS SHORTINT
	MEMBER month AS WORD
	MEMBER day AS WORD

VOSTRUCT _winTIME_STRUCT
	MEMBER  hour AS WORD
	MEMBER minute AS WORD
	MEMBER second AS WORD

VOSTRUCT _WINTIMESTAMP_STRUCT

	MEMBER year AS SHORTINT
	MEMBER month AS WORD
	MEMBER day AS WORD
	MEMBER hour AS WORD
	MEMBER minute AS WORD
	MEMBER second AS WORD
	MEMBER fraction AS DWORD
_DLL FUNC SQLColumns(hstmt AS PTR, szTableQualifier AS PSZ, cbTableQualifier AS SHORT,;
	szTableOwner AS PSZ, cbTableOwner AS SHORT,szTableName AS PSZ,;
	cbTableName AS SHORT, szColumnName AS PSZ, cbColumnName AS SHORT);
	AS SHORTINT PASCAL:odbc32.SQLColumns


_DLL FUNC SQLSetScrollOptions(hstmt AS PTR, fConcurrency AS WORD, crowKeyset AS LONG,;
	crowRowset AS WORD) AS SHORTINT PASCAL:odbc32.SQLSetScrollOptions


_DLL FUNC SQLDriverConnect(hdbc AS PTR, hwnd AS PTR,szConnStrIn AS PSZ,cbConnStrIn AS SHORT,;
	szConnStrOut AS PSZ, cbConnStrOutMax AS SHORT,pcbConnStrOut AS SHORT PTR,;
	fDriverCompletion AS WORD) AS SHORTINT PASCAL:odbc32.SQLDriverConnect

_DLL FUNC SQLGetConnectOption(hdbc AS PTR, fOption AS WORD, pvParam AS PTR) AS SHORTINT PASCAL:odbc32.SQLGetConnectOption


_DLL FUNC SQLGetData( hstmt AS PTR,  icol AS WORD, fCType AS SHORT, rgbValue AS PTR,;
	cbValueMax AS LONG, pcbValue AS LONG PTR) AS SHORTINT PASCAL:odbc32.SQLGetData


_DLL FUNC SQLGetFunctions( hdbc AS PTR,  fFunction AS WORD,pfExists AS WORD PTR) AS SHORTINT PASCAL:odbc32.SQLGetFunctions


_DLL FUNC  SQLGetInfo( hdbc AS PTR,  fInfoType AS WORD, rgbInfoValue AS PTR, cbInfoValueMax AS SHORT,;
	pcbInfoValue AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLGetInfo


_DLL FUNC  SQLGetStmtOption( hstmt AS PTR,  fOption AS WORD,    pvParam AS PTR) AS SHORTINT PASCAL:odbc32.SQLGetStmtOption


_DLL FUNC  SQLGetTypeInfo( hstmt AS PTR,    fSqlType AS SHORT ) AS SHORTINT PASCAL:odbc32.SQLGetTypeInfo


_DLL FUNC SQLParamData( hstmt AS PTR, prgbValue AS PTR) AS SHORTINT PASCAL:odbc32.SQLParamData


_DLL FUNC  SQLPutData(hstmt AS PTR,  rgbValue AS PTR,  cbValue AS LONG) AS SHORTINT PASCAL:odbc32.SQLPutData


_DLL FUNC  SQLSetConnectOption( hdbc AS PTR, fOption AS WORD, vParam AS DWORD) AS SHORTINT PASCAL:odbc32.SQLSetConnectOption


_DLL FUNC SQLSetStmtOption(hstmt AS PTR,    fOption AS WORD,    vParam AS DWORD) AS SHORTINT PASCAL:odbc32.SQLSetStmtOption



_DLL FUNC SQLSpecialColumns(hstmt AS PTR, fColType AS WORD, szTableQualifier AS PSZ,;
	cbTableQualifier AS SHORT, szTableOwner AS PSZ,;
	cbTableOwner AS SHORT, szTableName AS PSZ, cbTableName AS SHORT,;
	fScope AS WORD, fNullable AS WORD) AS SHORTINT PASCAL:odbc32.SQLSpecialColumns



_DLL FUNC SQLStatistics(hstmt AS PTR, szTableQualifier AS PSZ, cbTableQualifier AS SHORT,;
	szTableOwner AS PSZ, cbTableOwner AS SHORT, szTableName AS PSZ,;
	cbTableName AS SHORT, fUnique AS WORD, fAccuracy AS WORD) AS SHORTINT PASCAL:odbc32.SQLStatistics



_DLL FUNC  SQLTables(hstmt AS PTR, szTableQualifier AS PSZ, cbTableQualifier AS SHORT,;
	szTableOwner AS PSZ, cbTableOwner AS SHORT, szTableName AS PSZ,;
	cbTableName AS SHORT, szTableType AS PSZ, cbTableType AS SHORT);
	AS SHORTINT PASCAL:odbc32.SQLTables


_DLL FUNC  SQLBrowseConnect(hdbc AS PTR, szConnStrIn AS PSZ, cbConnStrIn AS SHORT,;
	szConnStrOut AS PSZ, cbConnStrOutMax AS SHORT, pcbConnStrOut AS SHORT PTR);
	AS SHORTINT PASCAL:odbc32.SQLBrowseConnect



_DLL FUNC SQLColumnPrivileges(hstmt AS PTR, szTableQualifier AS PSZ, cbTableQualifier AS SHORT,;
	szTableOwner AS PSZ,    cbTableOwner AS SHORT, szTableName AS PSZ,;
	cbTableName AS SHORT, szColumnName AS PSZ, cbColumnName AS SHORT);
	AS SHORTINT PASCAL:odbc32.SQLColumnPrivileges



_DLL FUNC SQLDataSources(henv AS PTR, fDirection AS WORD, szDSN AS PSZ, cbDSNMax AS SHORT,;
	pcbDSN AS SHORT PTR, szDescription AS PSZ, cbDescriptionMax AS SHORT,;
	pcbDescription AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLDataSources


_DLL FUNC SQLDescribeParam(hstmt AS PTR, ipar AS WORD, pfSqlType AS SHORT PTR,pcbColDef AS DWORD PTR,;
	pibScale AS SHORT PTR, pfNullable AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLDescribeParam



//  UH 09/30/1996
//_DLL FUNC  SQLExtendedFetch(hstmt AS PTR, fFetchType AS WORD,  irow AS SHORT, pcrow AS DWORD PTR,;
//              rgfRowStatus AS WORD PTR) AS SHORTINT PASCAL:odbc32.SQLExtendedFetch
_DLL FUNC  SQLExtendedFetch(hstmt AS PTR, fFetchType AS WORD,  irow AS LONG, pcrow AS DWORD PTR,;
	rgfRowStatus AS WORD PTR) AS SHORTINT PASCAL:odbc32.SQLExtendedFetch


_DLL FUNC SQLForeignKeys(hstmt AS PTR, szPkTableQualifier AS PSZ, cbPkTableQualifier AS SHORT,;
	szPkTableOwner AS PSZ, cbPkTableOwner AS SHORT, szPkTableName AS PSZ,;
	cbPkTableName AS SHORT, szFkTableQualifier AS PSZ, cbFkTableQualifier AS SHORT,;
	szFkTableOwner AS PSZ, cbFkTableOwner AS SHORT, szFkTableName AS PSZ,;
	cbFkTableName AS SHORT) AS SHORTINT PASCAL:odbc32.SQLForeignKeys


_DLL FUNC SQLMoreResults(hstmt AS PTR) AS SHORTINT PASCAL:odbc32.SQLMoreResults


_DLL FUNC SQLNativeSql(hdbc AS PTR, szSqlStrIn AS PSZ, cbSqlStrIn AS SHORT, szSqlStr AS PSZ,;
	cbSqlStrMax AS SHORT, pcbSqlStr AS LONG PTR) AS SHORTINT PASCAL:odbc32.SQLNativeSql


_DLL FUNC SQLNumParams(hstmt AS PTR, pspar AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLNumParams


_DLL FUNC SQLParamOptions( hstmt AS PTR, crow AS DWORD, pirow AS DWORD PTR) AS SHORTINT PASCAL:odbc32.SQLParamOptions


_DLL FUNC  SQLPrimaryKeys( hstmt AS PTR, szTableQualifier AS PSZ, cbTableQualifier AS SHORT,;
	szTableOwner AS PSZ,cbTableOwner AS SHORT, szTableName AS PSZ,;
	cbTableName AS SHORT) AS SHORTINT PASCAL:odbc32.SQLPrimaryKeys



_DLL FUNC SQLProcedureColumns(hstmt AS PTR, szProcQualifier AS PSZ, cbProcQualifier AS SHORT,;
	szProcOwner AS PSZ, cbProcOwner AS SHORT, szProcName AS PSZ,;
	cbProcName AS SHORT, szColumnName AS PSZ, cbColumnName AS SHORT);
	AS SHORTINT PASCAL:odbc32.SQLProcedureColumns


_DLL FUNC SQLProcedures(hstmt AS PTR, szProcQualifier AS PSZ, cbProcQualifier AS SHORT,;
	szProcOwner AS PSZ, cbProcOwner AS SHORT, szProcName AS PSZ,;
	cbProcName AS SHORT) AS SHORTINT PASCAL:odbc32.SQLProcedures



_DLL FUNC SQLSetPos(hstmt AS PTR, irow AS WORD, fOption AS WORD, fLock AS WORD) AS SHORTINT PASCAL:odbc32.SQLSetPos


_DLL FUNC SQLTablePrivileges(hstmt AS PTR,szTableQualifier AS PSZ, cbTableQualifier AS SHORT,;
	szTableOwner AS PSZ, cbTableOwner AS SHORT, szTableName AS PSZ,;
	cbTableName AS SHORT) AS SHORTINT PASCAL:odbc32.SQLTablePrivileges






_DLL FUNC SQLDrivers(henv AS PTR, fDirection AS WORD, szDriverDesc AS PSZ, cbDriverDescMax AS SHORT,;
	pcbDriverDesc AS SHORT PTR, szDriverAttributes AS PSZ, cbDrvrAttrMax AS SHORT,;
	pcbDrvrAttr AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLDrivers


_DLL FUNC SQLBindParameter( hstmt       AS PTR,  ;
	ipar        AS WORD, ;
	fParamType  AS SHORT,;
	fCType      AS SHORT,;
	fSqlType    AS SHORT,;
	cbColDef    AS DWORD,;
	ibScale     AS SHORT,;
	rgbValue    AS PTR,  ;
	cbValueMax  AS INT,  ;
	pcbValue    AS INT PTR) AS SHORTINT PASCAL:odbc32.SQLBindParameter



_DLL FUNC SQLAllocConnect(henv AS PTR, phdbc AS PTR) AS SHORTINT PASCAL:ODBC32.SQLAllocConnect


_DLL FUNC SQLAllocEnv(phenv AS PTR) AS SHORTINT PASCAL:ODBC32.SQLAllocEnv


_DLL FUNC SQLAllocStmt(hdbc AS PTR, phstmt AS PTR) AS SHORTINT PASCAL:odbc32.SQLAllocStmt



_DLL FUNC SQLCancel(hstmt AS PTR) AS SHORTINT PASCAL:odbc32.SQLCancel




_DLL FUNC SQLConnect(hdbc AS PTR, szDSN AS PSZ, cbDSN AS SHORT, szUID AS PSZ, cbUID AS SHORT,;
	szAuthStr AS PSZ, cbAythStr AS SHORT) AS SHORTINT PASCAL:odbc32.SQLConnect




_DLL FUNC SQLDisconnect(hdbc AS PTR) AS SHORTINT PASCAL:odbc32.SQLDisconnect


//  UH 11/27/1996
//  _dll func SQLExecDirect( hstmt as ptr, szSqlStr as psz,cbSqlStr as shart) as shortint pascal:odbc32.SQLExecDirect
_DLL FUNC SQLExecDirect( hstmt AS PTR, szSqlStr AS PSZ,cbSqlStr AS LONG) AS SHORTINT PASCAL:odbc32.SQLExecDirect


_DLL FUNC SQLExecute(hstmt AS PTR) AS SHORTINT PASCAL:odbc32.SQLExecute


_DLL FUNC SQLFetch(hstmt AS PTR) AS SHORTINT PASCAL:odbc32.SQLFetch


_DLL FUNC SQLFreeConnect(hdbc AS PTR) AS SHORTINT PASCAL:odbc32.SQLFreeConnect


_DLL FUNC SQLFreeEnv(henv AS PTR) AS SHORTINT PASCAL:odbc32.SQLFreeEnv


_DLL FUNC SQLFreeStmt(hstmt AS PTR, fOption AS WORD) AS SHORTINT PASCAL:odbc32.SQLFreeStmt





//  UH 11/27/1996
// _dll func SQLPrepare( hstmt as ptr, szSqlStr as psz, cbSqlStr as dword) as shortint pascal:odbc32.SQLPrepare
_DLL FUNC SQLPrepare( hstmt AS PTR, szSqlStr AS PSZ, cbSqlStr AS LONG) AS SHORTINT PASCAL:odbc32.SQLPrepare



_DLL FUNC SQLSetCursorName(hstmt AS PTR, szCursor AS PSZ, cbCursor AS SHORT) AS SHORTINT PASCAL:odbc32.SQLSetCursorName


_DLL FUNC SQLTransact(henv AS PTR, hdbc AS PTR, fType AS WORD) AS SHORTINT PASCAL:odbc32.SQLTransact





_DLL FUNC SQLBindCol(hstmt AS PTR, icol AS WORD, fCType AS SHORT, rgbValue AS PTR,;
	cbVzlueMax AS LONG, pcbValue AS LONG PTR) AS SHORTINT PASCAL:odbc32.SQLBindCol

_DLL FUNC SQLColAttributes(hstmt AS PTR, icol AS WORD, fDescType AS WORD, rgbDesc AS PTR,;
	cbDescMax AS SHORT, pcbDesc AS SHORT PTR, pfDesc AS LONG PTR) AS SHORTINT PASCAL:odbc32.SQLColAttributes

_DLL FUNC SQLDescribeCol(hstmt AS PTR, icol AS WORD, szColName AS PSZ, cbColNameMax AS SHORT,;
	pcbColName AS SHORT PTR, pfSqlType AS SHORT PTR, pcbColDef AS DWORD PTR,;
	pibScale AS SHORT PTR, pfNullable AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLDescribeCol

_DLL FUNC SQLError(henv AS PTR,  hdbc AS PTR, hstmt AS PTR, szSqlState AS PSZ,;
	pfNativeError AS SHORT PTR, szErrorMsg AS PSZ, cbErrorMsgMax AS SHORT,;
	pcbErrorMsg AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLError

_DLL FUNC  SQLGetCursorName(hstmt AS PTR,szCursor AS PSZ, cbCursorMax AS SHORT,;
	pcbCursor AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLGetCursorName


_DLL FUNC SQLNumResultCols( hstmt AS PTR, pccol AS SHORT PTR) AS SHORTINT PASCAL:odbc32.SQLNumResultCols


_DLL FUNC SQLRowCount(hstmt AS PTR, pcrow AS LONG PTR) AS SHORTINT PASCAL:odbc32.SQLRowCount


_DLL FUNC  SQLSetParam( hstmt AS PTR,  ipar AS WORD,    fCType AS SHORT,    fSqlType AS SHORT,  cbColDef AS DWORD,  ibScale AS SHORT,;
	rgbValue AS PTR,  pcbValue AS LONG PTR) AS SHORTINT PASCAL:odbc32.SQLSetParam


FUNCTION SQL_POSITION_TO(hstmt AS PTR,irow AS WORD) AS SHORTINT STRICT
	RETURN ( SQLSetPos(hstmt,irow,SQL_POSITION,SQL_LOCK_NO_CHANGE))


FUNCTION SQL_LOCK_RECORD(hstmt AS PTR,irow AS WORD, fLock AS WORD) AS SHORTINT STRICT
	RETURN ( SQLSetPos(hstmt,irow,SQL_POSITION,fLock))

FUNCTION SQL_REFRESH_RECORD(hstmt AS PTR, irow AS WORD, fLock AS WORD ) AS SHORTINT STRICT
	RETURN (SQLSetPos(hstmt,irow,SQL_REFRESH,fLock))

FUNCTION SQL_UPDATE_RECORD(hstmt AS PTR, irow AS WORD ) AS SHORTINT STRICT
	RETURN( SQLSetPos(hstmt,irow,SQL_UPDATE,SQL_LOCK_NO_CHANGE))

FUNCTION SQL_DELETE_RECORD(hstmt AS PTR,irow AS WORD) AS SHORTINT STRICT
	RETURN( SQLSetPos(hstmt,irow,SQL_DELETE,SQL_LOCK_NO_CHANGE))

FUNCTION SQL_ADD_RECORD(hstmt AS PTR, irow AS WORD )AS SHORTINT STRICT
	RETURN( SQLSetPos(hstmt,irow,SQL_ADD,SQL_LOCK_NO_CHANGE))



#region defines
DEFINE SQL_SPEC_MAJOR	:=	3     	/* Major version of specification  */
DEFINE SQL_SPEC_MINOR	:=	52     	/* Minor version of specification  */
DEFINE SQL_SPEC_STRING	:=	"03.52"	/* String constant for version */
DEFINE SQL_SQLSTATE_SIZE	:=	5	/* size of SQLSTATE */
DEFINE SQL_MAX_DSN_LENGTH	:=	32	/* maximum data source name size */
DEFINE SQL_MAX_OPTION_STRING_LENGTH	:=	256
DEFINE SQL_NO_DATA_FOUND	:=	SQL_NO_DATA
DEFINE SQL_HANDLE_SENV	:=		5
DEFINE SQL_ATTR_ODBC_VERSION	:=				200
DEFINE SQL_ATTR_CONNECTION_POOLING	:=			201
DEFINE SQL_ATTR_CP_MATCH	:=					202
DEFINE SQL_CP_OFF	:=							0U
DEFINE SQL_CP_ONE_PER_DRIVER	:=				1U
DEFINE SQL_CP_ONE_PER_HENV	:=					2U
DEFINE SQL_CP_DEFAULT	:=						SQL_CP_OFF
DEFINE SQL_CP_STRICT_MATCH	:=					0U
DEFINE SQL_CP_RELAXED_MATCH	:=				1U
DEFINE SQL_CP_MATCH_DEFAULT	:=				SQL_CP_STRICT_MATCH
DEFINE SQL_OV_ODBC2	:=						2U
DEFINE SQL_OV_ODBC3	:=						3U
DEFINE SQL_ACCESS_MODE	:=	101
DEFINE SQL_AUTOCOMMIT	:=	102
DEFINE SQL_LOGIN_TIMEOUT	:=	103
DEFINE SQL_OPT_TRACE	:=	104
DEFINE SQL_OPT_TRACEFILE	:=	105
DEFINE SQL_TRANSLATE_DLL	:=	106
DEFINE SQL_TRANSLATE_OPTION	:=	107
DEFINE SQL_TXN_ISOLATION	:=	108
DEFINE SQL_CURRENT_QUALIFIER	:=	109
DEFINE SQL_ODBC_CURSORS	:=	110
DEFINE SQL_QUIET_MODE	:=	111
DEFINE SQL_PACKET_SIZE	:=	112
DEFINE SQL_ATTR_ACCESS_MODE	:=		SQL_ACCESS_MODE
DEFINE SQL_ATTR_AUTOCOMMIT	:=			SQL_AUTOCOMMIT
DEFINE SQL_ATTR_CONNECTION_TIMEOUT	:=	113
DEFINE SQL_ATTR_CURRENT_CATALOG	:=	SQL_CURRENT_QUALIFIER
DEFINE SQL_ATTR_DISCONNECT_BEHAVIOR	:=	114
DEFINE SQL_ATTR_ENLIST_IN_DTC	:=		1207
DEFINE SQL_ATTR_ENLIST_IN_XA	:=		1208
DEFINE SQL_ATTR_LOGIN_TIMEOUT	:=		SQL_LOGIN_TIMEOUT
DEFINE SQL_ATTR_ODBC_CURSORS	:=		SQL_ODBC_CURSORS
DEFINE SQL_ATTR_PACKET_SIZE	:=		SQL_PACKET_SIZE
DEFINE SQL_ATTR_QUIET_MODE	:=			SQL_QUIET_MODE
DEFINE SQL_ATTR_TRACE	:=				SQL_OPT_TRACE
DEFINE SQL_ATTR_TRACEFILE	:=			SQL_OPT_TRACEFILE
DEFINE SQL_ATTR_TRANSLATE_LIB	:=		SQL_TRANSLATE_DLL
DEFINE SQL_ATTR_TRANSLATE_OPTION	:=	SQL_TRANSLATE_OPTION
DEFINE SQL_ATTR_TXN_ISOLATION	:=		SQL_TXN_ISOLATION
DEFINE SQL_ATTR_CONNECTION_DEAD	:=	1209	/* GetConnectAttr only */
DEFINE SQL_MODE_READ_WRITE	:=	0U
DEFINE SQL_MODE_READ_ONLY	:=	1U
DEFINE SQL_MODE_DEFAULT	:=	SQL_MODE_READ_WRITE
DEFINE SQL_AUTOCOMMIT_OFF	:=	0U
DEFINE SQL_AUTOCOMMIT_ON	:=	1U
DEFINE SQL_AUTOCOMMIT_DEFAULT	:=	SQL_AUTOCOMMIT_ON
DEFINE SQL_LOGIN_TIMEOUT_DEFAULT	:=	15U
DEFINE SQL_OPT_TRACE_OFF	:=	0U
DEFINE SQL_OPT_TRACE_ON	:=	1U
DEFINE SQL_OPT_TRACE_DEFAULT	:=	SQL_OPT_TRACE_OFF
DEFINE SQL_OPT_TRACE_FILE_DEFAULT	:=	"\\SQL.LOG"
DEFINE SQL_CUR_USE_IF_NEEDED	:=	0U
DEFINE SQL_CUR_USE_ODBC	:=	1U
DEFINE SQL_CUR_USE_DRIVER	:=	2U
DEFINE SQL_CUR_DEFAULT	:=	SQL_CUR_USE_DRIVER
DEFINE SQL_DB_RETURN_TO_POOL	:=			0U
DEFINE SQL_DB_DISCONNECT	:=				1U
DEFINE SQL_DB_DEFAULT	:=					SQL_DB_RETURN_TO_POOL
DEFINE SQL_DTC_DONE	:=					0L
DEFINE SQL_CD_TRUE	:=					1L		/* Connection is closed/dead */
DEFINE SQL_CD_FALSE	:=				0L		/* Connection is open/available */
DEFINE SQL_QUERY_TIMEOUT	:=		0
DEFINE SQL_MAX_ROWS	:=			1
DEFINE SQL_NOSCAN	:=				2
DEFINE SQL_MAX_LENGTH	:=			3
DEFINE SQL_ASYNC_ENABLE	:=		4	/* same as SQL_ATTR_ASYNC_ENABLE */
DEFINE SQL_BIND_TYPE	:=			5
DEFINE SQL_CURSOR_TYPE	:=			6
DEFINE SQL_CONCURRENCY	:=			7
DEFINE SQL_KEYSET_SIZE	:=			8
DEFINE SQL_ROWSET_SIZE	:=			9
DEFINE SQL_SIMULATE_CURSOR	:=		10
DEFINE SQL_RETRIEVE_DATA	:=		11
DEFINE SQL_USE_BOOKMARKS	:=		12
DEFINE SQL_GET_BOOKMARK	:=		13      /*      GetStmtOption Only */
DEFINE SQL_ROW_NUMBER	:=			14      /*      GetStmtOption Only */
DEFINE SQL_ATTR_ASYNC_ENABLE	:=				4
DEFINE SQL_ATTR_CONCURRENCY	:=				SQL_CONCURRENCY
DEFINE SQL_ATTR_CURSOR_TYPE	:=				SQL_CURSOR_TYPE
DEFINE SQL_ATTR_ENABLE_AUTO_IPD	:=			15
DEFINE SQL_ATTR_FETCH_BOOKMARK_PTR	:=			16
DEFINE SQL_ATTR_KEYSET_SIZE	:=				SQL_KEYSET_SIZE
DEFINE SQL_ATTR_MAX_LENGTH	:=					SQL_MAX_LENGTH
DEFINE SQL_ATTR_MAX_ROWS	:=					SQL_MAX_ROWS
DEFINE SQL_ATTR_NOSCAN	:=						SQL_NOSCAN
DEFINE SQL_ATTR_PARAM_BIND_OFFSET_PTR	:=		17
DEFINE SQL_ATTR_PARAM_BIND_TYPE	:=			18
DEFINE SQL_ATTR_PARAM_OPERATION_PTR	:=		19
DEFINE SQL_ATTR_PARAM_STATUS_PTR	:=			20
DEFINE SQL_ATTR_PARAMS_PROCESSED_PTR	:=		21
DEFINE SQL_ATTR_PARAMSET_SIZE	:=				22
DEFINE SQL_ATTR_QUERY_TIMEOUT	:=				SQL_QUERY_TIMEOUT
DEFINE SQL_ATTR_RETRIEVE_DATA	:=				SQL_RETRIEVE_DATA
DEFINE SQL_ATTR_ROW_BIND_OFFSET_PTR	:=		23
DEFINE SQL_ATTR_ROW_BIND_TYPE	:=				SQL_BIND_TYPE
DEFINE SQL_ATTR_ROW_NUMBER	:=					SQL_ROW_NUMBER	  	/*GetStmtAttr*/
DEFINE SQL_ATTR_ROW_OPERATION_PTR	:=			24
DEFINE SQL_ATTR_ROW_STATUS_PTR	:=				25
DEFINE SQL_ATTR_ROWS_FETCHED_PTR	:=			26
DEFINE SQL_ATTR_ROW_ARRAY_SIZE	:=				27
DEFINE SQL_ATTR_SIMULATE_CURSOR	:=			SQL_SIMULATE_CURSOR
DEFINE SQL_ATTR_USE_BOOKMARKS	:=				SQL_USE_BOOKMARKS
DEFINE SQL_COL_PRED_CHAR	:=		SQL_LIKE_ONLY
DEFINE SQL_COL_PRED_BASIC	:=		SQL_ALL_EXCEPT_LIKE
DEFINE SQL_IS_POINTER	:=							(-4)
DEFINE SQL_IS_UINTEGER	:=							(-5)
DEFINE SQL_IS_INTEGER	:=							(-6)
DEFINE SQL_IS_USMALLINT	:=						(-7)
DEFINE SQL_IS_SMALLINT	:=							(-8)
DEFINE SQL_PARAM_BIND_BY_COLUMN	:=			0U
DEFINE SQL_PARAM_BIND_TYPE_DEFAULT	:=			SQL_PARAM_BIND_BY_COLUMN
DEFINE SQL_QUERY_TIMEOUT_DEFAULT	:=	0U
DEFINE SQL_MAX_ROWS_DEFAULT	:=	0U
DEFINE SQL_NOSCAN_OFF	:=	0U     /*      1.0 FALSE */
DEFINE SQL_NOSCAN_ON	:=	1U     /*      1.0 TRUE */
DEFINE SQL_NOSCAN_DEFAULT	:=	SQL_NOSCAN_OFF
DEFINE SQL_MAX_LENGTH_DEFAULT	:=	0U
DEFINE SQL_ASYNC_ENABLE_OFF	:=			0U
DEFINE SQL_ASYNC_ENABLE_ON	:=				1U
DEFINE SQL_ASYNC_ENABLE_DEFAULT	:=	SQL_ASYNC_ENABLE_OFF
DEFINE SQL_BIND_BY_COLUMN	:=	0U
DEFINE SQL_BIND_TYPE_DEFAULT	:=	SQL_BIND_BY_COLUMN  /* Default value */
DEFINE SQL_CONCUR_READ_ONLY	:=	1
DEFINE SQL_CONCUR_LOCK	:=	2
DEFINE SQL_CONCUR_ROWVER	:=	3
DEFINE SQL_CONCUR_VALUES	:=	4
DEFINE SQL_CONCUR_DEFAULT	:=	SQL_CONCUR_READ_ONLY /* Default value */
DEFINE SQL_CURSOR_FORWARD_ONLY	:=	0U
DEFINE SQL_CURSOR_KEYSET_DRIVEN	:=	1U
DEFINE SQL_CURSOR_DYNAMIC	:=	2U
DEFINE SQL_CURSOR_STATIC	:=	3U
DEFINE SQL_CURSOR_TYPE_DEFAULT	:=	SQL_CURSOR_FORWARD_ONLY /* Default value */
DEFINE SQL_ROWSET_SIZE_DEFAULT	:=	1U
DEFINE SQL_KEYSET_SIZE_DEFAULT	:=	0U
DEFINE SQL_SC_NON_UNIQUE	:=	0U
DEFINE SQL_SC_TRY_UNIQUE	:=	1U
DEFINE SQL_SC_UNIQUE	:=	2U
DEFINE SQL_RD_OFF	:=	0U
DEFINE SQL_RD_ON	:=	1U
DEFINE SQL_RD_DEFAULT	:=	SQL_RD_ON
DEFINE SQL_UB_OFF	:=	0U
DEFINE SQL_UB_ON	:=						01U
DEFINE SQL_UB_DEFAULT	:=	SQL_UB_OFF
DEFINE SQL_UB_FIXED	:=					SQL_UB_ON
DEFINE SQL_UB_VARIABLE	:=					2U
DEFINE SQL_DESC_ARRAY_SIZE	:=						20
DEFINE SQL_DESC_ARRAY_STATUS_PTR	:=				21
DEFINE SQL_DESC_AUTO_UNIQUE_VALUE	:=				SQL_COLUMN_AUTO_INCREMENT
DEFINE SQL_DESC_BASE_COLUMN_NAME	:=				22
DEFINE SQL_DESC_BASE_TABLE_NAME	:=				23
DEFINE SQL_DESC_BIND_OFFSET_PTR	:=				24
DEFINE SQL_DESC_BIND_TYPE	:=						25
DEFINE SQL_DESC_CASE_SENSITIVE	:=					SQL_COLUMN_CASE_SENSITIVE
DEFINE SQL_DESC_CATALOG_NAME	:=					SQL_COLUMN_QUALIFIER_NAME
DEFINE SQL_DESC_CONCISE_TYPE	:=					SQL_COLUMN_TYPE
DEFINE SQL_DESC_DATETIME_INTERVAL_PRECISION	:=	26
DEFINE SQL_DESC_DISPLAY_SIZE	:=					SQL_COLUMN_DISPLAY_SIZE
DEFINE SQL_DESC_FIXED_PREC_SCALE	:=				SQL_COLUMN_MONEY
DEFINE SQL_DESC_LABEL	:=							SQL_COLUMN_LABEL
DEFINE SQL_DESC_LITERAL_PREFIX	:=					27
DEFINE SQL_DESC_LITERAL_SUFFIX	:=					28
DEFINE SQL_DESC_LOCAL_TYPE_NAME	:=				29
DEFINE SQL_DESC_MAXIMUM_SCALE	:=					30
DEFINE SQL_DESC_MINIMUM_SCALE	:=					31
DEFINE SQL_DESC_NUM_PREC_RADIX	:=					32
DEFINE SQL_DESC_PARAMETER_TYPE	:=					33
DEFINE SQL_DESC_ROWS_PROCESSED_PTR	:=				34
DEFINE SQL_DESC_ROWVER	:=							35
DEFINE SQL_DESC_SCHEMA_NAME	:=					SQL_COLUMN_OWNER_NAME
DEFINE SQL_DESC_SEARCHABLE	:=						SQL_COLUMN_SEARCHABLE
DEFINE SQL_DESC_TYPE_NAME	:=						SQL_COLUMN_TYPE_NAME
DEFINE SQL_DESC_TABLE_NAME	:=						SQL_COLUMN_TABLE_NAME
DEFINE SQL_DESC_UNSIGNED	:=						SQL_COLUMN_UNSIGNED
DEFINE SQL_DESC_UPDATABLE	:=						SQL_COLUMN_UPDATABLE
DEFINE SQL_DIAG_CURSOR_ROW_COUNT	:=			(-1249)
DEFINE SQL_DIAG_ROW_NUMBER	:=					(-1248)
DEFINE SQL_DIAG_COLUMN_NUMBER	:=				(-1247)
DEFINE SQL_DATE	:=	9
DEFINE SQL_INTERVAL	:=							10
DEFINE SQL_TIME	:=	10
DEFINE SQL_TIMESTAMP	:=	11
DEFINE SQL_LONGVARCHAR	:=	(-1)
DEFINE SQL_BINARY	:=	(-2)
DEFINE SQL_VARBINARY	:=	(-3)
DEFINE SQL_LONGVARBINARY	:=	(-4)
DEFINE SQL_BIGINT	:=	(-5)
DEFINE SQL_TINYINT	:=	(-6)
DEFINE SQL_BIT	:=	(-7)
DEFINE SQL_GUID	:=				(-11)
DEFINE SQL_CODE_YEAR	:=				1
DEFINE SQL_CODE_MONTH	:=				2
DEFINE SQL_CODE_DAY	:=				3
DEFINE SQL_CODE_HOUR	:=				4
DEFINE SQL_CODE_MINUTE	:=				5
DEFINE SQL_CODE_SECOND	:=				6
DEFINE SQL_CODE_YEAR_TO_MONTH	:=			7
DEFINE SQL_CODE_DAY_TO_HOUR	:=			8
DEFINE SQL_CODE_DAY_TO_MINUTE	:=			9
DEFINE SQL_CODE_DAY_TO_SECOND	:=			10
DEFINE SQL_CODE_HOUR_TO_MINUTE	:=			11
DEFINE SQL_CODE_HOUR_TO_SECOND	:=			12
DEFINE SQL_CODE_MINUTE_TO_SECOND	:=		13
DEFINE SQL_INTERVAL_YEAR	:=					(100 + SQL_CODE_YEAR)
DEFINE SQL_INTERVAL_MONTH	:=					(100 + SQL_CODE_MONTH)
DEFINE SQL_INTERVAL_DAY	:=					(100 + SQL_CODE_DAY)
DEFINE SQL_INTERVAL_HOUR	:=					(100 + SQL_CODE_HOUR)
DEFINE SQL_INTERVAL_MINUTE	:=					(100 + SQL_CODE_MINUTE)
DEFINE SQL_INTERVAL_SECOND	:=		(100 + SQL_CODE_SECOND)
DEFINE SQL_INTERVAL_YEAR_TO_MONTH	:=			(100 + SQL_CODE_YEAR_TO_MONTH)
DEFINE SQL_INTERVAL_DAY_TO_HOUR	:=			(100 + SQL_CODE_DAY_TO_HOUR)
DEFINE SQL_INTERVAL_DAY_TO_MINUTE	:=			(100 + SQL_CODE_DAY_TO_MINUTE)
DEFINE SQL_INTERVAL_DAY_TO_SECOND	:=			(100 + SQL_CODE_DAY_TO_SECOND)
DEFINE SQL_INTERVAL_HOUR_TO_MINUTE	:=			(100 + SQL_CODE_HOUR_TO_MINUTE)
DEFINE SQL_INTERVAL_HOUR_TO_SECOND	:=			(100 + SQL_CODE_HOUR_TO_SECOND)
DEFINE SQL_INTERVAL_MINUTE_TO_SECOND	:=		(100 + SQL_CODE_MINUTE_TO_SECOND)
DEFINE SQL_UNICODE	:=				SQL_WCHAR
DEFINE SQL_UNICODE_VARCHAR	:=		SQL_WVARCHAR
DEFINE SQL_UNICODE_LONGVARCHAR	:=	SQL_WLONGVARCHAR
DEFINE SQL_UNICODE_CHAR	:=		SQL_WCHAR
DEFINE SQL_C_CHAR	:=	SQL_CHAR             /* CHAR, VARCHAR, DECIMAL, NUMERIC */
DEFINE SQL_C_LONG	:=	SQL_INTEGER          /* INTEGER                      */
DEFINE SQL_C_SHORT	:=	SQL_SMALLINT         /* SMALLINT                     */
DEFINE SQL_C_FLOAT	:=	SQL_REAL             /* REAL                         */
DEFINE SQL_C_DOUBLE	:=	SQL_DOUBLE           /* FLOAT, DOUBLE                */
DEFINE SQL_C_NUMERIC	:=		SQL_NUMERIC
DEFINE SQL_C_DEFAULT	:=	99
DEFINE SQL_SIGNED_OFFSET	:=	(-20)
DEFINE SQL_UNSIGNED_OFFSET	:=	(-22)
DEFINE SQL_C_DATE	:=	SQL_DATE
DEFINE SQL_C_TIME	:=	SQL_TIME
DEFINE SQL_C_TIMESTAMP	:=	SQL_TIMESTAMP
DEFINE SQL_C_TYPE_DATE	:=					SQL_TYPE_DATE
DEFINE SQL_C_TYPE_TIME	:=					SQL_TYPE_TIME
DEFINE SQL_C_TYPE_TIMESTAMP	:=			SQL_TYPE_TIMESTAMP
DEFINE SQL_C_INTERVAL_YEAR	:=				SQL_INTERVAL_YEAR
DEFINE SQL_C_INTERVAL_MONTH	:=			SQL_INTERVAL_MONTH
DEFINE SQL_C_INTERVAL_DAY	:=				SQL_INTERVAL_DAY
DEFINE SQL_C_INTERVAL_HOUR	:=				SQL_INTERVAL_HOUR
DEFINE SQL_C_INTERVAL_MINUTE	:=			SQL_INTERVAL_MINUTE
DEFINE SQL_C_INTERVAL_SECOND	:=			SQL_INTERVAL_SECOND
DEFINE SQL_C_INTERVAL_YEAR_TO_MONTH	:=	SQL_INTERVAL_YEAR_TO_MONTH
DEFINE SQL_C_INTERVAL_DAY_TO_HOUR	:=		SQL_INTERVAL_DAY_TO_HOUR
DEFINE SQL_C_INTERVAL_DAY_TO_MINUTE	:=	SQL_INTERVAL_DAY_TO_MINUTE
DEFINE SQL_C_INTERVAL_DAY_TO_SECOND	:=	SQL_INTERVAL_DAY_TO_SECOND
DEFINE SQL_C_INTERVAL_HOUR_TO_MINUTE	:=	SQL_INTERVAL_HOUR_TO_MINUTE
DEFINE SQL_C_INTERVAL_HOUR_TO_SECOND	:=	SQL_INTERVAL_HOUR_TO_SECOND
DEFINE SQL_C_INTERVAL_MINUTE_TO_SECOND	:=	SQL_INTERVAL_MINUTE_TO_SECOND
DEFINE SQL_C_BINARY	:=	SQL_BINARY
DEFINE SQL_C_BIT	:=	SQL_BIT
DEFINE SQL_C_SBIGINT	:=	(SQL_BIGINT+SQL_SIGNED_OFFSET)	   /* SIGNED BIGINT */
DEFINE SQL_C_UBIGINT	:=	(SQL_BIGINT+SQL_UNSIGNED_OFFSET)   /* UNSIGNED BIGINT */
DEFINE SQL_C_TINYINT	:=	SQL_TINYINT
DEFINE SQL_C_SLONG	:=	(SQL_C_LONG+SQL_SIGNED_OFFSET)    /* SIGNED INTEGER  */
DEFINE SQL_C_SSHORT	:=	(SQL_C_SHORT+SQL_SIGNED_OFFSET)   /* SIGNED SMALLINT */
DEFINE SQL_C_STINYINT	:=	(SQL_TINYINT+SQL_SIGNED_OFFSET)   /* SIGNED TINYINT  */
DEFINE SQL_C_ULONG	:=	(SQL_C_LONG+SQL_UNSIGNED_OFFSET)  /* UNSIGNED INTEGER*/
DEFINE SQL_C_USHORT	:=	(SQL_C_SHORT+SQL_UNSIGNED_OFFSET) /* UNSIGNED SMALLINT*/
DEFINE SQL_C_UTINYINT	:=	(SQL_TINYINT+SQL_UNSIGNED_OFFSET) /* UNSIGNED TINYINT*/
DEFINE SQL_C_BOOKMARK	:=	SQL_C_ULONG                       /* BOOKMARK        */
DEFINE SQL_C_GUID	:=	SQL_GUID
DEFINE SQL_TYPE_NULL	:=	0
DEFINE SQL_C_VARBOOKMARK	:=		SQL_C_BINARY
DEFINE SQL_NO_ROW_NUMBER	:=						(-1)
DEFINE SQL_NO_COLUMN_NUMBER	:=					(-1)
DEFINE SQL_ROW_NUMBER_UNKNOWN	:=					(-2)
DEFINE SQL_COLUMN_NUMBER_UNKNOWN	:=				(-2)
DEFINE SQL_DEFAULT_PARAM	:=	(-5)
DEFINE SQL_IGNORE	:=	(-6)
DEFINE SQL_COLUMN_IGNORE	:=			SQL_IGNORE
DEFINE SQL_LEN_DATA_AT_EXEC_OFFSET	:=	(-100)
DEFINE SQL_LEN_BINARY_ATTR_OFFSET	:=	(-100)
DEFINE SQL_PARAM_TYPE_DEFAULT	:=	SQL_PARAM_INPUT_OUTPUT
DEFINE SQL_SETPARAM_VALUE_MAX	:=	(-1L)
DEFINE SQL_COLUMN_COUNT	:=	0
DEFINE SQL_COLUMN_NAME	:=	1
DEFINE SQL_COLUMN_TYPE	:=	2
DEFINE SQL_COLUMN_LENGTH	:=	3
DEFINE SQL_COLUMN_PRECISION	:=	4
DEFINE SQL_COLUMN_SCALE	:=	5
DEFINE SQL_COLUMN_DISPLAY_SIZE	:=	6
DEFINE SQL_COLUMN_NULLABLE	:=	7
DEFINE SQL_COLUMN_UNSIGNED	:=	8
DEFINE SQL_COLUMN_MONEY	:=	9
DEFINE SQL_COLUMN_UPDATABLE	:=	10
DEFINE SQL_COLUMN_AUTO_INCREMENT	:=	11
DEFINE SQL_COLUMN_CASE_SENSITIVE	:=	12
DEFINE SQL_COLUMN_SEARCHABLE	:=	13
DEFINE SQL_COLUMN_TYPE_NAME	:=	14
DEFINE SQL_COLUMN_TABLE_NAME	:=	15
DEFINE SQL_COLUMN_OWNER_NAME	:=	16
DEFINE SQL_COLUMN_QUALIFIER_NAME	:=	17
DEFINE SQL_COLUMN_LABEL	:=	18
DEFINE SQL_COLATT_OPT_MAX	:=	SQL_COLUMN_LABEL
DEFINE SQL_COLATT_OPT_MIN	:=	SQL_COLUMN_COUNT
DEFINE SQL_ATTR_READONLY	:=	0
DEFINE SQL_ATTR_WRITE	:=	1
DEFINE SQL_ATTR_READWRITE_UNKNOWN	:=	2
DEFINE SQL_UNSEARCHABLE	:=	0
DEFINE SQL_LIKE_ONLY	:=	1
DEFINE SQL_ALL_EXCEPT_LIKE	:=	2
DEFINE SQL_SEARCHABLE	:=	3
DEFINE SQL_PRED_SEARCHABLE	:=				SQL_SEARCHABLE
DEFINE SQL_NO_TOTAL	:=	(-4)
DEFINE SQL_API_SQLALLOCHANDLESTD	:=	73
DEFINE SQL_API_SQLBULKOPERATIONS	:=	24
DEFINE SQL_API_SQLBINDPARAMETER	:=	72
DEFINE SQL_API_SQLBROWSECONNECT	:=	55
DEFINE SQL_API_SQLCOLATTRIBUTES	:=	6
DEFINE SQL_API_SQLCOLUMNPRIVILEGES	:=	56
DEFINE SQL_API_SQLDESCRIBEPARAM	:=	58
DEFINE SQL_API_SQLDRIVERCONNECT	:=	41
DEFINE SQL_API_SQLDRIVERS	:=	71
DEFINE SQL_API_SQLEXTENDEDFETCH	:=	59
DEFINE SQL_API_SQLFOREIGNKEYS	:=	60
DEFINE SQL_API_SQLMORERESULTS	:=	61
DEFINE SQL_API_SQLNATIVESQL	:=	62
DEFINE SQL_API_SQLNUMPARAMS	:=	63
DEFINE SQL_API_SQLPARAMOPTIONS	:=	64
DEFINE SQL_API_SQLPRIMARYKEYS	:=	65
DEFINE SQL_API_SQLPROCEDURECOLUMNS	:=	66
DEFINE SQL_API_SQLPROCEDURES	:=	67
DEFINE SQL_API_SQLSETPOS	:=	68
DEFINE SQL_API_SQLSETSCROLLOPTIONS	:=	69
DEFINE SQL_API_SQLTABLEPRIVILEGES	:=	70
DEFINE SQL_API_ALL_FUNCTIONS	:=	0		/* See CAUTION above */
DEFINE SQL_API_LOADBYORDINAL	:=	199		/* See CAUTION above */
DEFINE SQL_API_ODBC3_ALL_FUNCTIONS	:=	999
DEFINE SQL_API_ODBC3_ALL_FUNCTIONS_SIZE	:=	250		/* array of 250 words */
DEFINE SQL_INFO_FIRST	:=	0
DEFINE SQL_ACTIVE_CONNECTIONS	:=	0	/* MAX_DRIVER_CONNECTIONS */
DEFINE SQL_ACTIVE_STATEMENTS	:=	1	/* MAX_CONCURRENT_ACTIVITIES */
DEFINE SQL_DRIVER_HDBC	:=	3
DEFINE SQL_DRIVER_HENV	:=	4
DEFINE SQL_DRIVER_HSTMT	:=	5
DEFINE SQL_DRIVER_NAME	:=	6
DEFINE SQL_DRIVER_VER	:=	7
DEFINE SQL_ODBC_API_CONFORMANCE	:=	9
DEFINE SQL_ODBC_VER	:=	10
DEFINE SQL_ROW_UPDATES	:=	11
DEFINE SQL_ODBC_SAG_CLI_CONFORMANCE	:=	12
DEFINE SQL_ODBC_SQL_CONFORMANCE	:=	15
DEFINE SQL_PROCEDURES	:=	21
DEFINE SQL_CONCAT_NULL_BEHAVIOR	:=	22
DEFINE SQL_CURSOR_ROLLBACK_BEHAVIOR	:=	24
DEFINE SQL_EXPRESSIONS_IN_ORDERBY	:=	27
DEFINE SQL_MAX_OWNER_NAME_LEN	:=	32	/* MAX_SCHEMA_NAME_LEN */
DEFINE SQL_MAX_PROCEDURE_NAME_LEN	:=	33
DEFINE SQL_MAX_QUALIFIER_NAME_LEN	:=	34	/* MAX_CATALOG_NAME_LEN */
DEFINE SQL_MULT_RESULT_SETS	:=	36
DEFINE SQL_MULTIPLE_ACTIVE_TXN	:=	37
DEFINE SQL_OUTER_JOINS	:=	38
DEFINE SQL_OWNER_TERM	:=	39
DEFINE SQL_PROCEDURE_TERM	:=	40
DEFINE SQL_QUALIFIER_NAME_SEPARATOR	:=	41
DEFINE SQL_QUALIFIER_TERM	:=	42
DEFINE SQL_SCROLL_OPTIONS	:=	44
DEFINE SQL_TABLE_TERM	:=	45
DEFINE SQL_CONVERT_FUNCTIONS	:=	48
DEFINE SQL_NUMERIC_FUNCTIONS	:=	49
DEFINE SQL_STRING_FUNCTIONS	:=	50
DEFINE SQL_SYSTEM_FUNCTIONS	:=	51
DEFINE SQL_TIMEDATE_FUNCTIONS	:=	52
DEFINE SQL_CONVERT_BIGINT	:=	53
DEFINE SQL_CONVERT_BINARY	:=	54
DEFINE SQL_CONVERT_BIT	:=	55
DEFINE SQL_CONVERT_CHAR	:=	56
DEFINE SQL_CONVERT_DATE	:=	57
DEFINE SQL_CONVERT_DECIMAL	:=	58
DEFINE SQL_CONVERT_DOUBLE	:=	59
DEFINE SQL_CONVERT_FLOAT	:=	60
DEFINE SQL_CONVERT_INTEGER	:=	61
DEFINE SQL_CONVERT_LONGVARCHAR	:=	62
DEFINE SQL_CONVERT_NUMERIC	:=	63
DEFINE SQL_CONVERT_REAL	:=	64
DEFINE SQL_CONVERT_SMALLINT	:=	65
DEFINE SQL_CONVERT_TIME	:=	66
DEFINE SQL_CONVERT_TIMESTAMP	:=	67
DEFINE SQL_CONVERT_TINYINT	:=	68
DEFINE SQL_CONVERT_VARBINARY	:=	69
DEFINE SQL_CONVERT_VARCHAR	:=	70
DEFINE SQL_CONVERT_LONGVARBINARY	:=	71
DEFINE SQL_ODBC_SQL_OPT_IEF	:=	73		/* SQL_INTEGRITY */
DEFINE SQL_CORRELATION_NAME	:=	74
DEFINE SQL_NON_NULLABLE_COLUMNS	:=	75
DEFINE SQL_DRIVER_HLIB	:=	76
DEFINE SQL_DRIVER_ODBC_VER	:=	77
DEFINE SQL_LOCK_TYPES	:=	78
DEFINE SQL_POS_OPERATIONS	:=	79
DEFINE SQL_POSITIONED_STATEMENTS	:=	80
DEFINE SQL_BOOKMARK_PERSISTENCE	:=	82
DEFINE SQL_STATIC_SENSITIVITY	:=	83
DEFINE SQL_FILE_USAGE	:=	84
DEFINE SQL_COLUMN_ALIAS	:=	87
DEFINE SQL_GROUP_BY	:=	88
DEFINE SQL_KEYWORDS	:=	89
DEFINE SQL_OWNER_USAGE	:=	91
DEFINE SQL_QUALIFIER_USAGE	:=	92
DEFINE SQL_QUOTED_IDENTIFIER_CASE	:=	93
DEFINE SQL_SUBQUERIES	:=	95
DEFINE SQL_UNION	:=	96
DEFINE SQL_MAX_ROW_SIZE_INCLUDES_LONG	:=	103
DEFINE SQL_MAX_CHAR_LITERAL_LEN	:=	108
DEFINE SQL_TIMEDATE_ADD_INTERVALS	:=	109
DEFINE SQL_TIMEDATE_DIFF_INTERVALS	:=	110
DEFINE SQL_NEED_LONG_DATA_LEN	:=	111
DEFINE SQL_MAX_BINARY_LITERAL_LEN	:=	112
DEFINE SQL_LIKE_ESCAPE_CLAUSE	:=	113
DEFINE SQL_QUALIFIER_LOCATION	:=	114
//DEFINE SQL_OJ_CAPABILITIES	:=	65003  /* Temp value until ODBC 3.0 */
DEFINE SQL_ACTIVE_ENVIRONMENTS	:=					116
DEFINE SQL_ALTER_DOMAIN	:=						117
DEFINE SQL_SQL_CONFORMANCE	:=						118
DEFINE SQL_DATETIME_LITERALS	:=					119
DEFINE SQL_ASYNC_MODE	:=							10021	/* new X/Open spec */
DEFINE SQL_BATCH_ROW_COUNT	:=						120
DEFINE SQL_BATCH_SUPPORT	:=						121
DEFINE SQL_CATALOG_LOCATION	:=					SQL_QUALIFIER_LOCATION
DEFINE SQL_CATALOG_NAME_SEPARATOR	:=				SQL_QUALIFIER_NAME_SEPARATOR
DEFINE SQL_CATALOG_TERM	:=						SQL_QUALIFIER_TERM
DEFINE SQL_CATALOG_USAGE	:=						SQL_QUALIFIER_USAGE
DEFINE SQL_CONVERT_WCHAR	:=						122
DEFINE SQL_CONVERT_INTERVAL_DAY_TIME	:=			123
DEFINE SQL_CONVERT_INTERVAL_YEAR_MONTH	:=			124
DEFINE SQL_CONVERT_WLONGVARCHAR	:=				125
DEFINE SQL_CONVERT_WVARCHAR	:=					126
DEFINE SQL_CREATE_ASSERTION	:=					127
DEFINE SQL_CREATE_CHARACTER_SET	:=				128
DEFINE SQL_CREATE_COLLATION	:=					129
DEFINE SQL_CREATE_DOMAIN	:=						130
DEFINE SQL_CREATE_SCHEMA	:=						131
DEFINE SQL_CREATE_TABLE	:=						132
DEFINE SQL_CREATE_TRANSLATION	:=					133
DEFINE SQL_CREATE_VIEW	:=							134
DEFINE SQL_DRIVER_HDESC	:=						135
DEFINE SQL_DROP_ASSERTION	:=						136
DEFINE SQL_DROP_CHARACTER_SET	:=					137
DEFINE SQL_DROP_COLLATION	:=						138
DEFINE SQL_DROP_DOMAIN	:=							139
DEFINE SQL_DROP_SCHEMA	:=							140
DEFINE SQL_DROP_TABLE	:=							141
DEFINE SQL_DROP_TRANSLATION	:=					142
DEFINE SQL_DROP_VIEW	:=							143
DEFINE SQL_DYNAMIC_CURSOR_ATTRIBUTES1	:=			144
DEFINE SQL_DYNAMIC_CURSOR_ATTRIBUTES2	:=			145
DEFINE SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES1	:=		146
DEFINE SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES2	:=		147
DEFINE SQL_INDEX_KEYWORDS	:=						148
DEFINE SQL_INFO_SCHEMA_VIEWS	:=					149
DEFINE SQL_KEYSET_CURSOR_ATTRIBUTES1	:=			150
DEFINE SQL_KEYSET_CURSOR_ATTRIBUTES2	:=			151
DEFINE SQL_MAX_ASYNC_CONCURRENT_STATEMENTS	:=		10022	/* new X/Open spec */
DEFINE SQL_ODBC_INTERFACE_CONFORMANCE	:=			152
DEFINE SQL_PARAM_ARRAY_ROW_COUNTS	:=				153
DEFINE SQL_PARAM_ARRAY_SELECTS	:=				154
DEFINE SQL_SCHEMA_TERM	:=							SQL_OWNER_TERM
DEFINE SQL_SCHEMA_USAGE	:=						SQL_OWNER_USAGE
DEFINE SQL_SQL92_DATETIME_FUNCTIONS	:=			155
DEFINE SQL_SQL92_FOREIGN_KEY_DELETE_RULE	:=		156
DEFINE SQL_SQL92_FOREIGN_KEY_UPDATE_RULE	:=		157
DEFINE SQL_SQL92_GRANT	:=							158
DEFINE SQL_SQL92_NUMERIC_VALUE_FUNCTIONS	:=		159
DEFINE SQL_SQL92_PREDICATES	:=					160
DEFINE SQL_SQL92_RELATIONAL_JOIN_OPERATORS	:=		161
DEFINE SQL_SQL92_REVOKE	:=						162
DEFINE SQL_SQL92_ROW_VALUE_CONSTRUCTOR	:=			163
DEFINE SQL_SQL92_STRING_FUNCTIONS	:=				164
DEFINE SQL_SQL92_VALUE_EXPRESSIONS	:=				165
DEFINE SQL_STANDARD_CLI_CONFORMANCE	:=			166
DEFINE SQL_STATIC_CURSOR_ATTRIBUTES1	:=			167
DEFINE SQL_STATIC_CURSOR_ATTRIBUTES2	:=			168
DEFINE SQL_AGGREGATE_FUNCTIONS	:=					169
DEFINE SQL_DDL_INDEX	:=							170
DEFINE SQL_DM_VER	:=								171
DEFINE SQL_INSERT_STATEMENT	:=					172
DEFINE SQL_CONVERT_GUID	:=						173
DEFINE SQL_UNION_STATEMENT	:=						SQL_UNION
DEFINE SQL_DTC_TRANSITION_COST	:=					1750
DEFINE SQL_AT_ADD_COLUMN_SINGLE	:=				0x00000020L
DEFINE SQL_AT_ADD_COLUMN_DEFAULT	:=				0x00000040L
DEFINE SQL_AT_ADD_COLUMN_COLLATION	:=				0x00000080L
DEFINE SQL_AT_SET_COLUMN_DEFAULT	:=				0x00000100L
DEFINE SQL_AT_DROP_COLUMN_DEFAULT	:=				0x00000200L
DEFINE SQL_AT_DROP_COLUMN_CASCADE	:=				0x00000400L
DEFINE SQL_AT_DROP_COLUMN_RESTRICT	:=				0x00000800L
DEFINE SQL_AT_ADD_TABLE_CONSTRAINT	:=				0x00001000L
DEFINE SQL_AT_DROP_TABLE_CONSTRAINT_CASCADE	:=	0x00002000L
DEFINE SQL_AT_DROP_TABLE_CONSTRAINT_RESTRICT	:=	0x00004000L
DEFINE SQL_AT_CONSTRAINT_NAME_DEFINITION	:=		0x00008000L
DEFINE SQL_AT_CONSTRAINT_INITIALLY_DEFERRED	:=	0x00010000L
DEFINE SQL_AT_CONSTRAINT_INITIALLY_IMMEDIATE	:=	0x00020000L
DEFINE SQL_AT_CONSTRAINT_DEFERRABLE	:=			0x00040000L
DEFINE SQL_AT_CONSTRAINT_NON_DEFERRABLE	:=		0x00080000L
DEFINE SQL_CVT_CHAR	:=	0x00000001L
DEFINE SQL_CVT_NUMERIC	:=	0x00000002L
DEFINE SQL_CVT_DECIMAL	:=	0x00000004L
DEFINE SQL_CVT_INTEGER	:=	0x00000008L
DEFINE SQL_CVT_SMALLINT	:=	0x00000010L
DEFINE SQL_CVT_FLOAT	:=	0x00000020L
DEFINE SQL_CVT_REAL	:=	0x00000040L
DEFINE SQL_CVT_DOUBLE	:=	0x00000080L
DEFINE SQL_CVT_VARCHAR	:=	0x00000100L
DEFINE SQL_CVT_LONGVARCHAR	:=	0x00000200L
DEFINE SQL_CVT_BINARY	:=	0x00000400L
DEFINE SQL_CVT_VARBINARY	:=	0x00000800L
DEFINE SQL_CVT_BIT	:=	0x00001000L
DEFINE SQL_CVT_TINYINT	:=	0x00002000L
DEFINE SQL_CVT_BIGINT	:=	0x00004000L
DEFINE SQL_CVT_DATE	:=	0x00008000L
DEFINE SQL_CVT_TIME	:=	0x00010000L
DEFINE SQL_CVT_TIMESTAMP	:=	0x00020000L
DEFINE SQL_CVT_LONGVARBINARY	:=	0x00040000L
DEFINE SQL_CVT_INTERVAL_YEAR_MONTH	:=		0x00080000L
DEFINE SQL_CVT_INTERVAL_DAY_TIME	:=		0x00100000L
DEFINE SQL_CVT_WCHAR	:=						0x00200000L
DEFINE SQL_CVT_WLONGVARCHAR	:=				0x00400000L
DEFINE SQL_CVT_WVARCHAR	:=					0x00800000L
DEFINE SQL_CVT_GUID	:=						0x01000000L
DEFINE SQL_FN_CVT_CONVERT	:=	0x00000001L
DEFINE SQL_FN_CVT_CAST	:=						0x00000002L
DEFINE SQL_FN_STR_CONCAT	:=	0x00000001L
DEFINE SQL_FN_STR_INSERT	:=	0x00000002L
DEFINE SQL_FN_STR_LEFT	:=	0x00000004L
DEFINE SQL_FN_STR_LTRIM	:=	0x00000008L
DEFINE SQL_FN_STR_LENGTH	:=	0x00000010L
DEFINE SQL_FN_STR_LOCATE	:=	0x00000020L
DEFINE SQL_FN_STR_LCASE	:=	0x00000040L
DEFINE SQL_FN_STR_REPEAT	:=	0x00000080L
DEFINE SQL_FN_STR_REPLACE	:=	0x00000100L
DEFINE SQL_FN_STR_RIGHT	:=	0x00000200L
DEFINE SQL_FN_STR_RTRIM	:=	0x00000400L
DEFINE SQL_FN_STR_SUBSTRING	:=	0x00000800L
DEFINE SQL_FN_STR_UCASE	:=	0x00001000L
DEFINE SQL_FN_STR_ASCII	:=	0x00002000L
DEFINE SQL_FN_STR_CHAR	:=	0x00004000L
DEFINE SQL_FN_STR_DIFFERENCE	:=	0x00008000L
DEFINE SQL_FN_STR_LOCATE_2	:=	0x00010000L
DEFINE SQL_FN_STR_SOUNDEX	:=	0x00020000L
DEFINE SQL_FN_STR_SPACE	:=	0x00040000L
DEFINE SQL_FN_STR_BIT_LENGTH	:=				0x00080000L
DEFINE SQL_FN_STR_CHAR_LENGTH	:=				0x00100000L
DEFINE SQL_FN_STR_CHARACTER_LENGTH	:=			0x00200000L
DEFINE SQL_FN_STR_OCTET_LENGTH	:=				0x00400000L
DEFINE SQL_FN_STR_POSITION	:=					0x00800000L
DEFINE SQL_SSF_CONVERT	:=						0x00000001L
DEFINE SQL_SSF_LOWER	:=						0x00000002L
DEFINE SQL_SSF_UPPER	:=						0x00000004L
DEFINE SQL_SSF_SUBSTRING	:=					0x00000008L
DEFINE SQL_SSF_TRANSLATE	:=					0x00000010L
DEFINE SQL_SSF_TRIM_BOTH	:=					0x00000020L
DEFINE SQL_SSF_TRIM_LEADING	:=				0x00000040L
DEFINE SQL_SSF_TRIM_TRAILING	:=				0x00000080L
DEFINE SQL_FN_NUM_ABS	:=	0x00000001L
DEFINE SQL_FN_NUM_ACOS	:=	0x00000002L
DEFINE SQL_FN_NUM_ASIN	:=	0x00000004L
DEFINE SQL_FN_NUM_ATAN	:=	0x00000008L
DEFINE SQL_FN_NUM_ATAN2	:=	0x00000010L
DEFINE SQL_FN_NUM_CEILING	:=	0x00000020L
DEFINE SQL_FN_NUM_COS	:=	0x00000040L
DEFINE SQL_FN_NUM_COT	:=	0x00000080L
DEFINE SQL_FN_NUM_EXP	:=	0x00000100L
DEFINE SQL_FN_NUM_FLOOR	:=	0x00000200L
DEFINE SQL_FN_NUM_LOG	:=	0x00000400L
DEFINE SQL_FN_NUM_MOD	:=	0x00000800L
DEFINE SQL_FN_NUM_SIGN	:=	0x00001000L
DEFINE SQL_FN_NUM_SIN	:=	0x00002000L
DEFINE SQL_FN_NUM_SQRT	:=	0x00004000L
DEFINE SQL_FN_NUM_TAN	:=	0x00008000L
DEFINE SQL_FN_NUM_PI	:=	0x00010000L
DEFINE SQL_FN_NUM_RAND	:=	0x00020000L
DEFINE SQL_FN_NUM_DEGREES	:=	0x00040000L
DEFINE SQL_FN_NUM_LOG10	:=	0x00080000L
DEFINE SQL_FN_NUM_POWER	:=	0x00100000L
DEFINE SQL_FN_NUM_RADIANS	:=	0x00200000L
DEFINE SQL_FN_NUM_ROUND	:=	0x00400000L
DEFINE SQL_FN_NUM_TRUNCATE	:=	0x00800000L
DEFINE SQL_SNVF_BIT_LENGTH	:=					0x00000001L
DEFINE SQL_SNVF_CHAR_LENGTH	:=				0x00000002L
DEFINE SQL_SNVF_CHARACTER_LENGTH	:=			0x00000004L
DEFINE SQL_SNVF_EXTRACT	:=					0x00000008L
DEFINE SQL_SNVF_OCTET_LENGTH	:=				0x00000010L
DEFINE SQL_SNVF_POSITION	:=					0x00000020L
DEFINE SQL_FN_TD_NOW	:=	0x00000001L
DEFINE SQL_FN_TD_CURDATE	:=	0x00000002L
DEFINE SQL_FN_TD_DAYOFMONTH	:=	0x00000004L
DEFINE SQL_FN_TD_DAYOFWEEK	:=	0x00000008L
DEFINE SQL_FN_TD_DAYOFYEAR	:=	0x00000010L
DEFINE SQL_FN_TD_MONTH	:=	0x00000020L
DEFINE SQL_FN_TD_QUARTER	:=	0x00000040L
DEFINE SQL_FN_TD_WEEK	:=	0x00000080L
DEFINE SQL_FN_TD_YEAR	:=	0x00000100L
DEFINE SQL_FN_TD_CURTIME	:=	0x00000200L
DEFINE SQL_FN_TD_HOUR	:=	0x00000400L
DEFINE SQL_FN_TD_MINUTE	:=	0x00000800L
DEFINE SQL_FN_TD_SECOND	:=	0x00001000L
DEFINE SQL_FN_TD_TIMESTAMPADD	:=	0x00002000L
DEFINE SQL_FN_TD_TIMESTAMPDIFF	:=	0x00004000L
DEFINE SQL_FN_TD_DAYNAME	:=	0x00008000L
DEFINE SQL_FN_TD_MONTHNAME	:=	0x00010000L
DEFINE SQL_FN_TD_CURRENT_DATE	:=				0x00020000L
DEFINE SQL_FN_TD_CURRENT_TIME	:=				0x00040000L
DEFINE SQL_FN_TD_CURRENT_TIMESTAMP	:=			0x00080000L
DEFINE SQL_FN_TD_EXTRACT	:=					0x00100000L
DEFINE SQL_SDF_CURRENT_DATE	:=				0x00000001L
DEFINE SQL_SDF_CURRENT_TIME	:=				0x00000002L
DEFINE SQL_SDF_CURRENT_TIMESTAMP	:=			0x00000004L
DEFINE SQL_FN_SYS_USERNAME	:=	0x00000001L
DEFINE SQL_FN_SYS_DBNAME	:=	0x00000002L
DEFINE SQL_FN_SYS_IFNULL	:=	0x00000004L
DEFINE SQL_FN_TSI_FRAC_SECOND	:=	0x00000001L
DEFINE SQL_FN_TSI_SECOND	:=	0x00000002L
DEFINE SQL_FN_TSI_MINUTE	:=	0x00000004L
DEFINE SQL_FN_TSI_HOUR	:=	0x00000008L
DEFINE SQL_FN_TSI_DAY	:=	0x00000010L
DEFINE SQL_FN_TSI_WEEK	:=	0x00000020L
DEFINE SQL_FN_TSI_MONTH	:=	0x00000040L
DEFINE SQL_FN_TSI_QUARTER	:=	0x00000080L
DEFINE SQL_FN_TSI_YEAR	:=	0x00000100L
DEFINE SQL_CA1_NEXT	:=						0x00000001L
DEFINE SQL_CA1_ABSOLUTE	:=					0x00000002L
DEFINE SQL_CA1_RELATIVE	:=					0x00000004L
DEFINE SQL_CA1_BOOKMARK	:=					0x00000008L
DEFINE SQL_CA1_LOCK_NO_CHANGE	:=				0x00000040L
DEFINE SQL_CA1_LOCK_EXCLUSIVE	:=				0x00000080L
DEFINE SQL_CA1_LOCK_UNLOCK	:=					0x00000100L
DEFINE SQL_CA1_POS_POSITION	:=				0x00000200L
DEFINE SQL_CA1_POS_UPDATE	:=					0x00000400L
DEFINE SQL_CA1_POS_DELETE	:=					0x00000800L
DEFINE SQL_CA1_POS_REFRESH	:=					0x00001000L
DEFINE SQL_CA1_POSITIONED_UPDATE	:=			0x00002000L
DEFINE SQL_CA1_POSITIONED_DELETE	:=			0x00004000L
DEFINE SQL_CA1_SELECT_FOR_UPDATE	:=			0x00008000L
DEFINE SQL_CA1_BULK_ADD	:=					0x00010000L
DEFINE SQL_CA1_BULK_UPDATE_BY_BOOKMARK	:=		0x00020000L
DEFINE SQL_CA1_BULK_DELETE_BY_BOOKMARK	:=		0x00040000L
DEFINE SQL_CA1_BULK_FETCH_BY_BOOKMARK	:=		0x00080000L
DEFINE SQL_CA2_READ_ONLY_CONCURRENCY	:=		0x00000001L
DEFINE SQL_CA2_LOCK_CONCURRENCY	:=			0x00000002L
DEFINE SQL_CA2_OPT_ROWVER_CONCURRENCY	:=		0x00000004L
DEFINE SQL_CA2_OPT_VALUES_CONCURRENCY	:=		0x00000008L
DEFINE SQL_CA2_SENSITIVITY_ADDITIONS	:=		0x00000010L
DEFINE SQL_CA2_SENSITIVITY_DELETIONS	:=		0x00000020L
DEFINE SQL_CA2_SENSITIVITY_UPDATES	:=			0x00000040L
DEFINE SQL_CA2_MAX_ROWS_SELECT	:=				0x00000080L
DEFINE SQL_CA2_MAX_ROWS_INSERT	:=				0x00000100L
DEFINE SQL_CA2_MAX_ROWS_DELETE	:=				0x00000200L
DEFINE SQL_CA2_MAX_ROWS_UPDATE	:=				0x00000400L
DEFINE SQL_CA2_MAX_ROWS_CATALOG	:=			0x00000800L
//DEFINE SQL_CA2_MAX_ROWS_AFFECTS_ALL	:=		(SQL_CA2_MAX_ROWS_SELECT | 					SQL_CA2_MAX_ROWS_INSERT | SQL_CA2_MAX_ROWS_DELETE | 					SQL_CA2_MAX_ROWS_UPDATE | SQL_CA2_MAX_ROWS_CATALOG
DEFINE SQL_CA2_MAX_ROWS_AFFECTS_ALL	:=  0xF80L
DEFINE SQL_CA2_CRC_EXACT	:=					0x00001000L
DEFINE SQL_CA2_CRC_APPROXIMATE	:=				0x00002000L
DEFINE SQL_CA2_SIMULATE_NON_UNIQUE	:=			0x00004000L
DEFINE SQL_CA2_SIMULATE_TRY_UNIQUE	:=			0x00008000L
DEFINE SQL_CA2_SIMULATE_UNIQUE	:=				0x00010000L
DEFINE SQL_OAC_NONE	:=	0x0000
DEFINE SQL_OAC_LEVEL1	:=	0x0001
DEFINE SQL_OAC_LEVEL2	:=	0x0002
DEFINE SQL_OSCC_NOT_COMPLIANT	:=	0x0000
DEFINE SQL_OSCC_COMPLIANT	:=	0x0001
DEFINE SQL_OSC_MINIMUM	:=	0x0000
DEFINE SQL_OSC_CORE	:=	0x0001
DEFINE SQL_OSC_EXTENDED	:=	0x0002
DEFINE SQL_CB_NULL	:=	0x0000
DEFINE SQL_CB_NON_NULL	:=	0x0001
DEFINE SQL_SO_FORWARD_ONLY	:=	0x00000001L
DEFINE SQL_SO_KEYSET_DRIVEN	:=	0x00000002L
DEFINE SQL_SO_DYNAMIC	:=	0x00000004L
DEFINE SQL_SO_MIXED	:=	0x00000008L
DEFINE SQL_SO_STATIC	:=	0x00000010L
DEFINE SQL_FD_FETCH_RESUME	:=	0x00000040L
DEFINE SQL_FD_FETCH_BOOKMARK	:=	0x00000080L
DEFINE SQL_TXN_VERSIONING	:=	0x00000010L
DEFINE SQL_CN_NONE	:=	0x0000
DEFINE SQL_CN_DIFFERENT	:=	0x0001
DEFINE SQL_CN_ANY	:=	0x0002
DEFINE SQL_NNC_NULL	:=	0x0000
DEFINE SQL_NNC_NON_NULL	:=	0x0001
DEFINE SQL_NC_START	:=	0x0002
DEFINE SQL_NC_END	:=	0x0004
DEFINE SQL_FILE_NOT_SUPPORTED	:=	0x0000
DEFINE SQL_FILE_TABLE	:=	0x0001
DEFINE SQL_FILE_QUALIFIER	:=	0x0002
DEFINE SQL_FILE_CATALOG	:=					SQL_FILE_QUALIFIER	// ODBC 3.0
DEFINE SQL_GD_BLOCK	:=	0x00000004L
DEFINE SQL_GD_BOUND	:=	0x00000008L
DEFINE SQL_PS_POSITIONED_DELETE	:=	0x00000001L
DEFINE SQL_PS_POSITIONED_UPDATE	:=	0x00000002L
DEFINE SQL_PS_SELECT_FOR_UPDATE	:=	0x00000004L
DEFINE SQL_GB_NOT_SUPPORTED	:=	0x0000
DEFINE SQL_GB_GROUP_BY_EQUALS_SELECT	:=	0x0001
DEFINE SQL_GB_GROUP_BY_CONTAINS_SELECT	:=	0x0002
DEFINE SQL_GB_NO_RELATION	:=	0x0003
DEFINE SQL_GB_COLLATE	:=						0x0004
DEFINE SQL_OU_DML_STATEMENTS	:=	0x00000001L
DEFINE SQL_OU_PROCEDURE_INVOCATION	:=	0x00000002L
DEFINE SQL_OU_TABLE_DEFINITION	:=	0x00000004L
DEFINE SQL_OU_INDEX_DEFINITION	:=	0x00000008L
DEFINE SQL_OU_PRIVILEGE_DEFINITION	:=	0x00000010L
DEFINE SQL_SU_DML_STATEMENTS	:=			SQL_OU_DML_STATEMENTS
DEFINE SQL_SU_PROCEDURE_INVOCATION	:=		SQL_OU_PROCEDURE_INVOCATION
DEFINE SQL_SU_TABLE_DEFINITION	:=			SQL_OU_TABLE_DEFINITION
DEFINE SQL_SU_INDEX_DEFINITION	:=			SQL_OU_INDEX_DEFINITION
DEFINE SQL_SU_PRIVILEGE_DEFINITION	:=		SQL_OU_PRIVILEGE_DEFINITION
DEFINE SQL_QU_DML_STATEMENTS	:=	0x00000001L
DEFINE SQL_QU_PROCEDURE_INVOCATION	:=	0x00000002L
DEFINE SQL_QU_TABLE_DEFINITION	:=	0x00000004L
DEFINE SQL_QU_INDEX_DEFINITION	:=	0x00000008L
DEFINE SQL_QU_PRIVILEGE_DEFINITION	:=	0x00000010L
DEFINE SQL_CU_DML_STATEMENTS	:=			SQL_QU_DML_STATEMENTS
DEFINE SQL_CU_PROCEDURE_INVOCATION	:=		SQL_QU_PROCEDURE_INVOCATION
DEFINE SQL_CU_TABLE_DEFINITION	:=			SQL_QU_TABLE_DEFINITION
DEFINE SQL_CU_INDEX_DEFINITION	:=			SQL_QU_INDEX_DEFINITION
DEFINE SQL_CU_PRIVILEGE_DEFINITION	:=		SQL_QU_PRIVILEGE_DEFINITION
DEFINE SQL_SQ_COMPARISON	:=	0x00000001L
DEFINE SQL_SQ_EXISTS	:=	0x00000002L
DEFINE SQL_SQ_IN	:=	0x00000004L
DEFINE SQL_SQ_QUANTIFIED	:=	0x00000008L
DEFINE SQL_SQ_CORRELATED_SUBQUERIES	:=	0x00000010L
DEFINE SQL_U_UNION	:=	0x00000001L
DEFINE SQL_U_UNION_ALL	:=	0x00000002L
DEFINE SQL_BP_CLOSE	:=	0x00000001L
DEFINE SQL_BP_DELETE	:=	0x00000002L
DEFINE SQL_BP_DROP	:=	0x00000004L
DEFINE SQL_BP_TRANSACTION	:=	0x00000008L
DEFINE SQL_BP_UPDATE	:=	0x00000010L
DEFINE SQL_BP_OTHER_HSTMT	:=	0x00000020L
DEFINE SQL_BP_SCROLL	:=	0x00000040L
DEFINE SQL_SS_ADDITIONS	:=	0x00000001L
DEFINE SQL_SS_DELETIONS	:=	0x00000002L
DEFINE SQL_SS_UPDATES	:=	0x00000004L
DEFINE SQL_CV_CREATE_VIEW	:=					0x00000001L
DEFINE SQL_CV_CHECK_OPTION	:=					0x00000002L
DEFINE SQL_CV_CASCADED	:=						0x00000004L
DEFINE SQL_CV_LOCAL	:=						0x00000008L
DEFINE SQL_LCK_NO_CHANGE	:=	0x00000001L
DEFINE SQL_LCK_EXCLUSIVE	:=	0x00000002L
DEFINE SQL_LCK_UNLOCK	:=	0x00000004L
DEFINE SQL_POS_POSITION	:=	0x00000001L
DEFINE SQL_POS_REFRESH	:=	0x00000002L
DEFINE SQL_POS_UPDATE	:=	0x00000004L
DEFINE SQL_POS_DELETE	:=	0x00000008L
DEFINE SQL_POS_ADD	:=	0x00000010L
DEFINE SQL_QL_START	:=	0x0001
DEFINE SQL_QL_END	:=	0x0002
DEFINE SQL_AF_AVG	:=						0x00000001L
DEFINE SQL_AF_COUNT	:=					0x00000002L
DEFINE SQL_AF_MAX	:=						0x00000004L
DEFINE SQL_AF_MIN	:=						0x00000008L
DEFINE SQL_AF_SUM	:=						0x00000010L
DEFINE SQL_AF_DISTINCT	:=					0x00000020L
DEFINE SQL_AF_ALL	:=						0x00000040L
DEFINE SQL_SC_SQL92_ENTRY	:=				0x00000001L
DEFINE SQL_SC_FIPS127_2_TRANSITIONAL	:=	0x00000002L
DEFINE SQL_SC_SQL92_INTERMEDIATE	:=		0x00000004L
DEFINE SQL_SC_SQL92_FULL	:=				0x00000008L
DEFINE SQL_DL_SQL92_DATE	:=						0x00000001L
DEFINE SQL_DL_SQL92_TIME	:=						0x00000002L
DEFINE SQL_DL_SQL92_TIMESTAMP	:=					0x00000004L
DEFINE SQL_DL_SQL92_INTERVAL_YEAR	:=				0x00000008L
DEFINE SQL_DL_SQL92_INTERVAL_MONTH	:=				0x00000010L
DEFINE SQL_DL_SQL92_INTERVAL_DAY	:=				0x00000020L
DEFINE SQL_DL_SQL92_INTERVAL_HOUR	:=				0x00000040L
DEFINE SQL_DL_SQL92_INTERVAL_MINUTE	:=			0x00000080L
DEFINE SQL_DL_SQL92_INTERVAL_SECOND	:=			0x00000100L
DEFINE SQL_DL_SQL92_INTERVAL_YEAR_TO_MONTH	:=		0x00000200L
DEFINE SQL_DL_SQL92_INTERVAL_DAY_TO_HOUR	:=		0x00000400L
DEFINE SQL_DL_SQL92_INTERVAL_DAY_TO_MINUTE	:=		0x00000800L
DEFINE SQL_DL_SQL92_INTERVAL_DAY_TO_SECOND	:=		0x00001000L
DEFINE SQL_DL_SQL92_INTERVAL_HOUR_TO_MINUTE	:=	0x00002000L
DEFINE SQL_DL_SQL92_INTERVAL_HOUR_TO_SECOND	:=	0x00004000L
DEFINE SQL_DL_SQL92_INTERVAL_MINUTE_TO_SECOND	:=	0x00008000L
DEFINE SQL_CL_START	:=						SQL_QL_START
DEFINE SQL_CL_END	:=							SQL_QL_END
DEFINE SQL_BRC_PROCEDURES	:=			0x0000001
DEFINE SQL_BRC_EXPLICIT	:=			0x0000002
DEFINE SQL_BRC_ROLLED_UP	:=			0x0000004
DEFINE SQL_BS_SELECT_EXPLICIT	:=				0x00000001L
DEFINE SQL_BS_ROW_COUNT_EXPLICIT	:=			0x00000002L
DEFINE SQL_BS_SELECT_PROC	:=					0x00000004L
DEFINE SQL_BS_ROW_COUNT_PROC	:=				0x00000008L
DEFINE SQL_PARC_BATCH	:=		1
DEFINE SQL_PARC_NO_BATCH	:=	2
DEFINE SQL_PAS_BATCH	:=				1
DEFINE SQL_PAS_NO_BATCH	:=			2
DEFINE SQL_PAS_NO_SELECT	:=			3
DEFINE SQL_IK_NONE	:=							0x00000000L
DEFINE SQL_IK_ASC	:=							0x00000001L
DEFINE SQL_IK_DESC	:=							0x00000002L
DEFINE SQL_IK_ALL	:=							0x00000003L
DEFINE SQL_ISV_ASSERTIONS	:=					0x00000001L
DEFINE SQL_ISV_CHARACTER_SETS	:=				0x00000002L
DEFINE SQL_ISV_CHECK_CONSTRAINTS	:=			0x00000004L
DEFINE SQL_ISV_COLLATIONS	:=					0x00000008L
DEFINE SQL_ISV_COLUMN_DOMAIN_USAGE	:=			0x00000010L
DEFINE SQL_ISV_COLUMN_PRIVILEGES	:=			0x00000020L
DEFINE SQL_ISV_COLUMNS	:=						0x00000040L
DEFINE SQL_ISV_CONSTRAINT_COLUMN_USAGE	:=		0x00000080L
DEFINE SQL_ISV_CONSTRAINT_TABLE_USAGE	:=		0x00000100L
DEFINE SQL_ISV_DOMAIN_CONSTRAINTS	:=			0x00000200L
DEFINE SQL_ISV_DOMAINS	:=						0x00000400L
DEFINE SQL_ISV_KEY_COLUMN_USAGE	:=			0x00000800L
DEFINE SQL_ISV_REFERENTIAL_CONSTRAINTS	:=		0x00001000L
DEFINE SQL_ISV_SCHEMATA	:=					0x00002000L
DEFINE SQL_ISV_SQL_LANGUAGES	:=				0x00004000L
DEFINE SQL_ISV_TABLE_CONSTRAINTS	:=			0x00008000L
DEFINE SQL_ISV_TABLE_PRIVILEGES	:=			0x00010000L
DEFINE SQL_ISV_TABLES	:=						0x00020000L
DEFINE SQL_ISV_TRANSLATIONS	:=				0x00040000L
DEFINE SQL_ISV_USAGE_PRIVILEGES	:=			0x00080000L
DEFINE SQL_ISV_VIEW_COLUMN_USAGE	:=			0x00100000L
DEFINE SQL_ISV_VIEW_TABLE_USAGE	:=			0x00200000L
DEFINE SQL_ISV_VIEWS	:=						0x00400000L
//DEFINE SQL_AM_NONE	:=			0
//DEFINE SQL_AM_CONNECTION	:=	1
//DEFINE SQL_AM_STATEMENT	:=	2
DEFINE SQL_AD_CONSTRAINT_NAME_DEFINITION	:=			0x00000001L
DEFINE SQL_AD_ADD_DOMAIN_CONSTRAINT	:=				0x00000002L
DEFINE SQL_AD_DROP_DOMAIN_CONSTRAINT	:=				0x00000004L
DEFINE SQL_AD_ADD_DOMAIN_DEFAULT	:=		 			0x00000008L
DEFINE SQL_AD_DROP_DOMAIN_DEFAULT	:=		 			0x00000010L
DEFINE SQL_AD_ADD_CONSTRAINT_INITIALLY_DEFERRED	:=	0x00000020L
DEFINE SQL_AD_ADD_CONSTRAINT_INITIALLY_IMMEDIATE	:=	0x00000040L
DEFINE SQL_AD_ADD_CONSTRAINT_DEFERRABLE	:=			0x00000080L
DEFINE SQL_AD_ADD_CONSTRAINT_NON_DEFERRABLE	:=		0x00000100L
DEFINE SQL_CS_CREATE_SCHEMA	:=				0x00000001L
DEFINE SQL_CS_AUTHORIZATION	:=				0x00000002L
DEFINE SQL_CS_DEFAULT_CHARACTER_SET	:=		0x00000004L
DEFINE SQL_CTR_CREATE_TRANSLATION	:=			0x00000001L
DEFINE SQL_CA_CREATE_ASSERTION	:=					0x00000001L
DEFINE SQL_CA_CONSTRAINT_INITIALLY_DEFERRED	:=	0x00000010L
DEFINE SQL_CA_CONSTRAINT_INITIALLY_IMMEDIATE	:=	0x00000020L
DEFINE SQL_CA_CONSTRAINT_DEFERRABLE	:=			0x00000040L
DEFINE SQL_CA_CONSTRAINT_NON_DEFERRABLE	:=		0x00000080L
DEFINE SQL_CCS_CREATE_CHARACTER_SET	:=		0x00000001L
DEFINE SQL_CCS_COLLATE_CLAUSE	:=				0x00000002L
DEFINE SQL_CCS_LIMITED_COLLATION	:=			0x00000004L
DEFINE SQL_CCOL_CREATE_COLLATION	:=			0x00000001L
DEFINE SQL_CDO_CREATE_DOMAIN	:=					0x00000001L
DEFINE SQL_CDO_DEFAULT	:=							0x00000002L
DEFINE SQL_CDO_CONSTRAINT	:=						0x00000004L
DEFINE SQL_CDO_COLLATION	:=						0x00000008L
DEFINE SQL_CDO_CONSTRAINT_NAME_DEFINITION	:=		0x00000010L
DEFINE SQL_CDO_CONSTRAINT_INITIALLY_DEFERRED	:=	0x00000020L
DEFINE SQL_CDO_CONSTRAINT_INITIALLY_IMMEDIATE	:=	0x00000040L
DEFINE SQL_CDO_CONSTRAINT_DEFERRABLE	:=			0x00000080L
DEFINE SQL_CDO_CONSTRAINT_NON_DEFERRABLE	:=		0x00000100L
DEFINE SQL_CT_CREATE_TABLE	:=						0x00000001L
DEFINE SQL_CT_COMMIT_PRESERVE	:=					0x00000002L
DEFINE SQL_CT_COMMIT_DELETE	:=					0x00000004L
DEFINE SQL_CT_GLOBAL_TEMPORARY	:=					0x00000008L
DEFINE SQL_CT_LOCAL_TEMPORARY	:=					0x00000010L
DEFINE SQL_CT_CONSTRAINT_INITIALLY_DEFERRED	:=	0x00000020L
DEFINE SQL_CT_CONSTRAINT_INITIALLY_IMMEDIATE	:=	0x00000040L
DEFINE SQL_CT_CONSTRAINT_DEFERRABLE	:=			0x00000080L
DEFINE SQL_CT_CONSTRAINT_NON_DEFERRABLE	:=		0x00000100L
DEFINE SQL_CT_COLUMN_CONSTRAINT	:=				0x00000200L
DEFINE SQL_CT_COLUMN_DEFAULT	:=					0x00000400L
DEFINE SQL_CT_COLUMN_COLLATION	:=					0x00000800L
DEFINE SQL_CT_TABLE_CONSTRAINT	:=					0x00001000L
DEFINE SQL_CT_CONSTRAINT_NAME_DEFINITION	:=		0x00002000L
DEFINE SQL_DI_CREATE_INDEX	:=						0x00000001L
DEFINE SQL_DI_DROP_INDEX	:=						0x00000002L
DEFINE SQL_DC_DROP_COLLATION	:=					0x00000001L
DEFINE SQL_DD_DROP_DOMAIN	:=						0x00000001L
DEFINE SQL_DD_RESTRICT	:=							0x00000002L
DEFINE SQL_DD_CASCADE	:=							0x00000004L
DEFINE SQL_DS_DROP_SCHEMA	:=						0x00000001L
DEFINE SQL_DS_RESTRICT	:=							0x00000002L
DEFINE SQL_DS_CASCADE	:=							0x00000004L
DEFINE SQL_DCS_DROP_CHARACTER_SET	:=				0x00000001L
DEFINE SQL_DA_DROP_ASSERTION	:=					0x00000001L
DEFINE SQL_DT_DROP_TABLE	:=						0x00000001L
DEFINE SQL_DT_RESTRICT	:=							0x00000002L
DEFINE SQL_DT_CASCADE	:=							0x00000004L
DEFINE SQL_DTR_DROP_TRANSLATION	:=				0x00000001L
DEFINE SQL_DV_DROP_VIEW	:=						0x00000001L
DEFINE SQL_DV_RESTRICT	:=							0x00000002L
DEFINE SQL_DV_CASCADE	:=							0x00000004L
DEFINE SQL_IS_INSERT_LITERALS	:=					0x00000001L
DEFINE SQL_IS_INSERT_SEARCHED	:=					0x00000002L
DEFINE SQL_IS_SELECT_INTO	:=						0x00000004L
DEFINE SQL_OIC_CORE	:=							1U
DEFINE SQL_OIC_LEVEL1	:=							2U
DEFINE SQL_OIC_LEVEL2	:=							3U
DEFINE SQL_SFKD_CASCADE	:=						0x00000001L
DEFINE SQL_SFKD_NO_ACTION	:=						0x00000002L
DEFINE SQL_SFKD_SET_DEFAULT	:=					0x00000004L
DEFINE SQL_SFKD_SET_NULL	:=						0x00000008L
DEFINE SQL_SFKU_CASCADE	:=						0x00000001L
DEFINE SQL_SFKU_NO_ACTION	:=						0x00000002L
DEFINE SQL_SFKU_SET_DEFAULT	:=					0x00000004L
DEFINE SQL_SFKU_SET_NULL	:=						0x00000008L
DEFINE SQL_SG_USAGE_ON_DOMAIN	:=					0x00000001L
DEFINE SQL_SG_USAGE_ON_CHARACTER_SET	:=			0x00000002L
DEFINE SQL_SG_USAGE_ON_COLLATION	:=				0x00000004L
DEFINE SQL_SG_USAGE_ON_TRANSLATION	:=				0x00000008L
DEFINE SQL_SG_WITH_GRANT_OPTION	:=				0x00000010L
DEFINE SQL_SG_DELETE_TABLE	:=						0x00000020L
DEFINE SQL_SG_INSERT_TABLE	:=						0x00000040L
DEFINE SQL_SG_INSERT_COLUMN	:=					0x00000080L
DEFINE SQL_SG_REFERENCES_TABLE	:=					0x00000100L
DEFINE SQL_SG_REFERENCES_COLUMN	:=				0x00000200L
DEFINE SQL_SG_SELECT_TABLE	:=						0x00000400L
DEFINE SQL_SG_UPDATE_TABLE	:=						0x00000800L
DEFINE SQL_SG_UPDATE_COLUMN	:=					0x00001000L
DEFINE SQL_SP_EXISTS	:=							0x00000001L
DEFINE SQL_SP_ISNOTNULL	:=						0x00000002L
DEFINE SQL_SP_ISNULL	:=							0x00000004L
DEFINE SQL_SP_MATCH_FULL	:=						0x00000008L
DEFINE SQL_SP_MATCH_PARTIAL	:=					0x00000010L
DEFINE SQL_SP_MATCH_UNIQUE_FULL	:=				0x00000020L
DEFINE SQL_SP_MATCH_UNIQUE_PARTIAL	:=				0x00000040L
DEFINE SQL_SP_OVERLAPS	:=							0x00000080L
DEFINE SQL_SP_UNIQUE	:=							0x00000100L
DEFINE SQL_SP_LIKE	:=								0x00000200L
DEFINE SQL_SP_IN	:=								0x00000400L
DEFINE SQL_SP_BETWEEN	:=							0x00000800L
DEFINE SQL_SP_COMPARISON	:=						0x00001000L
DEFINE SQL_SP_QUANTIFIED_COMPARISON	:=			0x00002000L
DEFINE SQL_SRJO_CORRESPONDING_CLAUSE	:=			0x00000001L
DEFINE SQL_SRJO_CROSS_JOIN	:=						0x00000002L
DEFINE SQL_SRJO_EXCEPT_JOIN	:=					0x00000004L
DEFINE SQL_SRJO_FULL_OUTER_JOIN	:=				0x00000008L
DEFINE SQL_SRJO_INNER_JOIN	:=						0x00000010L
DEFINE SQL_SRJO_INTERSECT_JOIN	:=					0x00000020L
DEFINE SQL_SRJO_LEFT_OUTER_JOIN	:=				0x00000040L
DEFINE SQL_SRJO_NATURAL_JOIN	:=					0x00000080L
DEFINE SQL_SRJO_RIGHT_OUTER_JOIN	:=				0x00000100L
DEFINE SQL_SRJO_UNION_JOIN	:=						0x00000200L
DEFINE SQL_SR_USAGE_ON_DOMAIN	:=					0x00000001L
DEFINE SQL_SR_USAGE_ON_CHARACTER_SET	:=			0x00000002L
DEFINE SQL_SR_USAGE_ON_COLLATION	:=				0x00000004L
DEFINE SQL_SR_USAGE_ON_TRANSLATION	:=				0x00000008L
DEFINE SQL_SR_GRANT_OPTION_FOR	:=					0x00000010L
DEFINE SQL_SR_CASCADE	:=							0x00000020L
DEFINE SQL_SR_RESTRICT	:=							0x00000040L
DEFINE SQL_SR_DELETE_TABLE	:=						0x00000080L
DEFINE SQL_SR_INSERT_TABLE	:=						0x00000100L
DEFINE SQL_SR_INSERT_COLUMN	:=					0x00000200L
DEFINE SQL_SR_REFERENCES_TABLE	:=					0x00000400L
DEFINE SQL_SR_REFERENCES_COLUMN	:=				0x00000800L
DEFINE SQL_SR_SELECT_TABLE	:=						0x00001000L
DEFINE SQL_SR_UPDATE_TABLE	:=						0x00002000L
DEFINE SQL_SR_UPDATE_COLUMN	:=					0x00004000L
DEFINE SQL_SRVC_VALUE_EXPRESSION	:=				0x00000001L
DEFINE SQL_SRVC_NULL	:=							0x00000002L
DEFINE SQL_SRVC_DEFAULT	:=						0x00000004L
DEFINE SQL_SRVC_ROW_SUBQUERY	:=					0x00000008L
DEFINE SQL_SVE_CASE	:=							0x00000001L
DEFINE SQL_SVE_CAST	:=							0x00000002L
DEFINE SQL_SVE_COALESCE	:=						0x00000004L
DEFINE SQL_SVE_NULLIF	:=							0x00000008L
DEFINE SQL_SCC_XOPEN_CLI_VERSION1	:=				0x00000001L
DEFINE SQL_SCC_ISO92_CLI	:=						0x00000002L
DEFINE SQL_US_UNION	:=							SQL_U_UNION
DEFINE SQL_US_UNION_ALL	:=						SQL_U_UNION_ALL
DEFINE SQL_DTC_ENLIST_EXPENSIVE	:=				0x00000001L
DEFINE SQL_DTC_UNENLIST_EXPENSIVE	:=				0x00000002L
DEFINE SQL_FETCH_FIRST_USER	:=				31
DEFINE SQL_FETCH_FIRST_SYSTEM	:=				32
DEFINE SQL_ENTIRE_ROWSET	:=	0
DEFINE SQL_POSITION	:=	0               /*      1.0 FALSE */
DEFINE SQL_REFRESH	:=	1               /*      1.0 TRUE */
DEFINE SQL_UPDATE	:=	2
DEFINE SQL_DELETE	:=	3
DEFINE SQL_ADD	:=	4
DEFINE SQL_SETPOS_MAX_OPTION_VALUE	:=			SQL_ADD
DEFINE SQL_UPDATE_BY_BOOKMARK	:=		 5
DEFINE SQL_DELETE_BY_BOOKMARK	:=		 6
DEFINE SQL_FETCH_BY_BOOKMARK	:=		 7
DEFINE SQL_LOCK_NO_CHANGE	:=	0               /*      1.0 FALSE */
DEFINE SQL_LOCK_EXCLUSIVE	:=	1               /*      1.0 TRUE */
DEFINE SQL_LOCK_UNLOCK	:=	2
DEFINE SQL_SETPOS_MAX_LOCK_VALUE	:=		SQL_LOCK_UNLOCK
DEFINE SQL_BEST_ROWID	:=	1
DEFINE SQL_ROWVER	:=	2
DEFINE SQL_PC_NOT_PSEUDO	:=	1
DEFINE SQL_QUICK	:=	0
DEFINE SQL_ENSURE	:=	1
DEFINE SQL_TABLE_STAT	:=	0
DEFINE SQL_ALL_CATALOGS	:=				"%"
DEFINE SQL_ALL_SCHEMAS	:=					"%"
DEFINE SQL_ALL_TABLE_TYPES	:=				"%"
DEFINE SQL_DRIVER_NOPROMPT	:=	0
DEFINE SQL_DRIVER_COMPLETE	:=	1
DEFINE SQL_DRIVER_PROMPT	:=	2
DEFINE SQL_DRIVER_COMPLETE_REQUIRED	:=	3
DEFINE SQL_FETCH_BOOKMARK	:=	8
DEFINE SQL_ROW_SUCCESS	:=	0
DEFINE SQL_ROW_DELETED	:=	1
DEFINE SQL_ROW_UPDATED	:=	2
DEFINE SQL_ROW_NOROW	:=	3
DEFINE SQL_ROW_ADDED	:=	4
DEFINE SQL_ROW_ERROR	:=	5
DEFINE SQL_ROW_SUCCESS_WITH_INFO	:=		 6
DEFINE SQL_ROW_PROCEED	:=					 0
DEFINE SQL_ROW_IGNORE	:=					 1
DEFINE SQL_PARAM_SUCCESS	:=				0
DEFINE SQL_PARAM_SUCCESS_WITH_INFO	:=		6
DEFINE SQL_PARAM_ERROR	:=					5
DEFINE SQL_PARAM_UNUSED	:=				7
DEFINE SQL_PARAM_DIAG_UNAVAILABLE	:=		1
DEFINE SQL_PARAM_PROCEED	:=				0
DEFINE SQL_PARAM_IGNORE	:=				1
DEFINE SQL_CASCADE	:=	0
DEFINE SQL_RESTRICT	:=	1
DEFINE SQL_SET_NULL	:=	2
DEFINE SQL_NO_ACTION	:=			 3
DEFINE SQL_SET_DEFAULT	:=			 4
DEFINE SQL_INITIALLY_DEFERRED	:=			5
DEFINE SQL_INITIALLY_IMMEDIATE	:=			6
DEFINE SQL_NOT_DEFERRABLE	:=			7
DEFINE SQL_PARAM_TYPE_UNKNOWN	:=	0
DEFINE SQL_PARAM_INPUT	:=	1
DEFINE SQL_PARAM_INPUT_OUTPUT	:=	2
DEFINE SQL_RESULT_COL	:=	3
DEFINE SQL_PARAM_OUTPUT	:=	4
DEFINE SQL_RETURN_VALUE	:=	5
DEFINE SQL_PT_UNKNOWN	:=	0
DEFINE SQL_PT_PROCEDURE	:=	1
DEFINE SQL_PT_FUNCTION	:=	2
DEFINE SQL_DATABASE_NAME	:=	16    /* Use SQLGetConnectOption/SQL_CURRENT_QUALIFIER */
DEFINE SQL_FD_FETCH_PREV	:=	SQL_FD_FETCH_PRIOR
DEFINE SQL_FETCH_PREV	:=	SQL_FETCH_PRIOR
DEFINE SQL_CONCUR_TIMESTAMP	:=	SQL_CONCUR_ROWVER
DEFINE SQL_SCCO_OPT_TIMESTAMP	:=	SQL_SCCO_OPT_ROWVER
DEFINE SQL_CC_DELETE	:=	SQL_CB_DELETE
DEFINE SQL_CR_DELETE	:=	SQL_CB_DELETE
DEFINE SQL_CC_CLOSE	:=	SQL_CB_CLOSE
DEFINE SQL_CR_CLOSE	:=	SQL_CB_CLOSE
DEFINE SQL_CC_PRESERVE	:=	SQL_CB_PRESERVE
DEFINE SQL_CR_PRESERVE	:=	SQL_CB_PRESERVE
DEFINE SQL_FETCH_RESUME	:=	7
DEFINE SQL_SCROLL_FORWARD_ONLY	:=	0L    /*-SQL_CURSOR_FORWARD_ONLY */
DEFINE SQL_SCROLL_KEYSET_DRIVEN	:=	(-1L) /*-SQL_CURSOR_KEYSET_DRIVEN */
DEFINE SQL_SCROLL_DYNAMIC	:=	(-2L) /*-SQL_CURSOR_DYNAMIC */
DEFINE SQL_SCROLL_STATIC	:=	(-3L) /*-SQL_CURSOR_STATIC */
DEFINE TRACE_VERSION	:=	1000		/* Version of trace API */
DEFINE TRACE_ON	:=			0x00000001L
DEFINE TRACE_VS_EVENT_ON	:=	0x00000002L
DEFINE ODBC_VS_FLAG_UNICODE_ARG	:=	0x00000001L	/* the argument is unicode */
DEFINE ODBC_VS_FLAG_UNICODE_COR	:=	0x00000002L	/* the correlation is unicode */
DEFINE ODBC_VS_FLAG_RETCODE	:=		0x00000004L	/* RetCode field is set */
DEFINE ODBC_VS_FLAG_STOP	:=		0x00000008L	/* Stop firing visual studio analyzer events */
// Unicode support
DEFINE SQL_WCHAR	:=		 	(-8)
DEFINE SQL_WVARCHAR	:=		(-9)
DEFINE SQL_WLONGVARCHAR	:=		(-10)
DEFINE SQL_C_WCHAR	:=			SQL_WCHAR
DEFINE SQL_C_TCHAR	:=		SQL_C_CHAR
DEFINE SQL_SQLSTATE_SIZEW	:=	10	/* size of SQLSTATE for unicode */
#endregion
