//
// Copyright (c) XSharp B.V.  All Rights Reserved.  
// Licensed under the Apache License, Version 2.0.  
// See License.txt in the project root for license information.
//

INTERNAL DEFINE __CAVOSTR_SQLCLASS_SUBSYS                 := VOErrors.__CAVOSTR_SQLCLASS_SUBSYS             
INTERNAL DEFINE __CAVOSTR_SQLCLASS__ENV_ALLOC             := VOErrors.__CAVOSTR_SQLCLASS__ENV_ALLOC         
INTERNAL DEFINE __CAVOSTR_SQLCLASS__ENV_FREE              := VOErrors.__CAVOSTR_SQLCLASS__ENV_FREE          
INTERNAL DEFINE __CAVOSTR_SQLCLASS__CON_ALLOC             := VOErrors.__CAVOSTR_SQLCLASS__CON_ALLOC         
INTERNAL DEFINE __CAVOSTR_SQLCLASS__CON_FREE              := VOErrors.__CAVOSTR_SQLCLASS__CON_FREE          
INTERNAL DEFINE __CAVOSTR_SQLCLASS__CONNECTED             := VOErrors.__CAVOSTR_SQLCLASS__CONNECTED         
INTERNAL DEFINE __CAVOSTR_SQLCLASS__NOT_CONN              := VOErrors.__CAVOSTR_SQLCLASS__NOT_CONN          
INTERNAL DEFINE __CAVOSTR_SQLCLASS__CANCELLED             := VOErrors.__CAVOSTR_SQLCLASS__CANCELLED         
INTERNAL DEFINE __CAVOSTR_SQLCLASS__ODBC_VO               := VOErrors.__CAVOSTR_SQLCLASS__ODBC_VO           
INTERNAL DEFINE __CAVOSTR_SQLCLASS__GENERAL_ERR           := VOErrors.__CAVOSTR_SQLCLASS__GENERAL_ERR       
INTERNAL DEFINE __CAVOSTR_SQLCLASS__STMT_NOT_ALLOC        := VOErrors.__CAVOSTR_SQLCLASS__STMT_NOT_ALLOC    
INTERNAL DEFINE __CAVOSTR_SQLCLASS__STMT_PREP             := VOErrors.__CAVOSTR_SQLCLASS__STMT_PREP         
INTERNAL DEFINE __CAVOSTR_SQLCLASS__NO_STMT               := VOErrors.__CAVOSTR_SQLCLASS__NO_STMT           
INTERNAL DEFINE __CAVOSTR_SQLCLASS__STMT_ALLOC            := VOErrors.__CAVOSTR_SQLCLASS__STMT_ALLOC        
INTERNAL DEFINE __CAVOSTR_SQLCLASS__FUNCSEQ_ERR           := VOErrors.__CAVOSTR_SQLCLASS__FUNCSEQ_ERR       
INTERNAL DEFINE __CAVOSTR_SQLCLASS__PARM_TYPE             := VOErrors.__CAVOSTR_SQLCLASS__PARM_TYPE         
INTERNAL DEFINE __CAVOSTR_SQLCLASS__MEM_ALLOC             := VOErrors.__CAVOSTR_SQLCLASS__MEM_ALLOC         
INTERNAL DEFINE __CAVOSTR_SQLCLASS__BADCOL                := VOErrors.__CAVOSTR_SQLCLASS__BADCOL            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__BADFLD                := VOErrors.__CAVOSTR_SQLCLASS__BADFLD            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__BADPAR                := VOErrors.__CAVOSTR_SQLCLASS__BADPAR            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__BADRECNO              := VOErrors.__CAVOSTR_SQLCLASS__BADRECNO          
INTERNAL DEFINE __CAVOSTR_SQLCLASS__BACKWARDS             := VOErrors.__CAVOSTR_SQLCLASS__BACKWARDS         
INTERNAL DEFINE __CAVOSTR_SQLCLASS__BOF                   := VOErrors.__CAVOSTR_SQLCLASS__BOF               
INTERNAL DEFINE __CAVOSTR_SQLCLASS__EOF                   := VOErrors.__CAVOSTR_SQLCLASS__EOF               
INTERNAL DEFINE __CAVOSTR_SQLCLASS__NOFLDS                := VOErrors.__CAVOSTR_SQLCLASS__NOFLDS            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__NO_KEY                := VOErrors.__CAVOSTR_SQLCLASS__NO_KEY            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__NO_ROW                := VOErrors.__CAVOSTR_SQLCLASS__NO_ROW            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__NO_INS                := VOErrors.__CAVOSTR_SQLCLASS__NO_INS            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__INV_OP                := VOErrors.__CAVOSTR_SQLCLASS__INV_OP            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__NO_CSR                := VOErrors.__CAVOSTR_SQLCLASS__NO_CSR            
INTERNAL DEFINE __CAVOSTR_SQLCLASS__BADVALID              := VOErrors.__CAVOSTR_SQLCLASS__BADVALID          
INTERNAL DEFINE __CAVOSTR_SQLCLASS__EMPTY                 := VOErrors.__CAVOSTR_SQLCLASS__EMPTY             
INTERNAL DEFINE __CAVOSTR_SQLCLASS__UPDATE_COL            := VOErrors.__CAVOSTR_SQLCLASS__UPDATE_COL        
INTERNAL DEFINE __CAVOSTR_SQLCLASS__NODATAFIELDSEXIST     := VOErrors.__CAVOSTR_SQLCLASS__NODATAFIELDSEXIST 
INTERNAL DEFINE __CAVOSTR_SQLCLASS__BADFIELDPOSITION      := VOErrors.__CAVOSTR_SQLCLASS__BADFIELDPOSITION  
INTERNAL DEFINE __CAVOSTR_SQLCLASS__INVALIDCOLATT         := VOErrors.__CAVOSTR_SQLCLASS__INVALIDCOLATT     

