// 317. compiler crash with VS generated code for resources and /lb+
// crashes only with /lb+
BEGIN NAMESPACE VnMacro.Properties
    #using System
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GLOBAL::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")] ;
    [GLOBAL::System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [GLOBAL::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    INTERNAL CLASS Resources
        [GLOBAL::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
        INTERNAL CONSTRUCTOR()
            RETURN
        STATIC PRIVATE resourceMan AS GLOBAL::System.Resources.ResourceManager
        STATIC PRIVATE resourceCulture AS GLOBAL::System.Globalization.CultureInfo
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        INTERNAL STATIC ACCESS ResourceManager() AS GLOBAL::System.Resources.ResourceManager
            IF System.Object.ReferenceEquals(resourceMan, NULL)
                LOCAL temp := GLOBAL::System.Resources.ResourceManager{"VnMacro.Properties.Resources", typeof(Resources):Assembly} AS GLOBAL::System.Resources.ResourceManager
                resourceMan := temp
            ENDIF
            RETURN resourceMan
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        INTERNAL STATIC ACCESS Culture() AS GLOBAL::System.Globalization.CultureInfo
            RETURN resourceCulture
        INTERNAL STATIC ASSIGN Culture( value AS GLOBAL::System.Globalization.CultureInfo )
            resourceCulture := value
    
    END CLASS
END NAMESPACE
