//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.0.0.7
//     Timestamp      : 9-12-2018 12:36:55
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE XSharp
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")] ;
    [System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    INTERNAL CLASS Collations
        
        PRIVATE static resourceMan AS System.Resources.ResourceManager
        PRIVATE static resourceCulture AS System.Globalization.CultureInfo
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
        CONSTRUCTOR()  STRICT
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY ResourceManager AS System.Resources.ResourceManager
        
            GET
                if (OBJECT.ReferenceEquals(resourceMan, NULL))
                    LOCAL temp := System.Resources.ResourceManager{"XSharp.Collations", typeof(Collations):@@Assembly} AS System.Resources.ResourceManager
                    resourceMan := temp
                endif
                RETURN resourceMan
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY Culture AS System.Globalization.CultureInfo
        
            GET
                RETURN resourceCulture
            END GET
        
            SET
                resourceCulture := value
            END SET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY BRAZIL AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("BRAZIL", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CROATIA AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CROATIA", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CZECH852 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CZECH852", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY CZECH895 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("CZECH895", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY DANISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("DANISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY DUTCH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("DUTCH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY FINNISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("FINNISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY FRENCH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("FRENCH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GENERIC AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GENERIC", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GERMAN AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GERMAN", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY GERMAN2 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("GERMAN2", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY HUNG852 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("HUNG852", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY HUNGCWI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("HUNGCWI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ITALIAN AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ITALIAN", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY NORWEGN AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("NORWEGN", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY POL_ISO AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("POL-ISO", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY POL_MAZ AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("POL-MAZ", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY POL852 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("POL852", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY PORT850 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("PORT850", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY PORT860 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("PORT860", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY ROMANIA AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("ROMANIA", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY RUSSIAN AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("RUSSIAN", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SERBIA AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SERBIA", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SL_W_95 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SL-W-95", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SL_W_AS7 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SL-W-AS7", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SL_W_EE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SL-W-EE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SLOV852 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SLOV852", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SLOV895 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SLOV895", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SPANISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SPANISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SWEDISH AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SWEDISH", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY UK AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("UK", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
    
    END CLASS
END NAMESPACE
