//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 1.2.0.0
//     Timestamp      : 22-3-2018 22:37:06
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE XSharp
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")] ;
    [System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    INTERNAL CLASS Collations
        
        PRIVATE static resourceMan AS System.Resources.ResourceManager
        PRIVATE static resourceCulture AS System.Globalization.CultureInfo
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
        CONSTRUCTOR()
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY ResourceManager AS System.Resources.ResourceManager
        
            GET
                if (OBJECT.ReferenceEquals(resourceMan, NULL))
                    LOCAL temp := System.Resources.ResourceManager{"XSharp.Collations", typeof(Collations):@@Assembly} AS System.Resources.ResourceManager
                    resourceMan := temp
                endif
                RETURN resourceMan
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)] ;
        INTERNAL STATIC PROPERTY Culture AS System.Globalization.CultureInfo
        
            GET
                RETURN resourceCulture
            END GET
        
            SET
                resourceCulture := value
            END SET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Brazil AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Brazil", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Croatia AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Croatia", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Czech852 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Czech852", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Czech895 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Czech895", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Danish AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Danish", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Dutch AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Dutch", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Finnish AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Finnish", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY French AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("French", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Generic AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Generic", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY German AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("German", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY German2 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("German2", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Hung852 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Hung852", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY HungCWI AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("HungCWI", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Italian AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Italian", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Norwegn AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Norwegn", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Pol_Iso AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Pol-Iso", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Pol_Maz AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Pol-Maz", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Pol852 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Pol852", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Port850 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Port850", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Port860 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Port860", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Romania AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Romania", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Russian AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Russian", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Serbia AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Serbia", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SL_W_95 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SL-W-95", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SL_W_AS7 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SL-W-AS7", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY SL_W_EE AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("SL-W-EE", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Slov852 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Slov852", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Slov895 AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Slov895", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Spanish AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Spanish", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Swedish AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Swedish", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        INTERNAL STATIC PROPERTY Uk AS BYTE[]
        
            GET
                LOCAL obj := ResourceManager:GetObject("Uk", resourceCulture) AS OBJECT
                RETURN ((BYTE[])(obj))
            END GET
        END PROPERTY
    
    END CLASS
END NAMESPACE
