CLASS ICONDB INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICONDB", _GetInst()})
	RETURN SELF

END CLASS
CLASS ICONDBSELECT INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICONDBSELECT", _GetInst()})
	RETURN SELF

END CLASS
CLASS ICONRECORD INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICONRECORD", _GetInst()})
	RETURN SELF

END CLASS
CLASS ICONRECORDSELECT INHERIT Icon
CONSTRUCTOR() 
   SUPER(ResourceID{"ICONRECORDSELECT", _GetInst()})
	RETURN SELF

END CLASS
CLASS RBNTOOLBAR INHERIT Bitmap
CONSTRUCTOR() 
   SUPER(ResourceID{"RBNTOOLBAR", _GetInst()})
	RETURN SELF


END CLASS
